"""Additional exact-name Massachusetts flower references for the durable DEV Sandbox.

These records are public external references used only to exercise realistic potency,
terpene, and source-provenance flows in DEV. They do not certify or replace the
identity of any DoobieLogic sandbox package.
"""
from __future__ import annotations

from typing import Any


def _r(analysis: str, key: str, name: str, value: float | None, value_text: str, units: str = "%") -> dict[str, Any]:
    return {
        "analysis": analysis,
        "key": key,
        "name": name,
        "value": value,
        "value_text": value_text,
        "units": units,
        "status": "Pass",
    }


ADDITIONAL_MA_FLOWER_COA_FIXTURES: dict[str, dict[str, Any]] = {
    "Animal Tsunami": {
        "source_url": "https://opencoa.org/coa/019f4113-5e16-7299-b58c-5267d990c46e/animal-tsunami-101025-4",
        "source_state": "MA",
        "source_license_holder": "617 Therapeutic Health Center, Inc.",
        "product_name": "Bulk Flower - Animal Tsunami",
        "product_type": "Flower",
        "batch_number": "Animal Tsunami 101025-4",
        "lab_name": "Kaycha MA, LLC",
        "lab_license_number": "IL281349",
        "lab_id": "NA51121001-012",
        "metrc_source_id": "1A40A030000DB89000000919",
        "metrc_lab_id": "",
        "date_tested": "2025-11-28T00:00:00+00:00",
        "overall_status": "pass",
        "source_safety_verified": False,
        "source_safety_note": (
            "OpenCOA reports the laboratory overall status as Pass; detailed contaminant rows "
            "were not machine-readable, so detailed safety verification is not asserted."
        ),
        "total_thc": 33.31,
        "total_cbd": None,
        "total_cannabinoids": 38.836,
        "total_terpenes": 1.762,
        "results": [
            _r("cannabinoids", "thca", "THCA", 35.69, "35.69"),
            _r("cannabinoids", "delta_9_thc", "Delta-9 THC", 2.01, "2.01"),
            _r("cannabinoids", "cbga", "CBGA", 0.95, "0.95"),
            _r("cannabinoids", "thcva", "THCVA", 0.18, "0.18"),
            _r("terpenes", "linalool", "Linalool", 0.408, "0.408"),
            _r("terpenes", "limonene", "Limonene", 0.392, "0.392"),
            _r("terpenes", "beta_caryophyllene", "Beta-Caryophyllene", 0.301, "0.301"),
            _r("terpenes", "guaiol", "Guaiol", 0.118, "0.118"),
            _r("terpenes", "alpha_humulene", "Alpha-Humulene", 0.100, "0.100"),
            _r("terpenes", "beta_myrcene", "Beta-Myrcene", 0.100, "0.100"),
            _r("terpenes", "beta_pinene", "Beta-Pinene", 0.074, "0.074"),
            _r("terpenes", "bisabolol", "Alpha-Bisabolol", 0.069, "0.069"),
            _r("terpenes", "fenchol", "Fenchol", 0.056, "0.056"),
            _r("terpenes", "alpha_terpineol", "Alpha-Terpineol", 0.054, "0.054"),
            _r("terpenes", "alpha_pinene", "Alpha-Pinene", 0.047, "0.047"),
            _r("terpenes", "borneol", "Borneol", 0.022, "0.022"),
            _r("terpenes", "caryophyllene_oxide", "Caryophyllene Oxide", 0.021, "0.021"),
        ],
    },
    "Candy Sparqs": {
        "source_url": "https://opencoa.org/coa/019d9003-044f-73b4-9aa8-3b91d3647015/candy",
        "source_state": "MA",
        "source_license_holder": "LC Square, LLC.",
        "product_name": "Candy Sparqs 10.10.2025 C Test Sample",
        "product_type": "Flower",
        "batch_number": "Candy",
        "lab_name": "Green Valley Analytics LLC",
        "lab_license_number": "IL281359",
        "lab_id": "156713",
        "metrc_source_id": "1A40A030000CBE9000003294",
        "metrc_lab_id": "",
        "date_tested": "2025-10-27T00:00:00+00:00",
        "overall_status": "pass",
        "source_safety_verified": True,
        "source_safety_note": (
            "OpenCOA exposes passing heavy-metal, microbial, mycotoxin, and pesticide panels "
            "for this source record."
        ),
        "total_thc": 23.038,
        "total_cbd": 0.0,
        "total_cannabinoids": 27.083,
        "total_terpenes": 3.136,
        "results": [
            _r("cannabinoids", "thca", "THCA", 26.27, "26.27"),
            _r("cannabinoids", "cbga", "CBGA", 0.81, "0.81"),
            _r("terpenes", "beta_caryophyllene", "Beta-Caryophyllene", 1.068, "1.068"),
            _r("terpenes", "limonene", "Limonene", 0.639, "0.639"),
            _r("terpenes", "linalool", "Linalool", 0.478, "0.478"),
            _r("terpenes", "beta_myrcene", "Beta-Myrcene", 0.286, "0.286"),
            _r("terpenes", "alpha_humulene", "Alpha-Humulene", 0.212, "0.212"),
            _r("terpenes", "nerolidol", "Trans-Nerolidol", 0.102, "0.102"),
            _r("terpenes", "beta_pinene", "Beta-Pinene", 0.083, "0.083"),
            _r("terpenes", "fenchol", "Fenchol", 0.075, "0.075"),
            _r("terpenes", "alpha_terpineol", "Alpha-Terpineol", 0.063, "0.063"),
            _r("terpenes", "alpha_pinene", "Alpha-Pinene", 0.056, "0.056"),
            _r("terpenes", "bisabolol", "Alpha-Bisabolol", 0.042, "0.042"),
            _r("terpenes", "camphene", "Camphene", 0.017, "0.017"),
            _r("terpenes", "borneol", "Borneol", 0.015, "0.015"),
        ],
    },
    "Runtz OG": {
        "source_url": "https://opencoa.org/coa/019f8195-5c06-7307-b641-78c051cade78/runtzog-f5-04282026",
        "source_state": "MA",
        "source_license_holder": "berkley botanicals llc",
        "product_name": "Renew - Runtz OG - Bulk Flower",
        "product_type": "Flower",
        "batch_number": "RuntzOG-F5-04282026",
        "lab_name": "Kaycha MA, LLC",
        "lab_license_number": "IL281349",
        "lab_id": "NA60508014-003",
        "metrc_source_id": "1A40A030000D5AD000016369",
        "metrc_lab_id": "",
        "date_tested": "2026-05-17T00:00:00+00:00",
        "overall_status": "pass",
        "source_safety_verified": False,
        "source_safety_note": (
            "OpenCOA reports the laboratory overall status as Pass; detailed contaminant rows "
            "were not machine-readable, so detailed safety verification is not asserted."
        ),
        "total_thc": 29.624,
        "total_cbd": None,
        "total_cannabinoids": 34.613,
        "total_terpenes": 3.399,
        "results": [
            _r("cannabinoids", "thca", "THCA", 33.43, "33.43"),
            _r("cannabinoids", "cbga", "CBGA", 0.69, "0.69"),
            _r("cannabinoids", "delta_9_thc", "Delta-9 THC", 0.31, "0.31"),
            _r("cannabinoids", "thcva", "THCVA", 0.18, "0.18"),
            _r("terpenes", "limonene", "Limonene", 1.483, "1.483"),
            _r("terpenes", "linalool", "Linalool", 0.569, "0.569"),
            _r("terpenes", "beta_myrcene", "Beta-Myrcene", 0.327, "0.327"),
            _r("terpenes", "beta_caryophyllene", "Beta-Caryophyllene", 0.290, "0.290"),
            _r("terpenes", "beta_pinene", "Beta-Pinene", 0.214, "0.214"),
            _r("terpenes", "alpha_terpineol", "Alpha-Terpineol", 0.156, "0.156"),
            _r("terpenes", "alpha_pinene", "Alpha-Pinene", 0.120, "0.120"),
            _r("terpenes", "alpha_humulene", "Alpha-Humulene", 0.087, "0.087"),
            _r("terpenes", "farnesene", "Farnesene", 0.048, "0.048"),
            _r("terpenes", "nerolidol", "Trans-Nerolidol", 0.047, "0.047"),
            _r("terpenes", "bisabolol", "Alpha-Bisabolol", 0.032, "0.032"),
            _r("terpenes", "camphene", "Camphene", 0.026, "0.026"),
        ],
    },
    "Strawberry Cough": {
        "source_url": "https://reports.mcrlabs.com/reports/strawberry-cough_20",
        "source_dataset_url": "https://huggingface.co/datasets/cannlytics/cannabis_results",
        "source_record_id": "71449",
        "source_state": "MA",
        "source_license_holder": "EdGrowin'",
        "product_name": "Strawberry Cough",
        "product_type": "Flower",
        "batch_number": "",
        "lab_name": "MCR Labs Massachusetts",
        "lab_license_number": "IL281277",
        "lab_id": "",
        "metrc_source_id": "",
        "metrc_lab_id": "",
        "date_tested": "2024-04-12T00:00:00+00:00",
        "overall_status": "",
        "reference_scope": "potency_terpene_reference",
        "source_safety_verified": False,
        "source_safety_note": (
            "The public MCR report exposes potency, cannabinoid, terpene, and moisture results; "
            "it does not establish a complete MA contaminant compliance panel."
        ),
        "total_thc": 22.36,
        "total_cbd": 0.08,
        "total_cannabinoids": 28.3,
        "total_terpenes": 1.96,
        "results": [
            _r("cannabinoids", "thca", "THCA", 22.2, "22.2"),
            _r("cannabinoids", "cbga", "CBGA", 2.09, "2.09"),
            _r("cannabinoids", "delta_9_thc", "Delta-9 THC", 0.691, "0.691"),
            _r("cannabinoids", "cbca", "CBCA", 0.27, "0.27"),
            _r("cannabinoids", "thcva", "THCVA", 0.185, "0.185"),
            _r("cannabinoids", "cbda", "CBDA", 0.078, "0.078"),
            _r("cannabinoids", "cbd", "CBD", 0.0, "0"),
            _r("terpenes", "terpinolene", "Terpinolene", 0.54, "0.54"),
            _r("terpenes", "beta_myrcene", "Beta-Myrcene", 0.47, "0.47"),
            _r("terpenes", "beta_ocimene", "Beta-Ocimene", 0.15, "0.15"),
            _r("terpenes", "beta_caryophyllene", "Beta-Caryophyllene", 0.14, "0.14"),
            _r("terpenes", "limonene", "D-Limonene", 0.09, "0.09"),
            _r("terpenes", "linalool", "Linalool", 0.08, "0.08"),
            _r("terpenes", "beta_pinene", "Beta-Pinene", 0.07, "0.07"),
            _r("terpenes", "alpha_pinene", "Alpha-Pinene", 0.05, "0.05"),
            _r("terpenes", "geraniol", "Geraniol", 0.05, "0.05"),
            _r("terpenes", "alpha_humulene", "Alpha-Humulene", 0.05, "0.05"),
            _r("terpenes", "bisabolol", "Alpha-Bisabolol", 0.05, "0.05"),
            _r("terpenes", "camphene", "Camphene", 0.03, "0.03"),
            _r("terpenes", "delta_3_carene", "Delta-3-Carene", 0.03, "0.03"),
            _r("terpenes", "alpha_terpinene", "Alpha-Terpinene", 0.03, "0.03"),
            _r("terpenes", "gamma_terpinene", "Gamma-Terpinene", 0.03, "0.03"),
            _r("terpenes", "cis_nerolidol", "Cis-Nerolidol", 0.03, "0.03"),
            _r("terpenes", "nerolidol", "Trans-Nerolidol", 0.03, "0.03"),
            _r("terpenes", "eucalyptol", "Eucalyptol", 0.02, "0.02"),
            _r("terpenes", "caryophyllene_oxide", "Caryophyllene Oxide", 0.02, "0.02"),
        ],
    },
}
