import { CultivationNetworkSetup } from "./CultivationNetworkSetup";
import { CultivationRadioSetup } from "./CultivationRadioSetup";
import { readSourcePreview } from "./telemetryReview";
import { TelemetryMappingTable, SourcePreviewTable, NormalizedPreviewTable, type ImportMapping, type PreviewSample } from "./telemetryMappingTable";
import { CultivationPushSetup, ConnectionHealthPanel } from "./CultivationPushSetup";
import { useEffect, useMemo, useState } from "react";
import { useQueryClient } from "@tanstack/react-query";
import { AggregateWindow, ZoneSelect, EvidenceList, ReadState, WriteState } from "./CultivationIntelligenceShared";
import { useIntelligence, useIntelligenceWrite } from "./cultivationIntelligenceQueries";
import { intelligenceScope, metricLabel, record, rows, textValue, type Connection, type RegistryMetric, type Room, type Workspace, type PushHealth } from "./cultivationIntelligenceTypes";
import "./cultivation-intelligence.css";

export function CultivationConnections() {
  return <ScopedConnections key={JSON.stringify(intelligenceScope())} />;
}
function ScopedConnections() {
  const [mode, setMode] = useState("file");
  const client = useQueryClient();
  const scopeKey = JSON.stringify(intelligenceScope());
  useEffect(() => () => { const scope: string[] = JSON.parse(scopeKey); void client.cancelQueries({ queryKey: ["cultivation-intelligence", ...scope] }); client.removeQueries({ queryKey: ["cultivation-intelligence", ...scope] }); }, [client, scopeKey]);
  const workspace = useIntelligence<Workspace>("/workspace");
  const connections = useIntelligence<{ connections: Connection[]; truncated: boolean }>("/connections");
  const [selected, setSelected] = useState("");
  const create = useIntelligenceWrite<Connection>("/connections", connection => setSelected(connection.id));
  return <section className="inventory-panel cultivation-intelligence" id="integration-cultivation"><h2>Cultivation connections</h2><p>Choose file evidence or normalized JSON push. Growlink remains export only. Supported Aranet Cloud and The Things Stack accounts connect below. Native Growlink, BACnet and Modbus need their own reviewed interfaces. Normalized HTTP push and finalized file imports are available independently. Import activity never establishes a live connection.</p>
    <ReadState query={workspace}>{scope => <><CultivationRadioSetup rooms={scope.rooms} /><CultivationNetworkSetup /><p>Administrator capability: {scope.can_manage_connections ? "Can manage cultivation connections" : "Read only. Administrator and effective cultivation connection permission required."}</p>
      {scope.can_manage_connections && <form onSubmit={event => { event.preventDefault(); const fields = new FormData(event.currentTarget); create.mutate({ provider: fields.get("provider"), label: fields.get("label"), mode, ...(mode === "push" ? { expected_interval_seconds: fields.get("expected_interval_seconds") ? Number(fields.get("expected_interval_seconds")) : null, stale_after_seconds: fields.get("stale_after_seconds") ? Number(fields.get("stale_after_seconds")) : null } : {}) }); }}><fieldset disabled={create.isPending}><div className="form-grid"><label>Collection mode<select value={mode} onChange={event => setMode(event.target.value)}><option value="file">File import</option><option value="push">Normalized JSON push</option></select></label><label>Import provider<select key={mode} name="provider"><option value="json">Generic JSON</option>{mode === "file" && <><option value="csv">Generic CSV</option><option value="growlink">Growlink export / live authorization pending</option></>}</select></label><label>Connection label<input name="label" required maxLength={120} /></label></div>{mode === "push" && <details><summary>Optional delivery expectations</summary><p>Use the actual producer schedule. These connection expectations do not establish per-sensor cadence or crop targets.</p><label>Expected interval (seconds)<input name="expected_interval_seconds" type="number" min={1} max={2678400} step={1} /></label><label>Stale after (seconds)<input name="stale_after_seconds" type="number" min={1} max={2678400} step={1} /></label></details>}<button className="primary">{mode === "push" ? "Create push connection" : "Create file configuration"}</button></fieldset><WriteState error={create.error} /></form>}
      <ReadState query={connections}>{data => <>{data.truncated && <p>Connection list is incomplete.</p>}{!data.connections.length && <p>No cultivation connections configured.</p>}<label>{data.connections.some(connection => connection.mode === "push") ? "Cultivation connection" : "File connection"}<select value={selected} onChange={event => setSelected(event.target.value)}><option value="">Choose a connection</option>{data.connections.filter(connection => connection.mode !== "network").map(connection => <option key={connection.id} value={connection.id}>{connection.label} Ãƒâ€šÃ‚Â· {connection.revoked_at || connection.status === "revoked" ? "Revoked" : connection.mode === "push" ? "Normalized JSON push" : "File evidence only"}</option>)}</select></label>
        {selected && (data.connections.find(connection => connection.id === selected) ? <ConnectionDetail key={JSON.stringify([...intelligenceScope(), selected])} connection={data.connections.find(connection => connection.id === selected)!} canManage={scope.can_manage_connections} rooms={scope.rooms} /> : <p>Selected connection is unavailable. Choose an exact record.</p>)}</>}</ReadState>
    </>}</ReadState>
  </section>;
}
function ConnectionDetail({ connection, canManage, rooms }: { connection: Connection; canManage: boolean; rooms: Room[] }) {
  const path = `/connections/${encodeURIComponent(connection.id)}`;
  const health = useIntelligence<PushHealth>(`${path}/health`);
  const devices = useIntelligence<{ devices: unknown[]; truncated: boolean }>(`${path}/devices`);
  const revoke = useIntelligenceWrite(`${path}/revoke`);
  const register = useIntelligenceWrite(`${path}/devices`);
  const drain = useIntelligenceWrite<{ processed: number; pending: number; conflicts: number }>(`${path}/drain`);
  const active = !connection.revoked_at && connection.status !== "revoked" && !revoke.isSuccess;
  return <div><p>Provider: {connection.provider} Ãƒâ€šÃ‚Â· Mode: {connection.mode} Ãƒâ€šÃ‚Â· Version {connection.version}</p><p>{active ? connection.mode === "push" ? "Normalized JSON push. Review grants and mappings below." : "File configuration. Live activation blocked." : "Revoked. Existing evidence is preserved; ingestion is disabled."}</p>
    {connection.mode === "push" && <CultivationPushSetup connection={connection} canManage={canManage && active} />}
    {connection.mode === "push" && <><button className="secondary" disabled={health.isFetching} onClick={() => void health.refetch()}>Refresh connection health</button>{health.isError && <p>Status unavailable</p>}</>}
    <ReadState query={health}>{data => connection.mode === "push" ? <ConnectionHealthPanel data={data} /> : <><p>Last import (count-only audit): {textValue(data.connection.last_import_at)}. Last local receipt: {textValue(record(data.edge).last_received_at)}. Last valid sensor reading: {textValue(record(data.edge).last_valid_observed_at)}.</p><p>These clocks do not establish live connection or expected freshness. Local states: {Object.entries(record(record(data.edge).counts)).map(([state, count]) => `${state}: ${textValue(count)}`).join(", ") || "Unknown"}.</p><p>Live contract: {data.live_contract_status === "blocked" ? "Blocked" : "Not approved for live activation"}. Local evidence store: {data.edge === null ? "Unavailable" : "Diagnostics available"}.</p></>}</ReadState>
    {canManage && active && <><button className="secondary" disabled={revoke.isPending} onClick={() => revoke.mutate({ version: connection.version })}>Revoke connection and preserve evidence</button><WriteState error={revoke.error} />
      <details><summary>Register device</summary><form onSubmit={event => { event.preventDefault(); const fields = new FormData(event.currentTarget); register.mutate({ version: connection.version, source_device_id: fields.get("source_device_id"), display_name: fields.get("display_name") || "" }); }}><fieldset disabled={register.isPending || register.isSuccess}><label>Source device ID<input required name="source_device_id" /></label><label>Device name<input name="display_name" /></label><button className="primary">Register device</button></fieldset><WriteState error={register.error} success={register.isSuccess} />{register.isSuccess && <button type="button" className="secondary" onClick={() => register.reset()}>Register another device</button>}</form></details>
    </>}
    <ReadState query={devices}>{data => <><h3>Scoped devices and mappings</h3>{data.truncated && <p>Device list is incomplete.</p>}{!data.devices.length && <p>No registered devices. There is no live device discovery.</p>}{rows(data.devices).map((device, index) => <DeviceDetails key={textValue(device.id, String(index))} device={device} canManage={canManage && active} rooms={rooms} />)}</>}</ReadState>
    {canManage && active && <><ImportEvidence connectionId={connection.id} connectionVersion={connection.version} /><details><summary>Process queued mapping evidence</summary><p>Retries local mapping resolution. No equipment control or automatic Work.</p><button className="secondary" disabled={drain.isPending} onClick={() => drain.mutate({ limit: 100 })}>Process up to 100 queued rows</button><WriteState error={drain.error} />{drain.data && <p role="status">Processed {drain.data.processed}; pending {drain.data.pending}; conflicts {drain.data.conflicts}.</p>}</details><ConnectionMaintenance path={path} /></>}
  </div>;
}
function ConnectionMaintenance({ path }: { path: string }) {
  const [open, setOpen] = useState(false);
  const [window, setWindow] = useState("");
  const maintenance = useIntelligence<Record<string, unknown>>(`${path}/maintenance`, open);
  const rollup = useIntelligenceWrite<Record<string, unknown>>(`${path}/rollup`);
  return <details onToggle={event => setOpen(event.currentTarget.open)}><summary>Local aggregate maintenance</summary>{open && <><ReadState query={maintenance}>{data => <><p>Retention protection: {textValue(data.retention_blocker, "Unknown protection state")}. Raw evidence cannot be deleted without durable acknowledged aggregates.</p><ArchiveRetention path={path} archiveConfigured={data.archive_configured === true} /><p>Limits: {Object.entries(record(data.configuration)).map(([key, value]) => `${key}: ${textValue(value)}`).join(", ") || "Unknown"}.</p></>}</ReadState><AggregateWindow onApply={setWindow} /><p>Selected aggregate window: {window ? new URLSearchParams(window).get("start") + " to " + new URLSearchParams(window).get("end") : "Choose explicit dates"}. This action builds local aggregates only; no cloud publication or receiver acknowledgement.</p><button className="secondary" disabled={!window || rollup.isPending} onClick={() => { const params = new URLSearchParams(window); rollup.mutate({ start: params.get("start"), end: params.get("end") }); }}>Build selected local aggregates</button><WriteState error={rollup.error} />{rollup.data && <p role="status">Rebuilt: {textValue(rollup.data.rebuilt)}; unchanged: {textValue(rollup.data.unchanged)}; blocked: {textValue(rollup.data.blocked)}; truncated: {rollup.data.truncated === true ? "Yes, incomplete" : rollup.data.truncated === false ? "No" : "Unknown"}. Missing evidence remains unknown.</p>}</>}</details>;
}
function ArchiveRetention({ path, archiveConfigured }: { path: string; archiveConfigured: boolean }) {
  const [cutoff, setCutoff] = useState("");
  const [reviewed, setReviewed] = useState<string | null>(null);
  const [acknowledged, setAcknowledged] = useState(false);
  const [error, setError] = useState("");
  const archive = useIntelligenceWrite<{ archived: number; acknowledged: number; stale: number; truncated: boolean }>(`${path}/archive`, () => { setReviewed(null); setAcknowledged(false); });
  const preview = useIntelligenceWrite<{ executed: false; eligible: null; blocker: string | null }>(`${path}/retention`);
  const remove = useIntelligenceWrite<{ executed: boolean; purged: number; protected: number; truncated: boolean; blocker: string | null }>(`${path}/retention`, () => { setReviewed(null); setAcknowledged(false); });
  const busy = archive.isPending || preview.isPending || remove.isPending;
  function prepare() {
    setReviewed(null); setAcknowledged(false); setError(""); remove.reset(); preview.reset();
    if (!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d{1,3})?Z$/.test(cutoff) || !Number.isFinite(Date.parse(cutoff)) || Date.parse(cutoff) >= Date.now()) { setError("Enter a past UTC timestamp ending in Z."); return; }
    preview.mutate({ before: cutoff, limit: 100, execute: false }, { onSuccess: result => { if (result.executed === false && result.eligible === null) setReviewed(cutoff); } });
  }
  return <section aria-label="Local archive and retention">{archiveConfigured ? <><button className="secondary" disabled={busy} onClick={() => archive.mutate({ limit: 100 })}>Archive local summaries</button><WriteState error={archive.error} />{archive.data && <p role="status">Archived: {archive.data.archived}. Exact revisions acknowledged: {archive.data.acknowledged}. Stale revisions: {archive.data.stale}. {archive.data.truncated ? "Archive is incomplete." : "Archive batch complete."} Raw readings stay local. No cloud publication.</p>}</> : <p>Local summary archive is not configured on this host.</p>}
    <details><summary>Raw reading retention</summary><p>Only eligible already-archived raw bodies can be removed. Pending, quarantined, conflicting and unacknowledged evidence stays protected. Identity records and summaries are preserved.</p><fieldset disabled={busy}><label>Raw readings before (UTC)<input value={cutoff} placeholder="2026-09-25T00:00:00Z" onChange={event => { setCutoff(event.target.value); setReviewed(null); setAcknowledged(false); preview.reset(); remove.reset(); setError(""); }} /></label><button className="secondary" onClick={prepare}>Preview retention prerequisites</button></fieldset>{error && <p role="alert">{error}</p>}<WriteState error={preview.error} />{reviewed === cutoff && preview.data && <><p>Preview checked prerequisites only. Eligible count is unknown until execution. Protection: {preview.data.blocker === "durable_aggregate_receiver_not_configured" ? "Local archive is not configured." : "Clean verified archives and resolved evidence are required."}</p><label><input type="checkbox" checked={acknowledged} disabled={busy} onChange={event => setAcknowledged(event.target.checked)} />I understand that only eligible already-archived raw bodies can be removed.</label><button className="secondary" disabled={!acknowledged || busy || !archiveConfigured} onClick={() => { if (reviewed === cutoff && acknowledged && archiveConfigured) remove.mutate({ before: reviewed, limit: 100, execute: true }); }}>Remove eligible raw readings</button></>}<WriteState error={remove.error} />{remove.data && <p role="status">{remove.data.executed ? `Raw bodies removed: ${remove.data.purged}. Protected: ${remove.data.protected}.` : "Removal was not executed."} {remove.data.truncated ? "This was an incomplete batch." : ""} {remove.data.protected > 0 ? "Protected evidence still needs resolved mappings and clean verified archives covering its full interval." : "Identity records and summaries remain preserved."}</p>}</details>
  </section>;
}
function DeviceMapping({ id, version: currentVersion, rooms }: { id: string; version: number; rooms: Room[] }) {
  const [version, setVersion] = useState(currentVersion);
  const registry = useIntelligence<{ metrics: RegistryMetric[] }>("/metrics");
  const [metric, setMetric] = useState("");
  const [roomId, setRoomId] = useState("");
  const map = useIntelligenceWrite<{ version: number }>(`/devices/${encodeURIComponent(id)}/mapping`, result => setVersion(result.version));
  const sensor = useIntelligenceWrite<{ version: number }>(`/devices/${encodeURIComponent(id)}/sensors`, result => setVersion(result.version));
  return <>{version !== currentVersion && <button className="secondary" onClick={() => { setVersion(currentVersion); map.reset(); sensor.reset(); }}>Use current device version {currentVersion} and keep input</button>}<form onSubmit={event => { event.preventDefault(); const fields = new FormData(event.currentTarget); map.mutate({ version, room_id: fields.get("room_id"), zone_id: fields.get("zone_id") || null, effective_at: new Date(String(fields.get("effective_at")) + "Z").toISOString() }); }}><h4>New time-effective room mapping</h4><fieldset disabled={map.isPending || map.isSuccess}><label>Mapped room<select name="room_id" required value={roomId} onChange={event => setRoomId(event.target.value)}><option value="">Choose canonical room</option>{rooms.map(room => <option key={room.id} value={room.id}>{room.display_name || room.room_code}</option>)}</select></label><ZoneSelect key={roomId} roomId={roomId} /><label>Effective at (UTC)<input type="datetime-local" name="effective_at" defaultValue={new Date(Date.now() + 3600000).toISOString().slice(0, 16)} required /></label><p>Time zone: UTC. Defaults one hour ahead. Existing evidence keeps its historical mapping.</p><button className="primary">Save mapping revision</button></fieldset><WriteState error={map.error} success={map.isSuccess} />{map.isSuccess && <button type="button" onClick={() => map.reset()}>Add another mapping revision</button>}</form>
    <ReadState query={registry}>{data => <form onSubmit={event => { event.preventDefault(); const fields = new FormData(event.currentTarget); sensor.mutate({ version, source_channel: fields.get("source_channel"), source_metric: fields.get("source_metric"), source_unit: fields.get("source_unit"), metric }); }}><h4>Map source channel</h4><fieldset disabled={sensor.isPending || sensor.isSuccess}><div className="form-grid"><label>Source channel<input required name="source_channel" /></label><label>Source metric<input required name="source_metric" /></label><label>Source unit<input required name="source_unit" /></label><label>Normalized measurement<select required value={metric} onChange={event => setMetric(event.target.value)}><option value="">Choose measurement</option>{data.metrics.map(item => <option key={item.metric} value={item.metric}>{metricLabel(item.metric, data.metrics)} ({item.unit})</option>)}</select></label></div><button className="primary">Save channel mapping</button></fieldset><WriteState error={sensor.error} success={sensor.isSuccess} />{sensor.isSuccess && <button type="button" onClick={() => sensor.reset()}>Map another channel</button>}</form>}</ReadState>
  </>;
}
function DeviceDetails({ device, canManage, rooms }: { device: Record<string, unknown>; canManage: boolean; rooms: Room[] }) {
  const [open, setOpen] = useState(false);
  const id = typeof device.id === "string" ? device.id : "";
  const mappings = useIntelligence<{ mappings: unknown[]; truncated: boolean }>(`/devices/${encodeURIComponent(id)}/mapping`, open && Boolean(id));
  const sensors = useIntelligence<{ sensors: unknown[]; truncated: boolean }>(`/devices/${encodeURIComponent(id)}/sensors`, open && Boolean(id));
  return <details onToggle={event => setOpen(event.currentTarget.open)}><summary>{textValue(device.display_name || device.source_device_id || device.id)}</summary><p>Canonical device: {id || "Unknown"}. Source device: {textValue(device.source_device_id)}. Version: {textValue(device.version)}</p>{open && <><ReadState query={mappings}>{data => <><EvidenceList value={data.mappings} empty="No mapping history. Room and zone attribution unknown." />{data.mappings.map((item, i) => { const entry = record(item); return <p key={i}>Zone: {textValue(entry.zone_id, "No zone assigned")}. Effective: {textValue(entry.effective_at)}</p>; })}{data.truncated && <p>Mapping history incomplete.</p>}</>}</ReadState><ReadState query={sensors}>{data => <>{rows(data.sensors).map((sensor, i) => <p key={i}>{textValue(sensor.source_channel)}: {textValue(sensor.source_metric)} ({textValue(sensor.source_unit)}) to {textValue(sensor.metric)} ({textValue(sensor.unit)})</p>)}{!data.sensors.length && <p>No mapped sensor channels.</p>}{data.truncated && <p>Sensor list incomplete.</p>}</>}</ReadState>{canManage && id && typeof device.version === "number" && <DeviceMapping id={id} version={device.version} rooms={rooms} />}</>}</details>;
}
type Mapping = ImportMapping;
type Preview = { sample_rows?: PreviewSample[]; samples_truncated?: boolean; digest: string; rows: unknown; unknown_channels: unknown[]; conflicts: unknown[]; can_commit: boolean };
export function ImportEvidence({ connectionId, connectionVersion = 0 }: { connectionId: string; connectionVersion?: number }) {
  const [reviewedVersion, setReviewedVersion] = useState<number | null>(null);
  const [format, setFormat] = useState("json");
  const [content, setContent] = useState("");
  const [mappings, setMappings] = useState<Mapping[]>([]);
  const registry = useIntelligence<{ metrics: RegistryMetric[] }>("/metrics");
  const source = useMemo(() => { try { return { rows: readSourcePreview(content, format), error: "" }; } catch (error) { return { rows: [], error: error instanceof Error ? error.message : "Unable to preview selected file." }; } }, [content, format]);
  const [validation, setValidation] = useState("");
  const [readingFile, setReadingFile] = useState(false);
  const [reviewed, setReviewed] = useState<{ format: string; content: string; mappings: Mapping[]; digest: string } | null>(null);
  const preview = useIntelligenceWrite<Preview>(`/connections/${encodeURIComponent(connectionId)}/imports/preview`);
  const commit = useIntelligenceWrite<{ accepted: number; duplicates: number; conflicts: number; queued_for_mapping: number; quarantined?: number; dispositions?: unknown[] }>(`/connections/${encodeURIComponent(connectionId)}/imports`, () => setReviewed(null));
  const invalidate = () => { setReviewed(null); preview.reset(); commit.reset(); setValidation(""); };
  function prepare() {
    setValidation(""); setReviewed(null); setReviewedVersion(connectionVersion);
    if (!content.trim() || new TextEncoder().encode(content).length > 1048576) { setValidation("Supply JSON or CSV content up to 1 MiB and 500 rows."); return; }
    if (source.error) { setValidation(source.error); return; }
    if (mappings.some(mapping => Object.values(mapping).some(value => !value.trim()))) { setValidation("Complete each channel mapping or remove it to leave that channel pending review."); return; }
    preview.mutate({ format, content, mappings }, { onSuccess: result => { if (result.can_commit && typeof result.digest === "string" && result.digest) setReviewed({ format, content, mappings, digest: result.digest }); } });
  }
  const busy = preview.isPending || commit.isPending || readingFile;
  return <section><h3>Import JSON / CSV evidence</h3><p>Choose a file explicitly or paste measurement content. Maximum 1 MiB and 500 rows. Preview validates content before a separate digest-confirmed commit. No filesystem path is sent.</p><fieldset disabled={busy}><label>File format<select value={format} onChange={event => { invalidate(); setFormat(event.target.value); }}><option value="json">JSON</option><option value="csv">CSV</option></select></label><label>Choose evidence file<input type="file" accept=".json,.csv,application/json,text/csv" onChange={async event => { const file = event.target.files?.[0]; invalidate(); setContent(""); if (!file) return; if (file.size > 1048576) { setValidation("File exceeds 1 MiB."); return; } setReadingFile(true); try { setContent(await file.text()); setFormat(file.name.toLowerCase().endsWith(".csv") ? "csv" : "json"); } catch { setValidation("Unable to read this file. Choose it again."); } finally { setReadingFile(false); } }} /></label><label>Measurement content<textarea rows={6} value={content} onChange={event => { invalidate(); setContent(event.target.value); }} /></label><p>Required row fields: event_id, source_device_id, source_channel, source_metric, value, unit, observed_at. Timestamps need a timezone, for example 2026-09-26T12:00:00Z or 2026-09-26T08:00:00-04:00. Unit examples: C for temperature, s for duration. Values are observations, not agronomic targets. JSON is an array of objects with these exact keys; CSV starts with this exact header:</p><code>event_id,source_device_id,source_channel,source_metric,value,unit,observed_at</code>{source.error && <p role="alert">{source.error}</p>}{source.rows.length > 0 && <SourcePreviewTable readings={source.rows} />}<ReadState query={registry}>{data => <><button type="button" className="secondary" disabled={!source.rows.length} onClick={() => { invalidate(); const unique = new Map<string, Mapping>(); for (const row of source.rows) { const mapping = { source_channel: textValue(row.source_channel, ""), source_metric: textValue(row.source_metric, ""), unit: textValue(row.unit, ""), metric: "" }; const key = JSON.stringify([mapping.source_channel, mapping.source_metric, mapping.unit]); if (!unique.has(key)) unique.set(key, mapping); } if (unique.size > 200) { setValidation("More than 200 distinct channels. Split the export before mapping."); return; } setMappings([...unique.values()]); }}>Use source channels for mapping</button><TelemetryMappingTable mappings={mappings} metrics={data.metrics} onChange={value => { invalidate(); setMappings(value); }} /></>}</ReadState><button className="secondary" onClick={prepare}>Preview import</button></fieldset>
    {validation && <p role="alert">{validation}</p>}<WriteState error={preview.error} />{preview.data && <div><p>Preview rows: {typeof preview.data.rows === "number" ? preview.data.rows : Array.isArray(preview.data.rows) ? preview.data.rows.length : "Unknown"}. Unknown channels: {preview.data.unknown_channels.length}. Conflicts: {preview.data.conflicts.length}.</p><NormalizedPreviewTable samples={preview.data.sample_rows || []} truncated={preview.data.samples_truncated === true} />{preview.data.unknown_channels.length > 0 ? <EvidenceList value={preview.data.unknown_channels} empty="" /> : <p>No unknown channels reported.</p>}{preview.data.conflicts.length > 0 ? <EvidenceList value={preview.data.conflicts} empty="" /> : <p>No preview conflicts reported.</p>}<p>{preview.data.can_commit ? "Review this preview before committing." : "Commit blocked. Resolve validation or mapping conflicts first."}</p></div>}
    {reviewed && reviewedVersion !== connectionVersion && <p role="alert">Connection mapping version changed. Input is retained; preview again before committing.</p>}<button className="primary" disabled={!reviewed || busy || reviewedVersion !== connectionVersion} onClick={() => { if (reviewed && reviewedVersion === connectionVersion) commit.mutate(reviewed); }}>Commit reviewed import</button><WriteState error={commit.error} />{commit.data && <p role="status">Import committed. Accepted {commit.data.accepted}; duplicates {commit.data.duplicates}; conflicts {commit.data.conflicts}; queued for mapping {commit.data.queued_for_mapping}; quarantined {commit.data.quarantined ?? "Unknown"}. This is file evidence, not live connection health.</p>}{commit.data?.dispositions && <ul>{rows(commit.data.dispositions).map((item, i) => <li key={i}>{textValue(item.status)}: {textValue(item.reason, "No reason supplied")}</li>)}</ul>}
  </section>;
}
