import { describe, expect, it } from "vitest";
import { renderToStaticMarkup } from "react-dom/server";
import { CurrentRoomConditions } from "./CurrentRoomConditions";
import type { LatestReading } from "./cultivationIntelligenceTypes";

const reading: LatestReading = { connection_id: "connection", source_device_id: "source", source_channel: "air", device_id: "device", sensor_id: "sensor", metric: "temperature", value: 25, unit: "C", original_value: 77, original_unit: "F", observed_at: "2026-09-26T12:01:00Z", received_at: "2026-09-26T12:01:02Z", data_age_seconds: 2, latency_seconds: 2, quality: "valid", state: "ready", reason: null, freshness: "fresh", status: "in_target", snapshot: { organization_id: "org", facility_id: "facility", connection_id: "connection", room_id: "room", device_id: "device", sensor_id: "sensor", mapping_revision: "mapping", metric: "temperature", effective_from: "2026-09-26T00:00:00Z", effective_to: "2026-09-27T00:00:00Z", recipe_revision: "recipe", target_min: 20, target_max: 26 } };
function render(readings: LatestReading[]) { return renderToStaticMarkup(<CurrentRoomConditions roomId="room" latest={{ as_of: "2026-09-26T12:01:02Z", readings, truncated: false, status: "UNKNOWN" }} />); }
describe("current mapped sensor evidence", () => {
  it("shows normalized 77 F as 25 C with immutable source evidence", () => { const html = render([reading]); expect(html).toContain("25 C"); expect(html).toContain("Original: 77 F"); expect(html).toContain("Mapping revision: mapping"); expect(html).toContain("Within recorded target"); });
  it.each(["quarantined", "conflict", "archived", "pending"])("hides invalid latest value and original for %s", state => { const html = render([{ ...reading, state, value: 98765, original_value: 98766, status: state === "archived" ? "unavailable" : "invalid" }]); expect(html).not.toContain("98765"); expect(html).not.toContain("98766"); expect(html).toContain("Current value unavailable"); });
  it("does not let another fresh source mask a stale source", () => { const html = render([reading, { ...reading, source_device_id: "old-source", sensor_id: "old", value: 22, freshness: "stale", status: "stale" }]); expect(html).toContain("25 C"); expect(html).toContain("Stale source. Current value unknown"); expect(html).not.toContain("22 C"); });
  it.each([null, 120])("separates current out-of-target readings from threshold %s", threshold_seconds => { const html = render([{ ...reading, value: 30, status: "above", snapshot: { ...reading.snapshot, threshold_seconds } }]); expect(html).toContain("Above recorded target"); expect(html).toContain("does not establish a duration-qualified alarm"); expect(html).toContain(threshold_seconds ? "120 seconds" : "not configured"); });
  it("keeps missing recipe unknown, supports future metrics and excludes other rooms", () => { const html = render([{ ...reading, metric: "future_metric", unit: "custom", snapshot: { ...reading.snapshot, recipe_revision: null } }, { ...reading, value: 999, snapshot: { ...reading.snapshot, room_id: "other" } }]); expect(html).toContain("Other measurements"); expect(html).toContain("future metric"); expect(html).toContain("Target unknown"); expect(html).not.toContain("Within recorded target"); expect(html).not.toContain("999"); });
  it("shows exact empty state without old manual or aggregate fallback", () => { expect(render([])).toContain("No mapped sensor readings yet."); });
});
