import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { apiDownload, apiGet, apiPost, apiPostForm, downloadBlob } from "../lib/api";
import type { AuditDetail, AuditLine, AuditSummary, InventoryPackage, InventoryResponse } from "../types/inventory";
import { CameraScanner } from "./CameraScanner";
import { StreamlitDialog } from "./StreamlitDialog";

type Operation = "retail" | "production";
type SnapshotPreview = { reference:string; columns:string[]; rows:Record<string,unknown>[]; row_count:number };
type SnapshotScope = { reference:string; row_count:number; lot_ids:string[] };
type CountTarget = { line:AuditLine; rawCode:string; recount:boolean };

const EDITABLE = new Set(["draft","in_progress"]);
const REASONS = ["","Count correction","Damage","Waste","Return","Transfer timing","Receiving timing","Unknown"];
const EMPTY_PACKAGES:InventoryPackage[]=[];
const EMPTY_AUDITS:AuditSummary[]=[];

export function InventoryAudits({ operation, embedded = false }: { operation: Operation; embedded?: boolean }) {
  const client=useQueryClient();
  const [selectedId,setSelectedId]=useState("");
  const [snapshotScope,setSnapshotScope]=useState<SnapshotScope|null>(null);
  const audits=useQuery({queryKey:["audits",operation],queryFn:({signal})=>apiGet<AuditSummary[]>(`/api/v1/inventory/${operation}/audits`,signal)});
  const inventory=useQuery({queryKey:["audit-inventory",operation],queryFn:({signal})=>apiGet<InventoryResponse>(`/api/v1/inventory/${operation}/packages?view=all`,signal)});
  const detail=useQuery({queryKey:["audit",operation,selectedId],enabled:Boolean(selectedId),queryFn:({signal})=>apiGet<AuditDetail>(`/api/v1/inventory/${operation}/audits/${selectedId}`,signal)});
  const refresh=async()=>{await Promise.all([client.invalidateQueries({queryKey:["audits",operation]}),client.invalidateQueries({queryKey:["audit",operation,selectedId]}),client.invalidateQueries({queryKey:["audit-inventory",operation]}),client.invalidateQueries({queryKey:["inventory"]})])};
  const current=detail.data;
  return <div className={embedded?"embedded-audits exact-audits":"page exact-audits"}>
    <h2>{operation==="retail"?"Retail Scan Audit":"Inventory Audit & Reconciliation"}</h2>
    <p className="section-note">Each audit is an independent saved workspace. Start another audit at any time, pause one, return later, or stop and report on partial work.</p>
    {operation==="retail"?<RetailSnapshotIntake inventory={inventory.data?.items??EMPTY_PACKAGES} scope={snapshotScope} onImported={scope=>{setSnapshotScope(scope);refresh()}}/>:null}
    <CreateAudit operation={operation} packages={inventory.data?.items??EMPTY_PACKAGES} audits={audits.data??EMPTY_AUDITS} snapshotScope={snapshotScope} onCreated={audit=>{setSelectedId(audit.id);refresh()}}/>
    {audits.isError?<div className="form-error">Audit history could not be loaded: {audits.error.message}</div>:null}
    <AuditDashboard audits={audits.data??EMPTY_AUDITS} selectedId={selectedId} operation={operation} onSelect={setSelectedId} onSaved={refresh}/>
    {selectedId&&detail.isLoading?<div className="state">Loading saved audit…</div>:null}
    {detail.isError?<div className="form-error">Audit could not be loaded: {detail.error.message}</div>:null}
    {current?<OpenAudit key={current.audit.id} operation={operation} detail={current} onBack={()=>setSelectedId("")} onSaved={refresh}/>:null}
  </div>;
}

function RetailSnapshotIntake({inventory,scope,onImported}:{inventory:InventoryPackage[];scope:SnapshotScope|null;onImported:(scope:SnapshotScope)=>void}){
  const [source,setSource]=useState("Upload Dutchie inventory export");
  const [preview,setPreview]=useState<SnapshotPreview|null>(null);
  const [mapping,setMapping]=useState<Record<string,string>>({});
  const previewFile=useMutation({mutationFn:async(file:File)=>{const form=new FormData();form.append("file",file);return apiPostForm<SnapshotPreview>("/api/v1/inventory/retail/audits/retail-snapshot/preview",form)},onSuccess:data=>{setPreview(data);setMapping(guessMapping(data.columns))}});
  const importFile=useMutation({mutationFn:()=>apiPost<SnapshotScope&{rows:number}>("/api/v1/inventory/retail/audits/retail-snapshot/import",{reference:preview?.reference,rows:preview?.rows??[],mapping}),onSuccess:data=>onImported({reference:data.reference,row_count:data.rows,lot_ids:data.lot_ids})});
  const usingActive=source.startsWith("Use active");
  return <details className="streamlit-expander audit-source" open={!inventory.length}><summary>Load or refresh Dutchie retail inventory</summary><div className="streamlit-expander-body">
    <p>Upload the inventory report you want to audit. Reusing Buyer Ops inventory is still available, but a fresh upload is the default.</p>
    {scope?<div className="info-banner">Next audit source: <strong>{scope.reference}</strong> · {scope.row_count.toLocaleString()} imported row(s).</div>:null}
    <fieldset className="radio-row"><legend>Inventory source</legend><label><input type="radio" checked={!usingActive} onChange={()=>setSource("Upload Dutchie inventory export")}/>Upload Dutchie inventory export</label>{inventory.length?<label><input type="radio" checked={usingActive} onChange={()=>{setSource("Use active Buyer Ops inventory");setPreview(null);onImported({reference:"Active Buyer Ops inventory",row_count:inventory.length,lot_ids:inventory.map(row=>row.id)})}}/>Use active Buyer Ops inventory</label>:null}</fieldset>
    {!usingActive?<label className="file-drop">Dutchie inventory file<input type="file" accept=".csv,.xlsx,.xls" onChange={event=>{const file=event.target.files?.[0];if(file)previewFile.mutate(file)}}/></label>:null}
    {previewFile.isError?<div className="form-error">{previewFile.error.message}</div>:null}
    {preview?<><p>Selected source: <strong>{preview.reference}</strong> · {preview.row_count.toLocaleString()} row(s)</p><SnapshotMapping columns={preview.columns} mapping={mapping} onChange={(field,value)=>setMapping(current=>({...current,[field]:value}))}/><button className="primary" onClick={()=>importFile.mutate()}>Import & Use for Next Audit</button>{importFile.isSuccess?<div className="success-banner">Imported {preview.row_count.toLocaleString()} rows from {preview.reference}. This upload is now the source for your next audit.</div>:null}{importFile.isError?<div className="form-error">Retail inventory could not be imported: {importFile.error.message}</div>:null}</>:usingActive?<div className="info-banner">Selected source: <strong>Active Buyer Ops inventory</strong> · {inventory.length.toLocaleString()} row(s)</div>:<div className="info-banner">Upload the inventory report you want to audit, or intentionally choose current Buyer Ops inventory.</div>}
  </div></details>;
}

const SNAPSHOT_FIELDS:[string,string][]=[["product_name","Product name *"],["quantity","Quantity in stock *"],["sku","Sku"],["upc","Upc"],["external_product_id","External Product Id"],["lot_code","Lot Code"],["compliance_package_id","Compliance Package Id"],["external_inventory_id","External Inventory Id"],["barcode_value","Barcode Value"],["location_code","Location Code"],["unit","Unit"],["unit_cost","Unit Cost"],["retail_price","Retail Price"]];
function SnapshotMapping({columns,mapping,onChange}:{columns:string[];mapping:Record<string,string>;onChange:(field:string,value:string)=>void}){return <div className="form-grid two">{SNAPSHOT_FIELDS.map(([field,label])=><label key={field}>{label}<select value={mapping[field]??"Not provided"} onChange={event=>onChange(field,event.target.value)}>{!field.match(/^(product_name|quantity)$/)?<option>Not provided</option>:null}{columns.map(column=><option key={column}>{column}</option>)}</select></label>)}</div>}

function CreateAudit({operation,packages,audits,snapshotScope,onCreated}:{operation:Operation;packages:InventoryPackage[];audits:AuditSummary[];snapshotScope:SnapshotScope|null;onCreated:(audit:AuditSummary)=>void}){
  const [number,setNumber]=useState(`${operation==="retail"?"RTL":"PROD"}-${timestamp()}`);
  const [scope,setScope]=useState(operation==="retail"?"Full store":"Full facility");
  const [selected,setSelected]=useState<string[]>([]);
  const [blind,setBlind]=useState(true);const [tolerance,setTolerance]=useState(0);const [notes,setNotes]=useState("");
  useEffect(()=>{const allowed=snapshotScope?.lot_ids?.length?snapshotScope.lot_ids:packages.map(row=>row.id);setSelected(allowed);if(operation==="retail"&&snapshotScope?.reference)setScope(`Uploaded report: ${snapshotScope.reference}`)},[operation,packages,snapshotScope]);
  const create=useMutation({mutationFn:()=>apiPost<AuditSummary>(`/api/v1/inventory/${operation}/audits`,{audit_number:number,scope_label:scope,notes,lot_ids:selected,blind_count:blind,recount_tolerance:tolerance}),onSuccess:audit=>{onCreated(audit);setNumber(`${operation==="retail"?"RTL":"PROD"}-${timestamp(new Date(Date.now()+1000))}`);setNotes("")}});
  return <details className="streamlit-expander" open={!audits.length}><summary>Start New Audit</summary><div className="streamlit-expander-body">
    {!packages.length?<div className="info-banner">Load inventory for this facility before starting an audit.</div>:<>{operation==="retail"&&snapshotScope?.lot_ids.length?<><div className="success-banner">Audit source: <strong>{snapshotScope.reference}</strong> · {snapshotScope.lot_ids.length.toLocaleString()} inventory item(s) from that upload.</div><p>Only items represented in the most recently imported audit report are selected for this new audit.</p></>:operation==="retail"?<div className="warning-banner">No uploaded audit report is selected. This audit will use all durable inventory currently stored for the facility.</div>:null}<div className="form-grid two"><label>Audit name / number<input value={number} onChange={event=>setNumber(event.target.value)}/></label><label>Scope<input value={scope} onChange={event=>setScope(event.target.value)}/></label></div><label>Inventory to count<select multiple value={selected} onChange={event=>setSelected([...event.target.selectedOptions].map(option=>option.value))}>{packages.filter(row=>!snapshotScope?.lot_ids.length||snapshotScope.lot_ids.includes(row.id)).map(row=><option value={row.id} key={row.id}>{row.product_name} · {row.lot_code} · {row.location}</option>)}</select></label><div className="form-grid two"><label className="toggle"><input type="checkbox" checked={blind} onChange={event=>setBlind(event.target.checked)}/>Blind first count</label><label>Recount tolerance<input type="number" min="0" step="0.1" value={tolerance} onChange={event=>setTolerance(Number(event.target.value))}/></label></div><label>Notes (optional)<textarea rows={3} value={notes} onChange={event=>setNotes(event.target.value)}/></label><button className="primary" disabled={!number.trim()||!selected.length||create.isPending} onClick={()=>create.mutate()}>Start New Audit</button>{create.isSuccess?<div className="success-banner">Audit started from the selected inventory source. You can leave it, start another, and return later.</div>:null}{create.isError?<div className="form-error">We couldn’t start the audit. Nothing was opened: {create.error.message}</div>:null}</>}</div></details>;
}

function AuditDashboard({audits,selectedId,operation,onSelect,onSaved}:{audits:AuditSummary[];selectedId:string;operation:Operation;onSelect:(id:string)=>void;onSaved:()=>void}){
  const transition=useMutation({mutationFn:({id,status}:{id:string;status:string})=>apiPost(`/api/v1/inventory/${operation}/audits/${id}/status`,{status}),onSuccess:onSaved});
  const groups:[string,Set<string>][]=[["Active",new Set(["in_progress","draft"])],["Paused",new Set(["paused"])],["Stopped",new Set(["stopped"])],["Completed",new Set(["completed"])],["Cancelled",new Set(["cancelled"])] ];
  return <section className="audit-dashboard"><h3>Audit Dashboard</h3>{!audits.length?<div className="info-banner">No audit history yet. Start the first audit above.</div>:groups.map(([heading,statuses])=>{const rows=audits.filter(audit=>statuses.has(audit.status));return rows.length?<div key={heading}><h4>{heading} Audits</h4>{rows.map(audit=><article className="audit-session-card" key={audit.id}><div><strong>{audit.audit_number}</strong><span>{audit.scope_label} · {label(audit.status)}</span><small>{audit.scanned_count}/{audit.total_count} scanned · {(audit.scanned_count/Math.max(audit.total_count,1)*100).toFixed(0)}% · {audit.recount_count} recount(s) waiting · Started by {audit.created_by}</small>{selectedId===audit.id?<small>Currently open</small>:null}</div><button className="secondary" onClick={()=>{if(["paused","draft"].includes(audit.status))transition.mutate({id:audit.id,status:"in_progress"});onSelect(audit.id)}}>{audit.status==="in_progress"?"Open":["paused","draft"].includes(audit.status)?"Resume":"Review"}</button></article>)}</div>:null})}{transition.isError?<div className="form-error">{transition.error.message}</div>:null}</section>;
}

function OpenAudit({operation,detail,onBack,onSaved}:{operation:Operation;detail:AuditDetail;onBack:()=>void;onSaved:()=>void}){
  const audit=detail.audit;const editable=EDITABLE.has(audit.status);const scanned=detail.lines.filter(row=>row.first_count_quantity!=null).length;const recounts=detail.lines.filter(row=>row.recount_required).length;const pending=detail.lines.length-scanned;const exceptions=detail.scans.filter(row=>row.match_status!=="matched");
  const [showReport,setShowReport]=useState(["stopped","completed","cancelled"].includes(audit.status));const [confirmed,setConfirmed]=useState(false);const [postAdjustments,setPostAdjustments]=useState(true);const [target,setTarget]=useState<CountTarget|null>(null);
  useEffect(()=>{if(["stopped","completed","cancelled"].includes(audit.status))setShowReport(true)},[audit.status]);
  const transition=useMutation({mutationFn:(status:string)=>apiPost(`/api/v1/inventory/${operation}/audits/${audit.id}/status`,{status}),onSuccess:(_data,status)=>{onSaved();if(status==="paused")onBack()}});
  const complete=useMutation({mutationFn:()=>apiPost(`/api/v1/inventory/${operation}/audits/${audit.id}/complete`,{post_adjustments:postAdjustments}),onSuccess:onSaved});
  return <section className="open-audit"><hr/><h2>{audit.audit_number}</h2><p>Audit ID: {audit.id} · {audit.scope_label} · {label(audit.status)}</p><div className="metrics four"><Metric name="Products scanned" value={`${scanned}/${detail.lines.length}`}/><Metric name="Remaining" value={pending}/><Metric name="Recounts" value={recounts}/><Metric name="Scan exceptions" value={exceptions.length}/></div><div className="audit-nav"><button className="secondary" onClick={onBack}>Back to Dashboard</button>{editable?<button className="secondary" onClick={()=>transition.mutate("paused")}>Pause Audit</button>:<span/>}{editable?<button className="secondary" onClick={()=>transition.mutate("stopped")}>Stop & Review</button>:<span/>}<button className="secondary" onClick={()=>setShowReport(true)}>Generate Current Report</button></div>
    {editable&&pending?<><div className="info-banner">First pass in progress: {pending} item(s) remain. You can pause or stop at any time.</div><LiveScanner operation={operation} auditId={audit.id} lines={detail.lines} recount={false} onTarget={setTarget} onSaved={onSaved}/></>:null}
    {editable&&!pending&&recounts?<><div className="warning-banner">First pass complete. {recounts} item(s) require recount.</div><LiveScanner operation={operation} auditId={audit.id} lines={detail.lines} recount onTarget={setTarget} onSaved={onSaved}/></>:null}
    {editable&&!pending&&!recounts?<div className="completion-panel"><div className="success-banner">The intended count scope is fully counted and ready for completion.</div><label className="toggle"><input type="checkbox" checked={confirmed} onChange={event=>setConfirmed(event.target.checked)}/>I reviewed the count and confirm the intended audit scope is complete</label><label className="toggle"><input type="checkbox" checked={postAdjustments} onChange={event=>setPostAdjustments(event.target.checked)}/>Post approved corrections to the append-only inventory ledger</label><button className="primary" disabled={!confirmed} onClick={()=>complete.mutate()}>Complete Audit</button></div>:null}
    {audit.status==="stopped"?<><div className="warning-banner">This audit was stopped before completion. Its current results are preserved.</div><button className="primary" onClick={()=>transition.mutate("in_progress")}>Reopen Audit</button></>:null}{audit.status==="paused"?<button className="primary" onClick={()=>transition.mutate("in_progress")}>Resume Audit</button>:null}{audit.status==="completed"?<div className="success-banner">This audit is completed and preserved as historical record.</div>:null}{!editable&&!['stopped','paused','completed'].includes(audit.status)?<div className="info-banner">Audit status: {label(audit.status)}</div>:null}
    {exceptions.length?<details className="streamlit-expander"><summary>Scan exceptions ({exceptions.length})</summary><div className="streamlit-expander-body"><Table rows={exceptions.map(row=>({"Scanned Code":row.raw_code,Result:label(row.match_status),Stage:label(row.scan_stage),"Scanned By":row.scanned_by,Time:row.scanned_at}))}/></div></details>:null}
    {showReport?<AuditReport operation={operation} detail={detail}/>:null}{transition.isError||complete.isError?<div className="form-error">{transition.error?.message??complete.error?.message}</div>:null}<CountDialog operation={operation} auditId={audit.id} target={target} onClose={()=>setTarget(null)} onSaved={()=>{setTarget(null);onSaved()}}/>
  </section>;
}

function LiveScanner({operation,auditId,lines,recount,onTarget,onSaved}:{operation:Operation;auditId:string;lines:AuditLine[];recount:boolean;onTarget:(target:CountTarget)=>void;onSaved:()=>void}){
  const [code,setCode]=useState("");const [manual,setManual]=useState("");
  const eligible=lines.filter(line=>recount?line.recount_required:line.first_count_quantity==null);
  const preview=useMutation({mutationFn:(rawCode:string)=>apiPost<AuditLine>(`/api/v1/inventory/${operation}/audits/${auditId}/scan/preview`,{raw_code:rawCode,recount}),onSuccess:(line,rawCode)=>onTarget({line,rawCode,recount}),onSettled:onSaved});
  return <section className="live-scanner"><h3>{recount?"Recount scanner":"Scan and count"}</h3><p>Camera, Bluetooth/USB scanner, typed code, and manual product selection all remain available.</p><CameraScanner disabled={preview.isPending} onCode={value=>preview.mutate(value)}/><details className="streamlit-expander"><summary>Bluetooth / USB scanner or typed code</summary><div className="streamlit-expander-body"><label>Scan or enter item code<input value={code} placeholder="Dutchie ID, UPC, SKU, lot, or METRC package ID" onChange={event=>setCode(event.target.value)} onKeyDown={event=>{if(event.key==="Enter"&&code.trim())preview.mutate(code)}}/></label><button className="primary" disabled={!code.trim()||preview.isPending} onClick={()=>preview.mutate(code)}>Find item</button></div></details><details className="streamlit-expander"><summary>Cannot scan? Choose the inventory item</summary><div className="streamlit-expander-body">{eligible.length?<><label>Inventory item<select value={manual||eligible[0].id} onChange={event=>setManual(event.target.value)}>{eligible.map(line=><option value={line.id} key={line.id}>{line.product_name} · {line.lot_code} · {line.location}</option>)}</select></label><button className="secondary" onClick={()=>{const line=eligible.find(row=>row.id===(manual||eligible[0].id));if(line)onTarget({line,rawCode:line.primary_code,recount})}}>Enter count for selected item</button></>:<div className="success-banner">No items remain in this count stage.</div>}</div></details>{preview.isError?<div className="form-error">{preview.error.message}</div>:null}</section>;
}

function CountDialog({operation,auditId,target,onClose,onSaved}:{operation:Operation;auditId:string;target:CountTarget|null;onClose:()=>void;onSaved:()=>void}){const [quantity,setQuantity]=useState(0);const [reason,setReason]=useState("");const [notes,setNotes]=useState("");useEffect(()=>{setQuantity(0);setReason("");setNotes("")},[target]);const save=useMutation({mutationFn:()=>apiPost(`/api/v1/inventory/${operation}/audits/${auditId}/scan/count`,{raw_code:target?.rawCode,quantity,recount:target?.recount??false,reason,notes}),onSuccess:onSaved});const line=target?.line;return <StreamlitDialog open={Boolean(target)} onClose={onClose} title="Enter inventory count">{line?<div className="count-dialog"><h3>{line.product_name}</h3><p>{line.lot_code} · {line.location}</p>{target?.recount||line.expected_quantity!=null?<Metric name="Expected quantity" value={`${line.expected_quantity??0} ${line.unit}`}/>:<div className="info-banner">Blind count is active. Expected inventory stays hidden during the first pass.</div>}<label>Physical quantity in stock<input type="number" min="0" step="1" value={quantity} onChange={event=>setQuantity(Number(event.target.value))}/></label><label>Variance reason<select value={reason} onChange={event=>setReason(event.target.value)}>{REASONS.map(value=><option key={value}>{value}</option>)}</select></label><label>Count note (optional)<input value={notes} onChange={event=>setNotes(event.target.value)}/></label><div className="two-column-grid"><button className="primary" onClick={()=>save.mutate()}>Save & scan next</button><button className="secondary" onClick={onClose}>Cancel</button></div>{save.isError?<div className="form-error">Count was not saved: {save.error.message}</div>:null}</div>:null}</StreamlitDialog>}

function AuditReport({operation,detail}:{operation:Operation;detail:AuditDetail}){const status=EDITABLE.has(detail.audit.status)?"Partial":label(detail.audit.status);const rows=detail.lines.map(line=>({"Product Name":line.product_name,"SKU / UPC":line.sku_or_upc,"Lot / Batch":line.lot_code,"METRC Package":line.metrc_package,Location:line.location,Expected:line.expected_quantity,"First Count":line.first_count_quantity,Recount:line.recount_quantity,"Final Count":line.counted_quantity,Variance:line.variance_quantity,Unit:line.unit,Reason:line.reason,Notes:line.notes,"Counted By":line.counted_by,"Unit Cost":line.unit_cost,"Retail Price":line.retail_price,"Cost Impact":line.variance_quantity*line.unit_cost,"Revenue Impact":line.variance_quantity*line.retail_price,"Scan Status":line.first_count_quantity==null?"Not scanned":"Scanned"}));async function download(extension:"csv"|"xlsx"){const blob=await apiDownload(`/api/v1/inventory/${operation}/audits/${detail.audit.id}/report.${extension}`);downloadBlob(blob,`inventory_audit_${detail.audit.audit_number}_${detail.audit.status}.${extension}`)}return <section className="audit-report"><h3>Audit Report</h3><div className="info-banner">Report status: <strong>{status}</strong>. Unscanned items remain visible and are not presented as completed counts.</div>{rows.length?<><Table rows={rows}/><div className="two-column-grid"><button className="secondary" onClick={()=>download("csv")}>Export CSV</button><button className="secondary" onClick={()=>download("xlsx")}>Export Excel</button></div><details className="streamlit-expander"><summary>Activity log</summary><div className="streamlit-expander-body"><Table rows={detail.events.map(event=>({Action:event.action,Actor:event.actor,Time:event.occurred_at,Changes:event.changes_json}))}/></div></details></>:<div className="info-banner">No audit detail is available yet.</div>}</section>}

function Table({rows}:{rows:Record<string,unknown>[]}){const columns=rows[0]?Object.keys(rows[0]):[];return <div className="table-wrap"><table><thead><tr>{columns.map(column=><th key={column}>{column}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={index}>{columns.map(column=><td key={column}>{row[column]==null||row[column]===""?"—":String(row[column])}</td>)}</tr>)}</tbody></table></div>}
function Metric({name,value}:{name:string;value:string|number}){return <article className="metric"><span>{name}</span><strong>{value}</strong></article>}
function label(value:string){return value.replaceAll("_"," ").replace(/\b\w/g,char=>char.toUpperCase())}
function timestamp(d=new Date()){return [d.getFullYear(),String(d.getMonth()+1).padStart(2,"0"),String(d.getDate()).padStart(2,"0")].join("")+"-"+[String(d.getHours()).padStart(2,"0"),String(d.getMinutes()).padStart(2,"0"),String(d.getSeconds()).padStart(2,"0")].join("")}
function guessMapping(columns:string[]){const aliases:Record<string,string[]>={product_name:["Product Name","Item Name","Name","Product"],quantity:["Available","Quantity","Qty","On Hand","Quantity Available","Inventory"],sku:["SKU","Product SKU","Item SKU"],upc:["UPC","Barcode","GTIN"],external_product_id:["Dutchie Product ID","Product ID","External Product ID"],lot_code:["Lot","Lot Number","Batch","Batch ID"],compliance_package_id:["METRC Package ID","Package ID","Package Tag"],external_inventory_id:["Dutchie Inventory ID","Inventory ID","External Inventory ID"],barcode_value:["QR Code","Barcode Value","Label Code"],location_code:["Location","Room","Shelf","Bin"],unit:["Unit","UOM","Unit of Measure"],unit_cost:["Unit Cost","Cost","Inventory Cost"],retail_price:["Retail Price","Price","Unit Price"]};const result:Record<string,string>={};for(const [field,names] of Object.entries(aliases)){result[field]=columns.find(column=>names.some(name=>column.trim().toLowerCase()===name.toLowerCase()))??((field==="product_name"||field==="quantity")?columns[0]:"Not provided")}return result}
