import { useQuery } from "@tanstack/react-query";
import { useEffect, useMemo, useState } from "react";
import { apiGet } from "../lib/api";
import { StreamlitDialog } from "./StreamlitDialog";

type Product360Snapshot = {
  product: { id:string; sku:string; name:string; item_type:string; base_unit:string; unit_cost:number; retail_price:number; upc:string; active:boolean };
  profile: { brand:string; category:string; subcategory:string; strain:string; manufacturer:string; product_format:string; description:string; retail_enabled:boolean; production_enabled:boolean } | null;
  inventory: { packages: PackageRow[]; on_hand:number; reserved:number; available_after_reserved:number; package_count:number };
  sales: { windows: Record<string,{quantity:number;net_sales:number}>; daily_velocity:number; sales_trend_pct:number|null; source:string };
  decision: { signal:string; reason:string; target_days:number; target_units:number; days_on_hand:number|null; stockout_date:string|null };
  economics: { unit_cost:number; retail_price:number; margin_pct:number|null; inventory_value:number; retail_value:number; gross_profit_value:number; sell_through_pct:number; estimated_reorder_cost:number; estimated_reorder_retail_value:number; estimated_reorder_gross_profit:number };
  age: { oldest_age_days:number|null; nearest_expiration_days:number|null; last_received_date:string|null };
  compliance: { status:string; lab_status:string };
  open_orders: { id:string; order_number:string; order_type:string; status:string; quantity:number; fulfilled_quantity:number; unit:string }[];
  production_orders: { id:string; order_number:string; status:string; requested_units:number; due_at:string|null; product_format:string }[];
  aliases: { alias:string; source:string }[];
  mappings: { system_name:string; external_id:string; external_name:string }[];
  value_history: { value_type:string; amount:number; currency:string; effective_at:string }[];
};
type PackageRow = { id:string; package_id:string; lot_code:string; location:string; status:string; balance:number; reserved:number; unit:string; received_at:string|null; expiration_at:string|null; lab_status:string; coa_reference:string; source_name:string };
type Tab = "Overview"|"Inventory"|"Sales"|"Purchasing"|"Packages"|"Compliance"|"Audits";
const TABS:Tab[]=["Overview","Inventory","Sales","Purchasing","Packages","Compliance","Audits"];

export function Product360Drawer({productId="",lotId="",open,onClose,onNavigate}:{productId?:string;lotId?:string;open:boolean;onClose:()=>void;onNavigate:(page:string)=>void}){
  const [tab,setTab]=useState<Tab>("Overview");
  useEffect(()=>{if(open)setTab("Overview")},[open,productId,lotId]);
  const path=lotId?`/api/v1/product-360/by-lot/${encodeURIComponent(lotId)}`:productId?`/api/v1/product-360/${encodeURIComponent(productId)}`:"";
  const snapshot=useQuery({queryKey:["product-360-full",productId,lotId],enabled:open&&Boolean(path),queryFn:({signal})=>apiGet<Product360Snapshot>(path,signal)});
  const data=snapshot.data;
  const title=data?.product.name??"Loading product…";
  const subtitle=data?`${data.product.sku} · ${data.profile?.brand||"No brand"} · ${data.profile?.category||data.product.item_type}`:"Cross-workspace operational decision object";
  const footer=data?<><button className="secondary" type="button" onClick={()=>navigate("Inventory")}>Inventory</button><button className="secondary" type="button" onClick={()=>navigate("Sales & Category Trends")}>Sales</button><button className="primary" type="button" onClick={()=>navigate("Purchase Orders")}>Purchase Orders</button></>:null;
  function navigate(page:string){onClose();onNavigate(page)}
  function stagePo(){if(!data)return;sessionStorage.setItem("buyer-dash-po-inventory-selection",JSON.stringify([{product_id:data.product.id,sku:data.product.sku,description:data.product.name,quantity:Math.max(1,data.decision.target_units),price:data.economics.unit_cost}]));navigate("Purchase Orders")}
  function auditSku(){if(!data)return;sessionStorage.setItem("buyer-dash-audit-product-focus",JSON.stringify({product_id:data.product.id,sku:data.product.sku,product_name:data.product.name}));navigate("Inventory Audits")}
  return <StreamlitDialog open={open} onClose={onClose} eyebrow="PRODUCT 360 · operational decision object" title={title} subtitle={subtitle} footer={footer}>
    {snapshot.isLoading?<div className="state">Loading durable Product 360 evidence…</div>:null}
    {snapshot.isError?<div className="state error">{snapshot.error.message}</div>:null}
    {data?<>
      <section className="quantity-summary"><span>On hand<strong>{number(data.inventory.on_hand)} {data.product.base_unit}</strong></span><span>30d sold<strong>{number(data.sales.windows["30"]?.quantity??0)}</strong></span><span>Days on hand<strong>{data.decision.days_on_hand==null?"∞":number(data.decision.days_on_hand)}</strong></span><span>Margin<strong>{data.economics.margin_pct==null?"—":`${number(data.economics.margin_pct)}%`}</strong></span></section>
      <div className="info-banner"><strong>{data.decision.signal}</strong><br/><span>{data.decision.reason}</span></div>
      <div className="view-tabs product-360-tabs" role="tablist" aria-label="Product 360 evidence">{TABS.map(value=><button key={value} type="button" className={tab===value?"active":""} onClick={()=>setTab(value)}>{value}</button>)}</div>
      {tab==="Overview"?<Overview data={data}/>:null}
      {tab==="Inventory"?<Inventory data={data}/>:null}
      {tab==="Sales"?<Sales data={data}/>:null}
      {tab==="Purchasing"?<Purchasing data={data} onStage={stagePo}/>:null}
      {tab==="Packages"?<Packages data={data}/>:null}
      {tab==="Compliance"?<Compliance data={data} onTraceability={()=>navigate("Integrations")}/>:null}
      {tab==="Audits"?<Audits data={data} onAudit={auditSku}/>:null}
    </>:null}
  </StreamlitDialog>;
}

function Overview({data}:{data:Product360Snapshot}){return <div className="product-360-panel"><section className="quantity-summary"><span>Inventory cost<strong>{money(data.economics.inventory_value)}</strong></span><span>Retail value<strong>{money(data.economics.retail_value)}</strong></span><span>Sell-through<strong>{number(data.economics.sell_through_pct)}%</strong></span></section><div className="catalog-row"><strong>Vendor / brand</strong><span>{data.profile?.brand||data.age.last_received_date&&data.inventory.packages.find(row=>row.source_name)?.source_name||"Not available"}</span></div><div className="catalog-row"><strong>Reserved</strong><span>{number(data.inventory.reserved)} {data.product.base_unit}</span></div><div className="catalog-row"><strong>Available after reserved</strong><span>{number(data.inventory.available_after_reserved)} {data.product.base_unit}</span></div><div className="catalog-row"><strong>Packages</strong><span>{data.inventory.package_count}</span></div><div className="catalog-row"><strong>Last received</strong><span>{data.age.last_received_date||"Not available"}</span></div><div className="catalog-row"><strong>Oldest package age</strong><span>{data.age.oldest_age_days==null?"Not available":`${data.age.oldest_age_days} days`}</span></div><div className="catalog-row"><strong>Nearest expiration</strong><span>{data.age.nearest_expiration_days==null?"Not available":`${data.age.nearest_expiration_days} days`}</span></div><div className="catalog-row"><strong>Projected stockout</strong><span>{data.decision.stockout_date||"No velocity-based date"}</span></div><h3>Catalog identity</h3><div className="catalog-row"><strong>UPC</strong><span>{data.product.upc||"—"}</span></div>{data.aliases.map(row=><div className="catalog-row" key={`${row.source}-${row.alias}`}><strong>Alias</strong><span>{row.alias}</span><small>{row.source}</small></div>)}{data.mappings.map(row=><div className="catalog-row" key={`${row.system_name}-${row.external_id}`}><strong>{row.system_name}</strong><span>{row.external_id}</span><small>{row.external_name}</small></div>)}{data.value_history.length?<><h3>Value history</h3>{data.value_history.slice(0,8).map(row=><div className="catalog-row" key={`${row.value_type}-${row.effective_at}`}><strong>{row.value_type.replaceAll("_"," ")}</strong><span>{money(row.amount)}</span><small>{new Date(row.effective_at).toLocaleString()}</small></div>)}</>:null}</div>}
function Inventory({data}:{data:Product360Snapshot}){return <div className="product-360-panel"><section className="quantity-summary"><span>On hand<strong>{number(data.inventory.on_hand)}</strong></span><span>Reserved<strong>{number(data.inventory.reserved)}</strong></span><span>Available<strong>{number(data.inventory.available_after_reserved)}</strong></span></section><PackageTable rows={data.inventory.packages}/>{!data.inventory.packages.length?<div className="empty">No inventory rows are loaded for this product in the active facility.</div>:null}</div>}
function Sales({data}:{data:Product360Snapshot}){const windows=[7,30,60,90];return <div className="product-360-panel"><section className="quantity-summary">{windows.map(days=><span key={days}>{days}d<strong>{number(data.sales.windows[String(days)]?.quantity??0)}</strong></span>)}</section>{data.sales.sales_trend_pct!=null?<div className="info-banner">Recent 7-day pace is {Math.abs(data.sales.sales_trend_pct).toFixed(1)}% {data.sales.sales_trend_pct>=0?"faster":"slower"} than the 30-day pace.</div>:null}<p className="source-caption">{data.sales.source}</p><div className="table-wrap"><table><thead><tr><th>Window</th><th>Units sold</th><th>Net sales</th></tr></thead><tbody>{windows.map(days=><tr key={days}><td>{days} days</td><td>{number(data.sales.windows[String(days)]?.quantity??0)}</td><td>{money(data.sales.windows[String(days)]?.net_sales??0)}</td></tr>)}</tbody></table></div></div>}
function Purchasing({data,onStage}:{data:Product360Snapshot;onStage:()=>void}){return <div className="product-360-panel"><section className="quantity-summary"><span>Suggested {data.decision.target_days}-day fill<strong>{data.decision.target_units.toLocaleString()} units</strong></span><span>Estimated cost<strong>{money(data.economics.estimated_reorder_cost)}</strong></span><span>Projected gross profit<strong>{money(data.economics.estimated_reorder_gross_profit)}</strong></span></section><p className="source-caption">This is a deterministic draft based on current facility sales velocity and on-hand. PO Builder remains the final review/export workflow.</p><h3>Open demand</h3>{data.open_orders.map(row=><article className="catalog-row" key={row.id}><strong>{row.order_number}</strong><span>{number(row.quantity-row.fulfilled_quantity)} {row.unit}</span><small>{row.order_type} · {row.status}</small></article>)}{data.production_orders.map(row=><article className="catalog-row" key={row.id}><strong>{row.order_number}</strong><span>{number(row.requested_units)} units</span><small>production · {row.status}</small></article>)}{!data.open_orders.length&&!data.production_orders.length?<div className="empty">No open demand.</div>:null}<button className="primary submit" type="button" onClick={onStage}>{data.decision.target_units>0?"Add / update in PO":"Open PO Builder"}</button></div>}
function Packages({data}:{data:Product360Snapshot}){return <div className="product-360-panel"><PackageTable rows={data.inventory.packages}/>{data.age.oldest_age_days!=null?<p className="source-caption">Oldest detected package age: {data.age.oldest_age_days} days.</p>:null}</div>}
function Compliance({data,onTraceability}:{data:Product360Snapshot;onTraceability:()=>void}){return <div className="product-360-panel"><p className="source-caption">This tab reflects traceability/compliance fields present in the current DoobieLogic source. It does not claim live state-system parity unless the state-system workflow verifies it.</p><section className="quantity-summary"><span>Packages<strong>{data.inventory.package_count}</strong></span><span>Status<strong>{data.compliance.status||"Not available"}</strong></span><span>Lab<strong>{data.compliance.lab_status||"Not available"}</strong></span></section>{data.inventory.packages.some(row=>row.coa_reference)?<>{data.inventory.packages.filter(row=>row.coa_reference).map(row=><div className="catalog-row" key={row.id}><strong>{row.package_id}</strong><span>{row.lab_status||"Lab result"}</span><small>{row.coa_reference}</small></div>)}</>:null}<button className="secondary submit" type="button" onClick={onTraceability}>Open traceability</button></div>}
function Audits({data,onAudit}:{data:Product360Snapshot;onAudit:()=>void}){return <div className="product-360-panel"><p className="source-caption">Keep this Product 360 context and open the existing durable audit workflow.</p><div className="catalog-row"><strong>{data.product.name}</strong><span>{data.product.sku}</span><small>{data.inventory.package_count} package(s) in this facility</small></div><button className="primary submit" type="button" onClick={onAudit}>Audit this SKU</button></div>}
function PackageTable({rows}:{rows:PackageRow[]}){return <div className="table-wrap"><table><thead><tr><th>Package / Lot</th><th>On hand</th><th>Reserved</th><th>Room</th><th>Status</th><th>Received</th><th>Expires</th><th>Lab</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td>{row.package_id||row.lot_code}</td><td>{number(row.balance)} {row.unit}</td><td>{number(row.reserved)}</td><td>{row.location||"—"}</td><td>{row.status||"—"}</td><td>{row.received_at?new Date(row.received_at).toLocaleDateString():"—"}</td><td>{row.expiration_at?new Date(row.expiration_at).toLocaleDateString():"—"}</td><td>{row.lab_status||"—"}</td></tr>)}</tbody></table></div>}
function number(value:number){return Number(value||0).toLocaleString(undefined,{maximumFractionDigits:1})}
function money(value:number){return Number(value||0).toLocaleString(undefined,{style:"currency",currency:"USD",maximumFractionDigits:2})}
