import { useState } from "react";
import { CurrentRoomConditions } from "./CurrentRoomConditions";
import type { EdgeLatest } from "./cultivationIntelligenceTypes";
import { EnvironmentTable, type EnvironmentReading } from "./CultivationEnvironmentPanel";
import { ConnectionFreshness, AggregateWindow, EvidenceList, ReadState, WriteState } from "./CultivationIntelligenceShared";
import { useIntelligence, useIntelligenceWrite } from "./cultivationIntelligenceQueries";
import { record, rows, textValue, type Cycle, type Recipe, type Room, type Zone } from "./cultivationIntelligenceTypes";

type Detail = { edge_latest?: EdgeLatest | null; connection_freshness?: unknown; room: Room; plants: { id: string; plant_tag: string; phase: string }[]; cycles: Cycle[]; environment: { readings?: EnvironmentReading[] }; edge_summary: unknown; events: unknown[]; work: unknown[]; zones?: Zone[]; approved_targets?: unknown[]; can_manage_connections?: boolean; costs: { recorded_total?: number | null; recorded_entry_count?: number; total: number | null; allocation_status: string }; truncated: boolean; can_manage: boolean };
export function Room360({ roomId, recipes }: { roomId: string; recipes: Recipe[] }) {
  const [window, setWindow] = useState("");
  const query = useIntelligence<Detail>(`/rooms/${encodeURIComponent(roomId)}${window}`);
  const [tab, setTab] = useState("Crop");
  return <ReadState query={query}>{data => data.room.id !== roomId ? <p role="alert">Requested room is unavailable. No alternative room was selected.</p> : <div className="cultivation-intelligence"><h3>{data.room.display_name || data.room.room_code}</h3><p>{data.room.phase} · {data.room.active ? "Active" : "Inactive"}</p>
    {data.truncated && <p role="status">This is a bounded, incomplete view of room evidence.</p>}
    <nav className="ci-tabs" aria-label="Room sections">{["Crop", "Environment", "Operations"].map(name => <button className="secondary" aria-pressed={tab === name} key={name} onClick={() => setTab(name)}>{name}</button>)}</nav>
    {tab === "Crop" && <><h4>Canonical plants</h4>{data.plants.length ? <ul>{data.plants.map(plant => <li key={plant.id}><a href={`/cultivation?plant=${encodeURIComponent(plant.id)}`}>{plant.plant_tag}</a> · {plant.phase}</li>)}</ul> : <p>No canonical plants are currently linked to this room.</p>}<h4>Crop cycles and recipes</h4>{data.cycles.length ? data.cycles.map(cycle => <p key={cycle.id}><a href={`/cultivation?room=${encodeURIComponent(roomId)}&cycle=${encodeURIComponent(cycle.id)}`}>Open Crop Cycle: {cycle.display_name || cycle.cycle_code}</a> · {recipes.find(recipe => recipe.id === cycle.recipe_id)?.name || "No evidenced recipe context"}</p>) : <p>No evidenced cycle occupancy. Historical membership is unknown.</p>}</>}
    {tab === "Environment" && <><CurrentRoomConditions latest={data.edge_latest} roomId={roomId} /><p>Environment, root-zone and irrigation evidence stay separate by source. Missing coverage is unknown, never healthy. Recipe deviations require historical approved targets.</p><ConnectionFreshness value={data.connection_freshness} /><AggregateWindow onApply={setWindow} /><RoomEvidence summary={data.edge_summary} /><h4>Current approved setpoint targets</h4><p>Decision support only, not equipment controls.</p>{!rows(data.approved_targets).length && <p>No current approved target evidence.</p>}{rows(data.approved_targets).map((target, i) => <p key={i}>{textValue(target.metric)}: {textValue(target.minimum, "No minimum")} to {textValue(target.maximum, "no maximum")} {textValue(target.unit)}; recipe version {textValue(target.recipe_version)}; continuous deviation threshold {target.threshold_seconds == null ? "not configured" : `${textValue(target.threshold_seconds)} seconds`}</p>)}<h4>Manual environment observations</h4>{data.environment?.readings?.length ? <EnvironmentTable readings={data.environment.readings} /> : <p>No latest observation evidence is available.</p>}<p>Close this window to use Room environment and explicit Work actions below.</p></>}
    {tab === "Operations" && <><h4>Zones</h4><EvidenceList value={data.zones} empty="No zones supplied." />{data.can_manage_connections && <CreateZone roomId={roomId} />}<h4>Events</h4><EvidenceList value={data.events} empty="No recorded room events." /><h4>Work</h4>{rows(data.work).map((work, index) => <p key={index}>{typeof work.id === "string" ? <a href={`/work?item=${encodeURIComponent(work.id)}`}>{textValue(work.title, "Open Work")}</a> : "Work reference unavailable"}</p>)}{!data.work.length && <p>No linked Work evidence.</p>}<p>Recorded costs: {data.costs.recorded_total == null ? "Unknown" : data.costs.recorded_total}. Entries: {data.costs.recorded_entry_count ?? "Unknown"}. All recorded room entries, not allocated cycle costs. Allocation: {data.costs.allocation_status}. True COGS, grade and revenue are not established by this evidence.</p><a href="/cultivation">Open canonical costs and regulatory health</a>{data.can_manage && <CultivationEventForm roomId={roomId} />}</>}
  </div>}</ReadState>;
}
function evidenceTime(value: unknown): string {
  if (typeof value !== "number") return textValue(value);
  const date = new Date(value * 1000);
  return Number.isFinite(date.getTime()) ? date.toISOString() : "Unknown";
}
export function RoomEvidence({ summary }: { summary: unknown }) {
  const value = record(summary);
  const streams = rows(value.streams);
  return <section><h4>Coverage and deterministic deviations</h4><p>Summary state: {textValue(value.status)}. Window: {evidenceTime(value.start)} to {evidenceTime(value.end)}. {value.truncated === true ? "Summary is incomplete." : ""}</p>{!streams.length && <p>No persisted stream coverage is available. Environment, root-zone and irrigation history remain unknown.</p>}
    {streams.map((stream, index) => { const snapshot = record(stream.snapshot); return <details key={index}><summary>{textValue(stream.metric, "Unspecified measurement")} · {textValue(snapshot.sensor_id, "Unspecified source")}</summary><p>Connection: {textValue(snapshot.connection_id)} · Device: {textValue(snapshot.device_id)} · Mapping: {textValue(snapshot.mapping_revision)}</p><p>Coverage seconds: {textValue(stream.coverage_seconds)} · Unknown seconds: {textValue(stream.unknown_seconds)}</p>{["event", "duration", "volume"].includes(textValue(stream.kind)) ? <p>Recorded {textValue(stream.kind)} total: {textValue(stream.total)} {textValue(stream.unit, "")}. Coverage between discrete observations is unknown.</p> : stream.kind === "state" ? <p>Observed active seconds: {textValue(stream.active_seconds)}</p> : <p>Sample mean: {textValue(stream.sample_mean)} · Time-weighted mean: {textValue(stream.time_weighted_mean)} {textValue(stream.unit, "")}</p>}{stream.metric === "ppfd" && <p>Measured DLI contribution: {textValue(stream.measured_dli_contribution)}. {stream.dli_partial !== false ? "Partial coverage; not extrapolated to a day." : "Full reported interval."}</p>}<p>Attribution coverage intervals: {Array.isArray(stream.attribution_intervals) ? stream.attribution_intervals.map(interval => Array.isArray(interval) ? interval.map(evidenceTime).join(" to ") : "Unknown").join("; ") || "None" : "Unknown"}</p><p>Recipe revision: {textValue(snapshot.recipe_revision)}. Above target seconds: {snapshot.recipe_revision ? textValue(stream.above_seconds) : "Unknown"} · Below target seconds: {snapshot.recipe_revision ? textValue(stream.below_seconds) : "Unknown"}</p><p>Cumulative out-of-target seconds: {snapshot.recipe_revision && typeof stream.above_seconds === "number" && typeof stream.below_seconds === "number" ? stream.above_seconds + stream.below_seconds : "Unknown"}. This duration is separate from threshold-qualified continuous deviation episodes. Continuous threshold: {snapshot.threshold_seconds == null ? "not configured" : `${textValue(snapshot.threshold_seconds)} seconds`}. Gaps break continuity.</p>{typeof snapshot.threshold_seconds === "number" && snapshot.threshold_seconds > 0 && rows(stream.deviations).length ? <ul>{rows(stream.deviations).map((deviation, i) => <li key={i}>{textValue(deviation.direction)} · {evidenceTime(deviation.start)} to {evidenceTime(deviation.end)} · {textValue(deviation.seconds)} seconds</li>)}</ul> : <p>No deviation intervals supplied. This does not establish complete in-target coverage.</p>}</details>; })}
  </section>;
}
export function CultivationEventForm({ roomId = null, cycleId = null }: { roomId?: string | null; cycleId?: string | null }) {
  const save = useIntelligenceWrite("/events");
  return <form onSubmit={event => { event.preventDefault(); const fields = new FormData(event.currentTarget); save.mutate({ room_id: roomId, cycle_id: cycleId, event_type: fields.get("event_type"), title: fields.get("title"), notes: fields.get("notes"), occurred_at: fields.get("occurred_at") }); }}><h4>Record operational event</h4><fieldset disabled={save.isPending || save.isSuccess}><div className="form-grid"><label>Event type<input name="event_type" required /></label><label>Title<input name="title" required /></label><label>Occurred at (ISO with timezone)<input name="occurred_at" defaultValue={new Date().toISOString()} required /></label><label>Notes<textarea name="notes" /></label></div><button className="primary">Save event</button></fieldset><WriteState error={save.error} success={save.isSuccess} />{save.isSuccess && <button type="button" className="secondary" onClick={() => save.reset()}>Record another event</button>}</form>;
}
function CreateZone({ roomId }: { roomId: string }) {
  const save = useIntelligenceWrite(`/rooms/${encodeURIComponent(roomId)}/zones`);
  return <form onSubmit={event => { event.preventDefault(); const fields = new FormData(event.currentTarget); save.mutate({ zone_code: fields.get("zone_code"), display_name: fields.get("display_name") || "" }); }}><h4>Create zone</h4><fieldset disabled={save.isPending || save.isSuccess}><label>Zone code<input name="zone_code" required /></label><label>Zone name<input name="display_name" /></label><button className="primary">Create zone</button></fieldset><WriteState error={save.error} success={save.isSuccess} />{save.isSuccess && <button type="button" onClick={() => save.reset()}>Create another zone</button>}</form>;
}
