import { sourceUnits } from "./telemetryReview";
import { metricLabel, textValue, type RegistryMetric } from "./cultivationIntelligenceTypes";

export type ImportMapping = { source_channel: string; source_metric: string; metric: string; unit: string };
export type PreviewSample = { row_index: number; source_device_id: string | null; source_channel: string | null; source_metric: string | null; original_value: string | number | null; original_unit: string | null; normalized_value: number | null; normalized_unit: string | null; metric: string | null; observed_at: string | null; room_id: string | null; room_name: string | null; zone_id: string | null; zone_name: string | null; cycle_id: string | null; cycle_name: string | null; status: string };
export function NormalizedPreviewTable({ samples, truncated }: { samples: PreviewSample[]; truncated: boolean }) {
  const labels: Record<string, string> = { normalized_not_committed: "Normalized, not committed", pending_mapping: "Assign a device, room and channel mapping", invalid_measurement: "Check value, quality, unit and timestamp", metric_conflict: "Selected measurement conflicts with the registered sensor" };
  return <section aria-label="Server normalized preview"><h4>Server normalized preview</h4><p>Actual resolved destinations and converted values. No readings have been committed by this preview.</p><div className="ci-table-scroll" role="region" aria-label="Normalized sample readings" tabIndex={0}><table><thead><tr>{["Row", "Source", "Original", "Normalized", "Observed (UTC)", "Destination", "Review status"].map(label => <th key={label} scope="col">{label}</th>)}</tr></thead><tbody>{samples.map(row => <tr key={row.row_index}><td>{row.row_index + 1}</td><td>{textValue(row.source_device_id)} / {textValue(row.source_channel)}<br />{textValue(row.source_metric)}</td><td>{textValue(row.original_value)} {textValue(row.original_unit, "")}</td><td>{row.status !== "normalized_not_committed" || row.normalized_value == null || !Number.isFinite(row.normalized_value) ? "Unavailable" : `${row.normalized_value} ${row.normalized_unit}`}<br />{textValue(row.metric, "")}</td><td>{textValue(row.observed_at)}</td><td>{textValue(row.room_name, "Unassigned room")} / {textValue(row.zone_name, row.zone_id ? "Zone name unavailable" : "No zone assigned")}<br />Crop: {textValue(row.cycle_name, "No crop assigned")}</td><td>{labels[row.status] || "Unavailable"}</td></tr>)}</tbody></table></div>{truncated && <p>Showing the first 20 rows. Counts cover the full file.</p>}</section>;
}
export function TelemetryMappingTable({ mappings, metrics, onChange }: { mappings: ImportMapping[]; metrics: RegistryMetric[]; onChange: (value: ImportMapping[]) => void }) {
  function update(index: number, field: keyof ImportMapping, value: string) { onChange(mappings.map((mapping, i) => i === index ? { ...mapping, [field]: value } : mapping)); }
  return <section aria-label="Review channel mappings"><h4>Review channel mappings</h4><p>Match each source channel and original unit to a measurement. Room, zone and effective time are saved in the device mapping above. Leaving a channel unmapped queues its evidence for review.</p>
    {mappings.map((mapping, index) => <fieldset className="ci-stage" key={index}><legend>Channel mapping {index + 1}</legend><div className="form-grid">
      <label>Source channel<input required maxLength={160} value={mapping.source_channel} onChange={e => update(index, "source_channel", e.target.value)} /></label>
      <label>Source measurement<input required maxLength={160} value={mapping.source_metric} onChange={e => update(index, "source_metric", e.target.value)} /></label>
      <label>Original unit<select required value={mapping.unit} onChange={e => update(index, "unit", e.target.value)}><option value="">Choose unit</option>{[...new Set([mapping.unit, ...sourceUnits(mapping.metric, metrics.find(item => item.metric === mapping.metric)?.unit || "")])].filter(Boolean).map(unit => <option key={unit} value={unit}>{unit}</option>)}</select></label>
      <label>Normalized measurement<select required value={mapping.metric} onChange={e => update(index, "metric", e.target.value)}><option value="">Choose measurement</option>{metrics.map(metric => <option key={metric.metric} value={metric.metric}>{metricLabel(metric.metric, metrics)} ({metric.unit})</option>)}</select></label>
    </div><button type="button" className="secondary" onClick={() => onChange(mappings.filter((_, i) => i !== index))}>Remove mapping {index + 1}</button></fieldset>)}
    <button type="button" className="secondary" disabled={mappings.length >= 200} onClick={() => onChange([...mappings, { source_channel: "", source_metric: "", unit: "", metric: "" }])}>Add channel mapping</button>
  </section>;
}

export function SourcePreviewTable({ readings }: { readings: Record<string, unknown>[] }) {
  return <section aria-label="Selected file preview"><h4>Selected file preview</h4><p>Original source values only. Server validation has not established normalized values or room attribution.</p><div className="ci-table-scroll" role="region" aria-label="Source readings" tabIndex={0}><table><thead><tr>{["Source event", "Device", "Channel", "Value", "Unit", "Observation time", "Quality"].map(label => <th key={label} scope="col">{label}</th>)}</tr></thead><tbody>{readings.slice(0, 20).map((reading, i) => <tr key={i}>{["event_id", "source_device_id", "source_channel", "value", "unit", "observed_at", "quality"].map(key => <td key={key}>{textValue(reading[key], key === "quality" ? "Not supplied" : "Missing")}</td>)}</tr>)}</tbody></table></div>{readings.length > 20 && <p>Showing 20 of {readings.length} rows. Server preview validates the whole selected file.</p>}</section>;
}
