from __future__ import annotations

import json

from sqlalchemy import create_engine
from sqlalchemy.orm import Session

from modules.coman import ComanRepository
from modules.coman.models import Base, Facility, InventoryLot
from modules.commerce_storefronts.wholesale_service import WholesaleCommerceStorefrontService
from modules.cultivation.service import CultivationService
from modules.extraction.repository import ExtractionRepository
from modules.material_lineage.harvest_guard import GuardedHarvestAllocationService
from modules.material_lineage.service import MaterialLineageService
from modules.package_studio.service import (
    PackageStudioInputPlan,
    PackageStudioOutputPlan,
    PackageStudioPlan,
    PackageStudioService,
)
from modules.product_master import ProductMasterRepository


STRAINS = (
    "Gastro Pop",
    "GMO",
    "Strawberry Cough",
    "Blue Dream",
    "Wedding Cake",
    "Super Lemon Haze",
    "Gelato 41",
    "Motorbreath",
    "Permanent Marker",
    "Animal Face",
)

FLOWER_FORMATS = (
    ("Flower Jar 1g", 1.0, 10),
    ("Flower Jar 3.5g", 3.5, 10),
    ("Flower Pouch 7g", 7.0, 5),
    ("Flower Pouch 14g", 14.0, 2),
    ("Flower Pouch 28g", 28.0, 1),
    ("Smalls Pouch 3.5g", 3.5, 10),
    ("Ground Flower Pouch 7g", 7.0, 5),
)

EXTRACT_FORMATS = (
    ("bho_cured", "BHO", "Cured Badder 1g"),
    ("ethanol_crude", "Ethanol", "Distillate 1g"),
    ("dry_sift", "Dry Sift", "Dry Sift 1g"),
)


def _engine():
    engine = create_engine("sqlite+pysqlite:///:memory:", future=True)
    Base.metadata.create_all(engine)
    return engine


def _mark_passed_coa(engine, lot_id: str, reference: str, *, thca: float, tac: float, terpenes: float) -> None:
    with Session(engine) as session, session.begin():
        lot = session.get(InventoryLot, lot_id)
        assert lot is not None
        lot.status = "available"
        lot.notes = json.dumps(
            {
                "lab_testing_state": "Passed",
                "coa_reference": reference,
                "thca_percent": thca,
                "tac_percent": tac,
                "total_terpenes_percent": terpenes,
            }
        )


def _profile(master: ProductMasterRepository, organization_id: str, product_id: str, *, strain: str, category: str, product_format: str) -> None:
    master.update_profile(
        organization_id,
        product_id,
        actor="vertical-audit",
        brand="Cowboy Kush",
        category=category,
        subcategory=product_format,
        strain=strain,
        manufacturer="Cowboy Kush Vertical",
        product_format=product_format,
        description=f"{strain} {product_format} generated by the vertical 100-item operator audit.",
        retail_enabled=True,
        production_enabled=True,
    )


def test_vertical_organization_100_finished_items_seed_to_sale_current_state():
    engine = _engine()
    coman = ComanRepository(engine)
    master = ProductMasterRepository(engine)
    cultivation = CultivationService(engine)
    harvest_allocator = GuardedHarvestAllocationService(engine)
    studio = PackageStudioService(engine)
    extraction = ExtractionRepository(engine)
    lineage = MaterialLineageService(engine)

    organization = coman.create_organization("Cowboy Kush Vertical Audit")
    facility = coman.create_facility(organization.id, "Vertical Cultivation + Manufacturing + Wholesale", "VERT-100")
    with Session(engine) as session, session.begin():
        row = session.get(Facility, facility.id)
        assert row is not None
        row.cultivation_enabled = True
        row.production_enabled = True
        row.retail_enabled = True
        row.commercial_enabled = True
        row.license_number = "VERTICAL-AUDIT-LICENSE"
        row.license_type = "cultivation+manufacturing+retail"

    final_lot_ids: list[str] = []
    flower_final_lot_ids: list[str] = []
    extract_final_lot_ids: list[str] = []
    extraction_bulk_lot_ids: list[str] = []
    final_product_ids: list[str] = []

    for strain_index, strain in enumerate(STRAINS, start=1):
        strain_code = f"S{strain_index:02d}"
        flower_source_product = coman.create_product(
            organization.id,
            sku=f"{strain_code}-BULK-FLOWER",
            name=f"{strain} Bulk Flower",
            item_type="cannabis",
            base_unit="g",
            unit_cost=2.0,
            retail_price=0,
            actor="vertical-audit",
        )
        trim_source_product = coman.create_product(
            organization.id,
            sku=f"{strain_code}-TRIM",
            name=f"{strain} Trim",
            item_type="cannabis",
            base_unit="g",
            unit_cost=0.75,
            retail_price=0,
            actor="vertical-audit",
        )
        _profile(master, organization.id, flower_source_product.id, strain=strain, category="Bulk Flower", product_format="Bulk Flower")
        _profile(master, organization.id, trim_source_product.id, strain=strain, category="Trim", product_format="Trim")

        plants = [
            cultivation.create_plant(
                organization.id,
                facility.id,
                plant_tag=f"{strain_code}-P{plant_index:02d}",
                strain_name=strain,
                phase="flowering",
                room_code=f"FLOWER-{strain_index:02d}",
                actor="vertical-audit",
            )
            for plant_index in range(1, 3)
        ]
        harvest = cultivation.create_harvest(
            organization.id,
            facility.id,
            harvest_code=f"{strain_code}-H-001",
            plant_ids=[plant.id for plant in plants],
            actor="vertical-audit",
        )
        cultivation.transition_harvest(
            organization.id,
            facility.id,
            harvest["id"],
            status="active",
            actor="vertical-audit",
            wet_weight=4000,
            unit="g",
        )
        cultivation.transition_harvest(
            organization.id,
            facility.id,
            harvest["id"],
            status="drying",
            actor="vertical-audit",
            dry_weight=1000,
            unit="g",
        )
        harvest_outputs = [
            {
                "product_id": flower_source_product.id,
                "lot_code": f"{strain_code}-H-001-FLOWER",
                "quantity": 700,
                "unit": "g",
                "purpose": "finished_flower",
                "measurement_basis": "dry",
                "status": "available",
                "location_code": "BULK-FLOWER-VAULT",
                "compliance_package_id": f"HARV-{strain_code}-FLOWER",
            },
            {
                "product_id": trim_source_product.id,
                "lot_code": f"{strain_code}-H-001-TRIM",
                "quantity": 300,
                "unit": "g",
                "purpose": "trim",
                "measurement_basis": "dry",
                "status": "available",
                "location_code": "EXTRACTION-STAGING",
                "compliance_package_id": f"HARV-{strain_code}-TRIM",
            },
        ]
        preview = harvest_allocator.preview_harvest_allocation(
            organization_id=organization.id,
            facility_id=facility.id,
            harvest_id=harvest["id"],
            outputs=harvest_outputs,
            losses=[],
        )
        assert preview["reconciliation"]["dry"]["remaining"] == 0
        committed = harvest_allocator.commit_harvest_allocation(
            organization_id=organization.id,
            facility_id=facility.id,
            harvest_id=harvest["id"],
            outputs=harvest_outputs,
            losses=[],
            preview_key=preview["preview_key"],
            actor="vertical-audit",
        )
        cultivation.transition_harvest(
            organization.id,
            facility.id,
            harvest["id"],
            status="completed",
            actor="vertical-audit",
        )
        flower_source_lot_id, trim_source_lot_id = committed["output_lot_ids"]
        _mark_passed_coa(engine, flower_source_lot_id, f"COA-{strain_code}-HARVEST", thca=26 + strain_index / 10, tac=29 + strain_index / 10, terpenes=2 + strain_index / 100)
        _mark_passed_coa(engine, trim_source_lot_id, f"COA-{strain_code}-TRIM", thca=18 + strain_index / 10, tac=21 + strain_index / 10, terpenes=1.4 + strain_index / 100)

        # Seven retail-ready flower SKUs from the same harvested flower lot.
        studio_outputs: list[PackageStudioOutputPlan] = []
        total_source_equivalent = 0.0
        for format_index, (format_name, grams_each, units) in enumerate(FLOWER_FORMATS, start=1):
            product = coman.create_product(
                organization.id,
                sku=f"{strain_code}-F{format_index:02d}",
                name=f"{strain} {format_name}",
                item_type="finished_good",
                base_unit="unit",
                unit_cost=round(grams_each * 2.0 + 0.75, 2),
                retail_price=round(max(10.0, grams_each * 9.0), 2),
                upc=f"850{strain_index:02d}{format_index:02d}00000",
                actor="vertical-audit",
            )
            _profile(master, organization.id, product.id, strain=strain, category="Flower", product_format=format_name)
            source_equivalent = grams_each * units
            total_source_equivalent += source_equivalent
            studio_outputs.append(
                PackageStudioOutputPlan(
                    product_id=product.id,
                    lot_code=f"{strain_code}-F{format_index:02d}-LOT",
                    inventory_quantity=units,
                    inventory_unit="unit",
                    source_equivalent_quantity=source_equivalent,
                    source_equivalent_unit="g",
                    compliance_package_id=f"PKG-{strain_code}-F{format_index:02d}",
                    purpose="standard",
                    location_code="FINISHED-GOODS",
                    notes=f"Source COA COA-{strain_code}-HARVEST should remain attached to this child package.",
                )
            )
            final_product_ids.append(product.id)
        flower_pack = studio.commit(
            PackageStudioPlan(
                action_type="multi_build",
                inputs=(PackageStudioInputPlan(lot_id=flower_source_lot_id, quantity=total_source_equivalent, unit="g"),),
                outputs=tuple(studio_outputs),
                source_unit="g",
                run_number=f"PKG-{strain_code}-FLOWER",
                reason="Package retail flower from reconciled harvest",
            ),
            organization_id=organization.id,
            facility_id=facility.id,
            actor="vertical-audit",
        )
        flower_final_lot_ids.extend(flower_pack.output_lot_ids)
        final_lot_ids.extend(flower_pack.output_lot_ids)

        # Three extract branches per strain. Each consumes physical trim through the
        # Extraction platform, records process weight, output, COGS, QA/COA, then
        # uses Package Studio for the final 1 g retail-ready units.
        for extract_index, (workflow_key, method, format_name) in enumerate(EXTRACT_FORMATS, start=1):
            bulk_extract = coman.create_product(
                organization.id,
                sku=f"{strain_code}-X{extract_index:02d}-BULK",
                name=f"{strain} {format_name} Bulk",
                item_type="cannabis",
                base_unit="g",
                unit_cost=0,
                retail_price=0,
                actor="vertical-audit",
            )
            _profile(master, organization.id, bulk_extract.id, strain=strain, category="Bulk Extract", product_format=format_name)
            retail_extract = coman.create_product(
                organization.id,
                sku=f"{strain_code}-X{extract_index:02d}",
                name=f"{strain} {format_name}",
                item_type="finished_good",
                base_unit="unit",
                unit_cost=8.0,
                retail_price=35.0,
                upc=f"860{strain_index:02d}{extract_index:02d}00000",
                actor="vertical-audit",
            )
            _profile(master, organization.id, retail_extract.id, strain=strain, category="Concentrates", product_format=format_name)
            final_product_ids.append(retail_extract.id)

            run = extraction.create_run(
                organization_id=organization.id,
                facility_id=facility.id,
                batch_number=f"EXT-{strain_code}-{extract_index:02d}",
                method=method,
                workflow_key=workflow_key,
                product_family=format_name,
                strain=strain,
                operator="vertical-audit",
                license_number="VERTICAL-AUDIT-LICENSE",
                actor="vertical-audit",
            )
            run_input = extraction.reserve_input(
                organization_id=organization.id,
                facility_id=facility.id,
                run_id=run.id,
                lot_id=trim_source_lot_id,
                quantity=50,
                unit="g",
                role="primary_input",
                source_reference=f"HARV-{strain_code}-TRIM",
                actor="vertical-audit",
            )
            extraction.consume_input(
                organization_id=organization.id,
                facility_id=facility.id,
                run_input_id=run_input.id,
                quantity=50,
                actor="vertical-audit",
            )
            extraction.record_stage_event(
                organization_id=organization.id,
                facility_id=facility.id,
                run_id=run.id,
                stage_key="intake",
                event_type="completed",
                input_weight_g=50,
                output_weight_g=50,
                actor="vertical-audit",
            )
            extraction.add_cost_event(
                organization_id=organization.id,
                facility_id=facility.id,
                run_id=run.id,
                category="labor",
                amount_usd=25,
                quantity=1,
                unit="hour",
                actor="vertical-audit",
            )
            output = extraction.create_output(
                organization_id=organization.id,
                facility_id=facility.id,
                run_id=run.id,
                product_id=bulk_extract.id,
                lot_code=f"EXT-{strain_code}-{extract_index:02d}-BULK",
                quantity=10,
                unit="g",
                output_label=f"{strain} {format_name} Bulk",
                compliance_package_id=f"EXT-PKG-{strain_code}-{extract_index:02d}",
                location_code="EXTRACTION-QA",
                actor="vertical-audit",
            )
            extraction_bulk_lot_ids.append(output.lot_id)
            extraction.record_qa_event(
                organization_id=organization.id,
                facility_id=facility.id,
                run_id=run.id,
                output_id=output.id,
                event_type="coa_attached",
                result="passed",
                coa_reference=f"COA-EXT-{strain_code}-{extract_index:02d}",
                actor="vertical-audit",
            )
            extraction.record_qa_event(
                organization_id=organization.id,
                facility_id=facility.id,
                run_id=run.id,
                event_type="release",
                result="passed",
                actor="vertical-audit",
            )
            balance = extraction.mass_balance(organization.id, facility.id, run.id)
            assert balance["consumed_input"] == 50
            assert balance["recorded_output"] == 10
            assert extraction.cogs_summary(organization.id, facility.id, run.id)["total"] > 0

            packaged_extract = studio.commit(
                PackageStudioPlan(
                    action_type="build_run",
                    inputs=(PackageStudioInputPlan(lot_id=output.lot_id, quantity=10, unit="g"),),
                    outputs=(
                        PackageStudioOutputPlan(
                            product_id=retail_extract.id,
                            lot_code=f"{strain_code}-X{extract_index:02d}-LOT",
                            inventory_quantity=10,
                            inventory_unit="unit",
                            source_equivalent_quantity=10,
                            source_equivalent_unit="g",
                            compliance_package_id=f"PKG-{strain_code}-X{extract_index:02d}",
                            purpose="standard",
                            location_code="FINISHED-GOODS",
                            notes=f"Extraction COA COA-EXT-{strain_code}-{extract_index:02d} should remain attached to this child package.",
                        ),
                    ),
                    source_unit="g",
                    run_number=f"PKG-{strain_code}-X{extract_index:02d}",
                    reason="Package extraction output into retail-ready units",
                ),
                organization_id=organization.id,
                facility_id=facility.id,
                actor="vertical-audit",
            )
            extract_final_lot_ids.extend(packaged_extract.output_lot_ids)
            final_lot_ids.extend(packaged_extract.output_lot_ids)

    assert len(final_product_ids) == 100
    assert len(final_lot_ids) == 100
    assert len(flower_final_lot_ids) == 70
    assert len(extract_final_lot_ids) == 30
    assert all(coman.inventory_balance(organization.id, lot_id) > 0 for lot_id in final_lot_ids)

    with Session(engine) as session:
        final_lots = [session.get(InventoryLot, lot_id) for lot_id in final_lot_ids]
        extraction_bulk_lots = [session.get(InventoryLot, lot_id) for lot_id in extraction_bulk_lot_ids]
    assert all(lot is not None and lot.status == "available" for lot in final_lots)
    assert all(lot is not None and lot.compliance_package_id for lot in final_lots)

    # Current-state audit: all 100 final packages exist and are physically available,
    # but Package Studio does not inherit source COA metadata into the child lot notes.
    wholesale = WholesaleCommerceStorefrontService(engine).wholesale_inventory(organization.id, facility.id)
    final_ids = set(final_lot_ids)
    eligible_final = [row for row in wholesale["items"] if row["lot_id"] in final_ids]
    blocked_final = [row for row in wholesale["blocked_items"] if row["lot_id"] in final_ids]
    assert len(eligible_final) == 0
    assert len(blocked_final) == 100
    assert all("COA reference is missing" in row["blocked_reasons"] for row in blocked_final)

    # Flower packages can traverse Package Studio back to the canonical harvest/plant graph.
    flower_with_plant_ancestry = 0
    for lot_id in flower_final_lot_ids:
        graph = lineage.lot_graph(organization_id=organization.id, facility_id=facility.id, lot_id=lot_id)
        if any(node["type"] == "plant" for node in graph["nodes"]):
            flower_with_plant_ancestry += 1
    assert flower_with_plant_ancestry == 70

    # Extraction consumes real inventory and releases through QA, but extraction has not
    # yet been added to the canonical material graph, so its packaged children stop at
    # the extraction output lot instead of reaching harvest/plants.
    extract_with_plant_ancestry = 0
    for lot_id in extract_final_lot_ids:
        graph = lineage.lot_graph(organization_id=organization.id, facility_id=facility.id, lot_id=lot_id)
        if any(node["type"] == "plant" for node in graph["nodes"]):
            extract_with_plant_ancestry += 1
    assert extract_with_plant_ancestry == 0

    # Extraction QA stores the COA on its extraction output/event, but it does not
    # propagate the passed COA into shared InventoryLot metadata used by wholesale.
    assert len(extraction_bulk_lots) == 30
    assert all(lot is not None and "coa_reference" not in (lot.notes or "") for lot in extraction_bulk_lots)

    # The New Run picker uses ExtractionRepository.list_available_lots(), which is
    # broader than the filtered Extraction Inventory projection and currently offers
    # unrelated retail-ready finished packages as candidate extraction feedstock.
    extraction_picker = extraction.list_available_lots(organization.id, facility.id)
    picker_ids = {row["lot_id"] for row in extraction_picker}
    finished_offered_as_extraction_input = len(final_ids & picker_ids)
    assert finished_offered_as_extraction_input == 100
