alter table public.extraction_runs add column if not exists run_date date;
alter table public.extraction_runs add column if not exists jurisdiction varchar(64) not null default '';
alter table public.extraction_runs add column if not exists facility_license_name varchar(255) not null default '';
alter table public.extraction_runs add column if not exists client_name_snapshot varchar(255) not null default '';
alter table public.extraction_runs add column if not exists manual_batch_id_internal varchar(120);
alter table public.extraction_runs add column if not exists input_material_type varchar(120) not null default '';
alter table public.extraction_runs add column if not exists manual_input_weight_g double precision not null default 0;
alter table public.extraction_runs add column if not exists intermediate_output_g double precision not null default 0;
alter table public.extraction_runs add column if not exists manual_finished_output_g double precision not null default 0;
alter table public.extraction_runs add column if not exists residual_loss_g double precision not null default 0;
alter table public.extraction_runs add column if not exists machine_line varchar(160) not null default '';
alter table public.extraction_runs add column if not exists metrc_package_id_input varchar(255) not null default '';
alter table public.extraction_runs add column if not exists metrc_package_id_output varchar(255) not null default '';
alter table public.extraction_runs add column if not exists metrc_manifest_or_transfer_id varchar(255) not null default '';
alter table public.extraction_runs add column if not exists manual_coa_status varchar(32) not null default 'pending';
alter table public.extraction_runs add column if not exists manual_qa_hold boolean not null default false;
alter table public.extraction_runs add column if not exists processing_fee_usd double precision not null default 0;
alter table public.extraction_runs add column if not exists estimated_revenue_usd double precision not null default 0;
alter table public.extraction_runs add column if not exists manual_cogs_usd double precision not null default 0;
alter table public.extraction_toll_jobs add column if not exists jurisdiction varchar(64) not null default '';
alter table public.extraction_toll_jobs add column if not exists client_license_snapshot varchar(255) not null default '';
alter table public.extraction_toll_jobs add column if not exists material_received_at timestamptz;
alter table public.extraction_toll_jobs add column if not exists input_weight_g double precision not null default 0;
alter table public.extraction_toll_jobs add column if not exists expected_output_g double precision not null default 0;
alter table public.extraction_toll_jobs add column if not exists actual_output_g double precision not null default 0;
alter table public.extraction_toll_jobs add column if not exists coa_status varchar(32) not null default 'pending';
alter table public.extraction_toll_jobs add column if not exists job_status varchar(32) not null default 'queued';
update alembic_version set version_num = '0038_extraction_parity_fields' where version_num = '0037_function_acl_hardening';
