"""Add operational moat records for SOPs, LabelGuard, telemetry, cultivation harvests and external access.

Revision ID: 0044_operational_moats
Revises: 0043_sandbox_sync
"""

from alembic import op
import sqlalchemy as sa

revision = "0044_operational_moats"
down_revision = "0043_sandbox_sync"
branch_labels = None
depends_on = None


def _timestamps() -> list[sa.Column]:
    return [sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False)]


def upgrade() -> None:
    op.create_table("sop_documents", sa.Column("id", sa.String(36), primary_key=True), sa.Column("organization_id", sa.String(36), sa.ForeignKey("coman_organizations.id", ondelete="CASCADE"), nullable=False), sa.Column("facility_id", sa.String(36), sa.ForeignKey("coman_facilities.id", ondelete="CASCADE"), nullable=True), sa.Column("code", sa.String(80), nullable=False), sa.Column("title", sa.String(255), nullable=False), sa.Column("version", sa.Integer(), nullable=False), sa.Column("status", sa.String(24), nullable=False, server_default="draft"), sa.Column("body_text", sa.Text(), nullable=False, server_default=""), sa.Column("source_reference", sa.String(1024), nullable=False, server_default=""), sa.Column("effective_date", sa.Date(), nullable=True), sa.Column("required_roles_json", sa.Text(), nullable=False, server_default="[]"), sa.Column("control_rules_json", sa.Text(), nullable=False, server_default="[]"), sa.Column("created_by", sa.String(255), nullable=False), sa.Column("approved_by", sa.String(255), nullable=False, server_default=""), sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True), *_timestamps(), sa.UniqueConstraint("organization_id", "code", "version", name="uq_sop_document_version"), sa.CheckConstraint("status in ('draft','active','retired')", name="ck_sop_document_status"))
    op.create_index("ix_sop_document_org_status", "sop_documents", ["organization_id", "status", "code"]); op.create_index("ix_sop_documents_facility_id", "sop_documents", ["facility_id"])
    op.create_table("sop_acknowledgements", sa.Column("id", sa.String(36), primary_key=True), sa.Column("organization_id", sa.String(36), sa.ForeignKey("coman_organizations.id", ondelete="CASCADE"), nullable=False), sa.Column("facility_id", sa.String(36), sa.ForeignKey("coman_facilities.id", ondelete="CASCADE"), nullable=True), sa.Column("sop_document_id", sa.String(36), sa.ForeignKey("sop_documents.id", ondelete="CASCADE"), nullable=False), sa.Column("user_id", sa.String(255), nullable=False), sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=False), sa.Column("acknowledgement_text", sa.String(512), nullable=False, server_default="Reviewed and acknowledged"), sa.UniqueConstraint("sop_document_id", "user_id", name="uq_sop_ack_user"))
    op.create_index("ix_sop_ack_org_user", "sop_acknowledgements", ["organization_id", "user_id", "acknowledged_at"]); op.create_index("ix_sop_acknowledgements_facility_id", "sop_acknowledgements", ["facility_id"])
    op.create_table("sop_deviations", sa.Column("id", sa.String(36), primary_key=True), sa.Column("organization_id", sa.String(36), sa.ForeignKey("coman_organizations.id", ondelete="CASCADE"), nullable=False), sa.Column("facility_id", sa.String(36), sa.ForeignKey("coman_facilities.id", ondelete="CASCADE"), nullable=False), sa.Column("sop_document_id", sa.String(36), sa.ForeignKey("sop_documents.id", ondelete="RESTRICT"), nullable=False), sa.Column("entity_type", sa.String(80), nullable=False), sa.Column("entity_id", sa.String(255), nullable=False), sa.Column("rule_key", sa.String(120), nullable=False), sa.Column("severity", sa.String(24), nullable=False, server_default="medium"), sa.Column("status", sa.String(24), nullable=False, server_default="open"), sa.Column("evidence_json", sa.Text(), nullable=False, server_default="{}"), sa.Column("explanation", sa.Text(), nullable=False, server_default=""), sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False), sa.Column("detected_by", sa.String(255), nullable=False, server_default="system"), sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True), sa.Column("resolved_by", sa.String(255), nullable=False, server_default=""), sa.Column("resolution", sa.Text(), nullable=False, server_default=""), sa.CheckConstraint("severity in ('low','medium','high','critical')", name="ck_sop_deviation_severity"), sa.CheckConstraint("status in ('open','investigating','resolved','dismissed')", name="ck_sop_deviation_status"))
    op.create_index("ix_sop_deviation_facility_status", "sop_deviations", ["facility_id", "status", "detected_at"])
    op.create_table("label_templates", sa.Column("id", sa.String(36), primary_key=True), sa.Column("organization_id", sa.String(36), sa.ForeignKey("coman_organizations.id", ondelete="CASCADE"), nullable=False), sa.Column("facility_id", sa.String(36), sa.ForeignKey("coman_facilities.id", ondelete="CASCADE"), nullable=True), sa.Column("name", sa.String(160), nullable=False), sa.Column("version", sa.Integer(), nullable=False), sa.Column("jurisdiction", sa.String(80), nullable=False, server_default=""), sa.Column("license_scope", sa.String(80), nullable=False, server_default=""), sa.Column("status", sa.String(24), nullable=False, server_default="draft"), sa.Column("layout_json", sa.Text(), nullable=False, server_default="{}"), sa.Column("rules_json", sa.Text(), nullable=False, server_default="[]"), sa.Column("created_by", sa.String(255), nullable=False), sa.Column("approved_by", sa.String(255), nullable=False, server_default=""), sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True), *_timestamps(), sa.UniqueConstraint("organization_id", "name", "version", name="uq_label_template_version"), sa.CheckConstraint("status in ('draft','active','retired')", name="ck_label_template_status"))
    op.create_index("ix_label_template_org_status", "label_templates", ["organization_id", "status", "name"]); op.create_index("ix_label_templates_facility_id", "label_templates", ["facility_id"])
    op.create_table("label_reviews", sa.Column("id", sa.String(36), primary_key=True), sa.Column("organization_id", sa.String(36), sa.ForeignKey("coman_organizations.id", ondelete="CASCADE"), nullable=False), sa.Column("facility_id", sa.String(36), sa.ForeignKey("coman_facilities.id", ondelete="CASCADE"), nullable=False), sa.Column("template_id", sa.String(36), sa.ForeignKey("label_templates.id", ondelete="SET NULL"), nullable=True), sa.Column("product_id", sa.String(36), sa.ForeignKey("coman_products.id", ondelete="SET NULL"), nullable=True), sa.Column("package_id", sa.String(255), nullable=False, server_default=""), sa.Column("status", sa.String(24), nullable=False), sa.Column("input_json", sa.Text(), nullable=False, server_default="{}"), sa.Column("findings_json", sa.Text(), nullable=False, server_default="[]"), sa.Column("rule_set_reference", sa.String(1024), nullable=False, server_default=""), sa.Column("reviewed_by", sa.String(255), nullable=False), sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=False), sa.CheckConstraint("status in ('pass','warning','fail')", name="ck_label_review_status"))
    op.create_index("ix_label_review_facility_time", "label_reviews", ["facility_id", "reviewed_at"])
    op.create_table("machine_telemetry_events", sa.Column("id", sa.String(36), primary_key=True), sa.Column("organization_id", sa.String(36), sa.ForeignKey("coman_organizations.id", ondelete="CASCADE"), nullable=False), sa.Column("facility_id", sa.String(36), sa.ForeignKey("coman_facilities.id", ondelete="CASCADE"), nullable=False), sa.Column("machine_id", sa.String(36), sa.ForeignKey("coman_facility_machines.id", ondelete="CASCADE"), nullable=False), sa.Column("event_type", sa.String(24), nullable=False), sa.Column("metric_key", sa.String(120), nullable=False, server_default=""), sa.Column("numeric_value", sa.Float(), nullable=True), sa.Column("unit", sa.String(40), nullable=False, server_default=""), sa.Column("state", sa.String(80), nullable=False, server_default=""), sa.Column("source", sa.String(120), nullable=False, server_default="manual"), sa.Column("external_event_id", sa.String(255), nullable=False, server_default=""), sa.Column("payload_json", sa.Text(), nullable=False, server_default="{}"), sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False), sa.Column("received_at", sa.DateTime(timezone=True), nullable=False), sa.CheckConstraint("event_type in ('heartbeat','running','idle','downtime','fault','measurement','cycle')", name="ck_machine_telemetry_type"))
    op.create_index("ix_machine_telemetry_machine_time", "machine_telemetry_events", ["machine_id", "recorded_at"]); op.create_index("ix_machine_telemetry_facility_time", "machine_telemetry_events", ["facility_id", "recorded_at"])
    op.create_table("cultivation_harvests", sa.Column("id", sa.String(36), primary_key=True), sa.Column("organization_id", sa.String(36), sa.ForeignKey("coman_organizations.id", ondelete="CASCADE"), nullable=False), sa.Column("facility_id", sa.String(36), sa.ForeignKey("coman_facilities.id", ondelete="CASCADE"), nullable=False), sa.Column("harvest_code", sa.String(120), nullable=False), sa.Column("strain", sa.String(160), nullable=False), sa.Column("room", sa.String(160), nullable=False, server_default=""), sa.Column("plant_count", sa.Integer(), nullable=False, server_default="0"), sa.Column("wet_weight_g", sa.Float(), nullable=False, server_default="0"), sa.Column("dry_weight_g", sa.Float(), nullable=False, server_default="0"), sa.Column("waste_weight_g", sa.Float(), nullable=False, server_default="0"), sa.Column("labor_hours", sa.Float(), nullable=False, server_default="0"), sa.Column("status", sa.String(24), nullable=False, server_default="planned"), sa.Column("harvested_at", sa.DateTime(timezone=True), nullable=True), sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True), sa.Column("notes", sa.Text(), nullable=False, server_default=""), sa.Column("created_by", sa.String(255), nullable=False), *_timestamps(), sa.UniqueConstraint("facility_id", "harvest_code", name="uq_cultivation_harvest_code"), sa.CheckConstraint("status in ('planned','active','drying','completed','cancelled')", name="ck_cultivation_harvest_status"))
    op.create_index("ix_cultivation_harvest_facility_status", "cultivation_harvests", ["facility_id", "status", "harvested_at"])
    op.create_table("partner_portal_access", sa.Column("id", sa.String(36), primary_key=True), sa.Column("organization_id", sa.String(36), sa.ForeignKey("coman_organizations.id", ondelete="CASCADE"), nullable=False), sa.Column("facility_id", sa.String(36), sa.ForeignKey("coman_facilities.id", ondelete="CASCADE"), nullable=False), sa.Column("partner_id", sa.String(36), sa.ForeignKey("commercial_trade_partners.id", ondelete="CASCADE"), nullable=False), sa.Column("token_hash", sa.String(64), nullable=False), sa.Column("label", sa.String(160), nullable=False, server_default="Retailer Portal"), sa.Column("created_by", sa.String(255), nullable=False), sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True), sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True), sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True), *_timestamps(), sa.UniqueConstraint("token_hash", name="uq_partner_portal_token_hash"))
    op.create_index("ix_partner_portal_partner_active", "partner_portal_access", ["partner_id", "revoked_at", "expires_at"])
    op.create_table("service_accounts", sa.Column("id", sa.String(36), primary_key=True), sa.Column("organization_id", sa.String(36), sa.ForeignKey("coman_organizations.id", ondelete="CASCADE"), nullable=False), sa.Column("facility_id", sa.String(36), sa.ForeignKey("coman_facilities.id", ondelete="CASCADE"), nullable=True), sa.Column("name", sa.String(160), nullable=False), sa.Column("token_hash", sa.String(64), nullable=False), sa.Column("scopes_json", sa.Text(), nullable=False, server_default="[]"), sa.Column("active", sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column("created_by", sa.String(255), nullable=False), sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True), *_timestamps(), sa.UniqueConstraint("organization_id", "name", name="uq_service_account_name"), sa.UniqueConstraint("token_hash", name="uq_service_account_token_hash"))
    op.create_index("ix_service_account_org_active", "service_accounts", ["organization_id", "active"])
    op.create_table("webhook_subscriptions", sa.Column("id", sa.String(36), primary_key=True), sa.Column("organization_id", sa.String(36), sa.ForeignKey("coman_organizations.id", ondelete="CASCADE"), nullable=False), sa.Column("facility_id", sa.String(36), sa.ForeignKey("coman_facilities.id", ondelete="CASCADE"), nullable=True), sa.Column("name", sa.String(160), nullable=False), sa.Column("target_url", sa.String(2048), nullable=False), sa.Column("event_types_json", sa.Text(), nullable=False, server_default="[]"), sa.Column("secret_hash", sa.String(64), nullable=False), sa.Column("status", sa.String(24), nullable=False, server_default="active"), sa.Column("created_by", sa.String(255), nullable=False), *_timestamps(), sa.CheckConstraint("status in ('active','paused','disabled')", name="ck_webhook_subscription_status"))
    op.create_index("ix_webhook_subscription_org_status", "webhook_subscriptions", ["organization_id", "status"])
    op.create_table("webhook_deliveries", sa.Column("id", sa.String(36), primary_key=True), sa.Column("organization_id", sa.String(36), sa.ForeignKey("coman_organizations.id", ondelete="CASCADE"), nullable=False), sa.Column("facility_id", sa.String(36), sa.ForeignKey("coman_facilities.id", ondelete="CASCADE"), nullable=True), sa.Column("subscription_id", sa.String(36), sa.ForeignKey("webhook_subscriptions.id", ondelete="CASCADE"), nullable=False), sa.Column("event_type", sa.String(120), nullable=False), sa.Column("event_id", sa.String(255), nullable=False), sa.Column("payload_json", sa.Text(), nullable=False, server_default="{}"), sa.Column("status", sa.String(24), nullable=False, server_default="queued"), sa.Column("attempt_count", sa.Integer(), nullable=False, server_default="0"), sa.Column("last_error", sa.Text(), nullable=False, server_default=""), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("last_attempt_at", sa.DateTime(timezone=True), nullable=True), sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True), sa.CheckConstraint("status in ('queued','sending','succeeded','failed','dead_letter')", name="ck_webhook_delivery_status"))
    op.create_index("ix_webhook_delivery_status_time", "webhook_deliveries", ["status", "created_at"]); op.create_index("ix_webhook_delivery_subscription_time", "webhook_deliveries", ["subscription_id", "created_at"])


def downgrade() -> None:
    for table in ("webhook_deliveries", "webhook_subscriptions", "service_accounts", "partner_portal_access", "cultivation_harvests", "machine_telemetry_events", "label_reviews", "label_templates", "sop_deviations", "sop_acknowledgements", "sop_documents"):
        op.drop_table(table)
