import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useEffect, useMemo, useState } from "react";
import { apiGet, apiPost } from "../lib/api";

type Facility = { id:string; organization_id?:string; name:string; code:string; timezone_name?:string; license_number?:string; license_type?:string; active?:boolean; retail_enabled?:boolean; production_enabled?:boolean; cultivation_enabled?:boolean; commercial_enabled?:boolean };
type Organization = { id:string; name:string; slug:string; active:boolean; facilities:Facility[] };
type User = { id:string; organization_id:string; username:string; email:string; display_name:string; role:string; active:boolean; must_change_password:boolean; last_login_at:string|null; created_at:string; facility_ids:string[] };
type Context = { user:{ id?:string; display_name:string; email:string; role:string }; organization:{ id:string; name:string }|null; facilities:Facility[] };
const baseRoles = ["admin","buyer","planner","supervisor","operator","qa","read_only"];

export function AdminPage(){
  const client=useQueryClient();
  const context=useQuery({queryKey:["account-context"],queryFn:({signal})=>apiGet<Context>("/api/v1/account/context",signal)});
  const users=useQuery({queryKey:["admin-users"],queryFn:({signal})=>apiGet<User[]>("/api/v1/admin/users",signal)});
  const isDev=context.data?.user.role==="dev";
  const organizations=useQuery({queryKey:["admin-organizations"],queryFn:({signal})=>apiGet<Organization[]>("/api/v1/admin/organizations",signal),enabled:isDev});
  const [inviting,setInviting]=useState(false); const [editing,setEditing]=useState<User|null>(null); const [resetting,setResetting]=useState<User|null>(null);
  const refresh=()=>{client.invalidateQueries({queryKey:["admin-users"]});client.invalidateQueries({queryKey:["admin-organizations"]});client.invalidateQueries({queryKey:["account-context"]});};
  const facilityLookup=useMemo(()=>{const rows=isDev?(organizations.data??[]).flatMap(org=>org.facilities):(context.data?.facilities??[]);return new Map(rows.map(row=>[row.id,row]));},[isDev,organizations.data,context.data]);
  return <div className="page">
    <div className="page-heading"><div><div className="eyebrow">Admin Tools · Streamlit parity</div><h1>Users & Access</h1><p>Account identity, legacy username continuity, roles, facility permissions, password lifecycle, organizations and license-scoped operating facilities.</p></div><button className="primary" onClick={()=>setInviting(true)}>Invite / Link User</button></div>
    <section className="metrics"><Metric label="Users" value={users.data?.length??"—"}/><Metric label="Active" value={users.data?.filter(row=>row.active).length??"—"}/><Metric label="Forced password change" value={users.data?.filter(row=>row.must_change_password).length??"—"}/><Metric label={isDev?"Organizations":"Facilities"} value={isDev?(organizations.data?.length??"—"):(context.data?.facilities.length??"—")}/></section>
    {users.isError?<div className="state error">{users.error.message}</div>:null}
    <section className="inventory-panel"><div className="section-heading"><div><div className="eyebrow">Accounts</div><h2>Durable Users</h2></div></div><div className="table-wrap"><table><thead><tr><th>User</th><th>Username</th><th>Organization</th><th>Role</th><th>Facilities</th><th>Password</th><th>Status</th><th>Last login</th><th>Manage</th></tr></thead><tbody>{users.data?.map(row=><tr key={row.id}><td><strong>{row.display_name||row.email}</strong><br/><small>{row.email}<br/>{row.id}</small></td><td>{row.username||"—"}</td><td>{orgName(row.organization_id,organizations.data,context.data)}</td><td>{row.role}</td><td>{row.facility_ids.map(id=>facilityLookup.get(id)?.code??id).join(", ")||"None"}</td><td><span className={`badge ${row.must_change_password?"hold":"production-ready"}`}>{row.must_change_password?"Change required":"Current"}</span></td><td><span className={`badge ${row.active?"production-ready":"hold"}`}>{row.active?"Active":"Inactive"}</span></td><td>{row.last_login_at?new Date(row.last_login_at).toLocaleString():"Never"}</td><td><div className="heading-actions"><button className="link-button" onClick={()=>setEditing(row)}>Edit access</button><button className="link-button" onClick={()=>setResetting(row)}>Reset password</button></div></td></tr>)}</tbody></table></div></section>
    {isDev?<OrganizationFacilityAdmin organizations={organizations.data??[]} onSaved={refresh}/>:null}
    {inviting?<InviteUser context={context.data} organizations={organizations.data??[]} onClose={()=>setInviting(false)} onSaved={()=>{setInviting(false);refresh();}}/>:null}
    {editing?<EditUser user={editing} context={context.data} organizations={organizations.data??[]} onClose={()=>setEditing(null)} onSaved={()=>{setEditing(null);refresh();}}/>:null}
    {resetting?<ResetPassword user={resetting} onClose={()=>setResetting(null)} onSaved={()=>{setResetting(null);refresh();}}/>:null}
  </div>;
}

function OrganizationFacilityAdmin({organizations,onSaved}:{organizations:Organization[];onSaved:()=>void}){
  const [org,setOrg]=useState({name:"",slug:""}); const [facility,setFacility]=useState({organization_id:organizations[0]?.id??"",name:"",code:"",timezone_name:"America/New_York",license_number:"",license_type:"",retail_enabled:true,production_enabled:false,cultivation_enabled:false,commercial_enabled:true});
  useEffect(()=>{if(!facility.organization_id&&organizations[0])setFacility(current=>({...current,organization_id:organizations[0].id}));},[organizations,facility.organization_id]);
  const createOrg=useMutation({mutationFn:()=>apiPost("/api/v1/admin/organizations",org),onSuccess:()=>{setOrg({name:"",slug:""});onSaved();}});
  const createFacility=useMutation({mutationFn:()=>apiPost("/api/v1/admin/facilities",facility),onSuccess:()=>{setFacility(current=>({...current,name:"",code:"",license_number:"",license_type:""}));onSaved();}});
  return <><div className="page-heading section-heading"><div><div className="eyebrow">Level DEV</div><h2>Organizations & Facilities</h2><p>Create the company and the exact licensed operating contexts users can switch into.</p></div></div><div className="two-column-grid">
    <section className="inventory-panel"><h3>Create Organization</h3><div className="form-grid"><Text label="Company name" value={org.name} onChange={name=>setOrg({...org,name})}/><Text label="Slug" value={org.slug} onChange={slug=>setOrg({...org,slug})}/></div><button className="primary submit" disabled={!org.name.trim()||!org.slug.trim()||createOrg.isPending} onClick={()=>createOrg.mutate()}>Create Organization</button>{createOrg.isError?<div className="form-error">{createOrg.error.message}</div>:null}</section>
    <section className="inventory-panel"><h3>Create Licensed Facility</h3><div className="form-grid"><label>Organization<select value={facility.organization_id} onChange={e=>setFacility({...facility,organization_id:e.target.value})}><option value="">Select…</option>{organizations.filter(row=>row.active).map(row=><option value={row.id} key={row.id}>{row.name}</option>)}</select></label><Text label="Facility name" value={facility.name} onChange={name=>setFacility({...facility,name})}/><Text label="Facility code" value={facility.code} onChange={code=>setFacility({...facility,code})}/><Text label="Timezone" value={facility.timezone_name} onChange={timezone_name=>setFacility({...facility,timezone_name})}/><Text label="License number" value={facility.license_number} onChange={license_number=>setFacility({...facility,license_number})}/><Text label="License type" value={facility.license_type} onChange={license_type=>setFacility({...facility,license_type})}/></div><fieldset className="facility-checks"><legend>Capabilities</legend><Check label="Retail" checked={facility.retail_enabled} onChange={retail_enabled=>setFacility({...facility,retail_enabled})}/><Check label="Production / Manufacturing" checked={facility.production_enabled} onChange={production_enabled=>setFacility({...facility,production_enabled})}/><Check label="Cultivation" checked={facility.cultivation_enabled} onChange={cultivation_enabled=>setFacility({...facility,cultivation_enabled})}/><Check label="Commercial" checked={facility.commercial_enabled} onChange={commercial_enabled=>setFacility({...facility,commercial_enabled})}/></fieldset><button className="primary submit" disabled={!facility.organization_id||!facility.name.trim()||!facility.code.trim()||createFacility.isPending} onClick={()=>createFacility.mutate()}>Create Facility</button>{createFacility.isError?<div className="form-error">{createFacility.error.message}</div>:null}</section>
  </div><section className="inventory-panel"><div className="table-wrap"><table><thead><tr><th>Organization</th><th>Facility</th><th>Code</th><th>License</th><th>License Type</th><th>Capabilities</th></tr></thead><tbody>{organizations.flatMap(org=>org.facilities.map(facility=><tr key={facility.id}><td>{org.name}</td><td>{facility.name}</td><td>{facility.code}</td><td>{facility.license_number||"—"}</td><td>{facility.license_type||"—"}</td><td>{[facility.retail_enabled&&"Retail",facility.production_enabled&&"Production",facility.cultivation_enabled&&"Cultivation",facility.commercial_enabled&&"Commercial"].filter(Boolean).join(", ")||"None"}</td></tr>))}</tbody></table></div></section></>;
}

function InviteUser({context,organizations,onClose,onSaved}:{context:Context|undefined;organizations:Organization[];onClose:()=>void;onSaved:()=>void}){
  const isDev=context?.user.role==="dev"; const availableRoles=isDev?["dev",...baseRoles]:baseRoles;
  const defaultOrg=isDev?(organizations.find(row=>row.active)?.id??""):(context?.organization?.id??"");
  const [advanced,setAdvanced]=useState(false); const [form,setForm]=useState({auth_user_id:"",email:"",username:"",display_name:"",role:"buyer",organization_id:defaultOrg,facility_ids:facilitiesFor(defaultOrg,isDev,organizations,context).map(row=>row.id),redirect_to:`${window.location.origin}/`});
  const facilities=facilitiesFor(form.organization_id,isDev,organizations,context); const effectiveFacilities=form.role==="dev"?[]:form.facility_ids;
  const save=useMutation({mutationFn:()=>apiPost(advanced?"/api/v1/admin/users/link":"/api/v1/admin/users/invite",{...form,facility_ids:effectiveFacilities,organization_id:form.role==="dev"?"":form.organization_id}),onSuccess:onSaved});
  const changeOrg=(organization_id:string)=>setForm({...form,organization_id,facility_ids:facilitiesFor(organization_id,isDev,organizations,context).map(row=>row.id)});
  return <Modal title={advanced?"Link Existing Supabase User":"Invite User"} eyebrow="Authentication & authorization" onClose={onClose}><label className="toggle admin-mode"><input type="checkbox" checked={advanced} onChange={e=>setAdvanced(e.target.checked)}/>Already exists in Supabase Auth</label><div className="form-grid">{advanced?<Text label="Supabase user ID" value={form.auth_user_id} onChange={auth_user_id=>setForm({...form,auth_user_id})}/>:null}<Text label="Email" value={form.email} onChange={email=>setForm({...form,email})}/><Text label="Username" value={form.username} onChange={username=>setForm({...form,username})}/><Text label="Display name" value={form.display_name} onChange={display_name=>setForm({...form,display_name})}/><label>Role<select value={form.role} onChange={e=>setForm({...form,role:e.target.value,facility_ids:e.target.value==="dev"?[]:facilities.map(row=>row.id)})}>{availableRoles.map(role=><option key={role}>{role}</option>)}</select></label>{isDev&&form.role!=="dev"?<label>Organization<select value={form.organization_id} onChange={e=>changeOrg(e.target.value)}>{organizations.filter(row=>row.active).map(row=><option value={row.id} key={row.id}>{row.name}</option>)}</select></label>:null}</div>{form.role!=="dev"?<FacilityChecks facilities={facilities} selected={form.facility_ids} onChange={facility_ids=>setForm({...form,facility_ids})}/>:<div className="state">DEV accounts are platform-scoped and do not require a facility assignment.</div>}<button className="primary submit" disabled={!form.email||(!form.username&&!form.email)||(advanced&&!form.auth_user_id)||(form.role!=="dev"&&!effectiveFacilities.length)||save.isPending} onClick={()=>save.mutate()}>{advanced?"Link Account":"Send Invitation"}</button>{save.isError?<div className="form-error">{save.error.message}</div>:null}</Modal>;
}

function EditUser({user,context,organizations,onClose,onSaved}:{user:User;context:Context|undefined;organizations:Organization[];onClose:()=>void;onSaved:()=>void}){
  const isDev=context?.user.role==="dev"; const availableRoles=isDev?["dev",...baseRoles]:baseRoles;
  const [form,setForm]=useState({username:user.username,email:user.email,display_name:user.display_name,role:user.role,organization_id:user.organization_id,facility_ids:user.facility_ids,active:user.active,must_change_password:user.must_change_password});
  useEffect(()=>setForm({username:user.username,email:user.email,display_name:user.display_name,role:user.role,organization_id:user.organization_id,facility_ids:user.facility_ids,active:user.active,must_change_password:user.must_change_password}),[user]);
  const facilities=facilitiesFor(form.organization_id,isDev,organizations,context); const save=useMutation({mutationFn:()=>apiPost(`/api/v1/admin/users/${user.id}`,{...form,facility_ids:form.role==="dev"?[]:form.facility_ids,organization_id:form.role==="dev"?"":form.organization_id}),onSuccess:onSaved});
  return <Modal title={user.display_name||user.email} eyebrow="Authorization" onClose={onClose}><div className="form-grid"><Text label="Username" value={form.username} onChange={username=>setForm({...form,username})}/><Text label="Email" value={form.email} onChange={email=>setForm({...form,email})}/><Text label="Display name" value={form.display_name} onChange={display_name=>setForm({...form,display_name})}/><label>Role<select value={form.role} onChange={e=>{const role=e.target.value;setForm({...form,role,facility_ids:role==="dev"?[]:form.facility_ids})}}>{availableRoles.map(role=><option key={role}>{role}</option>)}</select></label>{isDev&&form.role!=="dev"?<label>Organization<select value={form.organization_id} onChange={e=>{const organization_id=e.target.value;setForm({...form,organization_id,facility_ids:facilitiesFor(organization_id,true,organizations,context).map(row=>row.id)})}}>{organizations.filter(row=>row.active).map(row=><option value={row.id} key={row.id}>{row.name}</option>)}</select></label>:null}<Check label="Account active" checked={form.active} onChange={active=>setForm({...form,active})}/><Check label="Force password change" checked={form.must_change_password} onChange={must_change_password=>setForm({...form,must_change_password})}/></div>{form.role!=="dev"?<FacilityChecks facilities={facilities} selected={form.facility_ids} onChange={facility_ids=>setForm({...form,facility_ids})}/>:null}<button className="primary submit" disabled={form.role!=="dev"&&!form.facility_ids.length||save.isPending} onClick={()=>save.mutate()}>Save Access</button>{save.isError?<div className="form-error">{save.error.message}</div>:null}</Modal>;
}

function ResetPassword({user,onClose,onSaved}:{user:User;onClose:()=>void;onSaved:()=>void}){const [password,setPassword]=useState("");const [confirm,setConfirm]=useState("");const save=useMutation({mutationFn:()=>apiPost(`/api/v1/admin/users/${user.id}/reset-password`,{password}),onSuccess:onSaved});return <Modal title={`Reset ${user.username||user.email}`} eyebrow="Password lifecycle" onClose={onClose}><p>The temporary password is applied to Supabase when configured and to the legacy compatibility hash. The user will be required to change it after sign-in.</p><div className="form-grid"><label>Temporary password<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label><label>Confirm password<input type="password" value={confirm} onChange={e=>setConfirm(e.target.value)}/></label></div>{confirm&&password!==confirm?<div className="form-error">Passwords do not match.</div>:null}<button className="primary submit" disabled={password.length<12||password!==confirm||save.isPending} onClick={()=>save.mutate()}>Reset Password & Require Change</button>{save.isError?<div className="form-error">{save.error.message}</div>:null}</Modal>}
function FacilityChecks({facilities,selected,onChange}:{facilities:Facility[];selected:string[];onChange:(ids:string[])=>void}){return <fieldset className="facility-checks"><legend>Facility access</legend>{facilities.map(row=><label className="toggle" key={row.id}><input type="checkbox" checked={selected.includes(row.id)} onChange={e=>onChange(e.target.checked?[...selected,row.id]:selected.filter(id=>id!==row.id))}/>{row.name} · {row.code}{row.license_type?` · ${row.license_type}`:""}</label>)}{!facilities.length?<span>No active facilities available.</span>:null}</fieldset>}
function facilitiesFor(orgId:string,isDev:boolean,organizations:Organization[],context:Context|undefined){return isDev?(organizations.find(row=>row.id===orgId)?.facilities.filter(row=>row.active!==false)??[]):(context?.facilities??[])}
function orgName(orgId:string,organizations:Organization[]|undefined,context:Context|undefined){if(!orgId)return"Platform";return organizations?.find(row=>row.id===orgId)?.name??(context?.organization?.id===orgId?context.organization.name:orgId)}
function Modal({title,eyebrow,onClose,children}:{title:string;eyebrow:string;onClose:()=>void;children:React.ReactNode}){return <div className="modal-backdrop"><div className="modal"><div className="modal-heading"><div><div className="eyebrow">{eyebrow}</div><h2>{title}</h2></div><button className="secondary" onClick={onClose}>Close</button></div>{children}</div></div>}
function Text({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}){return <label>{label}<input value={value} onChange={e=>onChange(e.target.value)}/></label>}
function Check({label,checked,onChange}:{label:string;checked:boolean;onChange:(checked:boolean)=>void}){return <label className="toggle"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/>{label}</label>}
function Metric({label,value}:{label:string;value:string|number}){return <article className="metric"><span>{label}</span><strong>{value}</strong></article>}
