import { useRef, useState, type ChangeEvent, type FormEvent } from "react";
import { ArrowUpRight } from "lucide-react";
import { MarketingPage, ConsultationCTA } from "../components/marketing/MarketingPage";
import { ConsultingLeadForm } from "../components/marketing/ConsultingLeadForm";
import { CSV_MAX_BYTES, inventoryColumns, inventoryHealth, operationsScore, parseInventoryCsv, safeFilename, scoreQuestions, type ColumnMapping, type ScoreAnswers } from "../lib/advisoryTools";
import { trackMarketingEvent } from "../lib/marketingAnalytics";
import "../advisory-forms.css";

function ToolIntro({name,title,children}:{name:string;title:string;children:React.ReactNode}) {
  return <section className="mh-hero mh-container"><nav className="advisory-breadcrumbs" aria-label="Breadcrumb"><a href="/">Home</a><span>/</span><a href="/consulting">Consulting</a><span>/</span><span aria-current="page">{name}</span></nav><span className="mh-eyebrow">DoobieLogic Advisory / Free tool</span><h1>{title}</h1><div className="ad-reading">{children}</div></section>;
}
function OperationsScore() {
  const [answers,setAnswers]=useState<ScoreAnswers>({}),[result,setResult]=useState<ReturnType<typeof operationsScore>|null>(null),[error,setError]=useState("");
  const started=useRef(false), resultRef=useRef<HTMLDivElement>(null);
  const groups=[...new Set(scoreQuestions.map(q=>q.category))];
  function complete(event:FormEvent) {event.preventDefault();try {const score=operationsScore(answers);setResult(score);setError("");trackMarketingEvent("operations_score_completed",{placement:"tool",item:"operations-score"});setTimeout(()=>{resultRef.current?.focus();resultRef.current?.scrollIntoView({behavior:"auto",block:"start"});},0);}catch(e){setError((e as Error).message);}}
  return <MarketingPage><ToolIntro name="Operations score" title="Where does the work need attention?"><p>25 questions about operational habits. Get a transparent self-assessment, then choose whether to share it for a review. This is not a regulatory compliance certification.</p></ToolIntro>
    <section className="mh-section mh-container"><div className="ad-reading"><h2>A useful starting point.</h2><p>Score each practice from 0 (not in place or unknown) to 4 (consistent and reviewed). Not applicable excludes that question. Your overall score is the sum of applicable answers divided by their maximum possible score, multiplied by 100. At least 15 applicable answers are required. All questions have equal weight.</p></div>
    <form onSubmit={complete} className="ad-form"><p className="ad-tool-status" role="status">{Object.keys(answers).length} of 25 questions answered</p>
      {groups.map(category=><section key={category} aria-label={category}><h3>{category}</h3>{scoreQuestions.filter(q=>q.category===category).map(q=><fieldset className="ad-question" key={q.id}><legend>{q.text}</legend><div className="ad-answer-options">{[[0,"0 · Not in place / unknown"],[1,"1 · Ad hoc"],[2,"2 · Partly defined"],[3,"3 · Usually followed"],[4,"4 · Consistent & reviewed"],[null,"Not applicable"]].map(([value,label])=><label key={String(value)}><input type="radio" name={q.id} required value={value===null?"na":value} checked={q.id in answers && answers[q.id]===value} onChange={()=>{setAnswers({...answers,[q.id]:value as number|null});setResult(null);if(!started.current){started.current=true;trackMarketingEvent("operations_score_started",{placement:"tool",item:"operations-score"});}}}/>{label}</label>)}</div></fieldset>)}</section>)}
      <button className="mh-button" type="submit">Calculate my operations score <ArrowUpRight size={17}/></button>{error&&<p role="alert">{error}</p>}
    </form></section>
    {result&&<><section className="mh-section mh-container"><div ref={resultRef} className="ad-tool-results" tabIndex={-1}><span className="mh-eyebrow">Your self-assessment</span><h2>Operational health: {result.overall}/100</h2><p>Based on {result.answered} applicable answers out of 25. Higher scores indicate more consistently reported processes, not independently verified performance or regulatory compliance.</p><div className="mh-control-grid">{result.categories.map(c=><article key={c.name}><h3>{c.name}</h3><p>{c.score===null?"Not assessed":`${c.score}/100`} · {c.count} applicable questions</p>{c.score!==null&&<progress max={100} value={c.score} aria-label={`${c.name}: ${c.score} out of 100`}/>}</article>)}</div><h3>Start the review here</h3><ul>{[...result.categories].filter(c=>c.score!==null).sort((a,b)=>a.score!-b.score!).slice(0,2).map(c=><li key={c.name}>{c.name}: review the lowest-scored practices with the people doing the work; assign one improvement and a review date.</li>)}</ul><div className="ad-actions"><ConsultationCTA service="operational-diagnostic" href="#consultation">Book an operational review</ConsultationCTA><a className="mh-text-link" href="/consulting/operational-diagnostic">Explore the $500 starting diagnostic <ArrowUpRight size={16}/></a></div></div></section><ConsultingLeadForm service="operational-diagnostic" sourceTool="operations-score" toolInputs={answers}/></>}
  </MarketingPage>;
}

function InventoryCheck() {
  const [csv,setCsv]=useState<ReturnType<typeof parseInventoryCsv>|null>(null),[mapping,setMapping]=useState<ColumnMapping>({}),[fileName,setFileName]=useState(""),[days,setDays]=useState(30),[error,setError]=useState(""),[result,setResult]=useState<ReturnType<typeof inventoryHealth>|null>(null),[loading,setLoading]=useState(false);
  const input=useRef<HTMLInputElement>(null), latest=useRef(0), resultRef=useRef<HTMLDivElement>(null);
  async function load(event:ChangeEvent<HTMLInputElement>) {
    const file=event.target.files?.[0]; const version=++latest.current;setCsv(null);setResult(null);setError("");setMapping({});if(!file)return;
    try {
      if(!/\.csv$/i.test(file.name))throw new Error("Select a .csv file. Spreadsheet workbooks and macros are not supported.");
      if(!file.size||file.size>CSV_MAX_BYTES)throw new Error("Select a nonempty CSV up to 2 MB.");
      setLoading(true);const bytes=await file.arrayBuffer();const text=new TextDecoder("utf-8",{fatal:true}).decode(bytes);const parsed=parseInventoryCsv(text);if(version!==latest.current)return;
      setCsv(parsed);setFileName(safeFilename(file.name));const initial:ColumnMapping={};for(const col of inventoryColumns){const found=parsed.headers.find(h=>h.toLowerCase().replace(/[ _-]/g,"")===col.toLowerCase().replace(/ /g,""));if(found)initial[col]=found;}setMapping(initial);
      trackMarketingEvent("inventory_check_started",{placement:"tool",item:"inventory-health-check"});
    }catch(e){if(version===latest.current)setError(e instanceof TypeError?"Use a UTF-8 encoded CSV file.":(e as Error).message);}finally{if(version===latest.current)setLoading(false);}
  }
  function analyze(event:FormEvent) {event.preventDefault();try{if(!csv)return;setResult(inventoryHealth(csv.headers,csv.rows,mapping,days));setError("");trackMarketingEvent("inventory_check_completed",{placement:"tool",item:"inventory-health-check"});setTimeout(()=>{resultRef.current?.focus();resultRef.current?.scrollIntoView({behavior:"auto",block:"start"});},0);}catch(e){setError((e as Error).message);}}
  return <MarketingPage><ToolIntro name="Inventory health check" title="A clearer read on your inventory."><p>Load a CSV, map the columns, and review what the data can tell you. Analysis runs in your browser. Your file is never uploaded, stored on our servers, or attached to a consulting inquiry.</p></ToolIntro>
    <section className="mh-section mh-container"><form className="ad-form" onSubmit={analyze}><h2>Start with your export.</h2><p>UTF-8 CSV only. Maximum 2 MB, 5,000 rows and 64 columns. Quantity and SKU or Product are required. Cost and Price should be per unit; sales and stock quantities must use matching units. Dates use YYYY-MM-DD. Avoid customer or employee information.</p><div className="ad-fields"><label className="ad-full">Inventory CSV<input ref={input} type="file" accept=".csv,text/csv" onChange={load} aria-describedby="csv-help"/></label></div><p id="csv-help">CSV text is never executed. Formula-like cells remain inert text; no spreadsheet exports are generated.</p>
      {loading&&<p role="status">Reading the CSV in your browser…</p>}
      {csv&&<><p role="status">{fileName}: {csv.rows.length} rows. {csv.formulaCells>0?`${csv.formulaCells} formula-like cells are treated as text, never executed.`:""}</p><h3>Map your columns</h3><div className="ad-fields ad-mapping">{inventoryColumns.map(col=><label key={col}>{col}<select aria-label={`${col} column`} value={mapping[col]||""} onChange={e=>{setMapping({...mapping,[col]:e.target.value});setResult(null);}}><option value="">Not available</option>{csv.headers.map(h=><option key={h}>{h}</option>)}</select></label>)}<label>Sales observation window (days)<input type="number" min={1} max={366} step={1} required value={days} onChange={e=>{setDays(Number(e.target.value));setResult(null);}}/></label></div><p>Use the actual time window covered by Sales Quantity. The default 30 days is a starting input, not an assumption about your file.</p><details><summary>Preview the first 3 rows</summary><div className="ad-table-wrap"><table><thead><tr>{csv.headers.map(h=><th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{csv.rows.slice(0,3).map((row,i)=><tr key={i}>{row.map((cell,j)=><td key={j}>{cell}</td>)}</tr>)}</tbody></table></div></details><div className="ad-actions"><button className="mh-button" type="submit">Analyze inventory <ArrowUpRight size={17}/></button><button type="button" className="mh-text-link" onClick={()=>{latest.current++;setCsv(null);setResult(null);setMapping({});setFileName("");setError("");if(input.current)input.current.value="";}}>Clear file and results</button></div></>}
      {error&&<p role="alert" className="ad-feedback">{error}</p>}
    </form></section>
    {result&&<><section className="mh-section mh-container"><div ref={resultRef} tabIndex={-1} className="ad-tool-results"><span className="mh-eyebrow">Your data / Your review</span><h2>Inventory review signals.</h2><div className="mh-control-grid">{result.metrics.map(m=><article key={m.label}><h3>{m.label}</h3><strong>{m.value}</strong><p>{m.explanation}</p></article>)}</div><h3>Calculation boundaries</h3><ul>{result.warnings.map(w=><li key={w}>{w}</li>)}</ul><p>These screens suggest questions for a review. They do not establish product safety, compliance, profitability or the right stock target for your business.</p><div className="ad-actions"><a className="mh-button" href="/consulting/inventory-profit-audit" onClick={()=>trackMarketingEvent("audit_cta_clicked",{placement:"tool",item:"inventory-profit-audit"})}>Get the full inventory &amp; profit audit <ArrowUpRight size={17}/></a></div></div></section><ConsultingLeadForm service="inventory-profit-audit" sourceTool="inventory-health-check"/></>}
  </MarketingPage>;
}
export default function AdvisoryTools(){return window.location.pathname.replace(/\/$/,"").endsWith("operations-score")?<OperationsScore/>:<InventoryCheck/>;}
