import { useQuery } from "@tanstack/react-query";
import { useMemo, useState } from "react";
import { apiGet } from "../lib/api";

type Row=Record<string,unknown>;
type Trends={category_mix:Row[];package_size_mix:Row[];top_movers:Row[];best_sellers_by_category:Row[];fast_movers_low_stock:Row[]};

export function BuyerTrendsPage(){
  const [trendDays,setTrendDays]=useState(30);const [compareDays,setCompareDays]=useState(30);const [multiplier,setMultiplier]=useState(1);const [topN,setTopN]=useState(10);
  const params=useMemo(()=>new URLSearchParams({trend_days:String(trendDays),compare_days:String(compareDays),run_rate_multiplier:String(multiplier),top_n:String(topN)}),[trendDays,compareDays,multiplier,topN]);
  const result=useQuery({queryKey:["buyer-trends",params.toString()],queryFn:({signal})=>apiGet<Trends>(`/api/v1/buyer-parity/trends?${params}`,signal)});const data=result.data;
  const categories=[...new Set((data?.best_sellers_by_category??[]).map(row=>String(row.mastercategory)))];
  return <div className="page exact-trends"><h1>📈 Trends</h1><p>This page reads the same uploaded Dutchie/BLAZE exports (if present) and surfaces quick signals: category mix, package-size mix, and velocity movers.</p><p><strong>Note:</strong> If you haven’t uploaded files yet, go to <strong>Inventory Dashboard</strong> first.</p><section className="inventory-panel parity-controls"><label>Trend window (days)<input type="range" min="7" max="120" value={trendDays} onChange={event=>setTrendDays(Number(event.target.value))}/><span>{trendDays}</span></label><label>Comparison window (prior days)<input type="range" min="7" max="120" value={compareDays} onChange={event=>setCompareDays(Number(event.target.value))}/><span>{compareDays}</span></label><label>Run-rate multiplier<input type="number" min="0.1" max="3" step="0.1" value={multiplier} onChange={event=>setMultiplier(Number(event.target.value))}/></label></section>
  {result.isError?<div className="state error">{result.error.message}</div>:null}{result.isLoading?<div className="state">Building Trends from active Buyer Dash data…</div>:null}{data?<><h3>Category Mix (Units)</h3><Table rows={data.category_mix} columns={["mastercategory","unitssold","units_per_day","unit_share"]}/><h3>Package Size Mix (Units)</h3><Table rows={data.package_size_mix} columns={["packagesize","unitssold","units_per_day"]}/><h3>Top Movers (SKU-level)</h3><Table rows={data.top_movers} columns={["product_name","mastercategory","strain_type","packagesize","unitssold","revenue","units_per_day","avg_price"]}/><h3>Best Sellers by Category</h3><label className="compact-field">Top N per category<input type="number" min="1" max="50" value={topN} onChange={event=>setTopN(Number(event.target.value))}/></label>{categories.length?categories.map(category=><details className="streamlit-expander" key={category}><summary>{title(category)} — Top {topN}</summary><div className="streamlit-expander-body"><Table rows={data.best_sellers_by_category.filter(row=>String(row.mastercategory)===category)} columns={["product_name","mastercategory","strain_type","packagesize","unitssold","revenue","units_per_day","avg_price"]}/></div></details>):<div className="info-banner">No categories found in sales data.</div>}{data.fast_movers_low_stock.length?<><h3>Fast Movers + Low Stock (SKU-level)</h3><Table rows={data.fast_movers_low_stock} columns={["product_name","subcategory","strain_type","packagesize","unitssold","units_per_day","onhandunits","risk_score"]}/></>:null}</>:null}</div>;
}
function title(value:string){return value.replace(/\b\w/g,char=>char.toUpperCase())}function head(value:string){return value.replaceAll("_"," ")}function show(value:unknown){if(value==null||value==="")return "—";if(typeof value==="number")return Number.isInteger(value)?value.toLocaleString():value.toLocaleString(undefined,{maximumFractionDigits:2});return String(value)}function Table({rows,columns}:{rows:Row[];columns:string[]}){const visible=columns.filter(column=>rows.some(row=>row[column]!==undefined));return <div className="table-wrap"><table><thead><tr>{visible.map(column=><th key={column}>{head(column)}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={index}>{visible.map(column=><td key={column}>{show(row[column])}</td>)}</tr>)}</tbody></table></div>}
