import { useQuery } from "@tanstack/react-query";
import { useMemo, useState } from "react";
import { apiGet } from "../lib/api";

type Row = Record<string, unknown>;
type Budget = { summary:{recommended_budget:number;active_inventory_cost:number;target_inventory_cost:number;recommended_position:number;avg_daily_cogs:number;on_order_cost:number;sales_window_total:number};categories:Row[];scenarios:Row[] };
export function BuyingBudgetPage(){
 const [days,setDays]=useState(30);const [target,setTarget]=useState(45);const [cogs,setCogs]=useState(50);const [safety,setSafety]=useState(10);const [growth,setGrowth]=useState(0);const [dead,setDead]=useState(false);const [quarantine,setQuarantine]=useState(false);const [accessories,setAccessories]=useState(false);const [onOrder,setOnOrder]=useState(0);
 const params=useMemo(()=>new URLSearchParams({selected_days:String(days),target_dos:String(target),cogs_pct:String(cogs),safety_stock_pct:String(safety),growth_adj_pct:String(growth),include_dead:String(dead),include_quarantine:String(quarantine),include_accessories:String(accessories),on_order_cost:String(onOrder)}),[days,target,cogs,safety,growth,dead,quarantine,accessories,onOrder]);
 const data=useQuery({queryKey:["buying-budget-parity",params.toString()],queryFn:({signal})=>apiGet<Budget>(`/api/v1/buying-budget-parity?${params}`,signal)});
 return <div className="page"><div className="page-heading"><div><div className="eyebrow">Retail Ops · Streamlit parity</div><h1>Buying Budget</h1><p>The original Purchasing Budget model: sales-window demand, target DOS, COGS fallback, safety stock, growth adjustment, exclusions, on-order cost and three planning scenarios.</p></div></div><section className="inventory-panel parity-controls"><label>Planning sales window<select value={days} onChange={e=>setDays(Number(e.target.value))}>{[14,30,60,90].map(v=><option key={v}>{v} days</option>)}</select></label><Num label="Target DOS" value={target} onChange={setTarget}/><Num label="COGS % fallback" value={cogs} onChange={setCogs}/><Num label="Safety stock %" value={safety} onChange={setSafety}/><Num label="Growth adjustment %" value={growth} onChange={setGrowth} min={-100}/><Num label="On-order inventory cost" value={onOrder} onChange={setOnOrder}/><Toggle label="Include dead stock?" value={dead} onChange={setDead}/><Toggle label="Include quarantine inventory?" value={quarantine} onChange={setQuarantine}/><Toggle label="Include accessories?" value={accessories} onChange={setAccessories}/></section>{data.isError?<div className="state error">{data.error.message}</div>:null}{data.isLoading?<div className="state">Calculating purchasing budget…</div>:null}{data.data?<><section className="metrics"><Metric label="Recommended Purchasing Budget" value={money(data.data.summary.recommended_budget)}/><Metric label="Current Active Inventory at Cost" value={money(data.data.summary.active_inventory_cost)}/><Metric label="Target Inventory at Cost" value={money(data.data.summary.target_inventory_cost)}/><Metric label="Over/Under Position" value={data.data.summary.recommended_position<0?`Overbought by ${money(Math.abs(data.data.summary.recommended_position))}`:`Available to Buy: ${money(data.data.summary.recommended_position)}`}/><Metric label="Avg Daily COGS" value={money(data.data.summary.avg_daily_cogs)}/><Metric label="On Order Cost" value={money(data.data.summary.on_order_cost)}/></section><div className="two-column-grid"><section className="inventory-panel"><div className="section-heading"><div><div className="eyebrow">Category allocation</div><h2>Current vs Target Inventory</h2></div></div><Bars rows={data.data.categories}/><Table rows={data.data.categories} columns={["Category","Current Inventory at Cost","Target Inventory at Cost","Recommended Budget"]}/></section><section className="inventory-panel"><div className="section-heading"><div><div className="eyebrow">Scenario planning</div><h2>Budget Scenario Table</h2></div></div><Table rows={data.data.scenarios} columns={["Scenario","Target Inventory","Current Active Inventory","On Order","Recommended Budget","Status"]}/></section></div></>:null}</div>;
}
function Num({label,value,onChange,min=0}:{label:string;value:number;onChange:(v:number)=>void;min?:number}){return <label>{label}<input type="number" min={min} value={value} onChange={e=>onChange(Number(e.target.value))}/></label>}function Toggle({label,value,onChange}:{label:string;value:boolean;onChange:(v:boolean)=>void}){return <label className="toggle"><input type="checkbox" checked={value} onChange={e=>onChange(e.target.checked)}/>{label}</label>}function Metric({label,value}:{label:string;value:string|number}){return <article className="metric"><span>{label}</span><strong>{value}</strong></article>}function money(v:number){return v.toLocaleString(undefined,{style:"currency",currency:"USD",maximumFractionDigits:0})}function Bars({rows}:{rows:Row[]}){const max=Math.max(...rows.map(r=>Number(r["Target Inventory at Cost"]||0)),1);return <div className="bar-list">{rows.slice(0,14).map((r,i)=><div className="mix-bar" key={`${i}-${String(r.Category)}`}><span>{String(r.Category)}</span><div><i style={{width:`${Number(r["Current Inventory at Cost"]||0)/max*100}%`}}/></div><strong>{money(Number(r["Current Inventory at Cost"]||0))}</strong></div>)}</div>}function show(v:unknown){if(v==null||v==="")return"—";if(typeof v==="number")return money(v);return String(v)}function Table({rows,columns}:{rows:Row[];columns:string[]}){return <div className="table-wrap"><table><thead><tr>{columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{columns.map(c=><td key={c}>{show(r[c])}</td>)}</tr>)}</tbody></table>{rows.length===0?<div className="empty">No category rows available.</div>:null}</div>}
