import { useMutation, useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { apiGet, apiPost } from "../lib/api";

type Row=Record<string,unknown>;
type Intelligence={lookback_days:number;summary:{tracked_skus:number;total_units_sold:number;total_revenue:number;at_risk_skus:number};by_category:Row[];by_product:Row[];purchase_priorities:Row[]};
type Brief={answer:string;explanation?:string};

export function BuyingRecommendationsPage(){
  const [lookback,setLookback]=useState(60);
  const data=useQuery({queryKey:["buyer-intelligence",lookback],queryFn:({signal})=>apiGet<Intelligence>(`/api/v1/buyer-parity/intelligence?lookback_days=${lookback}`,signal)});
  const brief=useMutation({mutationFn:()=>apiPost<Brief>("/api/v1/buyer-parity/buyer-brief",{state:"MA",question:"Build the exact data-backed Buyer Brief for this store.",categories:[],target_doh:21,velocity_adjustment:1,sales_days:lookback})});
  return <div className="page exact-buyer-intelligence"><h1>🧠 Buyer Intelligence</h1><p>Demand, coverage, and ranked buyer actions grounded in the sales and inventory data loaded for this store.</p>
    <details className="streamlit-expander"><summary>🌐 Optional live market references</summary><div className="streamlit-expander-body"><p>Use these external sources as directional market context. Prioritize your store-level sales, margin, and inventory data for buy decisions.</p><p><a href="https://www.headset.io/brands" target="_blank" rel="noreferrer">Headset Brand Marketplace</a> — Live, frequently updated brand-level market visibility across U.S. cannabis markets.</p></div></details>
    <section className="inventory-panel parity-controls"><label>Buyer intelligence lookback (days)<input type="range" min="14" max="120" value={lookback} onChange={event=>setLookback(Number(event.target.value))}/><span>{lookback}</span></label></section>
    {data.isError?<div className="state error">{data.error.message}</div>:null}{data.isLoading?<div className="state">Building Buyer Intelligence from the active sales and inventory data…</div>:null}
    {data.data?<><section className="metrics four"><Metric label="Tracked SKUs" value={data.data.summary.tracked_skus.toLocaleString()}/><Metric label="Units Sold" value={data.data.summary.total_units_sold.toLocaleString()}/><Metric label="Revenue" value={money(data.data.summary.total_revenue)}/><Metric label="Reorder Risk SKUs" value={data.data.summary.at_risk_skus.toLocaleString()}/></section><div className="two-column-grid buyer-intelligence-evidence"><section className="inventory-panel"><h4>Top Categories</h4><Table rows={data.data.by_category} columns={["category","units_sold","revenue"]}/></section><section className="inventory-panel"><h4>SKU Risk Table</h4><Table rows={data.data.by_product} columns={["product_name","category","strain_type","package_size","units_sold","revenue","avg_daily_units","on_hand_units","days_of_cover","risk_flag"]}/></section></div><hr/><h3>What to Buy</h3><p>At-a-glance replenishment by package size, strain family, and product format. Recommended units target 28 days of cover using the selected sales window.</p>{data.data.purchase_priorities.length?<Table rows={data.data.purchase_priorities} columns={["Need","Recommended units","Current on hand","Days of cover","Units sold","SKUs","Reason"]}/>:<div className="success-banner">No assortment-level replenishment gaps were found in the loaded data.</div>}<hr/><h3>🤖 Data-Backed Buyer Brief</h3><p>Starts with exact store evidence, then uses Doobie only for a data-specific interpretation. Generic AI filler is discarded.</p><button className="primary" disabled={brief.isPending} onClick={()=>brief.mutate()}>{brief.isPending?"Analyzing the exact SKUs, coverage, and assortment gaps in this store...":"Generate Buyer Brief"}</button>{brief.isError?<div className="info-banner">{brief.error.message}</div>:null}{brief.data?<section className="inventory-panel answer-copy">{brief.data.answer.split("\n").map((line,index)=><p key={index}>{line||<>&nbsp;</>}</p>)}{brief.data.explanation?<p>{brief.data.explanation}</p>:null}</section>:null}</>:null}
  </div>;
}
function Metric({label,value}:{label:string;value:string}){return <article className="metric"><span>{label}</span><strong>{value}</strong></article>}
function money(value:number){return value.toLocaleString(undefined,{style:"currency",currency:"USD",maximumFractionDigits:0})}
function show(value:unknown,column:string){if(value==null||value==="")return "—";if(column==="revenue")return money(Number(value));if(typeof value==="number")return Number.isInteger(value)?value.toLocaleString():value.toLocaleString(undefined,{maximumFractionDigits:2});return String(value)}
function head(value:string){return value.replaceAll("_"," ").replace(/\b\w/g,char=>char.toUpperCase())}
function Table({rows,columns}:{rows:Row[];columns:string[]}){const visible=columns.filter(column=>rows.some(row=>row[column]!==undefined));return <div className="table-wrap"><table><thead><tr>{visible.map(column=><th key={column}>{head(column)}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={index}>{visible.map(column=><td key={column}>{show(row[column],column)}</td>)}</tr>)}</tbody></table></div>}
