import { useQuery } from "@tanstack/react-query";
import { apiGet } from "../lib/api";

type Row = Record<string, unknown>;
type Intelligence = { summary: { tracked_skus:number; total_units_sold:number; at_risk_skus:number; overstock_watch:number }; purchase_priorities:Row[]; sku_risk:Row[]; overstock_watch:Row[]; category_risk:Row[] };
export function BuyingRecommendationsPage({onNavigate}:{onNavigate:(page:string)=>void}){
  const data=useQuery({queryKey:["buyer-intelligence-standalone"],queryFn:({signal})=>apiGet<Intelligence>("/api/v1/buyer-parity/intelligence",signal)});
  return <div className="page"><div className="page-heading"><div><div className="eyebrow">Retail Ops · Buyer Intelligence</div><h1>Buying Recommendations</h1><p>The original evidence-first buyer brief remains separate from the inventory workspace. Exact assortment needs and SKU risks are calculated first; Doobie handles the interpretation/action layer.</p></div><button className="primary" onClick={()=>onNavigate("Doobie")}>Open Doobie Buyer Brief</button></div>{data.isError?<div className="state error">{data.error.message}</div>:null}{data.isLoading?<div className="state">Building buyer recommendations…</div>:null}{data.data?<><section className="metrics"><Metric label="Tracked SKUs" value={data.data.summary.tracked_skus}/><Metric label="Units Sold" value={data.data.summary.total_units_sold.toLocaleString()}/><Metric label="Reorder Risk" value={data.data.summary.at_risk_skus}/><Metric label="Overstock Watch" value={data.data.summary.overstock_watch}/></section><Panel title="Buy First"><Table rows={data.data.purchase_priorities} columns={["Need","Recommended units","Current on hand","Days of cover","Units sold","SKUs","Reason"]}/></Panel><div className="two-column-grid"><Panel title="SKU Stockout Risk"><Table rows={data.data.sku_risk} columns={["product_name","category","on_hand_units","units_sold","days_of_cover"]}/></Panel><Panel title="Overstock / Slow Watch"><Table rows={data.data.overstock_watch} columns={["product_name","category","on_hand_units","units_sold","days_of_cover"]}/></Panel></div><Panel title="Category Risk"><Table rows={data.data.category_risk} columns={["category","skus","units_sold","on_hand","at_risk","overstock"]}/></Panel></>:null}</div>;
}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="inventory-panel"><div className="section-heading"><div><div className="eyebrow">Buyer evidence</div><h2>{title}</h2></div></div>{children}</section>}function Metric({label,value}:{label:string;value:string|number}){return <article className="metric"><span>{label}</span><strong>{value}</strong></article>}function head(v:string){return v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase())}function show(v:unknown){if(v==null||v==="")return"—";if(typeof v==="number")return Number.isInteger(v)?v.toLocaleString():v.toLocaleString(undefined,{maximumFractionDigits:2});return String(v)}function Table({rows,columns}:{rows:Row[];columns:string[]}){const visible=columns.filter(c=>rows.some(r=>r[c]!==undefined));return <div className="table-wrap"><table><thead><tr>{visible.map(c=><th key={c}>{head(c)}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{visible.map(c=><td key={c}>{show(r[c])}</td>)}</tr>)}</tbody></table>{rows.length===0?<div className="empty">No supported risk rows in the current data.</div>:null}</div>}
