import { useMutation, useQuery } from "@tanstack/react-query";
import { apiGet, apiPost } from "../lib/api";

type Row = Record<string, unknown>;
type Intelligence = { summary: { tracked_skus:number; total_units_sold:number; at_risk_skus:number; overstock_watch:number }; purchase_priorities:Row[]; sku_risk:Row[]; overstock_watch:Row[]; category_risk:Row[] };
type Brief = { answer:string; explanation?:string; recommendations?:unknown[]; risk_flags?:unknown[]; inefficiencies?:unknown[]; confidence?:string; mode?:string };
export function BuyingRecommendationsPage({onNavigate}:{onNavigate:(page:string)=>void}){
  const data=useQuery({queryKey:["buyer-intelligence-standalone"],queryFn:({signal})=>apiGet<Intelligence>("/api/v1/buyer-parity/intelligence",signal)});
  const brief=useMutation({mutationFn:()=>apiPost<Brief>("/api/v1/buyer-parity/buyer-brief",{state:"MA",question:"What should I reorder right now with quantities, and which SKU or category risks should I address first?",categories:[],target_doh:21,velocity_adjustment:0.5,sales_days:60})});
  return <div className="page"><div className="page-heading"><div><div className="eyebrow">Retail Ops · Buyer Intelligence</div><h1>Buying Recommendations</h1><p>The original evidence-first buyer brief remains separate from the inventory workspace. Exact assortment needs and SKU risks are calculated first; Doobie interprets that same evidence without replacing it.</p></div><div className="heading-actions"><button className="secondary" onClick={()=>onNavigate("Doobie")}>Open Doobie Action Center</button><button className="primary" disabled={brief.isPending||!data.data} onClick={()=>brief.mutate()}>{brief.isPending?"Generating…":"Generate Doobie Buyer Brief"}</button></div></div>{data.isError?<div className="state error">{data.error.message}</div>:null}{data.isLoading?<div className="state">Building buyer recommendations…</div>:null}{brief.isError?<div className="state error">{brief.error.message}</div>:null}{brief.data?<section className="inventory-panel"><div className="section-heading"><div><div className="eyebrow">Doobie Buyer Brief</div><h2>Interpretation of the current Buyer evidence</h2></div><span className="access-badge">{brief.data.confidence||"low"} confidence</span></div><div className="success-banner"><div className="answer-copy">{brief.data.answer.split("\n").map((line,index)=><p key={index}>{line||<>&nbsp;</>}</p>)}</div>{brief.data.explanation?<p>{brief.data.explanation}</p>:null}</div><List title="Recommendations" values={brief.data.recommendations}/><List title="Risk flags" values={brief.data.risk_flags}/><List title="Inefficiencies" values={brief.data.inefficiencies}/></section>:null}{data.data?<><section className="metrics"><Metric label="Tracked SKUs" value={data.data.summary.tracked_skus}/><Metric label="Units Sold" value={data.data.summary.total_units_sold.toLocaleString()}/><Metric label="Reorder Risk" value={data.data.summary.at_risk_skus}/><Metric label="Overstock Watch" value={data.data.summary.overstock_watch}/></section><Panel title="Buy First"><Table rows={data.data.purchase_priorities} columns={["Need","Recommended units","Current on hand","Days of cover","Units sold","SKUs","Reason"]}/></Panel><div className="two-column-grid"><Panel title="SKU Stockout Risk"><Table rows={data.data.sku_risk} columns={["product_name","category","on_hand_units","units_sold","days_of_cover"]}/></Panel><Panel title="Overstock / Slow Watch"><Table rows={data.data.overstock_watch} columns={["product_name","category","on_hand_units","units_sold","days_of_cover"]}/></Panel></div><Panel title="Category Risk"><Table rows={data.data.category_risk} columns={["category","skus","units_sold","on_hand","at_risk","overstock"]}/></Panel></>:null}</div>;
}
function List({title,values=[]}:{title:string;values?:unknown[]}){if(!values.length)return null;return <><h3>{title}</h3><ul className="exception-list">{values.map((value,index)=><li key={index}>{typeof value==="string"?value:JSON.stringify(value)}</li>)}</ul></>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="inventory-panel"><div className="section-heading"><div><div className="eyebrow">Buyer evidence</div><h2>{title}</h2></div></div>{children}</section>}function Metric({label,value}:{label:string;value:string|number}){return <article className="metric"><span>{label}</span><strong>{value}</strong></article>}function head(v:string){return v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase())}function show(v:unknown){if(v==null||v==="")return"—";if(typeof v==="number")return Number.isInteger(v)?v.toLocaleString():v.toLocaleString(undefined,{maximumFractionDigits:2});return String(v)}function Table({rows,columns}:{rows:Row[];columns:string[]}){const visible=columns.filter(c=>rows.some(r=>r[c]!==undefined));return <div className="table-wrap"><table><thead><tr>{visible.map(c=><th key={c}>{head(c)}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{visible.map(c=><td key={c}>{show(r[c])}</td>)}</tr>)}</tbody></table>{rows.length===0?<div className="empty">No supported risk rows in the current data.</div>:null}</div>}
