import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { apiGet, apiPost } from "../lib/api";
type Tx = { id: string; provider: string; operation_type: string; entity_type: string; entity_id: string; status: string; error_message: string; attempt_count: number; requested_at: string };
type Queue = { summary: Record<string, number>; items: Tx[] };
type Detail = { transaction: Tx; events: { id: string; from_status: string; to_status: string; actor: string; reason: string; occurred_at: string }[]; attempts: { id: string; attempt_number: number; http_status: number | null; error_message: string; started_at: string }[] };
export function CompliancePage() {
  const client = useQueryClient(); const [selected, setSelected] = useState<string | null>(null); const [reason, setReason] = useState("");
  const queue = useQuery({ queryKey: ["traceability"], queryFn: ({ signal }) => apiGet<Queue>("/api/v1/compliance/traceability", signal) });
  const detail = useQuery({ queryKey: ["traceability", selected], enabled: !!selected, queryFn: ({ signal }) => apiGet<Detail>(`/api/v1/compliance/traceability/${selected}`, signal) });
  const resolve = useMutation({ mutationFn: (action: string) => apiPost(`/api/v1/compliance/traceability/${selected}/resolve`, { action, reason }), onSuccess: () => { setReason(""); client.invalidateQueries({ queryKey: ["traceability"] }); } });
  return <div className="page"><div className="page-heading"><div><div className="eyebrow">Compliance</div><h1>Traceability</h1><p>Provider-neutral submission, retry, exception and reconciliation evidence.</p></div></div><section className="metrics"><Metric label="Transactions" value={queue.data?.summary.total ?? "—"}/><Metric label="In flight" value={queue.data?.summary.in_flight ?? "—"}/><Metric label="Needs reconciliation" value={queue.data?.summary.needs_reconciliation ?? "—"}/><Metric label="Verified" value={queue.data?.summary.verified ?? "—"}/></section><section className="inventory-panel"><div className="table-wrap"><table><thead><tr><th>Provider</th><th>Operation</th><th>Entity</th><th>Status</th><th>Attempts</th><th>Error</th><th>Requested</th></tr></thead><tbody>{queue.data?.items.map(row => <tr key={row.id} onClick={() => setSelected(row.id)}><td>{row.provider.toUpperCase()}</td><td>{row.operation_type}</td><td>{row.entity_type}: {row.entity_id}</td><td>{row.status.replaceAll("_", " ")}</td><td>{row.attempt_count}</td><td>{row.error_message || "—"}</td><td>{new Date(row.requested_at).toLocaleString()}</td></tr>)}</tbody></table>{queue.data?.items.length === 0 ? <div className="empty">No traceability transactions in this facility.</div> : null}</div></section>{detail.data ? <div className="modal-backdrop"><div className="modal"><div className="modal-heading"><div><div className="eyebrow">Compliance 360</div><h2>{detail.data.transaction.entity_id}</h2><p>{detail.data.transaction.provider.toUpperCase()} · {detail.data.transaction.status}</p></div><button className="secondary" onClick={() => setSelected(null)}>Close</button></div><label className="resolution-reason">Manual resolution reason<input value={reason} onChange={event => setReason(event.target.value)} /></label><div className="audit-actions"><button className="secondary" disabled={!reason} onClick={() => resolve.mutate("requeue")}>Requeue</button><button className="secondary" disabled={!reason} onClick={() => resolve.mutate("cancel")}>Cancel</button><button className="primary" disabled={!reason} onClick={() => resolve.mutate("verify")}>Mark verified</button></div><h3>Status history</h3>{detail.data.events.map(row => <article className="plant-event" key={row.id}><strong>{row.from_status} → {row.to_status}</strong><span>{row.reason}</span><small>{row.actor} · {new Date(row.occurred_at).toLocaleString()}</small></article>)}<h3>Provider attempts</h3>{detail.data.attempts.map(row => <article className="plant-event" key={row.id}><strong>Attempt {row.attempt_number}</strong><span>HTTP {row.http_status ?? "—"}</span><small>{row.error_message || new Date(row.started_at).toLocaleString()}</small></article>)}</div></div> : null}</div>;
}
function Metric({ label, value }: { label: string; value: string | number }) { return <article className="metric"><span>{label}</span><strong>{value}</strong></article>; }
