import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { apiGet, apiPost, apiPostForm } from "../lib/api";
type Catalog = { label: string; dataset_key: string; description: string; types: string[] };
type History = { id: string; dataset_key: string; dataset_label: string; filename: string; payload_size: number; row_count: number; column_count: number; quality: string; status: string; imported_by: string; activated_at: string; missing_fields: string[] };
type DataHub = { catalog: Catalog[]; history: History[] };
export function DataSettingsPage() {
  const client = useQueryClient(); const [files, setFiles] = useState<Record<string, File | undefined>>({});
  const data = useQuery({ queryKey: ["data-hub"], queryFn: ({ signal }) => apiGet<DataHub>("/api/v1/data-hub/datasets", signal) });
  const upload = useMutation({ mutationFn: ({ key, file }: { key: string; file: File }) => { const body = new FormData(); body.set("dataset_key", key); body.set("file", file); return apiPostForm<History>("/api/v1/data-hub/datasets", body); }, onSuccess: () => client.invalidateQueries({ queryKey: ["data-hub"] }) });
  const archive = useMutation({ mutationFn: () => apiPost<{ archived: number }>("/api/v1/data-hub/archive", {}), onSuccess: () => client.invalidateQueries({ queryKey: ["data-hub"] }) });
  return <div className="page"><div className="page-heading"><div><div className="eyebrow">Data Operations</div><h1>Data & Settings</h1><p>Durable, versioned source files scoped to the active facility.</p></div><button className="secondary" onClick={() => archive.mutate()}>Archive active sources</button></div><div className="dataset-grid">{data.data?.catalog.map(spec => { const active = data.data.history.find(row => row.dataset_key === spec.dataset_key && row.status === "active"); return <article className="dataset-card" key={spec.dataset_key}><div><h3>{spec.label}</h3><p>{spec.description}</p></div>{active ? <div className="dataset-current"><strong>{active.filename}</strong><span>{active.row_count.toLocaleString()} rows · {active.column_count} columns · {active.quality}</span></div> : <div className="dataset-current">No active source</div>}<input type="file" accept={spec.types.map(type => `.${type}`).join(",")} onChange={event => setFiles({ ...files, [spec.dataset_key]: event.target.files?.[0] })} /><button className="primary" disabled={!files[spec.dataset_key] || upload.isPending} onClick={() => upload.mutate({ key: spec.dataset_key, file: files[spec.dataset_key]! })}>Inspect and publish</button></article>; })}</div>{upload.isError ? <div className="form-error">{upload.error.message}</div> : null}<h2>Import history</h2><section className="inventory-panel"><div className="table-wrap"><table><thead><tr><th>Dataset</th><th>File</th><th>Status</th><th>Quality</th><th>Rows</th><th>Missing mapping</th><th>Published</th></tr></thead><tbody>{data.data?.history.map(row => <tr key={row.id}><td>{row.dataset_label}</td><td>{row.filename}</td><td>{row.status}</td><td>{row.quality}</td><td>{row.row_count.toLocaleString()}</td><td>{row.missing_fields.join(", ") || "None"}</td><td>{new Date(row.activated_at).toLocaleString()}</td></tr>)}</tbody></table></div></section></div>;
}
