import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { apiGet, apiPost } from "../lib/api";
type Proposal = { id: string; action_type: string; title: string; rationale: string; payload: Record<string, unknown>; preview: Record<string, unknown>; financial_impact_usd: number; risk_level: string; status: string; created_by: string; approved_by: string; created_at: string };
type Actions = { allowed_actions: string[]; items: Proposal[] };
export function DoobiePage() {
  const client = useQueryClient(); const [selected, setSelected] = useState<Proposal | null>(null); const actions = useQuery({ queryKey: ["doobie-actions"], queryFn: ({ signal }) => apiGet<Actions>("/api/v1/doobie/actions", signal) });
  const decision = useMutation({ mutationFn: (action: string) => apiPost(`/api/v1/doobie/actions/${selected?.id}/${action}`, {}), onSuccess: () => { client.invalidateQueries({ queryKey: ["doobie-actions"] }); setSelected(null); } });
  return <div className="page"><div className="page-heading"><div><div className="eyebrow">Doobie</div><h1>Action Center</h1><p>Recommendations remain drafts until a permitted human previews, approves, and executes them.</p></div></div><section className="metrics"><Metric label="Proposed" value={actions.data?.items.filter(row => row.status === "proposed").length ?? "—"}/><Metric label="Approved" value={actions.data?.items.filter(row => row.status === "approved").length ?? "—"}/><Metric label="Failed" value={actions.data?.items.filter(row => row.status === "failed").length ?? "—"}/><Metric label="Executed" value={actions.data?.items.filter(row => row.status === "executed").length ?? "—"}/></section><section className="inventory-panel"><div className="table-wrap"><table><thead><tr><th>Recommendation</th><th>Action</th><th>Risk</th><th>Impact</th><th>Status</th><th>Created</th></tr></thead><tbody>{actions.data?.items.map(row => <tr key={row.id} onClick={() => setSelected(row)}><td>{row.title}</td><td>{row.action_type.replaceAll("_", " ")}</td><td>{row.risk_level}</td><td>${row.financial_impact_usd.toFixed(2)}</td><td>{row.status}</td><td>{new Date(row.created_at).toLocaleString()}</td></tr>)}</tbody></table>{actions.data?.items.length === 0 ? <div className="empty">No proposed actions. Doobie cannot execute operational changes without a preview and approval.</div> : null}</div></section>{selected ? <div className="modal-backdrop"><div className="modal"><div className="modal-heading"><div><div className="eyebrow">Action preview</div><h2>{selected.title}</h2><p>{selected.rationale}</p></div><button className="secondary" onClick={() => setSelected(null)}>Close</button></div><div className="preview-json"><h3>Preview</h3><pre>{JSON.stringify(selected.preview, null, 2)}</pre><h3>Execution payload</h3><pre>{JSON.stringify(selected.payload, null, 2)}</pre></div><div className="audit-actions">{selected.status !== "executed" ? <button className="secondary" onClick={() => decision.mutate("reject")}>Reject</button> : null}{["proposed", "failed"].includes(selected.status) ? <button className="primary" onClick={() => decision.mutate("approve")}>Approve preview</button> : null}{selected.status === "approved" ? <button className="primary" onClick={() => decision.mutate("execute")}>Execute approved action</button> : null}</div>{decision.isError ? <div className="form-error">{decision.error.message}</div> : null}</div></div> : null}</div>;
}
function Metric({ label, value }: { label: string; value: string | number }) { return <article className="metric"><span>{label}</span><strong>{value}</strong></article>; }
