import { useQuery } from "@tanstack/react-query";
import { apiGet } from "../lib/api";

type FacilityRow={facility:{id:string;name:string;code:string;license_number:string;license_type:string;capabilities:{retail:boolean;production:boolean;cultivation:boolean;commercial:boolean}};inventory:{positive_lots:number;value:number};orders:{sales:number;purchase:number;overdue:number};production:{open:number;units:number};traceability:Record<string,number>;compliance:{open_sop_deviations:number;critical_sop:number;high_sop:number;label_failures:number};finance:{ar:number};risk_score:number};
type Enterprise={organization_id:string;facility_count:number;summary:{inventory_value:number;open_sales_orders:number;open_purchase_orders:number;open_production_orders:number;reconciliation_actions:number;open_ar:number;facilities_at_risk:number};facilities:FacilityRow[]};
const money=new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0});
export function EnterpriseControlPage({onNavigate}:{onNavigate:(page:string)=>void}){
  const data=useQuery({queryKey:["enterprise-control-tower"],queryFn:({signal})=>apiGet<Enterprise>("/api/v1/enterprise/control-tower",signal)});
  return <div className="page enterprise-control"><div className="page-heading"><div><div className="eyebrow">ENTERPRISE · MULTI-FACILITY</div><h1>See the operation before it becomes a fire.</h1><p>Organization-wide inventory, orders, production, traceability, compliance, and A/R ranked by where operator attention matters most.</p></div><div className="heading-actions"><button className="secondary" onClick={()=>onNavigate("Operations Control Tower")}>Facility Control Tower</button></div></div>
    {data.isLoading?<div className="state">Rolling up organization facilities…</div>:null}{data.isError?<div className="warning-banner">{data.error.message}</div>:null}
    {data.data?<><section className="metrics four"><Metric label="Facilities" value={data.data.facility_count} note={`${data.data.summary.facilities_at_risk} with active exceptions`}/><Metric label="Inventory value" value={money.format(data.data.summary.inventory_value)} note="positive on-hand at standard unit cost"/><Metric label="Open A/R" value={money.format(data.data.summary.open_ar)} note="all facilities"/><Metric label="Reconciliation" value={data.data.summary.reconciliation_actions} note="state actions needing attention"/></section>
      <section className="metrics four"><Metric label="Sales orders" value={data.data.summary.open_sales_orders} note="open wholesale demand"/><Metric label="Purchase orders" value={data.data.summary.open_purchase_orders} note="open inbound supply"/><Metric label="Production jobs" value={data.data.summary.open_production_orders} note="not complete/cancelled"/><Metric label="Priority" value={data.data.facilities[0]?.facility.name??"Clear"} note={data.data.facilities[0]?`risk score ${data.data.facilities[0].risk_score}`:"no active facilities"}/></section>
      <section className="inventory-panel"><div className="eyebrow">FACILITY PRIORITY STACK</div><h2>Ranked by operational risk</h2>{!data.data.facilities.length?<div className="info-banner">No active facilities are configured in this organization.</div>:<div className="table-wrap"><table><thead><tr><th>Facility</th><th>License</th><th>Risk</th><th>Inventory</th><th>Orders</th><th>Production</th><th>Traceability</th><th>SOP / Labels</th><th>A/R</th></tr></thead><tbody>{data.data.facilities.map(row=><tr key={row.facility.id}><td><strong>{row.facility.name}</strong><br/><small>{capabilities(row)}</small></td><td>{row.facility.license_type||"—"}<br/><small>{row.facility.license_number||row.facility.code}</small></td><td><span className="status-pill">{row.risk_score}</span></td><td>{money.format(row.inventory.value)}<br/><small>{row.inventory.positive_lots} positive lots</small></td><td>{row.orders.sales} sales · {row.orders.purchase} PO<br/><small>{row.orders.overdue} overdue</small></td><td>{row.production.open}<br/><small>{row.production.units.toLocaleString()} units planned</small></td><td>{row.traceability.needs_reconciliation??0}<br/><small>{row.traceability.in_flight??0} in flight</small></td><td>{row.compliance.open_sop_deviations} deviations<br/><small>{row.compliance.label_failures} label failures</small></td><td>{money.format(row.finance.ar)}</td></tr>)}</tbody></table></div>}</section>
    </>:null}
  </div>;
}
function Metric({label,value,note}:{label:string;value:string|number;note:string}){return <article className="metric"><span>{label}</span><strong>{value}</strong><small>{note}</small></article>}
function capabilities(row:FacilityRow){return Object.entries(row.facility.capabilities).filter(([,enabled])=>enabled).map(([name])=>name).join(" · ")||"No operating capability"}
