import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { apiGet, apiPost } from "../lib/api";
type Workflow = { key: string; label: string; method: string; stages: { key: string; label: string }[] }; type Run = { id: string; batch_number: string; method: string; workflow_key: string; current_stage_key: string; status: string; release_status: string; strain: string; operator: string; updated_at: string }; type Detail = { run: Run; inputs: { id: string; lot_id: string; reserved_quantity: number; consumed_quantity: number; unit: string; status: string }[]; outputs: { id: string; output_label: string; quantity: number; unit: string; status: string; coa_status: string; output_cost_usd: number }[]; events: { id: string; stage_key: string; event_type: string; loss_weight_g: number | null; occurred_at: string }[]; qa_events: { id: string; event_type: string; result: string; occurred_at: string }[]; mass_balance: Record<string, number>; cogs: Record<string, number> };
export function ExtractionPage() {
  const client = useQueryClient(); const [selected, setSelected] = useState<string | null>(null); const [creating, setCreating] = useState(false); const runs = useQuery({ queryKey: ["extraction-runs"], queryFn: ({ signal }) => apiGet<Run[]>("/api/v1/extraction/runs", signal) }); const detail = useQuery({ queryKey: ["extraction-run", selected], enabled: !!selected, queryFn: ({ signal }) => apiGet<Detail>(`/api/v1/extraction/runs/${selected}`, signal) }); const refresh = () => { client.invalidateQueries({ queryKey: ["extraction-runs"] }); client.invalidateQueries({ queryKey: ["extraction-run", selected] }); };
  return <div className="page"><div className="page-heading"><div><div className="eyebrow">Production Ops</div><h1>Extraction</h1><p>Material reservations, stage history, mass balance, QA release and true COGS.</p></div><button className="primary" onClick={() => setCreating(true)}>New extraction run</button></div><section className="inventory-panel production-panel"><div className="table-wrap"><table><thead><tr><th>Batch</th><th>Method</th><th>Stage</th><th>Status</th><th>Release</th><th>Strain</th><th>Operator</th><th>Updated</th></tr></thead><tbody>{runs.data?.map(row => <tr key={row.id} onClick={() => setSelected(row.id)}><td>{row.batch_number}</td><td>{row.method}</td><td>{row.current_stage_key}</td><td>{row.status}</td><td>{row.release_status}</td><td>{row.strain || "—"}</td><td>{row.operator || "—"}</td><td>{new Date(row.updated_at).toLocaleString()}</td></tr>)}</tbody></table>{runs.data?.length === 0 ? <div className="empty">No extraction runs in this facility.</div> : null}</div></section>{creating ? <CreateRun onClose={() => setCreating(false)} onSaved={() => { setCreating(false); refresh(); }}/> : null}{detail.data ? <RunDetail detail={detail.data} onClose={() => setSelected(null)} onSaved={refresh}/> : null}</div>;
}
function CreateRun({ onClose, onSaved }: { onClose: () => void; onSaved: () => void }) {
  const workflows = useQuery({ queryKey: ["extraction-workflows"], queryFn: ({ signal }) => apiGet<Workflow[]>("/api/v1/extraction/workflows", signal) }); const [batch, setBatch] = useState(""); const [key, setKey] = useState(""); const selected = workflows.data?.find(row => row.key === key); const save = useMutation({ mutationFn: () => apiPost("/api/v1/extraction/runs", { batch_number: batch, workflow_key: key, method: selected?.method, operator: "Web operator" }), onSuccess: onSaved });
  return <div className="modal-backdrop"><div className="modal compact"><div className="modal-heading"><div><div className="eyebrow">Extraction</div><h2>New run</h2></div><button className="secondary" onClick={onClose}>Close</button></div><div className="form-grid"><label>Batch number<input value={batch} onChange={event => setBatch(event.target.value)}/></label><label>Workflow<select value={key} onChange={event => setKey(event.target.value)}><option value="">Select…</option>{workflows.data?.map(row => <option value={row.key} key={row.key}>{row.label}</option>)}</select></label></div><button className="primary submit" disabled={!batch || !selected} onClick={() => save.mutate()}>Create run</button>{save.isError ? <div className="form-error">{save.error.message}</div> : null}</div></div>;
}
function RunDetail({ detail, onClose, onSaved }: { detail: Detail; onClose: () => void; onSaved: () => void }) {
  const [loss, setLoss] = useState(0); const mutate = useMutation({ mutationFn: (value: { path: string; body: object }) => apiPost(value.path, value.body), onSuccess: onSaved }); const balance = detail.mass_balance;
  return <div className="modal-backdrop"><div className="modal wide"><div className="modal-heading"><div><div className="eyebrow">Extraction Run 360</div><h2>{detail.run.batch_number}</h2><p>{detail.run.method} · {detail.run.current_stage_key} · {detail.run.status}</p></div><button className="secondary" onClick={onClose}>Close</button></div><div className="quantity-summary"><span>Consumed<strong>{(balance.consumed_input ?? 0).toFixed(3)} g</strong></span><span>Outputs<strong>{(balance.output_quantity ?? 0).toFixed(3)} g</strong></span><span>Yield<strong>{(balance.yield_pct ?? 0).toFixed(1)}%</strong></span></div><div className="inline-form"><input type="number" min="0" step="0.001" value={loss} onChange={event => setLoss(Number(event.target.value))}/><button className="secondary" onClick={() => mutate.mutate({ path: `/api/v1/extraction/runs/${detail.run.id}/events`, body: { stage_key: detail.run.current_stage_key, event_type: "measurement", loss_weight_g: loss, loss_reason: "Process loss" } })}>Record loss</button><button className="primary" onClick={() => mutate.mutate({ path: `/api/v1/extraction/runs/${detail.run.id}/events`, body: { stage_key: detail.run.current_stage_key, event_type: "completed" } })}>Complete stage</button></div><h3>Reserved inputs</h3>{detail.inputs.map(row => <article className="plant-event" key={row.id}><strong>{row.lot_id}</strong><span>{row.consumed_quantity} / {row.reserved_quantity} {row.unit}</span><small>{row.status}</small></article>)}<h3>Outputs & QA</h3>{detail.outputs.map(row => <article className="plant-event" key={row.id}><strong>{row.output_label}</strong><span>{row.quantity} {row.unit} · ${row.output_cost_usd.toFixed(2)}</span><small>{row.status} · COA {row.coa_status}</small></article>)}<h3>COGS</h3><article className="plant-event"><strong>Total</strong><span>${(detail.cogs.total ?? 0).toFixed(2)}</span><small>${(detail.cogs.cost_per_output_unit ?? 0).toFixed(2)} / output unit</small></article><h3>Process history</h3>{detail.events.map(row => <article className="plant-event" key={row.id}><strong>{row.stage_key}</strong><span>{row.event_type}{row.loss_weight_g != null ? ` · loss ${row.loss_weight_g}g` : ""}</span><small>{new Date(row.occurred_at).toLocaleString()}</small></article>)}{mutate.isError ? <div className="form-error">{mutate.error.message}</div> : null}</div></div>;
}
