import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { apiGet, apiPost } from "../lib/api";
type QueueRow = { order_id: string; Order: string; Product: string; Status: string; Planned: number; Actual: number; "Attainment %": number; COGS: number; QA: string; Attention: string };
type Detail = { order: { id: string; order_number: string; product_name: string; status: string; requested_units: number }; requirements: { product_name: string; quantity: number; unit: string }[]; outputs: { id: string; label: string; planned_quantity: number; actual_quantity: number; unit: string; status: string; lot_id: string | null }[]; events: { id: string; event_type: string; occurred_at: string; notes: string }[]; qa_events: { id: string; event_type: string; result: string; notes: string; occurred_at: string }[]; cogs: Record<string, number>; attainment_pct: number };
export function ProductionPage() {
  const client = useQueryClient(); const [selected, setSelected] = useState<string | null>(null); const queue = useQuery({ queryKey: ["production-orders"], queryFn: ({ signal }) => apiGet<QueueRow[]>("/api/v1/production/orders", signal) }); const detail = useQuery({ queryKey: ["production-order", selected], enabled: !!selected, queryFn: ({ signal }) => apiGet<Detail>(`/api/v1/production/orders/${selected}`, signal) }); const refresh = () => { client.invalidateQueries({ queryKey: ["production-orders"] }); client.invalidateQueries({ queryKey: ["production-order", selected] }); }; const action = useMutation({ mutationFn: (event_type: string) => apiPost(`/api/v1/production/orders/${selected}/events`, { event_type }), onSuccess: refresh });
  return <div className="page"><div className="page-heading"><div><div className="eyebrow">Production Ops</div><h1>Production</h1><p>Durable production queue, execution, material readiness, QA and cost visibility.</p></div></div><section className="inventory-panel production-panel"><div className="table-wrap"><table><thead><tr><th>Order</th><th>Product</th><th>Status</th><th>Planned</th><th>Actual</th><th>Attainment</th><th>COGS</th><th>QA</th><th>Attention</th></tr></thead><tbody>{queue.data?.map(row => <tr key={row.order_id} onClick={() => setSelected(row.order_id)}><td>{row.Order}</td><td>{row.Product}</td><td>{row.Status}</td><td>{row.Planned}</td><td>{row.Actual}</td><td>{row["Attainment %"].toFixed(1)}%</td><td>${row.COGS.toFixed(2)}</td><td>{row.QA}</td><td>{row.Attention}</td></tr>)}</tbody></table></div></section>{detail.data ? <div className="modal-backdrop"><div className="modal wide"><div className="modal-heading"><div><div className="eyebrow">Production Order 360</div><h2>{detail.data.order.order_number}</h2><p>{detail.data.order.product_name} · {detail.data.order.status}</p></div><button className="secondary" onClick={() => setSelected(null)}>Close</button></div><div className="quantity-summary"><span>Requested<strong>{detail.data.order.requested_units}</strong></span><span>Attainment<strong>{detail.data.attainment_pct.toFixed(1)}%</strong></span><span>Total COGS<strong>${(detail.data.cogs.total ?? 0).toFixed(2)}</strong></span></div><div className="audit-actions"><button className="secondary" onClick={() => action.mutate("hold")}>Place hold</button><button className="secondary" onClick={() => action.mutate("started")}>Start</button><button className="primary" onClick={() => action.mutate("completed")}>Complete</button></div><ProductionControls orderId={detail.data.order.id} outputs={detail.data.outputs} onSaved={refresh}/><h3>Material requirements</h3>{detail.data.requirements.map(row => <article className="plant-event" key={row.product_name}><strong>{row.product_name}</strong><span>{row.quantity.toLocaleString()} {row.unit}</span></article>)}<h3>QA history</h3>{detail.data.qa_events.map(event => <article className="plant-event" key={event.id}><strong>{event.event_type}</strong><span>{event.result}</span><small>{event.notes}</small></article>)}<h3>Execution history</h3>{detail.data.events.map(event => <article className="plant-event" key={event.id}><strong>{event.event_type}</strong><span>{event.notes || "—"}</span><small>{new Date(event.occurred_at).toLocaleString()}</small></article>)}</div></div> : null}</div>;
}
function ProductionControls({ orderId, outputs, onSaved }: { orderId: string; outputs: Detail["outputs"]; onSaved: () => void }) {
  const [cost, setCost] = useState(0); const [category, setCategory] = useState("material"); const mutation = useMutation({ mutationFn: (body: { path: string; data: object }) => apiPost(body.path, body.data), onSuccess: onSaved });
  return <section className="production-controls"><h3>Outputs, QA & true COGS</h3>{outputs.map(row => <article className="plant-event" key={row.id}><strong>{row.label}</strong><span>{row.actual_quantity} / {row.planned_quantity} {row.unit}</span><small>{row.status}{row.lot_id ? ` · lot ${row.lot_id}` : ""}</small></article>)}<div className="inline-form"><select value={category} onChange={event => setCategory(event.target.value)}>{["material","labor","packaging","machine","overhead","waste","other"].map(value => <option key={value}>{value}</option>)}</select><input aria-label="Cost amount" type="number" min="0" step="0.01" value={cost} onChange={event => setCost(Number(event.target.value))}/><button className="secondary" disabled={cost <= 0} onClick={() => mutation.mutate({ path: `/api/v1/production/orders/${orderId}/costs`, data: { category, amount_usd: cost } })}>Add cost</button><button className="secondary" onClick={() => mutation.mutate({ path: `/api/v1/production/orders/${orderId}/qa`, data: { event_type: "hold", result: "pending", notes: "Placed on QA hold from Order 360" } })}>QA hold</button><button className="primary" onClick={() => mutation.mutate({ path: `/api/v1/production/orders/${orderId}/qa`, data: { event_type: "release", result: "passed", notes: "QA release approved" } })}>QA release</button></div>{mutation.isError ? <div className="form-error">{mutation.error.message}</div> : null}</section>;
}
