import { useMutation, useQuery } from "@tanstack/react-query";
import { useEffect, useMemo, useState } from "react";
import { apiDownload, apiGet, apiPost, downloadBlob } from "../lib/api";

type Row = Record<string, unknown>;
type Workspace = { reorder_asap: Row[]; smart_priorities: Row[] };
type POLine = { sku:string; description:string; strain:string; size:string; quantity:number; price:number; total?:number };
type Review = { on_hand:number; review:boolean; review_reason:string };
type BuyerControls = { target_doh:number; velocity_adjustment:number; sales_days:number; sku_window:number };

const EMPTY_LINE: POLine = {sku:"",description:"",strain:"",size:"",quantity:1,price:0};
const PAYMENT_TERMS = ["Due on receipt","Prepaid","Net 7","Net 15","Net 30","Other"];
const SHIPPING_METHODS = ["Vendor delivery","Customer pickup","Common carrier","Other"];

export function PurchaseOrdersParityPage({onNavigate}:{onNavigate:(page:string)=>void}) {
  const controls = readBuyerControls();
  const [items,setItems] = useState<POLine[]>(readPoItems);
  const [draft,setDraft] = useState<POLine>(EMPTY_LINE);
  const [addedMessage,setAddedMessage] = useState("");
  const [store,setStore] = useState({name:"Cannabis Store",address:"123 Main St\nCity, State 12345",contact:"",phone:"",email:"",number:""});
  const [vendor,setVendor] = useState({name:"",address:"",contact:"",license:""});
  const [po,setPo] = useState({number:`PO-${today().replaceAll("-","")}`,date:today(),requestedDelivery:addDays(7),shippingMethod:SHIPPING_METHODS[0],terms:PAYMENT_TERMS[0],deliveryInstructions:"",notes:""});
  const [taxRate,setTaxRate] = useState(0); const [discount,setDiscount] = useState(0); const [shipping,setShipping] = useState(0);
  const [generatedPdf,setGeneratedPdf] = useState<Blob|null>(null);
  const params = useMemo(()=>new URLSearchParams({target_doh:String(controls.target_doh),velocity_adjustment:String(controls.velocity_adjustment),sales_days:String(controls.sales_days),sku_window:String(controls.sku_window)}),[controls.target_doh,controls.velocity_adjustment,controls.sales_days,controls.sku_window]);
  const data = useQuery({queryKey:["po-parity",params.toString()],queryFn:({signal})=>apiGet<Workspace>(`/api/v1/po-parity/workspace?${params}`,signal)});
  const itemKey = JSON.stringify(items);
  const review = useQuery({queryKey:["po-parity-review",params.toString(),itemKey],queryFn:()=>apiPost<Review[]>(`/api/v1/po-parity/review?${params}`,{items}),enabled:items.length>0});
  const subtotal = items.reduce((sum,item)=>sum+(item.total??item.quantity*item.price),0); const tax=subtotal*taxRate/100; const total=subtotal+tax-discount+shipping;
  useEffect(()=>{sessionStorage.setItem("buyer-dash-po-items",JSON.stringify(items));sessionStorage.setItem("buyer-dash-proposed-po-total",String(total))},[items,total]);
  useEffect(()=>setGeneratedPdf(null),[itemKey,store,vendor,po,taxRate,discount,shipping]);

  const reorderRows = useMemo<Row[]>(()=>(data.data?.reorder_asap??[]).map(row=>({...row,"Current Price":Number(row.unit_cost||0)>0?Number(row.unit_cost)/2:undefined})),[data.data]);
  const hasPrice = reorderRows.some(row=>Number(row["Current Price"]||0)>0);
  const addAllReorder = () => {const additions=reorderRows.map(row=>{const description=String(row.top_products||row.product_name||`${row.subcategory||""} ${row.strain_type||""} ${row.packagesize||""}`).split(",")[0].trim();return {sku:"",description,strain:String(row.strain_type||""),size:String(row.packagesize||""),quantity:Math.max(1,Number(row.reorderqty||1)),price:Number(row.unit_cost||0)>0?Number(row.unit_cost)/2:0,total:0}});setItems(current=>[...current,...additions]);setAddedMessage(`Added ${additions.length} item(s) to the PO. Fill in prices below.`)};
  const addSmart = () => {const additions=(data.data?.smart_priorities??[]).slice(0,25).map(row=>{const quantity=Number(row["Recommended units"]||row.recommended_units||row.recommended_quantity||0);const price=Number(row.unit_cost||0);return {sku:String(row.sku||""),description:String(row["Need"]||row.product_name||row.need||"").trim(),strain:String(row.strain_type||""),size:String(row.package_size||row.packagesize||""),quantity,price,total:quantity*price}}).filter(row=>row.description&&row.quantity>0);setItems(current=>[...current,...additions])};
  const pdfPayload = {store_name:store.name,store_address:store.address,store_phone:store.phone,store_contact:store.contact,store_number:store.number,vendor_name:vendor.name,vendor_license:vendor.license,vendor_address:vendor.address,vendor_contact:vendor.contact,po_number:po.number,po_date:po.date,terms:po.terms,fulfillment_notes:fulfillmentNotes(store.email,po),tax_rate:taxRate,discount,shipping,items};
  const generatePdf = useMutation({mutationFn:()=>apiDownload("/api/v1/po-parity/pdf",pdfPayload),onSuccess:setGeneratedPdf});
  const pdfName = `PO_${po.number}_${today().replaceAll("-","")}.pdf`;

  return <div className="page exact-po-builder">
    <h1>Purchase Order Builder</h1><p>Create professional purchase orders with automatic calculations and PDF export.</p>
    {data.isError?<div className="info-banner">💡 Go to <strong>📊 Inventory Dashboard</strong> and upload your files first — Reorder ASAP items will then appear here for quick PO creation.</div>:null}
    {data.data?<details className="streamlit-expander" open><summary>📊 Reorder Cross-Reference (from Inventory Dashboard)</summary><div className="streamlit-expander-body">{!reorderRows.length?<div className="success-banner">✅ No items flagged 'Reorder ASAP' in the current dashboard view.</div>:<><p><strong>{reorderRows.length} line(s)</strong> flagged as <em>Reorder ASAP</em> from your last Inventory Dashboard load. Use the button below to bulk-add them to the PO, or review individual rows first.{hasPrice?<> 💲 <strong>Current Price</strong> = inventory 'Current price' ÷ 2 (wholesale adjustment).</>:null}</p><Table rows={reorderRows} columns={["subcategory","strain_type","packagesize","onhandunits","avgunitsperday","daysonhand","reorderqty",...(hasPrice?["Current Price"]:[]),"top_products"]}/><button className="primary" onClick={addAllReorder}>➕ Add All Reorder ASAP Lines to PO</button>{addedMessage?<div className="success-banner">{addedMessage}</div>:null}</>}</div></details>:null}
    <hr/>
    <section className="inventory-panel"><h3>📋 Order Information</h3><div className="form-grid three"><div className="form-column"><Text label="Store Name" value={store.name} onChange={name=>setStore({...store,name})}/><Area label="Store Address" value={store.address} onChange={address=>setStore({...store,address})}/></div><div className="form-column"><Text label="Vendor Name" value={vendor.name} onChange={name=>setVendor({...vendor,name})}/><Area label="Vendor Address" value={vendor.address} onChange={address=>setVendor({...vendor,address})}/></div><div className="form-column"><Text label="PO Number" value={po.number} onChange={number=>setPo({...po,number})}/><DateField label="PO Date" value={po.date} onChange={date=>setPo({...po,date})}/></div></div><div className="form-grid three"><div className="form-column"><Text label="Buyer / Contact Name" value={store.contact} onChange={contact=>setStore({...store,contact})}/><Text label="Buyer Phone" value={store.phone} onChange={phone=>setStore({...store,phone})}/><Text label="Buyer Email" value={store.email} onChange={email=>setStore({...store,email})}/><Text label="Store / Location Number" value={store.number} onChange={number=>setStore({...store,number})}/></div><div className="form-column"><Text label="Vendor Contact" value={vendor.contact} onChange={contact=>setVendor({...vendor,contact})}/><Text label="Vendor License Number" value={vendor.license} onChange={license=>setVendor({...vendor,license})}/><DateField label="Requested Delivery Date" value={po.requestedDelivery} onChange={requestedDelivery=>setPo({...po,requestedDelivery})}/><SelectField label="Shipping Method" value={po.shippingMethod} options={SHIPPING_METHODS} onChange={shippingMethod=>setPo({...po,shippingMethod})}/></div><div className="form-column"><SelectField label="Payment Terms" value={po.terms} options={PAYMENT_TERMS} onChange={terms=>setPo({...po,terms})}/><Area label="Delivery Instructions" value={po.deliveryInstructions} placeholder="Receiving window, entrance, or appointment details." onChange={deliveryInstructions=>setPo({...po,deliveryInstructions})}/><Area label="PO Notes" value={po.notes} placeholder="Quality, substitution, or packaging instructions." onChange={notes=>setPo({...po,notes})}/></div></div></section>
    <section className="inventory-panel"><h3>📦 Line Items</h3><div className="form-grid po-line-form"><Text label="SKU" value={draft.sku} onChange={sku=>setDraft({...draft,sku})}/><Text label="Description" value={draft.description} onChange={description=>setDraft({...draft,description})}/><Text label="Strain" value={draft.strain} onChange={strain=>setDraft({...draft,strain})}/><Text label="Size" value={draft.size} onChange={size=>setDraft({...draft,size})}/><Num label="Qty" value={draft.quantity} min={1} onChange={quantity=>setDraft({...draft,quantity})}/><Num label="Price" value={draft.price} min={0} step={.01} onChange={price=>setDraft({...draft,price})}/></div><button className="primary" disabled={!draft.description.trim()} onClick={()=>{const quantity=Math.max(1,draft.quantity);const price=Math.max(0,draft.price);setItems(current=>[...current,{...draft,quantity,price,total:quantity*price}]);setDraft(EMPTY_LINE)}}>➕ Add Item</button></section>
    {items.length?<><section className="inventory-panel"><h4>Current Items</h4>{review.data?.some(row=>row.review)?<div className="warning-banner">⚠️ One or more PO line items already have &gt;=15 units on hand. Review flagged items before purchasing.</div>:null}<div className="table-wrap"><table><thead><tr>{["SKU","Description","Strain","Size","Quantity","Price","Total","On Hand (Inv)","Review?","Review Reason"].map(value=><th key={value}>{value}</th>)}</tr></thead><tbody>{items.map((item,index)=><tr key={`${index}-${item.description}`}><td>{item.sku}</td><td>{item.description}</td><td>{item.strain}</td><td>{item.size}</td><td>{item.quantity}</td><td>{money(item.price)}</td><td>{money(item.total??item.quantity*item.price)}</td><td>{review.data?.[index]?.on_hand??0}</td><td>{review.data?.[index]?.review?"true":"false"}</td><td>{review.data?.[index]?.review_reason??""}</td></tr>)}</tbody></table></div></section><section className="inventory-panel"><h3>💰 Totals</h3><div className="form-grid three"><Num label="Tax Rate (%)" value={taxRate} min={0} max={100} step={.1} onChange={setTaxRate}/><Num label="Discount ($)" value={discount} min={0} step={1} onChange={setDiscount}/><Num label="Shipping ($)" value={shipping} min={0} step={1} onChange={setShipping}/></div><div className="po-total-stack"><span>Subtotal: <strong>{money(subtotal)}</strong></span>{taxRate>0?<span>Tax ({taxRate}%): <strong>{money(tax)}</strong></span>:null}{discount>0?<span>Discount: <strong>-{money(discount)}</strong></span>:null}{shipping>0?<span>Shipping: <strong>{money(shipping)}</strong></span>:null}<span className="grand-total">Total: <strong>{money(total)}</strong></span></div><div className="heading-actions"><button className="secondary" onClick={()=>{setItems([]);setAddedMessage("");setGeneratedPdf(null)}}>🗑️ Clear All Items</button><button className="primary" disabled={generatePdf.isPending} onClick={()=>generatePdf.mutate()}>📄 Generate PDF</button>{generatedPdf?<button className="primary" onClick={()=>downloadBlob(generatedPdf,pdfName)}>📥 Download PDF</button>:null}</div>{generatePdf.isError?<div className="form-error">{generatePdf.error.message}</div>:null}</section></>:<div className="info-banner">👆 Add items to your purchase order using the form above</div>}
    <details className="streamlit-expander"><summary>Smart PO (additive)</summary><div className="streamlit-expander-body"><p>Smart PO adds deterministic Buyer Dash priorities without replacing the original purchase-order workflow above.</p><Table rows={data.data?.smart_priorities??[]} columns={["Need","Recommended units","Current on hand","Days of cover","Units sold","SKUs","Reason"]}/><div className="heading-actions"><button className="secondary" disabled={!data.data?.smart_priorities.length} onClick={addSmart}>Add Smart Recommendations</button><button className="secondary" onClick={()=>onNavigate("Doobie")}>Open Doobie</button></div></div></details>
  </div>;
}

function readBuyerControls():BuyerControls{try{return {...{target_doh:21,velocity_adjustment:.5,sales_days:60,sku_window:56},...JSON.parse(sessionStorage.getItem("buyer-dash-buyer-controls")||"{}")}}catch{return {target_doh:21,velocity_adjustment:.5,sales_days:60,sku_window:56}}}
function readPoItems():POLine[]{try{const value=JSON.parse(sessionStorage.getItem("buyer-dash-po-items")||"[]");return Array.isArray(value)?value:[]}catch{return []}}
function formatLocalDate(value:Date){const year=value.getFullYear();const month=String(value.getMonth()+1).padStart(2,"0");const day=String(value.getDate()).padStart(2,"0");return `${year}-${month}-${day}`}
function today(){return formatLocalDate(new Date())}
function addDays(days:number){const value=new Date();value.setDate(value.getDate()+days);return formatLocalDate(value)}
function fulfillmentNotes(email:string,po:{requestedDelivery:string;shippingMethod:string;deliveryInstructions:string;notes:string}){const date=new Date(`${po.requestedDelivery}T00:00:00`).toLocaleDateString("en-US",{month:"2-digit",day:"2-digit",year:"numeric"});return [email?`Buyer email: ${email}`:"",`Requested delivery: ${date}`,`Shipping method: ${po.shippingMethod}`,po.deliveryInstructions?`Delivery instructions: ${po.deliveryInstructions}`:"",po.notes].filter(Boolean).join("\n")}
function Text({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}){return <label>{label}<input value={value} onChange={event=>onChange(event.target.value)}/></label>}
function Area({label,value,placeholder,onChange}:{label:string;value:string;placeholder?:string;onChange:(value:string)=>void}){return <label>{label}<textarea value={value} placeholder={placeholder} onChange={event=>onChange(event.target.value)}/></label>}
function DateField({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}){return <label>{label}<input type="date" value={value} onChange={event=>onChange(event.target.value)}/></label>}
function SelectField({label,value,options,onChange}:{label:string;value:string;options:string[];onChange:(value:string)=>void}){return <label>{label}<select value={value} onChange={event=>onChange(event.target.value)}>{options.map(option=><option key={option}>{option}</option>)}</select></label>}
function Num({label,value,onChange,min=0,max,step=1}:{label:string;value:number;onChange:(value:number)=>void;min?:number;max?:number;step?:number}){return <label>{label}<input type="number" min={min} max={max} step={step} value={value} onChange={event=>onChange(Number(event.target.value))}/></label>}
function money(value:number){return value.toLocaleString(undefined,{style:"currency",currency:"USD",minimumFractionDigits:2,maximumFractionDigits:2})}
function show(value:unknown,column:string){if(value==null||value==="")return "—";if(column==="Current Price")return money(Number(value));if(typeof value==="number")return Number.isInteger(value)?value.toLocaleString():value.toLocaleString(undefined,{maximumFractionDigits:2});return String(value)}
function Table({rows,columns}:{rows:Row[];columns:string[]}){const visible=columns.filter(column=>rows.some(row=>row[column]!==undefined));return <div className="table-wrap"><table><thead><tr>{visible.map(column=><th key={column}>{column.replaceAll("_"," ")}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={index}>{visible.map(column=><td key={column}>{show(row[column],column)}</td>)}</tr>)}</tbody></table>{rows.length===0?<div className="empty">No rows available.</div>:null}</div>}
