import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { apiGet } from "../lib/api";
type Trend = { window_days: number; summary: { net_sales: number; units: number; average_daily_sales: number; mapped_sales_pct: number }; daily: { date: string; quantity: number; net_sales: number }[]; categories: { category: string; quantity: number; net_sales: number }[]; products: { product_id: string | null; sku: string; product_name: string; category: string; quantity: number; net_sales: number }[] };
type Slow = { summary: { product_count: number; units_at_risk: number; cost_at_risk: number; zero_velocity_count: number }; items: { product_id: string; sku: string; product_name: string; brand: string; category: string; on_hand: number; unit: string; sold: number; daily_velocity: number; days_on_hand: number | null; oldest_age_days: number; score: number; suggested_discount_pct: number; inventory_value: number }[] };
type Delivery = { transaction_id: string; received_at: string; reference: string; product_name: string; sku: string; package_id: string; quantity: number; unit: string };
type Impact = { delivery: Delivery; before: { units: number; net_sales: number; orders: number }; after: { units: number; net_sales: number; orders: number }; lift: { units: number; net_sales: number; net_sales_pct: number | null }; window_days: number };
export function RetailInsightsPage() {
  const [tab, setTab] = useState<"trends" | "slow" | "delivery">("trends"); const [days, setDays] = useState(30); const [threshold, setThreshold] = useState(60); const [deliveryId, setDeliveryId] = useState("");
  const trends = useQuery({ queryKey: ["retail-trends", days], queryFn: ({ signal }) => apiGet<Trend>(`/api/v1/retail-insights/trends?days=${days}`, signal), enabled: tab === "trends" }); const slow = useQuery({ queryKey: ["slow-movers", days, threshold], queryFn: ({ signal }) => apiGet<Slow>(`/api/v1/retail-insights/slow-movers?days=${days}&threshold_doh=${threshold}`, signal), enabled: tab === "slow" }); const deliveries = useQuery({ queryKey: ["retail-deliveries"], queryFn: ({ signal }) => apiGet<Delivery[]>("/api/v1/retail-insights/deliveries", signal), enabled: tab === "delivery" }); const impact = useQuery({ queryKey: ["delivery-impact", deliveryId], queryFn: ({ signal }) => apiGet<Impact>(`/api/v1/retail-insights/deliveries/${deliveryId}/impact?window_days=14`, signal), enabled: Boolean(deliveryId) });
  return <div className="page"><div className="page-heading"><div><div className="eyebrow">Retail Ops · SQL sales ledger</div><h1>Reports & Insights</h1><p>Trends, category mix, slow-moving inventory and delivery lift from durable transactions.</p></div><div className="heading-actions"><label className="compact-field">Sales window<select value={days} onChange={event => setDays(Number(event.target.value))}><option value={14}>14 days</option><option value={30}>30 days</option><option value={60}>60 days</option><option value={90}>90 days</option></select></label></div></div><div className="view-tabs report-tabs"><button className={tab === "trends" ? "active" : ""} onClick={() => setTab("trends")}>Sales trends</button><button className={tab === "slow" ? "active" : ""} onClick={() => setTab("slow")}>Slow movers</button><button className={tab === "delivery" ? "active" : ""} onClick={() => setTab("delivery")}>Delivery impact</button></div>
  {tab === "trends" ? <>{trends.isLoading ? <State/> : trends.data ? <><section className="metrics"><Metric label="Net sales" value={money(trends.data.summary.net_sales)}/><Metric label="Units sold" value={trends.data.summary.units.toLocaleString()}/><Metric label="Average daily sales" value={money(trends.data.summary.average_daily_sales)}/><Metric label="Mapped sales" value={`${trends.data.summary.mapped_sales_pct.toFixed(1)}%`}/></section><div className="insights-grid"><section className="inventory-panel insight-card"><h2>Daily net sales</h2><TrendChart rows={trends.data.daily}/></section><section className="inventory-panel insight-card"><h2>Category mix</h2>{trends.data.categories.slice(0, 10).map(row => <Bar key={row.category} label={row.category} value={row.net_sales} max={trends.data!.categories[0]?.net_sales || 1}/>)}</section></div><section className="inventory-panel"><div className="table-wrap"><table><thead><tr><th>Product</th><th>SKU</th><th>Category</th><th>Units</th><th>Net sales</th></tr></thead><tbody>{trends.data.products.map(row => <tr key={`${row.product_id}-${row.sku}`}><td>{row.product_name}</td><td>{row.sku || "—"}</td><td>{row.category}</td><td>{row.quantity.toLocaleString()}</td><td>{money(row.net_sales)}</td></tr>)}</tbody></table></div></section></> : <State empty/>}</> : null}
  {tab === "slow" ? <>{slow.data ? <><section className="metrics"><Metric label="Slow products" value={slow.data.summary.product_count}/><Metric label="Units at risk" value={slow.data.summary.units_at_risk.toLocaleString()}/><Metric label="Cost at risk" value={money(slow.data.summary.cost_at_risk)}/><Metric label="No sales velocity" value={slow.data.summary.zero_velocity_count}/></section><div className="insight-controls"><label>DOH threshold<input type="number" min="1" value={threshold} onChange={event => setThreshold(Number(event.target.value))}/></label></div><section className="inventory-panel"><div className="table-wrap"><table><thead><tr><th>Decision</th><th>Product</th><th>Category</th><th>On hand</th><th>Window sold</th><th>DOH</th><th>Age</th><th>Cost at risk</th></tr></thead><tbody>{slow.data.items.map(row => <tr key={row.product_id}><td><span className="badge low-balance">{row.suggested_discount_pct ? `Consider ${row.suggested_discount_pct}%` : "Watch"}</span></td><td>{row.product_name}<br/><small>{row.sku} · {row.brand || "No brand"}</small></td><td>{row.category}</td><td>{row.on_hand.toLocaleString()} {row.unit}</td><td>{row.sold.toLocaleString()}</td><td>{row.days_on_hand == null ? "No velocity" : row.days_on_hand.toFixed(1)}</td><td>{row.oldest_age_days}d</td><td>{money(row.inventory_value)}</td></tr>)}</tbody></table></div></section></> : <State/>}</> : null}
  {tab === "delivery" ? <div className="delivery-layout"><section className="inventory-panel"><div className="table-wrap"><table><thead><tr><th>Received</th><th>Product</th><th>Package</th><th>Quantity</th><th>Reference</th></tr></thead><tbody>{deliveries.data?.map(row => <tr key={row.transaction_id} className={deliveryId === row.transaction_id ? "selected-row" : ""} onClick={() => setDeliveryId(row.transaction_id)}><td>{new Date(row.received_at).toLocaleDateString()}</td><td>{row.product_name}<br/><small>{row.sku}</small></td><td>{row.package_id}</td><td>{row.quantity} {row.unit}</td><td>{row.reference || "—"}</td></tr>)}</tbody></table></div></section><aside className="inventory-panel impact-card">{impact.data ? <><div className="eyebrow">{impact.data.window_days} days before vs after</div><h2>{impact.data.delivery.product_name}</h2><div className="impact-columns"><Metric label="Before sales" value={money(impact.data.before.net_sales)}/><Metric label="After sales" value={money(impact.data.after.net_sales)}/></div><div className={`impact-lift ${impact.data.lift.net_sales >= 0 ? "positive" : "negative"}`}><span>Net sales lift</span><strong>{impact.data.lift.net_sales >= 0 ? "+" : ""}{money(impact.data.lift.net_sales)}</strong><small>{impact.data.lift.net_sales_pct == null ? "No prior-period sales" : `${impact.data.lift.net_sales_pct.toFixed(1)}%`}</small></div><div className="catalog-row"><strong>Unit lift</strong><span>{impact.data.lift.units >= 0 ? "+" : ""}{impact.data.lift.units}</span></div><div className="catalog-row"><strong>Orders</strong><span>{impact.data.before.orders} → {impact.data.after.orders}</span></div></> : <div className="empty">Select a receipt to measure its sales impact.</div>}</aside></div> : null}</div>;
}
function TrendChart({ rows }: { rows: Trend["daily"] }) { const width = 700, height = 220, pad = 28, max = Math.max(...rows.map(row => row.net_sales), 1); const points = rows.map((row, index) => `${pad + index * ((width - pad * 2) / Math.max(rows.length - 1, 1))},${height - pad - row.net_sales / max * (height - pad * 2)}`).join(" "); return <svg className="trend-chart" viewBox={`0 0 ${width} ${height}`} role="img" aria-label="Daily net sales trend"><line x1={pad} x2={width-pad} y1={height-pad} y2={height-pad}/><polyline points={points}/>{rows.map((row, index) => <circle key={row.date} cx={pad + index * ((width-pad*2)/Math.max(rows.length-1,1))} cy={height-pad-row.net_sales/max*(height-pad*2)} r="3"><title>{row.date}: {money(row.net_sales)}</title></circle>)}</svg>; }
function Bar({ label, value, max }: { label: string; value: number; max: number }) { return <div className="mix-bar"><span>{label}</span><div><i style={{ width: `${value / max * 100}%` }}/></div><strong>{money(value)}</strong></div>; }
function Metric({ label, value }: { label: string; value: string | number }) { return <article className="metric"><span>{label}</span><strong>{value}</strong></article>; } function State({ empty = false }: { empty?: boolean }) { return <div className="state">{empty ? "No durable retail sales are available for this window." : "Loading retail insights…"}</div>; } function money(value: number) { return value.toLocaleString(undefined, { style: "currency", currency: "USD", maximumFractionDigits: 2 }); }
