import { useQuery } from "@tanstack/react-query";
import { useMemo, useState } from "react";
import { apiDownload, apiGet, downloadBlob } from "../lib/api";

type Row = Record<string, unknown>;
type Data = { controls: { velocity_days: number; min_doh: number; top_n: number; search: string }; facets: { categories: string[]; brands: string[]; decisions: string[] }; summary: { slow_skus: number; inventory_cost: number; dead_items: number; markdown_candidates: number }; discount_tiers: Row[]; items: Row[] };

export function SlowMoversPage() {
  const [velocity, setVelocity] = useState(56); const [minDoh, setMinDoh] = useState(90); const [topN, setTopN] = useState(100); const [search, setSearch] = useState(""); const [categories, setCategories] = useState<string[]>([]); const [brands, setBrands] = useState<string[]>([]); const [decisions, setDecisions] = useState<string[]>([]);
  const params = useMemo(() => { const p = new URLSearchParams({ velocity_days:String(velocity), min_doh:String(minDoh), top_n:String(topN), search }); categories.forEach(v=>p.append("category",v)); brands.forEach(v=>p.append("brand",v)); decisions.forEach(v=>p.append("decision",v)); return p; }, [velocity,minDoh,topN,search,categories,brands,decisions]);
  const data = useQuery({ queryKey:["slow-movers-parity",params.toString()], queryFn:({signal})=>apiGet<Data>(`/api/v1/slow-movers-parity?${params}`,signal) });
  const exportFile = async () => downloadBlob(await apiDownload(`/api/v1/slow-movers-parity/export?${params}`), "slow_movers.xlsx");
  return <div className="page"><div className="page-heading"><div><div className="eyebrow">Retail Ops · original Buyer Dash workflow</div><h1>Slow Movers</h1><p>Decision-first slow-mover workflow with the original filters, DOH scoring, discount tiers, KPI strip and Excel export.</p></div><button className="secondary" disabled={!data.data} onClick={exportFile}>Export Slow Movers (Excel)</button></div>
  <section className="inventory-panel parity-controls slow-controls"><label>Velocity Window<select value={velocity} onChange={e=>setVelocity(Number(e.target.value))}><option value={14}>14 days</option><option value={28}>28 days</option><option value={56}>56 days</option><option value={84}>84 days</option></select></label><label>Min DOH Threshold<input type="number" min={0} step={5} value={minDoh} onChange={e=>setMinDoh(Number(e.target.value))}/></label><label>Top N<select value={topN} onChange={e=>setTopN(Number(e.target.value))}>{[25,50,100,250,500].map(n=><option key={n} value={n}>{n}</option>)}</select></label><label>Search Product<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Product name…"/></label></section>
  {data.data ? <section className="inventory-panel parity-controls facet-controls"><Multi label="Categories" values={data.data.facets.categories} selected={categories} onChange={setCategories}/><Multi label="Brands" values={data.data.facets.brands} selected={brands} onChange={setBrands}/><Multi label="Decision" values={data.data.facets.decisions} selected={decisions} onChange={setDecisions}/></section> : null}
  {data.isError ? <div className="state error">{data.error.message}</div> : null}{data.isLoading ? <div className="state">Building Slow Movers from the active Buyer Dash sources…</div> : null}
  {data.data ? <><section className="metrics"><Metric label="Slow SKUs" value={data.data.summary.slow_skus}/><Metric label="Inventory Cost" value={money(data.data.summary.inventory_cost)}/><Metric label="Dead Items" value={data.data.summary.dead_items}/><Metric label="Markdown Candidates" value={data.data.summary.markdown_candidates}/></section><section className="inventory-panel"><div className="section-heading"><div><div className="eyebrow">Action tiers</div><h2>Discount Tier Summary</h2></div></div><Table rows={data.data.discount_tiers} columns={["discount_tier","skus","inventory_cost","inventory_retail"]}/></section><section className="inventory-panel"><div className="section-heading"><div><div className="eyebrow">Decision-first</div><h2>Slow Mover Table</h2></div></div><Table rows={data.data.items} columns={["decision","discount_tier","product_name","brand","category","onhandunits","unitssold","daily_run_rate","days_on_hand","inventory_cost","inventory_retail","velocity_band"]}/></section></> : null}</div>;
}
function Multi({label,values,selected,onChange}:{label:string;values:string[];selected:string[];onChange:(values:string[])=>void}){return <label>{label}<select multiple value={selected} onChange={e=>onChange(Array.from(e.target.selectedOptions).map(o=>o.value))}>{values.map(v=><option key={v}>{v}</option>)}</select><small>{selected.length ? `${selected.length} selected` : `All ${label.toLowerCase()}`}</small></label>}
function Metric({label,value}:{label:string;value:string|number}){return <article className="metric"><span>{label}</span><strong>{value}</strong></article>} function money(value:number){return value.toLocaleString(undefined,{style:"currency",currency:"USD",maximumFractionDigits:0})} function head(v:string){return v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase())} function show(v:unknown){if(v==null||v==="")return"—";if(typeof v==="number")return Number.isInteger(v)?v.toLocaleString():v.toLocaleString(undefined,{maximumFractionDigits:2});return String(v)} function Table({rows,columns}:{rows:Row[];columns:string[]}){const visible=columns.filter(c=>rows.some(r=>r[c]!==undefined));return <div className="table-wrap"><table><thead><tr>{visible.map(c=><th key={c}>{head(c)}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{visible.map(c=><td key={c}>{show(r[c])}</td>)}</tr>)}</tbody></table>{rows.length===0?<div className="empty">No products match these filters.</div>:null}</div>}
