import { useEffect, useMemo, useState, type ReactNode } from "react";
import { useQuery } from "@tanstack/react-query";
import { Link, useSearchParams } from "react-router-dom";
import { apiGet, apiPost, apiDownload, downloadBlob } from "../lib/api";
import { calculate, complianceChecks, formDefaults, num, packUnit, planDefaults, planRow, today, whiteLabelReportPayload, type Form, type PlanRow, type ResultRow } from "./whiteLabelRepackParity";

type Step = 0 | 1 | 2 | 3 | 4;
type Scenario = { form: Form; plan: PlanRow[]; simpleMode: boolean };
export type DurablePlan = { id:string; name:string; revision:number; status:string; execution_status:string|null; production_order_id:string|null; source_lot_id:string; scenario:Scenario; source:{lot_code:string;quantity:number;unit:string}; economics:{outputs:{package_size_g:number;units:number;packaged_g:number}[]} };
type SourceLot = { id:string; lot_code:string; package_id:string; product_name:string; status:string };

export function WhiteLabelRepackPage(){
  const [step,setStep]=useState<Step>(0); const [form,setForm]=useState<Form>(formDefaults); const [plan,setPlan]=useState<PlanRow[]>(planDefaults); const [simpleMode,setSimpleMode]=useState(true); const [scenarioName,setScenarioName]=useState("Current Session"); const [loadName,setLoadName]=useState(""); const [notice,setNotice]=useState("");
  const [exporting,setExporting]=useState(false); const [exportError,setExportError]=useState("");
  const [params,setParams]=useSearchParams();
  const [current,setCurrent]=useState<DurablePlan|null>(null);
  const [sourceId,setSourceId]=useState(""); const [sourceSearch,setSourceSearch]=useState("");
  const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  const [offset,setOffset]=useState(0);
  const scope=[localStorage.getItem("buyer-dash-organization"),localStorage.getItem("buyer-dash-facility")];
  const saved=useQuery({queryKey:["white-label-plans",...scope,offset],queryFn:({signal})=>apiGet<DurablePlan[]>(`/api/v1/white-label/plans?offset=${offset}`,signal)});
  const sources=useQuery({queryKey:["white-label-sources",...scope,sourceSearch],queryFn:({signal})=>apiGet<SourceLot[]>(`/api/v1/white-label/sources?q=${encodeURIComponent(sourceSearch)}`,signal)});
  const requested=params.get("plan")||"";
  const restore=useQuery({queryKey:["white-label-plan",...scope,requested],enabled:!!requested&&(!current||current.id!==requested),retry:false,queryFn:({signal})=>apiGet<DurablePlan>(`/api/v1/white-label/plans/${encodeURIComponent(requested)}`,signal)});
  useEffect(()=>{const row=restore.data;if(!row||row.id!==requested||current?.id===requested)return;setCurrent(row);setForm(structuredClone(row.scenario.form));setPlan(structuredClone(row.scenario.plan));setSimpleMode(row.scenario.simpleMode);setSourceId(row.source_lot_id);setScenarioName(row.name);setLoadName(row.id)},[restore.data,requested,current]);
  const calc=useMemo(()=>calculate(form,plan),[form,plan]);
  const set=<T extends string|number>(key:string,value:T)=>setForm(current=>({...current,[key]:value}));
  const updatePlan=(index:number,key:keyof PlanRow,value:number|boolean)=>setPlan(current=>current.map((row,i)=>i===index?{...row,[key]:value}:row));
  const addPlanRow=()=>setPlan(current=>[...current,planRow(false,0,0,.2,0)]);
  const removePlanRow=(index:number)=>setPlan(current=>current.filter((_,i)=>i!==index));
  const run=async(action:()=>Promise<void>)=>{setBusy(true);setError("");try{await action()}catch(e){setError(e instanceof Error?e.message:"Could not save plan.")}finally{setBusy(false)}};
  const accept=(source:DurablePlan)=>{setCurrent(source);setForm(structuredClone(source.scenario.form));setPlan(structuredClone(source.scenario.plan));setSimpleMode(source.scenario.simpleMode);setSourceId(source.source_lot_id);setScenarioName(source.name);setLoadName(source.id);setParams({plan:source.id});};
  const save=()=>run(async()=>{const result=await apiPost<DurablePlan>(`/api/v1/white-label/plans${current?`/${current.id}`:""}`,{name:scenarioName,source_lot_id:sourceId,scenario:{form,plan,simpleMode},revision:current?.revision});accept(result);await saved.refetch();setNotice(`Saved durable plan: ${result.name}`)});
  const duplicate=()=>{setCurrent(null);setScenarioName(`${scenarioName} Copy`);setParams({});setNotice("Copy ready. Save durable plan to persist it.")};
  const clear=()=>{setCurrent(null);setSourceId("");setForm(formDefaults());setPlan(planDefaults());setSimpleMode(true);setScenarioName("Current Session");setLoadName("");setParams({});setNotice("New unsaved scenario.")};
  const apply=()=>run(async()=>{const source=await apiGet<DurablePlan>(`/api/v1/white-label/plans/${loadName||requested}`);accept(source);setNotice(`Loaded ${source.name}`)});
  const dirty=!!current&&(scenarioName!==current.name||sourceId!==current.source_lot_id||JSON.stringify({form,plan,simpleMode})!==JSON.stringify(current.scenario));
  const transition=(action:"approve"|"cancel")=>run(async()=>{if(!current)return;const result=await apiPost<DurablePlan>(`/api/v1/white-label/plans/${current.id}/${action}`,{revision:current.revision});accept(result);await saved.refetch();setNotice(action==="approve"?"Approved. Production handoff created. Inventory has not been reserved or consumed.":"Draft cancelled.")});
  const exportReport=async()=>{setExporting(true);setExportError("");try{const blob=await apiDownload("/api/v1/executive-reports/white-label.pdf",whiteLabelReportPayload(scenarioName,form,plan,calc));downloadBlob(blob,`retail_ops_repack_report_${today()}.pdf`)}catch(error){setExportError(error instanceof Error?error.message:"Could not generate the report.")}finally{setExporting(false)}};
  return <div className="page"><div className="page-heading"><div><div className="eyebrow">White Label / Repack</div><h1>White Label / Repack</h1><p>Plan a private-label flower lot from bulk intake through package margin and release readiness.</p></div><div className="heading-actions"><button className="primary" disabled={exporting} onClick={exportReport}>{exporting?"Generating PDF…":"Export Retail Ops Report"}</button><small>Retail Ops executive PDF</small></div></div>{exportError?<div className="form-error">{exportError}</div>:null}
    <section className="inventory-panel scenario-controls"><Field label="Scenario Name"><input value={scenarioName} onChange={e=>setScenarioName(e.target.value)}/></Field><button className="secondary" disabled={busy||!sourceId||!!current&&current.status!=="draft"} onClick={save}>Save durable plan</button><Field label="Load Scenario"><select value={loadName} onChange={e=>setLoadName(e.target.value)}><option value="">Select saved plan</option>{saved.data?.map(item=><option value={item.id} key={item.id}>{item.name} / {item.status}</option>)}</select></Field><button className="secondary" onClick={duplicate}>Duplicate Scenario</button><button className="secondary" onClick={clear}>Clear Scenario</button><button className="primary" disabled={busy||!(loadName||requested)} onClick={apply}>Apply Loaded Scenario</button><button disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-100))}>Previous plans</button><button disabled={saved.data?.length!==100} onClick={()=>setOffset(offset+100)}>More plans</button></section>
    {requested&&!current?<div className="info-banner">A saved plan is selected. Apply Loaded Scenario to restore it.</div>:null}
    <section className="inventory-panel"><Field label="Find source lot or package"><input value={sourceSearch} onChange={e=>setSourceSearch(e.target.value)} placeholder="Search lot, package, or product"/></Field><Field label="Existing source inventory"><select value={sourceId} onChange={e=>setSourceId(e.target.value)}><option value="">Choose source inventory</option>{sourceId&&!sources.data?.some(lot=>lot.id===sourceId)?<option value={sourceId}>{current?.source.lot_code||sourceId}</option>:null}{sources.data?.map(lot=><option key={lot.id} value={lot.id}>{lot.lot_code} / {lot.product_name} / {lot.package_id} / {lot.status}</option>)}</select></Field><p>Search narrows the first 100 matching lots. Saving and approval validate current availability, QA and COA evidence. Planning estimates do not release inventory or certify labels.</p>
    {current?<><p>Plan status: <strong>{current.status}</strong>{current.execution_status?` / Execution: ${current.execution_status}`:""}{dirty?" / Unsaved changes":""}</p><button className="primary" disabled={busy||dirty||current.status!=="draft"} onClick={()=>transition("approve")}>Approve plan</button> <button className="secondary" disabled={busy||current.status!=="draft"} onClick={()=>transition("cancel")}>Cancel draft</button>{current.production_order_id?<p><Link to={`/production/runs/${current.production_order_id}`}>Production Run 360</Link> / <Link to={`/production/package-studio?white_label_plan=${current.id}`}>Package Studio</Link> / <Link to="/compliance/labels">Label Studio</Link></p>:null}</>:null}</section>
    {error||saved.error||sources.error||restore.error?<div className="form-error" role="alert">{error||saved.error?.message||sources.error?.message||restore.error?.message}</div>:null}{notice?<div className="success-banner">{notice}</div>:null}
    <div className="view-tabs white-label-tabs">{["Step 1: Bulk Lot","Step 2: Costs","Step 3: Package Plan","Step 4: Results","Step 5: Compliance"].map((label,i)=><button className={step===i?"active":""} key={label} onClick={()=>setStep(i as Step)}>{label}</button>)}</div>
    {step===0?<BulkLot form={form} set={set}/>:step===1?<Costs form={form} set={set}/>:step===2?<PackagePlanStep plan={plan} update={updatePlan} add={addPlanRow} remove={removePlanRow} simpleMode={simpleMode} setSimpleMode={setSimpleMode} allocation={calc.allocationTotal}/>:step===3?<Results calc={calc}/>:<Compliance form={form} set={set}/>} </div>
}

function BulkLot({form,set}:{form:Form;set:<T extends string|number>(key:string,value:T)=>void}){return <section className="inventory-panel white-label-step"><Info>Start with the bulk flower lot you are considering buying or repacking.</Info><Text label="Strain Name *" value={String(form.strain_name)} onChange={v=>set("strain_name",v)}/><Select label="Strain Type *" value={String(form.strain_type)} values={["Indica","Sativa","Hybrid","CBD","Mixed","Unknown"]} onChange={v=>set("strain_type",v)}/><Text label="Cultivator Name *" value={String(form.cultivator_name)} onChange={v=>set("cultivator_name",v)}/><Text label="Vendor Name *" value={String(form.vendor_name)} onChange={v=>set("vendor_name",v)}/><div className="two-col"><Num label="Bulk Weight *" value={num(form.bulk_weight_value)} min={0} onChange={v=>set("bulk_weight_value",v)}/><Select label="Weight Unit *" value={String(form.bulk_weight_unit)} values={["g","oz","lb"]} onChange={v=>set("bulk_weight_unit",v)}/></div><Num label="Total Bulk Cost ($) *" value={num(form.bulk_total_cost_usd)} min={0} onChange={v=>set("bulk_total_cost_usd",v)}/><Text label="Certificate of Analysis (COA) Link *" value={String(form.coa_link)} onChange={v=>set("coa_link",v)}/><Num label="THCA (%) *" value={num(form.thca_pct)} min={0} max={100} onChange={v=>set("thca_pct",v)}/><Num label="Terpenes (%) *" value={num(form.terpene_pct)} min={0} max={100} onChange={v=>set("terpene_pct",v)}/><details className="streamlit-expander"><summary>Advanced Lot Details</summary><div className="streamlit-expander-body form-grid"><Text label="Cultivator License Number" value={String(form.cultivator_license_number)} onChange={v=>set("cultivator_license_number",v)}/><Text label="Source METRC Package ID" value={String(form.source_metrc_package_id)} onChange={v=>set("source_metrc_package_id",v)}/><Text label="Batch or Lot Number" value={String(form.batch_or_lot_number)} onChange={v=>set("batch_or_lot_number",v)}/>{["harvest_date","testing_date","received_date"].map(key=><DateInput key={key} label={header(key)} value={String(form[key])} onChange={v=>set(key,v)}/>)}<Num label="Total THC (%)" value={num(form.total_thc_pct)} min={0} max={100} onChange={v=>set("total_thc_pct",v)}/><Num label="Moisture (%)" value={num(form.moisture_pct)} min={0} max={100} onChange={v=>set("moisture_pct",v)}/>{["testing_notes","buyer_notes","compliance_notes"].map(key=><Area key={key} label={header(key)} value={String(form[key])} onChange={v=>set(key,v)}/>)}</div></details></section>}
function Costs({form,set}:{form:Form;set:<T extends string|number>(key:string,value:T)=>void}){const primary=["discount_pct","shrink_loss_pct","labor_cost_total_usd","other_costs_usd"];const advanced=["freight_or_delivery_cost_usd","sample_or_testing_cost_usd","compliance_admin_cost_usd","qa_hold_loss_pct","trim_loss_pct","moisture_loss_pct"];const label=(key:string)=>({discount_pct:"Purchase Discount (%)",shrink_loss_pct:"Expected Shrink Loss (%)",labor_cost_total_usd:"Total Labor Cost ($)",other_costs_usd:"Other Costs ($)",freight_or_delivery_cost_usd:"Freight or Delivery Cost ($)",sample_or_testing_cost_usd:"Sampling or Testing Cost ($)",compliance_admin_cost_usd:"Compliance Administration Cost ($)",qa_hold_loss_pct:"QA Hold Loss (%)",trim_loss_pct:"Trim Loss (%)",moisture_loss_pct:"Moisture Loss (%)"}[key]||header(key));return <section className="inventory-panel white-label-step"><Info>Add the costs that change the true landed cost of the flower.</Info>{primary.map(key=><Num key={key} label={label(key)} value={num(form[key])} min={0} max={key.includes("pct")?100:undefined} onChange={v=>set(key,v)}/>)}<details className="streamlit-expander"><summary>Advanced Costs</summary><div className="streamlit-expander-body form-grid">{advanced.map(key=><Num key={key} label={label(key)} value={num(form[key])} min={0} max={key.includes("pct")?100:undefined} onChange={v=>set(key,v)}/>)}</div></details></section>}
function PackagePlanStep({plan,update,add,remove,simpleMode,setSimpleMode,allocation}:{plan:PlanRow[];update:(i:number,k:keyof PlanRow,v:number|boolean)=>void;add:()=>void;remove:(i:number)=>void;simpleMode:boolean;setSimpleMode:(v:boolean)=>void;allocation:number}){const invalidSize=plan.some(row=>row.enabled&&row.package_size_g<=0);return <section className="inventory-panel white-label-step"><Info>Choose how much of the lot goes into each package size. Packaging costs can vary by size.</Info><label className="toggle"><input type="checkbox" checked={simpleMode} onChange={e=>setSimpleMode(e.target.checked)}/> Simple Mode</label><PlanTable plan={plan} update={update} add={add} remove={remove} detailed={false}/>{!simpleMode?<details className="streamlit-expander"><summary>Packaging Cost Details</summary><div className="streamlit-expander-body"><PlanTable plan={plan} update={update} add={add} remove={remove} detailed/></div></details>:null}{allocation>100?<div className="warning-banner">Your package allocation is over 100%.</div>:allocation<100?<div className="warning-banner">You still have {(100-allocation).toFixed(1)}% unallocated.</div>:null}{invalidSize?<div className="warning-banner">Enabled package rows must have package_size_g &gt; 0.</div>:null}</section>}
function PlanTable({plan,update,add,remove,detailed}:{plan:PlanRow[];update:(i:number,k:keyof PlanRow,v:number|boolean)=>void;add?:()=>void;remove?:(i:number)=>void;detailed:boolean}){const cols:(keyof PlanRow)[]=detailed?["enabled","package_size_g","bag_or_container_cost_per_unit","label_cost_per_unit","tamper_seal_cost_per_unit","humidity_pack_cost_per_unit","compliance_sticker_cost_per_unit","other_packaging_cost_per_unit"]:["enabled","package_size_g","allocation_pct","target_retail_price_per_unit"];return <><div className="table-wrap"><table><thead><tr>{cols.map(c=><th key={c}>{c}</th>)}{!detailed?<th>total_packaging_cost_per_unit</th>:null}{remove?<th aria-label="Row actions"/>:null}</tr></thead><tbody>{plan.map((row,i)=><tr key={i}>{cols.map(c=><td key={c}>{c==="enabled"?<input type="checkbox" checked={row.enabled} onChange={e=>update(i,c,e.target.checked)}/>:<input className="table-input" type="number" min={0} step="any" value={row[c] as number} onChange={e=>update(i,c,Number(e.target.value))}/>}</td>)}{!detailed?<td>{packUnit(row)}</td>:null}{remove?<td><button className="table-row-action" aria-label={`Delete row ${i+1}`} title="Delete row" onClick={()=>remove(i)}>×</button></td>:null}</tr>)}</tbody></table></div>{add?<button className="secondary table-add-row" onClick={add}>Add row</button>:null}</>}
function Results({calc}:{calc:ReturnType<typeof calculate>}){return <section className="inventory-panel white-label-step"><Info>Review estimated units, revenue, profit, and margin.</Info>{calc.leftovers.length?<Info>Package-size rounding leaves partial grams in: {calc.leftovers.map(x=>`${x.size} (${x.grams.toFixed(2)} g)`).join(", ")}.</Info>:null}<div className="metrics five"><Metric l="Usable Weight" v={`${calc.usableWeight.toFixed(1)} g`}/><Metric l="Total Units" v={calc.totalUnits.toLocaleString()}/><Metric l="Total Revenue" v={money0(calc.totalRevenue)}/><Metric l="Gross Profit" v={money0(calc.grossProfit)}/><Metric l="Gross Margin %" v={`${calc.grossMargin.toFixed(1)}%`}/></div><div className="metrics"><Metric l="Leftover Grams" v={`${calc.leftover.toFixed(1)} g`}/><Metric l="Best Package Size by Margin" v={calc.best||"N/A"}/></div>{calc.rows.length?<><h4>Margin Readiness</h4><pre className="readiness-json">{JSON.stringify(calc.readiness,null,2)}</pre>{calc.readiness.incomplete_rows>0?<div className="warning-banner">Some margins are incomplete because required inputs are missing.</div>:null}</>:null}<ResultTable rows={calc.rows}/>{calc.rows.length?<><Bars title="Revenue" data={calc.rows.map(r=>[r.size,r.revenue??0])}/><Bars title="Gross Profit" data={calc.rows.map(r=>[r.size,r.profit??0])}/><Bars title="Gross Margin %" data={calc.rows.map(r=>[r.size,r.margin??0])}/></>:null}</section>}
function Compliance({form}:{form:Form;set:<T extends string|number>(key:string,value:T)=>void}){const checks=complianceChecks(form);return <section className="inventory-panel white-label-step"><Info>Check whether the lot has the documentation needed before launch.</Info><div className="table-wrap"><table><thead><tr><th>Requirement</th><th>Status</th></tr></thead><tbody>{checks.map(([req,status])=><tr key={req}><td>{req}</td><td>{status}</td></tr>)}</tbody></table></div></section>}

function ResultTable({rows}:{rows:ResultRow[]}){if(!rows.length)return <div className="table-wrap"/>;return <div className="table-wrap"><table><thead><tr>{["Product Name","Package Size","Allocation %","Grams Allocated","Units Produced","Retail Price","Total Packaging / Unit","Total Packaging Cost","All-In Cost / Unit","Break-even Price","Revenue","Gross Profit","Gross Margin %","Status","Missing Inputs"].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.product}><td>{r.product}</td><td>{r.size}</td><td>{r.allocation.toFixed(1)}</td><td>{r.grams.toFixed(2)}</td><td>{r.units}</td><td>{m(r.retail)}</td><td>{money2(r.packUnit)}</td><td>{money2(r.packTotal)}</td><td>{m(r.allInUnit)}</td><td>{m(r.breakEven)}</td><td>{m(r.revenue)}</td><td>{m(r.profit)}</td><td>{r.margin==null?"N/A":`${r.margin.toFixed(1)}%`}</td><td>{r.status}</td><td>{r.missing}</td></tr>)}</tbody></table></div>}
function Bars({title,data}:{title:string;data:[string,number][]}){const max=Math.max(1,...data.map(([,v])=>Math.max(0,v)));return <div className="chart-card"><h4>{title}</h4><div className="simple-bars">{data.map(([label,value])=><div className="simple-bar-row" key={label}><span>{label}</span><div><i style={{width:`${Math.max(0,value)/max*100}%`}}/></div><strong>{value.toLocaleString(undefined,{maximumFractionDigits:1})}</strong></div>)}</div></div>}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="compact-field"><span>{label}</span>{children}</label>}function Text({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <Field label={label}><input value={value} onChange={e=>onChange(e.target.value)}/></Field>}function Area({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <Field label={label}><textarea value={value} onChange={e=>onChange(e.target.value)}/></Field>}function Num({label,value,min,max,onChange}:{label:string;value:number;min?:number;max?:number;onChange:(v:number)=>void}){return <Field label={label}><input type="number" value={value} min={min} max={max} step="any" onChange={e=>onChange(Number(e.target.value))}/></Field>}function Select({label,value,values,onChange}:{label:string;value:string;values:string[];onChange:(v:string)=>void}){return <Field label={label}><select value={value} onChange={e=>onChange(e.target.value)}>{values.map(v=><option key={v}>{v}</option>)}</select></Field>}function DateInput({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <Field label={label}><input type="date" value={value} onChange={e=>onChange(e.target.value)}/></Field>}function Info({children}:{children:ReactNode}){return <div className="info-banner">{children}</div>}function Metric({l,v}:{l:string;v:string}){return <article className="metric"><span>{l}</span><strong>{v}</strong></article>}
function header(v:string){return v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase())}function money0(v:number){return v.toLocaleString(undefined,{style:"currency",currency:"USD",maximumFractionDigits:0})}function money2(v:number){return v.toLocaleString(undefined,{style:"currency",currency:"USD",minimumFractionDigits:2,maximumFractionDigits:2})}function m(v:number|null){return v==null?"N/A":money2(v)}
