import { useMemo, useState, type ReactNode } from "react";
import { apiDownload, downloadBlob } from "../lib/api";
import { calculate, complianceChecks, formDefaults, num, packUnit, planDefaults, planRow, today, whiteLabelReportPayload, type Form, type PlanRow, type ResultRow } from "./whiteLabelRepackParity";

type Step = 0 | 1 | 2 | 3 | 4;
type Scenario = { form: Form; plan: PlanRow[]; simpleMode: boolean };

export function WhiteLabelRepackPage(){
  const [step,setStep]=useState<Step>(0); const [form,setForm]=useState<Form>(formDefaults); const [plan,setPlan]=useState<PlanRow[]>(planDefaults); const [simpleMode,setSimpleMode]=useState(true); const [scenarioName,setScenarioName]=useState("Current Session"); const [loadName,setLoadName]=useState("Current Session"); const [notice,setNotice]=useState("");
  const [exporting,setExporting]=useState(false); const [exportError,setExportError]=useState("");
  const [saved,setSaved]=useState<Record<string,Scenario>>(()=>{try{return JSON.parse(sessionStorage.getItem("white-label-scenarios")||"{}")}catch{return{}}});
  const calc=useMemo(()=>calculate(form,plan),[form,plan]);
  const set=<T extends string|number>(key:string,value:T)=>setForm(current=>({...current,[key]:value}));
  const updatePlan=(index:number,key:keyof PlanRow,value:number|boolean)=>setPlan(current=>current.map((row,i)=>i===index?{...row,[key]:value}:row));
  const addPlanRow=()=>setPlan(current=>[...current,planRow(false,0,0,.2,0)]);
  const removePlanRow=(index:number)=>setPlan(current=>current.filter((_,i)=>i!==index));
  const persist=(next:Record<string,Scenario>)=>{setSaved(next);sessionStorage.setItem("white-label-scenarios",JSON.stringify(next))};
  const save=()=>{const name=scenarioName.trim()||"Current Session";persist({...saved,[name]:{form,plan,simpleMode}});setScenarioName(name);setNotice(`Saved scenario: ${name}`)};
  const duplicate=()=>{const source=saved[loadName];if(!source)return;const name=`${loadName} Copy`;persist({...saved,[name]:structuredClone(source)});setNotice(`Duplicated as ${name}`)};
  const clear=()=>{setForm(formDefaults());setPlan(planDefaults());setSimpleMode(true);setScenarioName("Current Session");setLoadName("Current Session");setNotice("Cleared scenario values for current session.")};
  const apply=()=>{const source=saved[loadName];if(!source)return;setForm(structuredClone(source.form));setPlan(structuredClone(source.plan));setSimpleMode(source.simpleMode);setScenarioName(loadName);setNotice(`Loaded ${loadName}`)};
  const exportReport=async()=>{setExporting(true);setExportError("");try{const blob=await apiDownload("/api/v1/executive-reports/white-label.pdf",whiteLabelReportPayload(scenarioName,form,plan,calc));downloadBlob(blob,`retail_ops_repack_report_${today()}.pdf`)}catch(error){setExportError(error instanceof Error?error.message:"Could not generate the report.")}finally{setExporting(false)}};
  const names=["Current Session",...Object.keys(saved).sort()];
  return <div className="page"><div className="page-heading"><div><div className="eyebrow">White Label / Repack</div><h1>White Label / Repack</h1><p>Plan a private-label flower lot from bulk intake through package margin and release readiness.</p></div><div className="heading-actions"><button className="primary" disabled={exporting} onClick={exportReport}>{exporting?"Generating PDF…":"Export Retail Ops Report"}</button><small>Retail Ops executive PDF</small></div></div>{exportError?<div className="form-error">{exportError}</div>:null}
    <section className="inventory-panel scenario-controls"><Field label="Scenario Name"><input value={scenarioName} onChange={e=>setScenarioName(e.target.value)}/></Field><button className="secondary" onClick={save}>Save Scenario</button><Field label="Load Scenario"><select value={loadName} onChange={e=>setLoadName(e.target.value)}>{names.map(name=><option key={name}>{name}</option>)}</select></Field><button className="secondary" onClick={duplicate}>Duplicate Scenario</button><button className="secondary" onClick={clear}>Clear Scenario</button>{loadName!=="Current Session"?<button className="primary" onClick={apply}>Apply Loaded Scenario</button>:null}</section>{notice?<div className="success-banner">{notice}</div>:null}
    <div className="view-tabs white-label-tabs">{["Step 1: Bulk Lot","Step 2: Costs","Step 3: Package Plan","Step 4: Results","Step 5: Compliance"].map((label,i)=><button className={step===i?"active":""} key={label} onClick={()=>setStep(i as Step)}>{label}</button>)}</div>
    {step===0?<BulkLot form={form} set={set}/>:step===1?<Costs form={form} set={set}/>:step===2?<PackagePlanStep plan={plan} update={updatePlan} add={addPlanRow} remove={removePlanRow} simpleMode={simpleMode} setSimpleMode={setSimpleMode} allocation={calc.allocationTotal}/>:step===3?<Results calc={calc}/>:<Compliance form={form} set={set}/>} </div>
}

function BulkLot({form,set}:{form:Form;set:<T extends string|number>(key:string,value:T)=>void}){return <section className="inventory-panel white-label-step"><Info>Start with the bulk flower lot you are considering buying or repacking.</Info><Text label="Strain Name *" value={String(form.strain_name)} onChange={v=>set("strain_name",v)}/><Select label="Strain Type *" value={String(form.strain_type)} values={["Indica","Sativa","Hybrid","CBD","Mixed","Unknown"]} onChange={v=>set("strain_type",v)}/><Text label="Cultivator Name *" value={String(form.cultivator_name)} onChange={v=>set("cultivator_name",v)}/><Text label="Vendor Name *" value={String(form.vendor_name)} onChange={v=>set("vendor_name",v)}/><div className="two-col"><Num label="Bulk Weight *" value={num(form.bulk_weight_value)} min={0} onChange={v=>set("bulk_weight_value",v)}/><Select label="Weight Unit *" value={String(form.bulk_weight_unit)} values={["g","oz","lb"]} onChange={v=>set("bulk_weight_unit",v)}/></div><Num label="Total Bulk Cost ($) *" value={num(form.bulk_total_cost_usd)} min={0} onChange={v=>set("bulk_total_cost_usd",v)}/><Text label="Certificate of Analysis (COA) Link *" value={String(form.coa_link)} onChange={v=>set("coa_link",v)}/><Num label="THCA (%) *" value={num(form.thca_pct)} min={0} max={100} onChange={v=>set("thca_pct",v)}/><Num label="Terpenes (%) *" value={num(form.terpene_pct)} min={0} max={100} onChange={v=>set("terpene_pct",v)}/><details className="streamlit-expander"><summary>Advanced Lot Details</summary><div className="streamlit-expander-body form-grid"><Text label="Cultivator License Number" value={String(form.cultivator_license_number)} onChange={v=>set("cultivator_license_number",v)}/><Text label="Source METRC Package ID" value={String(form.source_metrc_package_id)} onChange={v=>set("source_metrc_package_id",v)}/><Text label="Batch or Lot Number" value={String(form.batch_or_lot_number)} onChange={v=>set("batch_or_lot_number",v)}/>{["harvest_date","testing_date","received_date"].map(key=><DateInput key={key} label={header(key)} value={String(form[key])} onChange={v=>set(key,v)}/>)}<Num label="Total THC (%)" value={num(form.total_thc_pct)} min={0} max={100} onChange={v=>set("total_thc_pct",v)}/><Num label="Moisture (%)" value={num(form.moisture_pct)} min={0} max={100} onChange={v=>set("moisture_pct",v)}/>{["testing_notes","buyer_notes","compliance_notes"].map(key=><Area key={key} label={header(key)} value={String(form[key])} onChange={v=>set(key,v)}/>)}</div></details></section>}
function Costs({form,set}:{form:Form;set:<T extends string|number>(key:string,value:T)=>void}){const primary=["discount_pct","shrink_loss_pct","labor_cost_total_usd","other_costs_usd"];const advanced=["freight_or_delivery_cost_usd","sample_or_testing_cost_usd","compliance_admin_cost_usd","qa_hold_loss_pct","trim_loss_pct","moisture_loss_pct"];const label=(key:string)=>({discount_pct:"Purchase Discount (%)",shrink_loss_pct:"Expected Shrink Loss (%)",labor_cost_total_usd:"Total Labor Cost ($)",other_costs_usd:"Other Costs ($)",freight_or_delivery_cost_usd:"Freight or Delivery Cost ($)",sample_or_testing_cost_usd:"Sampling or Testing Cost ($)",compliance_admin_cost_usd:"Compliance Administration Cost ($)",qa_hold_loss_pct:"QA Hold Loss (%)",trim_loss_pct:"Trim Loss (%)",moisture_loss_pct:"Moisture Loss (%)"}[key]||header(key));return <section className="inventory-panel white-label-step"><Info>Add the costs that change the true landed cost of the flower.</Info>{primary.map(key=><Num key={key} label={label(key)} value={num(form[key])} min={0} max={key.includes("pct")?100:undefined} onChange={v=>set(key,v)}/>)}<details className="streamlit-expander"><summary>Advanced Costs</summary><div className="streamlit-expander-body form-grid">{advanced.map(key=><Num key={key} label={label(key)} value={num(form[key])} min={0} max={key.includes("pct")?100:undefined} onChange={v=>set(key,v)}/>)}</div></details></section>}
function PackagePlanStep({plan,update,add,remove,simpleMode,setSimpleMode,allocation}:{plan:PlanRow[];update:(i:number,k:keyof PlanRow,v:number|boolean)=>void;add:()=>void;remove:(i:number)=>void;simpleMode:boolean;setSimpleMode:(v:boolean)=>void;allocation:number}){const invalidSize=plan.some(row=>row.enabled&&row.package_size_g<=0);return <section className="inventory-panel white-label-step"><Info>Choose how much of the lot goes into each package size. Packaging costs can vary by size.</Info><label className="toggle"><input type="checkbox" checked={simpleMode} onChange={e=>setSimpleMode(e.target.checked)}/> Simple Mode</label><PlanTable plan={plan} update={update} add={add} remove={remove} detailed={false}/>{!simpleMode?<details className="streamlit-expander"><summary>Packaging Cost Details</summary><div className="streamlit-expander-body"><PlanTable plan={plan} update={update} add={add} remove={remove} detailed/></div></details>:null}{allocation>100?<div className="warning-banner">Your package allocation is over 100%.</div>:allocation<100?<div className="warning-banner">You still have {(100-allocation).toFixed(1)}% unallocated.</div>:null}{invalidSize?<div className="warning-banner">Enabled package rows must have package_size_g &gt; 0.</div>:null}</section>}
function PlanTable({plan,update,add,remove,detailed}:{plan:PlanRow[];update:(i:number,k:keyof PlanRow,v:number|boolean)=>void;add?:()=>void;remove?:(i:number)=>void;detailed:boolean}){const cols:(keyof PlanRow)[]=detailed?["enabled","package_size_g","bag_or_container_cost_per_unit","label_cost_per_unit","tamper_seal_cost_per_unit","humidity_pack_cost_per_unit","compliance_sticker_cost_per_unit","other_packaging_cost_per_unit"]:["enabled","package_size_g","allocation_pct","target_retail_price_per_unit"];return <><div className="table-wrap"><table><thead><tr>{cols.map(c=><th key={c}>{c}</th>)}{!detailed?<th>total_packaging_cost_per_unit</th>:null}{remove?<th aria-label="Row actions"/>:null}</tr></thead><tbody>{plan.map((row,i)=><tr key={i}>{cols.map(c=><td key={c}>{c==="enabled"?<input type="checkbox" checked={row.enabled} onChange={e=>update(i,c,e.target.checked)}/>:<input className="table-input" type="number" min={0} step="any" value={row[c] as number} onChange={e=>update(i,c,Number(e.target.value))}/>}</td>)}{!detailed?<td>{packUnit(row)}</td>:null}{remove?<td><button className="table-row-action" aria-label={`Delete row ${i+1}`} title="Delete row" onClick={()=>remove(i)}>×</button></td>:null}</tr>)}</tbody></table></div>{add?<button className="secondary table-add-row" onClick={add}>Add row</button>:null}</>}
function Results({calc}:{calc:ReturnType<typeof calculate>}){return <section className="inventory-panel white-label-step"><Info>Review estimated units, revenue, profit, and margin.</Info>{calc.leftovers.length?<Info>Package-size rounding leaves partial grams in: {calc.leftovers.map(x=>`${x.size} (${x.grams.toFixed(2)} g)`).join(", ")}.</Info>:null}<div className="metrics five"><Metric l="Usable Weight" v={`${calc.usableWeight.toFixed(1)} g`}/><Metric l="Total Units" v={calc.totalUnits.toLocaleString()}/><Metric l="Total Revenue" v={money0(calc.totalRevenue)}/><Metric l="Gross Profit" v={money0(calc.grossProfit)}/><Metric l="Gross Margin %" v={`${calc.grossMargin.toFixed(1)}%`}/></div><div className="metrics"><Metric l="Leftover Grams" v={`${calc.leftover.toFixed(1)} g`}/><Metric l="Best Package Size by Margin" v={calc.best||"—"}/></div>{calc.rows.length?<><h4>Margin Readiness</h4><pre className="readiness-json">{JSON.stringify(calc.readiness,null,2)}</pre>{calc.readiness.incomplete_rows>0?<div className="warning-banner">Some margins are incomplete because required inputs are missing.</div>:null}</>:null}<ResultTable rows={calc.rows}/>{calc.rows.length?<><Bars title="Revenue" data={calc.rows.map(r=>[r.size,r.revenue??0])}/><Bars title="Gross Profit" data={calc.rows.map(r=>[r.size,r.profit??0])}/><Bars title="Gross Margin %" data={calc.rows.map(r=>[r.size,r.margin??0])}/></>:null}</section>}
function Compliance({form}:{form:Form;set:<T extends string|number>(key:string,value:T)=>void}){const checks=complianceChecks(form);return <section className="inventory-panel white-label-step"><Info>Check whether the lot has the documentation needed before launch.</Info><div className="table-wrap"><table><thead><tr><th>Requirement</th><th>Status</th></tr></thead><tbody>{checks.map(([req,status])=><tr key={req}><td>{req}</td><td>{status}</td></tr>)}</tbody></table></div></section>}

function ResultTable({rows}:{rows:ResultRow[]}){if(!rows.length)return <div className="table-wrap"/>;return <div className="table-wrap"><table><thead><tr>{["Product Name","Package Size","Allocation %","Grams Allocated","Units Produced","Retail Price","Total Packaging / Unit","Total Packaging Cost","All-In Cost / Unit","Break-even Price","Revenue","Gross Profit","Gross Margin %","Status","Missing Inputs"].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.product}><td>{r.product}</td><td>{r.size}</td><td>{r.allocation.toFixed(1)}</td><td>{r.grams.toFixed(2)}</td><td>{r.units}</td><td>{m(r.retail)}</td><td>{money2(r.packUnit)}</td><td>{money2(r.packTotal)}</td><td>{m(r.allInUnit)}</td><td>{m(r.breakEven)}</td><td>{m(r.revenue)}</td><td>{m(r.profit)}</td><td>{r.margin==null?"N/A":`${r.margin.toFixed(1)}%`}</td><td>{r.status}</td><td>{r.missing}</td></tr>)}</tbody></table></div>}
function Bars({title,data}:{title:string;data:[string,number][]}){const max=Math.max(1,...data.map(([,v])=>Math.max(0,v)));return <div className="chart-card"><h4>{title}</h4><div className="simple-bars">{data.map(([label,value])=><div className="simple-bar-row" key={label}><span>{label}</span><div><i style={{width:`${Math.max(0,value)/max*100}%`}}/></div><strong>{value.toLocaleString(undefined,{maximumFractionDigits:1})}</strong></div>)}</div></div>}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="compact-field"><span>{label}</span>{children}</label>}function Text({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <Field label={label}><input value={value} onChange={e=>onChange(e.target.value)}/></Field>}function Area({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <Field label={label}><textarea value={value} onChange={e=>onChange(e.target.value)}/></Field>}function Num({label,value,min,max,onChange}:{label:string;value:number;min?:number;max?:number;onChange:(v:number)=>void}){return <Field label={label}><input type="number" value={value} min={min} max={max} step="any" onChange={e=>onChange(Number(e.target.value))}/></Field>}function Select({label,value,values,onChange}:{label:string;value:string;values:string[];onChange:(v:string)=>void}){return <Field label={label}><select value={value} onChange={e=>onChange(e.target.value)}>{values.map(v=><option key={v}>{v}</option>)}</select></Field>}function DateInput({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <Field label={label}><input type="date" value={value} onChange={e=>onChange(e.target.value)}/></Field>}function Info({children}:{children:ReactNode}){return <div className="info-banner">{children}</div>}function Metric({l,v}:{l:string;v:string}){return <article className="metric"><span>{l}</span><strong>{v}</strong></article>}
function header(v:string){return v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase())}function money0(v:number){return v.toLocaleString(undefined,{style:"currency",currency:"USD",maximumFractionDigits:0})}function money2(v:number){return v.toLocaleString(undefined,{style:"currency",currency:"USD",minimumFractionDigits:2,maximumFractionDigits:2})}function m(v:number|null){return v==null?"N/A":money2(v)}
