import type { HelpWalkthroughRegistry } from "./types";

export const operationsWalkthroughs: HelpWalkthroughRegistry = {
  "/help/getting-started": {
    title: "Get started in the right facility", category: "getting-started", summary: "Sign in, check your access and data source, and open the workspace for your job.", navPath: "Sign in → Access Context → Home", appPath: "/home",
    beforeYouStart: ["Have the username or email and password issued for your own account.", "Know which organization, facility, and operation you need. An active account doesn't automatically include facility access."],
    steps: [
      { id: "sign-in", title: "Sign in with your own account", instructions: ["Enter your username or email in Username, enter Password, and select Sign in.", "Forgot password? requests a reset email when Username contains an email address. For a username account, ask an administrator to reset the password in Admin Tools."], fields: [{ label: "Username", requirement: "Required.", guidance: "Enter your assigned username or account email.", example: "training.operator" }, { label: "Password", requirement: "Required.", guidance: "Enter your current password only in this control." }], expected: "Your workspace opens, or an access message explains what is missing." },
      { id: "confirm-context", title: "Check Access Context", instructions: ["Read the organization in Access Context and choose the intended Facility when a selector is available. Recheck the Active summary in the sidebar after the page refreshes.", "Organization switching is only shown to DEV accounts with more than one available organization."], fields: [{ label: "Facility", requirement: "Required operating context; choices depend on access.", guidance: "Choose the licensed site whose records you intend to use." }, { label: "Organization", requirement: "Conditional selector for DEV accounts.", guidance: "Choose the intended organization before selecting its facility." }], expected: "The header and sidebar identify the intended site." },
      { id: "choose-operation", title: "Choose the operation for this task", instructions: ["Use Operation to choose Retail Ops, Cultivation Ops, or Production Ops from the available choices.", "Recheck Facility afterward. Changing operations can switch to a facility that supports that operation. Your role and facility capabilities determine the choices."], fields: [{ label: "Operation", requirement: "Required selection.", guidance: "Choose the part of the business that owns the task." }], expected: "The navigation changes to match the operation and the facility is still the intended one." },
      { id: "check-source-readiness", title: "Check the data before relying on a workspace", instructions: ["Open Settings & Administration, then Imports & Data. On Readiness, review Dataset, Status, Source, Rows, and Updated.", "For retail analysis, expand Data source and check Buyer data mode. Uploads uses published files. Selecting Dutchie Live doesn't create a connection, and the current Buyer Operations and Trends endpoints cannot fetch live Dutchie data."], fields: [{ label: "Buyer data mode", requirement: "Conditional on Retail Ops.", guidance: "Use Uploads for published source files." }], expected: "You can identify the data source and update time, or the missing source that needs attention." },
      { id: "open-first-task", title: "Open a task or find a record", instructions: ["Return to Home and choose Needs Attention / Today. Read an inbox item's evidence before using its action button, or select Open on a Start a Task card.", "Use Search DoobieLogic to find a product, package, plant, order, partner, or tool. Check the result type before opening it.", "On a narrow screen, use Navigate for the work area, Tool for its workspace, and Settings and administration for setup pages."], fields: [{ label: "Search DoobieLogic", requirement: "Optional.", guidance: "Search by a known name or identifier and inspect the matching result." }], expected: "The selected workspace or record opens in your access context." }
    ],
    completion: ["Access Context identifies the intended organization, facility, and operation.", "You have opened a task with a known data source."],
    troubleshooting: [{ symptom: "No facility workspace access appears.", resolution: "Ask an administrator to assign Facility access in User Management. After they save, select Refresh access on the access screen." }, { symptom: "A facility or work area isn't offered.", resolution: "Ask an administrator to check your role, facility assignments, and enabled operations. Changing the visible operation doesn't grant access." }, { symptom: "Trends fails with Dutchie Live selected.", resolution: "Choose Uploads and check that Inventory and Product Sales are active in Data Hub. Live fetching isn't implemented for that endpoint." }],
    sourceFiles: ["frontend/src/components/AuthGate.tsx", "frontend/src/components/AppShell.tsx", "frontend/src/components/GlobalSearch.tsx", "frontend/src/pages/DataSettingsPage.tsx", "frontend/src/lib/workspaceRoutes.ts", "backend/app/routers/account.py", "backend/app/routers/buyer_parity.py"]
  },
  "/help/home": {
    title: "Choose the next job from Operations Home", category: "home", summary: "Read the current facility's exceptions and open the record or workspace that needs attention.", navPath: "Home → Needs Attention / Today", appPath: "/home",
    beforeYouStart: ["Confirm the organization and facility in Access Context.", "Home summarizes loaded facility data. Missing sources can leave the picture incomplete."],
    steps: [
      { id: "check-home-context", title: "Check the greeting and facility", instructions: ["Open Home, then Needs Attention / Today. Read the organization and facility beneath the greeting.", "Check the role named in the introduction. Start a Task cards are selected for that role, so another operator may see different cards."], expected: "Operations Home shows your context and the tasks available for your role." },
      { id: "read-home-metrics", title: "Read the summary signals together", instructions: ["Review Needs attention, Low stock, Open POs, and Data sources ready. Read the high-priority count and represented purchase order value beneath their totals.", "A missing value while data loads isn't a confirmed zero. If Data sources ready is incomplete, check Imports & Data before relying on the summary."], expected: "You can distinguish populated signals from missing or loading information." },
      { id: "open-inbox-item", title: "Choose an exception from the inbox", instructions: ["In Needs attention · Operations Inbox, read the area, severity, title, detail, and evidence for the item.", "Use its attached action button. Labels and destinations vary with the exception. Home displays up to eight items, so it is a starting view rather than a complete work list."], expected: "The related workspace opens, or a product drawer opens for the product or hold." },
      { id: "inspect-source-record", title: "Check the source record before changing anything", instructions: ["Confirm the product, lot, or other record matches the exception you chose and inspect its current state.", "Make any needed change using the destination workspace's controls. Opening an inbox item doesn't resolve it or submit a provider change."], expected: "The source record and its available actions are visible for review." },
      { id: "use-role-task", title: "Use a task card when no exception fits", instructions: ["Return to Home, read the Start a Task descriptions, and select Open on the card that fits the job.", "If Home reports no high-priority exceptions visible from loaded data, still check the task's data and scope. That message doesn't establish that every operation is complete."], expected: "The selected task workspace opens without creating a work item or changing records." }
    ], completion: ["You have opened the source record or task workspace for the issue.", "You have checked source readiness before relying on an absence of exceptions."],
    troubleshooting: [{ symptom: "The inbox shows an error.", resolution: "Read the error and check the facility. Don't treat a failed request as an empty queue; reopen Home after the access or service issue is corrected." }, { symptom: "A coworker's task card is missing from your Home.", resolution: "Compare your role and operation. Ask an administrator to review access if the task belongs to your job." }],
    sourceFiles: ["frontend/src/pages/HomePage.tsx", "frontend/src/components/Product360Drawer.tsx", "frontend/src/components/AppShell.tsx", "backend/app/routers/home.py"]
  },
  "/help/home/work-queue": {
    title: "Assign, track, and complete work", category: "home", summary: "Create facility tasks, keep progress and evidence current, and generate recurring work when it is due.", navPath: "Home → Work Queue", appPath: "/work",
    beforeYouStart: ["Confirm the facility. Work and eligible assignees are scoped to it.", "Creation and updates are available to dev, admin, buyer, planner, supervisor, operator, and qa roles.", "Due times display locally. Recurring schedules retain UTC time, which matters when daylight saving time changes."],
    steps: [
      { id: "filter-work", title: "Find the work you need", instructions: ["Choose View: My work, All work, Due in 24 hours, Overdue, or My priority work. Use All work to inspect unassigned or team work.", "Combine Status, Priority, and Assignee as needed. Previous and Next move through pages of 50 items."], fields: [{ label: "View", requirement: "Required filter; defaults to My work.", guidance: "Choose the slice of work you need." }, { label: "Status", requirement: "Optional filter.", guidance: "Choose a state or Any status." }, { label: "Priority", requirement: "Optional filter.", guidance: "Narrow by recorded urgency." }, { label: "Assignee", requirement: "Optional filter.", guidance: "Choose from the eligible facility list." }], expected: "Matching cards appear, or No work matches these filters is shown." },
      { id: "describe-work", title: "Create a clear task and assign it", instructions: ["Select Create work. Write an action in Title and use Description for the records to inspect and the completion check.", "Choose Priority and Assignee deliberately. Creating a task doesn't automatically assign it to you."], fields: [{ label: "Title", requirement: "Required; up to 240 characters.", guidance: "Name the job clearly.", example: "Review today's receiving exceptions" }, { label: "Description", requirement: "Optional; up to 20,000 characters.", guidance: "Explain the context and what a finished review should establish." }, { label: "Priority", requirement: "Defaults to medium.", guidance: "Choose low, medium, high, or critical for the actual urgency." }, { label: "Assignee", requirement: "Optional.", guidance: "Choose a person or leave Unassigned for triage." }], expected: "The form holds your unsaved task details." },
      { id: "set-work-schedule", title: "Set one-time or recurring timing", instructions: ["Leave Recurrence at One time for a single task and enter Due time only if it needs a deadline.", "For daily, weekly, or monthly work, set First due time. Last due time (optional) must be on or after it. Monthly work uses the anchor day, shortened to month end when necessary."], fields: [{ label: "Recurrence", requirement: "Defaults to One time.", guidance: "A recurrence saves a template for future generation." }, { label: "Due time", requirement: "Optional for one-time work.", guidance: "Enter local date and time; the app converts it to UTC." }, { label: "First due time", requirement: "Required for recurring work.", guidance: "Set the first occurrence in local time." }, { label: "Last due time (optional)", requirement: "Optional for recurring work.", guidance: "Set the end of generation if the schedule should stop." }], expected: "The form offers Save work or Save template for your selection." },
      { id: "link-save-work", title: "Link the task and save it", instructions: ["Optionally enter Linked workspace and a valid local Linked route. Supply Entity type and Entity ID together only when you have the exact record reference.", "Select Save work or Save template once and wait for Saved. Use All work if the new task doesn't match My work."], fields: [{ label: "Linked workspace", requirement: "Optional.", guidance: "Use the actual workspace name.", example: "Inventory" }, { label: "Linked route", requirement: "Optional.", guidance: "Use a local app route, not an external URL.", example: "/inventory" }, { label: "Entity type", requirement: "Required if Entity ID is supplied.", guidance: "Identify the referenced record type." }, { label: "Entity ID", requirement: "Required if Entity type is supplied.", guidance: "Use the exact existing ID, not a guessed display name." }], expected: "Saved. appears and the work or template is available in its list." },
      { id: "update-work-progress", title: "Record progress and blocks", instructions: ["Select Inspect work / update. Use Open linked workspace to inspect the operational record separately.", "Under Assignment and progress, update Assignee, Due time, or Priority as needed. Choose Status, enter supporting detail, and select Save changes."], fields: [{ label: "Status", requirement: "Current task state.", guidance: "Choose Open / reopen, Start work, Block work, or Complete work." }, { label: "Blocked reason", requirement: "Required for Block work; up to 2,000 characters.", guidance: "Explain what prevents progress and what will resolve it." }, { label: "Notes", requirement: "Optional; up to 20,000 characters.", guidance: "Record the work performed or handoff." }, { label: "Evidence / references", requirement: "Optional; up to 20,000 characters.", guidance: "Add verifiable record references without credentials." }], expected: "Saved. appears and the refreshed detail shows the updated progress." },
      { id: "complete-work", title: "Complete the task after checking its outcome", instructions: ["Verify the underlying work first. Completing a task doesn't receive stock, release holds, or submit state transactions.", "Set Status to Complete work, update Notes and Evidence / references, and select Save changes. Use Open / reopen and save if further work is needed."], expected: "The card shows completed and the detail shows Completed by and its timestamp." },
      { id: "generate-recurring-work", title: "Generate due work and maintain templates", instructions: ["Open Recurring templates and review the frequency, start time, and Active or Paused or ended state. Select Generate due work to create due occurrences; generation runs on request.", "Read the generated count. If the message says more may be due, another generation pass can continue that batch.", "Pause stops future generation; Resume allows it again. Choose Assignee on a template and Update future assignee to change future tasks. Review existing work separately."], expected: "The generation result states the number created and templates reflect the saved future behavior." }
    ], completion: ["The task has the intended assignee, priority, due time, and state.", "Completed tasks show completion details, and recurring templates show the intended active state."],
    troubleshooting: [{ symptom: "An update conflicts with another operator's changes.", resolution: "The page refreshes work after an update error. Read the latest detail before reapplying an intended change; don't overwrite a newer completion or assignment blindly." }, { symptom: "The new task isn't in My work.", resolution: "Choose All work and clear filters. If you saved a template, inspect Recurring templates and generate due occurrences when appropriate." }, { symptom: "An assignee is unavailable.", resolution: "Choose an eligible facility user. The list is bounded to the first 500 eligible users; ask an administrator to review membership if the needed person isn't offered." }],
    sourceFiles: ["frontend/src/pages/WorkQueuePage.tsx", "backend/app/routers/work.py", "backend/app/schemas/work.py", "backend/app/services/work.py"]
  },
  "/help/reports/sales-category-trends": {
    title: "Read Sales & Category Trends", category: "reports", summary: "Compare category mix, package sizes, and product movement using the facility's published inventory and sales sources.", navPath: "Reports → Sales & Category Trends", appPath: "/reports/sales-category-trends",
    beforeYouStart: ["Select the retail facility and Uploads in Buyer data mode.", "Publish both Inventory and Product Sales in Imports & Data. This analysis requires both active sources."],
    steps: [
      { id: "open-trends", title: "Open Trends and check its inputs", instructions: ["Choose Reports, then Sales & Category Trends. The page heading is Trends.", "If analysis cannot load, inspect Readiness and History in Imports & Data for active Inventory and Product Sales. The page's older Inventory Dashboard wording doesn't require a different source store."], expected: "Category Mix (Units), Package Size Mix (Units), and Top Movers (SKU-level) load, or a source error appears." },
      { id: "set-trend-periods", title: "Choose the analysis periods", instructions: ["Set Trend window (days) and Comparison window (prior days), each between 7 and 120 days.", "Wait for the tables after changing a control. There is no Save or Run button, and selecting a longer window cannot add history missing from the source file."], fields: [{ label: "Trend window (days)", requirement: "Required; 7 to 120, default 30.", guidance: "Choose a recent period represented by your sales data." }, { label: "Comparison window (prior days)", requirement: "Required; 7 to 120, default 30.", guidance: "Choose the prior comparison period." }], expected: "The chosen counts appear beside the sliders and the analysis refreshes." },
      { id: "set-run-rate", title: "Set the run-rate assumption", instructions: ["Set Run-rate multiplier between 0.1 and 3. Use 1 when no adjustment is intended.", "This changes the requested analysis, not recorded sales, stock, prices, or purchase orders. Keep the assumption with any figures you share."], fields: [{ label: "Run-rate multiplier", requirement: "Required; 0.1 to 3, default 1.", guidance: "Use a deliberate analysis adjustment.", example: "1" }], expected: "The input shows the assumption used for the refreshed results." },
      { id: "compare-sales-mix", title: "Read category and package-size mix", instructions: ["Compare unitssold, units per day, and unit share where shown in Category Mix (Units). Then review Package Size Mix (Units).", "Package sizes group products; they aren't instructions to convert inventory weights. Keep sales units distinct from an item's weight or volume."], expected: "You can identify the categories and sizes represented in the source and their reported unit totals." },
      { id: "inspect-trend-leaders", title: "Inspect product leaders and low-stock signals", instructions: ["Review Top Movers (SKU-level). Set Top N per category and expand a category under Best Sellers by Category.", "If Fast Movers + Low Stock (SKU-level) appears, compare units per day and onhandunits, then confirm current stock in Inventory before making a purchasing decision. Each returned table is bounded to 500 rows."], fields: [{ label: "Top N per category", requirement: "Required display setting; 1 to 50, default 10.", guidance: "Choose the number of leading products to inspect per category." }], expected: "The expanded category shows its leaders and any low-stock table identifies products for follow-up." }
    ], completion: ["The visible periods and multiplier match your analysis assumptions.", "You have identified specific rows to review in Inventory or Buying."],
    troubleshooting: [{ symptom: "Dutchie Live produces an error.", resolution: "Choose Uploads in Buyer data mode. The trends endpoint explicitly rejects Dutchie Live because live fetching isn't implemented." }, { symptom: "Categories are missing or totals look wrong.", resolution: "Check both active sources, their facility, coverage dates, and mappings in Data Hub. The sliders can't recover absent sales history." }],
    sourceFiles: ["frontend/src/pages/BuyerTrendsPage.tsx", "frontend/src/pages/DataSettingsPage.tsx", "backend/app/routers/buyer_parity.py"]
  },
  "/help/reports/executive": {
    title: "Generate Executive Reports", category: "reports", summary: "Download a report or operating pack for the current facility and check the data and session assumptions behind it.", navPath: "Reports → Executive Reports", appPath: "/reports/executive",
    beforeYouStart: ["Confirm the organization and facility. Even Company Executive Pack uses the current organization and facility context.", "You need report export permission and the required facility capability. Relevant operational records must be available."],
    steps: [
      { id: "choose-executive-report", title: "Find the report you need", instructions: ["Open Executive Reports and wait for the catalog. Read each card's title and operations label.", "Choose the report for your intended operation. Available cards depend on the active facility's capabilities."], expected: "The catalog shows the report cards available for this facility." },
      { id: "check-report-inputs", title: "Check session-specific inputs first", instructions: ["For Buyer Operations reporting, check the current buyer controls in that workspace before returning here. Reports use controls stored in this browser session, with defaults when none are stored.", "White Label / Repack contributes to the Retail Ops pack only when a current report payload exists in this session. Prepare that analysis first if you need it included."], expected: "The Retail Ops pack description includes White Label / Repack only when a session payload is available." },
      { id: "download-executive-pdf", title: "Generate an individual PDF", instructions: ["Select Generate & Download PDF on the intended card and wait while it shows Generating PDF.", "The server generates the document and the client checks that the response is a PDF before saving. Read any generation error rather than assuming the click completed the download."], expected: "A dated PDF downloads, or a visible error explains the failure." },
      { id: "download-report-pack", title: "Choose a combined operating pack", instructions: ["Under Executive report packs, choose Download Retail Ops Pack, Download Production Ops Pack, or Download Cultivation Ops Pack.", "Use Download Company Executive Pack for the available combined content in this context. Production sections depend on available facility production and extraction data."], expected: "One combined PDF downloads, or the page reports that suitable reports aren't available." },
      { id: "verify-report-file", title: "Inspect the downloaded document", instructions: ["Open the PDF and compare its sections, dates, and figures with the workspace you intended to report on.", "Check missing sections before sharing. A valid PDF confirms generation; it doesn't establish that the underlying records are complete."], expected: "You have a readable PDF whose content matches the intended reporting context." }
    ], completion: ["The PDF opens and contains the intended report sections.", "The facility and any buyer or repack session inputs have been checked."],
    troubleshooting: [{ symptom: "A pack says no reports are available.", resolution: "Check facility capabilities and source records. For a repack contribution, prepare the current White Label / Repack analysis in the same session." }, { symptom: "Export is denied or generation fails.", resolution: "Ask an administrator to check report export permission and facility capability. Retain the non-sensitive error and report name for support; an empty or renamed file isn't a successful export." }],
    sourceFiles: ["frontend/src/pages/ExecutiveReportsPage.tsx", "frontend/src/lib/api.ts", "backend/app/routers/executive_reports.py"]
  },
  "/help/reports/scheduled": {
    title: "Schedule and verify report delivery", category: "reports", summary: "Create a facility subscription, send a deliberate test, and inspect delivery outcomes before sending again.", navPath: "Reports → Scheduled Reports", appPath: "/reports/scheduled",
    beforeYouStart: ["Use a facility administrator account with report export permission and the report's facility capability.", "Confirm approved recipients and facility scope. Delivery requires live Spacemail validation.", "Daily and weekly schedules use elapsed UTC days. Monthly schedules move to the next month, clamped to its last day. Displayed times are local."],
    steps: [
      { id: "choose-report-recipients", title: "Choose the report and approved recipients", instructions: ["Under Create subscription, choose Report from the catalog.", "Enter plain recipient email addresses separated by commas, without display names or a trailing comma. The server accepts 1 to 20 entries and removes duplicates."], fields: [{ label: "Report", requirement: "Required.", guidance: "Choose the specific Executive Report to send." }, { label: "Recipients, separated by commas", requirement: "Required; 1 to 20 valid addresses.", guidance: "This list receives both test and regular deliveries.", example: "operations@example.com, manager@example.com" }], expected: "The unsaved form contains the intended report and addresses; no email has been sent." },
      { id: "create-report-subscription", title: "Set the cadence and save the subscription", instructions: ["Choose daily, weekly, or monthly in Cadence and select Create subscription once.", "Inspect the resulting card's report, recipients, Active state, and Next time. The first scheduled delivery is one cadence after creation, not an immediate send."], fields: [{ label: "Cadence", requirement: "Required; default weekly.", guidance: "Choose the interval. This form has no time-of-day or timezone input." }], expected: "A card appears with cadence, Active state, Next time, and Last attempt." },
      { id: "test-report-send", title: "Send a deliberate test", warning: "Test delivery sends the current report to every subscription recipient. It isn't a preview-only check.", instructions: ["Recheck the recipient list and select Test delivery once.", "Read the result and Delivery history. A sent result means Spacemail accepted the report, not that recipients opened it."], expected: "History records the attempt, its status, recipients, and detail." },
      { id: "process-due-subscriptions", title: "Process due scheduled reports", warning: "Process due subscriptions can send reports for due active subscriptions in this facility.", instructions: ["Review the cards, then select Process due subscriptions when you intend to send due reports.", "Delivery runs on this request or through an authorized scheduler, not merely because the page is open. One request processes up to ten due subscriptions. Review Delivery history and use More subscriptions for additional card pages."], expected: "Processed attempts appear in history and cards show updated attempt or schedule information." },
      { id: "run-pause-subscription", title: "Send on demand or pause future scheduling", warning: "Run now sends another report. Resolve processing or uncertain outcomes before requesting a new send.", instructions: ["Use Run now only when an extra immediate delivery is intended and inspect its history result.", "Use Pause to stop future scheduled processing or Resume to enable it again. Pausing doesn't recall mail already accepted by the provider."], expected: "The card shows Paused or Active and any deliberate send appears in history." },
      { id: "inspect-delivery-history", title: "Review uncertain outcomes before another send", instructions: ["Use Newer and Older to inspect pages of 50 delivery attempts. Match report, recipients, time, status, and detail.", "If delivery is processing or uncertain, have the mail outcome checked. Keep this page open after a network failure: the same report action retains its request identity so its existing result can be resolved. Don't reload and start a fresh send to guess what happened."], expected: "The last attempt has a reviewed outcome rather than an assumed success or failure." }
    ], completion: ["The subscription shows the intended recipients, cadence, state, and Next time.", "Every requested test or immediate send has a reviewed history outcome."],
    troubleshooting: [{ symptom: "Delivery is deferred because Spacemail is unavailable.", resolution: "Ask the responsible DEV operator to correct and validate mail setup. Read the attempt detail confirming no email was sent before planning another attempt." }, { symptom: "Delivery is needs_review or the request timed out.", resolution: "Check history and have the provider outcome reviewed. Don't issue a new send while the previous outcome remains uncertain." }, { symptom: "Recipient validation fails.", resolution: "Remove display names, empty entries, and trailing commas. Use no more than 20 plain email addresses." }],
    sourceFiles: ["frontend/src/pages/ScheduledReportsPage.tsx", "backend/app/routers/adoption.py", "backend/app/services/scheduled_reports.py"]
  },
  "/help/reports/insights": {
    title: "Inspect recorded sales and delivery impact", category: "reports", summary: "Review recorded retail transactions, slow movers, and receipt comparisons on the live Reports & Insights route.", navPath: "Open /reports → Reports & Insights", appPath: "/reports",
    beforeYouStart: ["Confirm the retail facility and its recorded sales, inventory, and receipts.", "This route is separate from Sales & Category Trends and isn't currently a separate standard Reports submenu item."],
    steps: [
      { id: "open-recorded-reports", title: "Open the report and choose the sales window", instructions: ["Open /reports and check the Reports & Insights heading and any retail regulatory-state message.", "Choose 14, 30, 60, or 90 days in Sales window. This affects Sales trends and Slow movers; delivery impact uses a fixed 14-day comparison."], fields: [{ label: "Sales window", requirement: "Required filter; default 30 days.", guidance: "Choose the recorded-sales period to inspect." }], expected: "The selected tab loads its facility transaction analysis." },
      { id: "review-recorded-sales", title: "Check sales coverage and product results", instructions: ["Select Sales trends and review Net sales, Units sold, Average daily sales, and Mapped sales.", "Compare Daily net sales, Category mix, and Product sales. Low mapping coverage needs investigation before relying on product-level conclusions."], expected: "Product sales shows Product, SKU, Category, Units, and Net sales for the window." },
      { id: "review-recorded-slow-movers", title: "Inspect stock cover and age", instructions: ["Select Slow movers and set DOH threshold. DOH means days on hand at the measured sales rate.", "Compare On hand with its unit, Window sold, DOH, Age, and Cost at risk. No velocity means there isn't a sales rate for the calculation. Consider percentage badges are suggestions, not saved discounts."], fields: [{ label: "DOH threshold", requirement: "Positive number; default 60.", guidance: "Set the days-of-stock threshold for identifying slower inventory." }], expected: "The slow-mover table refreshes with stock measures and recommendation badges." },
      { id: "review-recorded-delivery", title: "Choose the receipt to compare", instructions: ["Select Delivery impact and click a receipt row. Confirm Received, Product, Package, Quantity, and Reference.", "Read the before/after comparison for the 14-day windows around that receipt. It compares recorded sales; it doesn't prove the receipt alone caused the change."], expected: "The selected row is highlighted and the receipt's impact detail loads." },
      { id: "download-recorded-report", title: "Export the current table", instructions: ["Select Download current report CSV after the tab loads.", "Sales trends exports product sales, Slow movers exports its rows, and Delivery impact exports the receipt list. That last CSV doesn't contain the selected receipt's before/after detail."], expected: "A CSV downloads for the active tab's table." }
    ], completion: ["The selected window and tab match the reviewed analysis.", "Any downloaded CSV contains the intended table."],
    troubleshooting: [{ symptom: "Results differ from Sales & Category Trends.", resolution: "Compare sources and windows. /reports uses recorded transactions; Sales & Category Trends uses published Buyer Operations sources." }, { symptom: "CSV download is disabled.", resolution: "Wait for the active tab to load and inspect its error if it fails. An unavailable response doesn't supply a table to export." }],
    sourceFiles: ["frontend/src/pages/RetailInsightsPage.tsx", "frontend/src/components/RetailRegulatoryState.tsx", "backend/app/routers/retail_insights.py", "frontend/src/App.tsx", "frontend/src/lib/workspaceRoutes.ts"]
  },
  "/help/settings/imports-data": {
    title: "Publish retail sources in Data Hub", category: "settings", summary: "Inspect a source, map its columns, and publish a reusable revision for the selected facility.", navPath: "Settings & Administration → Imports & Data", appPath: "/settings/data",
    beforeYouStart: ["Confirm the facility and intended source file. Retail files must be nonempty and no larger than 10 MB.", "Use the file types offered for the chosen dataset; required columns and accepted types vary.", "Publishing is available to dev, admin, buyer, planner, supervisor, operator, qa, and trial roles. Read-only users can review status and history."],
    steps: [
      { id: "review-current-sources", title: "Check what is already active", instructions: ["Open Imports & Data. Data Hub starts on Readiness. Confirm Active Facility.", "Read Dataset, Status, Source, Rows, and Updated in Operational source status. Identify the existing source before replacing it."], expected: "You can identify the active source and its age, or the missing input." },
      { id: "choose-retail-dataset", title: "Choose the dataset before the file", instructions: ["Select Import Retail Data and use 1. Choose the dataset. Read its description and any Current source message.", "Changing datasets clears the file, mapping, and review confirmation. Extraction logs belong under Import Production Data, not a retail dataset."], fields: [{ label: "1. Choose the dataset", requirement: "Required.", guidance: "Choose the source category matching the export. Inventory and Product Sales are separate inputs." }], expected: "The description and accepted types match the intended dataset." },
      { id: "inspect-retail-upload", title: "Upload for inspection", instructions: ["Use 2. Upload the source file and wait for inspection.", "Read Rows, Columns, and Quality under 3. Review detected structure. Inspection doesn't replace the active source; publication is a separate action."], fields: [{ label: "2. Upload the source file", requirement: "Required to publish; up to 10 MB.", guidance: "Choose a nonempty file in an offered type and check its facility and export date." }], expected: "Detected structure, required mappings, and Preview first 8 rows appear, or an inspection error is shown." },
      { id: "review-retail-mappings", title: "Confirm each required column mapping", instructions: ["Under Confirm column mapping, select a source column for each required field. The exact field labels depend on the dataset.", "If required fields weren't detected, Ask Mapping Agent can fill suggestions. Review Suggested column, Confidence, and Why and correct mismatches yourself; suggestions don't publish data.", "Open Preview first 8 rows. Match actual values to the field meanings and use a unique source column for every required field."], expected: "All required fields are mapped, no duplicate-column error remains, and preview values fit their meanings." },
      { id: "publish-reviewed-source", title: "Confirm review and publish", warning: "Replace current source makes the new revision active for this facility's dataset. Recheck the file and mappings immediately before publication.", instructions: ["Select I reviewed the source and want it available to Retail Operations.", "Select 4. Publish source or 4. Replace current source and wait for the saved message. This publishes reusable inputs; it doesn't submit purchase orders or other operating decisions."], fields: [{ label: "I reviewed the source and want it available to Retail Operations.", requirement: "Required confirmation.", guidance: "Select after reviewing the file and every required mapping." }], expected: "The page reports that the source is saved and available across Retail Operations." },
      { id: "verify-published-source", title: "Check the revision and destination workspace", instructions: ["Open History and inspect Dataset, File, Status, Imported At, Imported By, and Rows. Return to Readiness to check the updated status.", "Open the destination workspace. Buyer Operations and Trends require both Inventory and Product Sales, with Uploads selected in Buyer data mode."], expected: "History identifies the active revision and the destination can read its required inputs." },
      { id: "archive-active-sources", title: "Archive sources only when retiring the facility's active inputs", warning: "Archive active sources archives every currently active Data Hub source in this facility, not only the dataset last selected.", instructions: ["If that is your intended task, open Archive durable sources in History and read the scope before selecting Archive active sources. The control is limited to dev, admin, and supervisor roles.", "Check the archived count and History. Historical revisions remain visible, but dependent analysis may no longer have active inputs."], expected: "The archived count appears and History reflects the archived state." }
    ], completion: ["History shows the intended active file and row count.", "Readiness and the destination workspace reflect the published source."],
    troubleshooting: [{ symptom: "Publish is disabled.", resolution: "Map every required field to a unique column and select the review checkbox. A successful inspection and selected file must still be present; changing datasets clears them." }, { symptom: "Inspection fails.", resolution: "Check the file is nonempty, within 10 MB, and in an accepted type for the selected dataset. Correct the export or selection before trying again." }, { symptom: "Publishing doesn't make Buyer Operations ready.", resolution: "Check the facility, both Inventory and Product Sales, their mappings, and Uploads mode. One of the two sources alone isn't enough." }],
    sourceFiles: ["frontend/src/pages/DataSettingsPage.tsx", "backend/app/routers/data_hub.py", "modules/data_hub_repository.py", "backend/app/routers/buyer_parity.py"]
  },
  "/help/settings/import-production-data": {
    title: "Import extraction run records", category: "settings", summary: "Review extraction log mappings and defaults before appending runs through Data Hub.", navPath: "Settings & Administration → Imports & Data → Import Production Data", appPath: "/settings/data",
    beforeYouStart: ["Select the facility that owns the log and confirm your import authorization.", "Use a nonempty CSV, XLSX, or XLS file no larger than 10 MB. Fields ending in _g represent grams.", "This intake appends extraction runs. Co-Man products, lots, customers, machines, and schedules belong in their own setup workspaces."],
    steps: [
      { id: "inspect-extraction-file", title: "Open production intake and inspect the log", instructions: ["Open Imports & Data, then Import Production Data. Read Production Ops source intake and Raw Data Upload Staging.", "Use Upload extraction runs file and wait for inspection before using the append control."], fields: [{ label: "Upload extraction runs file", requirement: "Required; CSV, XLSX, or XLS, up to 10 MB.", guidance: "Choose the facility's extraction log with meaningful headers and batch identifiers." }], expected: "Default controls and a mapped preview appear, or the page explains why the log couldn't be read." },
      { id: "set-extraction-defaults", title: "Set defaults for missing mapped values", instructions: ["Review each default against the source records. Don't keep an easy default that misstates a run's method, ownership, or status.", "Default COA Status describes the imported record; choosing Passed doesn't establish that the lab result was verified."], fields: [{ label: "Default Method", requirement: "Default for missing mapped method.", guidance: "Choose BHO, CO2, Rosin, or Ethanol to match the log." }, { label: "Default State", requirement: "Default for missing mapped state.", guidance: "Choose the applicable state from the offered list." }, { label: "Default Client Name", requirement: "Default for missing mapped client.", guidance: "Use the actual client or in-house ownership label.", example: "Training Client" }, { label: "Default Status", requirement: "Default for missing mapped status.", guidance: "Choose Processing, Queued, Complete, Hold, or Failed based on records." }, { label: "Default COA Status", requirement: "Default for missing mapped COA status.", guidance: "Choose Pending, Passed, Failed, or Not Submitted only when supported." }], expected: "Mapped run preview reflects defaults where mappings are absent." },
      { id: "check-extraction-mapping", title: "Check identifiers, dates, and units", instructions: ["When mapping confidence is below 0.75, confirm each displayed source-column selector. IGNORE leaves that input unmapped rather than supplying missing evidence.", "Check run_date, batch_id_internal, method, and gram-weight fields. The higher-confidence view doesn't expose mapping selectors; correct the source headers and inspect the file again if that preview is wrong."], expected: "The preview has the intended batch identities, dates, statuses, and units." },
      { id: "review-extraction-preview", title: "Inspect the numeric preview", instructions: ["Review Mapped run preview and investigate unexpected zeros. Numeric fields are converted for display; don't accept an invalid source value as a measured zero.", "The preview may derive yield_pct as finished output divided by input and post_process_efficiency_pct as finished output divided by intermediate output. Verify that source weights are grams. Open Upload diagnostics for inspection details."], expected: "The preview agrees with the log and any unexpected numeric values are resolved." },
      { id: "append-reviewed-extraction", title: "Append the reviewed runs", warning: "Append mapped runs to Extraction Command Center adds records. It isn't a preview or a replacement of all extraction history.", instructions: ["Select Append mapped runs to Extraction Command Center once after reviewing the rows.", "Read the Added count and any duplicate count. Duplicates use run_date + batch_id_internal + method. After an uncertain response, inspect Extraction before attempting another import."], expected: "The page reports runs added and any duplicates skipped." },
      { id: "verify-extraction-import", title: "Check the runs in Extraction", instructions: ["Open Extraction from Production and inspect the imported batch identifiers and values.", "For product, lot, BOM, machine, crew, or customer setup, use Open Co-Man Production from the import tab. Extraction defaults don't create those master records."], expected: "The intended runs are available in Extraction with the reviewed values." }
    ], completion: ["The import has an added count and any duplicate count.", "The intended batch records and units have been checked in Extraction."],
    troubleshooting: [{ symptom: "The preview has zero weights or mismatched fields.", resolution: "Check numeric source values and units. Correct visible mappings when available; otherwise correct file headers and inspect again before appending." }, { symptom: "An expected run is skipped as a duplicate.", resolution: "Compare its run date, internal batch ID, and method with existing records. Don't alter identifiers just to defeat duplicate detection." }],
    sourceFiles: ["frontend/src/pages/DataSettingsPage.tsx", "backend/app/routers/extraction_parity.py"]
  },
  "/help/settings/admin": {
    title: "Create users and manage facility access", category: "settings", summary: "Create a normal account, set its role and site access, and verify changes through Admin Tools.", navPath: "Settings & Administration → Admin Tools", appPath: "/settings/admin",
    beforeYouStart: ["Use an authorized admin or dev account. Company administrators manage their own organization; only DEV can manage DEV accounts.", "Decide the role and exact facility assignments. Administrators can access every facility in their organization.", "Use Create User for normal onboarding. The app creates authentication and application access together; migration invite/link tools aren't required."],
    steps: [
      { id: "open-user-create", title: "Open normal account creation", instructions: ["Open Admin Tools, locate User Management, and choose Create User.", "Check the organization. Non-DEV accounts require one. A company administrator's organization is fixed; a DEV operator can choose an available organization."], expected: "The form shows identity, role, organization, facility, and password controls." },
      { id: "enter-user-details", title: "Enter a recognizable account identity", instructions: ["Enter a unique Username and recognizable Display name. Usernames support letters, numbers, periods, underscores, and hyphens.", "Email (optional) can be left blank for username login through the app's compatibility identity. If supplied, use the user's intended contact email."], fields: [{ label: "Username", requirement: "Required; up to 120 characters.", guidance: "Use a unique login name without spaces.", example: "training.operator" }, { label: "Display name", requirement: "Optional; up to 255 characters.", guidance: "Use the name teammates should recognize.", example: "Training Operator" }, { label: "Email (optional)", requirement: "Optional.", guidance: "Use a valid intended contact address. Welcome delivery depends on mail configuration.", example: "operator@example.com" }], expected: "The unsaved form contains the intended identity." },
      { id: "set-user-scope", title: "Choose role and review every facility assignment", instructions: ["Choose Role, then review Organization and Facility access.", "The form can select all facilities by default and reset selections when role or organization changes. Clear unintended sites. A normal non-admin account with no facility selections has no facility workspace access."], fields: [{ label: "Role", requirement: "Required; choices depend on your own role.", guidance: "Grant the role needed for the job." }, { label: "Organization", requirement: "Required for non-DEV accounts.", guidance: "Keep the account in the organization that owns its work." }, { label: "Facility access", requirement: "Explicit selections for non-DEV accounts.", guidance: "Review every checked facility after role or organization changes. Admin access covers the organization." }, { label: "Select all facilities", requirement: "Optional convenience control.", guidance: "Use only when every offered facility is intended." }], expected: "The role and checked sites match the approved access." },
      { id: "set-user-password", title: "Set a matching temporary password", instructions: ["Enter at least 12 characters in Temporary password and repeat the value in Confirm temporary password.", "Keep Require password change selected for a normal temporary-password handoff. Share credentials only through your approved private process."], fields: [{ label: "Temporary password", requirement: "Required; at least 12 characters.", guidance: "Use a unique temporary password, not another user's password." }, { label: "Confirm temporary password", requirement: "Required and must match.", guidance: "Repeat the temporary password." }, { label: "Require password change", requirement: "Optional checkbox, selected by default.", guidance: "Keep selected when the user must replace the temporary password." }], expected: "No short-password or mismatch message remains and Create User is enabled when all required fields are complete." },
      { id: "save-new-user", title: "Create the account and verify the result", instructions: ["Recheck role and facility access, select Create User once, and wait for User created and stored securely.", "This creates the Supabase authentication identity and app access through the server. Welcome mail settings can affect creation when Email (optional) is supplied. After an ambiguous result, inspect the user list before retrying; don't create a separate identity manually."], expected: "The success message appears and the account becomes available in user management." },
      { id: "edit-existing-user", title: "Review and save existing account access", instructions: ["Choose Manage Existing and select User. Check Account Details & Access before changing role, organization, or facilities.", "Use Account active and Require password change at next login as needed, then Save all account changes. The form prevents deactivating your current account or changing its role."], fields: [{ label: "User", requirement: "Required for management.", guidance: "Select and verify the intended account." }, { label: "Account active", requirement: "Saved account state.", guidance: "Clear only when the selected account should be deactivated." }, { label: "Require password change at next login", requirement: "Optional.", guidance: "Select when the next login must require a password change." }], expected: "All account details and access assignments were updated. appears after success." },
      { id: "save-user-permissions", title: "Review facility-specific permissions", instructions: ["In the permission manager, select User and Facility. Compare role defaults, the override, and effective permission.", "Use Inherit role unless an explicit Allow or Deny is intended, then select Save user permissions. Non-admin users must be assigned to the facility before receiving its permission overrides."], fields: [{ label: "Facility", requirement: "Required for permission overrides.", guidance: "Choose the site whose effective access you're reviewing." }], expected: "The refreshed table shows saved effective Allowed or Denied results." },
      { id: "reset-account-password", title: "Reset the selected user's password when needed", warning: "Reset password replaces the selected user's password and requires a change. Verify User immediately before submitting.", instructions: ["In Reset Password, enter matching New temporary password and Confirm new password values of at least 12 characters.", "Select Reset password and wait for the result. For a newly assigned facility, the user can select Refresh access on the no-access screen after the assignment is saved."], fields: [{ label: "New temporary password", requirement: "Required for reset; at least 12 characters.", guidance: "Use a new unique temporary password." }, { label: "Confirm new password", requirement: "Required for reset and must match.", guidance: "Repeat the new temporary password." }], expected: "The page reports Password reset. The user will be required to change it." }
    ], completion: ["The account is visible with the intended role and assignments.", "Each account update, permission save, or password reset has its own success result; creation alone doesn't prove a user has signed in."],
    troubleshooting: [{ symptom: "Creation reports a duplicate or uncertain failure.", resolution: "Inspect existing users before retrying. If the username belongs to another person, choose a distinct one. Escalate unresolved authentication errors without sharing credentials." }, { symptom: "An emailed account is blocked by Spacemail setup.", resolution: "Have the responsible DEV operator configure and validate mail delivery. Don't bypass the error with direct Supabase edits or an invented email address." }, { symptom: "The user has no facility workspace access.", resolution: "Review and save Facility access for the account, then have the user choose Refresh access. No selected facility intentionally prevents normal facility access." }],
    sourceFiles: ["frontend/src/pages/AdminPage.tsx", "frontend/src/pages/AdminToolsPage.tsx", "frontend/src/components/UserPermissionManager.tsx", "frontend/src/components/AuthGate.tsx", "backend/app/routers/admin.py", "backend/app/routers/admin_user_create.py"]
  },
  "/help/settings/integration-wizard": {
    title: "Set up a facility with Integration Wizard", category: "settings", summary: "Work through connection, validation, and mapping evidence without confusing finished steps with operational readiness.", navPath: "Settings & Administration → Integration Wizard", appPath: "/settings/integration-wizard",
    beforeYouStart: ["Confirm the facility and intended operating mode. Required systems depend on capabilities and mode.", "Administrators can save progress and optional-system choices. Other permitted viewers can browse steps without saving progress."],
    steps: [
      { id: "confirm-wizard-facility", title: "Confirm the facility and mode", instructions: ["On 1. Confirm facility, check Facility, License type, Enabled operations, and the mode message.", "Use Review facility settings or Review operating mode if needed. Change Facility in the shell, then return and choose Confirm context and continue."], expected: "Choose systems opens for the intended facility." },
      { id: "choose-wizard-systems", title: "Choose optional systems deliberately", instructions: ["On 2. Choose systems, read each provider's Required or Optional label and evidence.", "Use Skip optional followed by the provider name only for a service you're deferring. Include restores it. Required providers cannot be skipped."], expected: "Deferred providers show Optional skipped and required items retain their evidence-based states." },
      { id: "connect-wizard-systems", title: "Save connections in advanced settings", instructions: ["On 3. Connect, use Open advanced settings for the relevant provider and save its configuration there.", "Return using Resume Integration Wizard. The wizard doesn't display stored secrets or save credentials itself."], expected: "Returning or selecting Refresh evidence shows the latest recorded provider state." },
      { id: "validate-wizard-systems", title: "Run deliberate connection tests", instructions: ["On 4. Validate, select the available Test / Validate control for the intended provider.", "Read the test result, Environment, and Last validation. Success proves connectivity, not stock synchronization, invoice posting, or production acceptance."], expected: "The recorded validation outcome updates or a failure directs you to advanced settings." },
      { id: "review-wizard-mapping", title: "Review the mapping and operating workflow", instructions: ["On 5. Map, select the provider's Review mapping and workflow button.", "For traceability, check the trusted facility/license mapping. For accounting, review Item mappings and customer synchronization before invoice posting. The wizard doesn't post business records."], expected: "The actual mapping destination opens and you can identify any remaining Needs mapping evidence." },
      { id: "prove-wizard-readiness", title: "Resolve missing evidence", instructions: ["On 6. Prove ready, read environment, validation times, mapping requirements, and blockers.", "Select Refresh evidence after corrections. Next doesn't override missing evidence or make a blocked workflow ready."], expected: "Cards reflect observed evidence, including unresolved Blocked, Needs validation, or Needs mapping states." },
      { id: "review-wizard-summary", title: "Continue from summary to operational readiness", instructions: ["On 7. Readiness summary, inspect the required-item counts. Deferred optional services don't by themselves block go-live.", "Select Open Implementation Readiness for operational evidence and manual reviews. Connected here means the recorded connection and shown setup checks passed; sandbox validation isn't production acceptance."], expected: "Implementation Readiness opens with the remaining setup and operational evidence." }
    ], completion: ["Included providers have reviewed states, environments, validation times, and mapping requirements.", "Remaining required work is identified in Implementation Readiness."],
    troubleshooting: [{ symptom: "A provider remains incomplete after a passing test.", resolution: "Read its mapping and workflow evidence, resolve those requirements in the linked workspace, then Refresh evidence." }, { symptom: "A required provider can't be skipped.", resolution: "Confirm the facility capabilities and mode. If correct, finish the required evidence instead of bypassing it." }, { symptom: "Progress was not saved appears.", resolution: "Check the error and administrator access. Reviewers can browse locally but cannot save administrator progress." }],
    sourceFiles: ["frontend/src/pages/IntegrationWizardPage.tsx", "backend/app/routers/adoption.py", "backend/app/services/integration_wizard.py"]
  },
  "/help/settings/implementation": {
    title: "Review implementation readiness", category: "settings", summary: "Check facility evidence, save supported manual reviews, and create follow-up work for unresolved setup.", navPath: "Settings & Administration → Implementation Readiness", appPath: "/settings/implementation",
    beforeYouStart: ["Confirm the facility. Readiness derives from its records and setup evidence.", "Administrators can save reviews and create work items. Supporting notes are required for manual attestations.", "A configured credential alone doesn't verify an operating workflow."],
    steps: [
      { id: "read-readiness-evidence", title: "Read statuses with their supporting evidence", instructions: ["Open Implementation Readiness and read each card's label, status, and evidence.", "Notice Optional setup; not a required go-live blocker. Separate optional work from required evidence gaps."], expected: "You can identify the evidence behind each readiness state." },
      { id: "open-readiness-workspace", title: "Open the source of the missing evidence", instructions: ["Use the card's Open button, which includes its destination route, to inspect underlying records.", "For provider setup, use Start or resume Integration Wizard. Resolve the actual issue there and return to inspect the evidence."], expected: "The relevant operating or setup workspace opens." },
      { id: "assign-readiness-review", title: "Record the owner, date, and review notes", instructions: ["On an editable card, select Owner, set Target date if needed, and write Notes describing evidence or remaining work.", "Reassign an unavailable owner to an eligible person. Wizard provider cards are read-only here."], fields: [{ label: "Owner", requirement: "Optional.", guidance: "Choose the person responsible for the review or follow-up." }, { label: "Target date", requirement: "Optional.", guidance: "Set the intended review date, not a provider execution time." }, { label: "Notes", requirement: "Required for manual attestation; otherwise optional. Up to 4,000 characters.", guidance: "Record the evidence, reference, and remaining blocker.", example: "Reviewed the training receipt against its approved delivery document." }], expected: "The form holds the review details until Save review." },
      { id: "save-manual-review", title: "Save an evidence-supported attestation", instructions: ["Where Manual attestation is offered, select complete, incomplete, not applicable, or needs review. Use Use evidence / clear attestation to remove a manual override.", "Add supporting Notes and select Save review. Automatic evidence cannot be overridden by this form."], fields: [{ label: "Manual attestation", requirement: "Optional; available only on manual items.", guidance: "Choose the documented review outcome rather than marking untested work complete." }], expected: "Review saved. appears and the card refreshes." },
      { id: "create-readiness-task", title: "Turn unresolved follow-up into work", instructions: ["Select Create Doobie Work item. The linked task opens in Work Queue.", "Set its Assignee, Due time, and Priority separately. The readiness Owner and Target date aren't copied into the created task. Use Open Doobie Work item when one already exists."], expected: "The linked task is inspectable in Work Queue and subsequent visits offer Open Doobie Work item." },
      { id: "recheck-readiness-result", title: "Recheck after resolving the underlying work", instructions: ["Finish the actual setup or review and return to Implementation Readiness.", "Read the evidence again. Completing a linked task doesn't create missing records or satisfy an automatic evidence check by itself."], expected: "The checklist shows available evidence and saved reviews with unresolved items still identified." }
    ], completion: ["Review notes and intended owners or dates are saved.", "Outstanding follow-up has a linked task where needed, and automatic evidence gaps remain visible."],
    troubleshooting: [{ symptom: "A manual attestation is rejected.", resolution: "Provide supporting Notes and confirm the card allows Manual attestation. Automatic evidence must be resolved at its source." }, { symptom: "The linked task has no owner despite a readiness Owner.", resolution: "Open Doobie Work item and set its Assignee and Due time. The annotation and task assignment are separate saved fields." }],
    sourceFiles: ["frontend/src/pages/ImplementationReadinessPage.tsx", "backend/app/routers/adoption.py", "backend/app/services/implementation_readiness.py", "backend/app/services/integration_wizard.py"]
  },
  "/help/settings/location": {
    title: "Review Facility Setup and receiving defaults", category: "settings", summary: "Check the facility's provider context, load live structure on request, and distinguish previews from verified changes.", navPath: "Settings & Administration → Location", appPath: "/settings/location",
    beforeYouStart: ["Confirm Facility in the shell. This route is titled Facility Setup.", "Live Metrc reads require a saved, validated exact-facility connection and trusted license mapping.", "Provider changes require an authorized role and supported action for the active environment. Some actions remain preview-only."],
    steps: [
      { id: "review-facility-connection", title: "Check the license and environment", instructions: ["Open Location and read the facility beneath Facility Setup. Review jurisdiction, license, environment, and the Metrc facility connection message.", "For a linked sandbox site, Validate this sandbox facility is offered when appropriate. Switch sites with Facility in the shell instead of replacing licenses to move between sites."], expected: "The connection identifies the intended facility or explains why live reads aren't ready." },
      { id: "review-employee-permissions", title: "Check the Metrc employee identity", instructions: ["If employee permission introspection is needed, enter the actual Metrc employee license number and select Save employee identity.", "Choose Check Metrc permissions and read the result. Provider-reported facility capabilities describe availability, not independent authorization to write."], fields: [{ label: "Metrc employee license number", requirement: "Conditional; used for facility permission introspection.", guidance: "Use the authorized employee identity, not the facility license." }], expected: "Permission sync complete or Permission enforcement displays the current result and limits." },
      { id: "load-provider-structure", title: "Load the structure you need", instructions: ["Under Facility workspaces, open Rooms & Locations or the needed section and select Load from Metrc. After loading, the control becomes Refresh from Metrc.", "Review active and inactive records and any warnings. Opening Facility Setup doesn't automatically refresh all provider lists."], expected: "The selected section shows returned provider records or a specific error." },
      { id: "prepare-new-room", title: "Prepare a room change only when needed", instructions: ["In Rooms & Locations, check the loaded list for an existing room first.", "Enter New room / location, select Metrc location type, and choose Create room. This prepares Review Metrc change rather than proving the provider created a room."], fields: [{ label: "New room / location", requirement: "Required for Create room.", guidance: "Use the intended room name after checking for duplicates.", example: "Training Room 2" }, { label: "Metrc location type", requirement: "Required for Create room.", guidance: "Choose a returned provider type appropriate to the location." }, { label: "New sublocation", requirement: "Only for Review sublocation request.", guidance: "This separate request remains a preview where execution hasn't been supported." }], expected: "Review Metrc change shows the action, license, and business values." },
      { id: "confirm-provider-change", title: "Submit only a supported reviewed change", warning: "Confirm & submit to Metrc sends the prepared change. Check the exact facility and values first; don't blindly resubmit an uncertain result.", instructions: ["Read Review Metrc change and confirm name, location type, and target license. If execution isn't enabled, resolve the stated gate and keep the result as a preview.", "For a supported change, select Confirm & submit to Metrc once and wait for readback. Inspect every non-verified outcome before another action."], expected: "Verified in Metrc appears only after required verification, with the affected list refreshed; other outcomes retain their status and message." },
      { id: "choose-receiving-defaults", title: "Set local receiving defaults", instructions: ["Open the receiving section under Facility workspaces. Review Auto-map products during receive and Default receiving room.", "Auto-map reuses approved incoming-item to catalog-product mappings for this facility. It doesn't guess a new relationship. Enter the room your team actually uses."], fields: [{ label: "Auto-map products during receive", requirement: "Optional saved checkbox.", guidance: "Enable when approved facility mappings should be reused." }, { label: "Default receiving room", requirement: "Saved default; up to 160 characters.", guidance: "Use the intended receiving location name.", example: "Receiving" }], expected: "The controls hold the intended defaults pending save." },
      { id: "save-location-defaults", title: "Save and verify the defaults", instructions: ["Select Save location settings and wait for Receiving defaults saved.", "Reopen the section and check its values. Saving defaults doesn't create a provider room or receive a delivery."], expected: "Receiving defaults saved. appears and saved values remain in the controls." }
    ], completion: ["The facility, license, and environment are correct.", "Provider submissions have reviewed verification outcomes and local default changes have a separate save result."],
    troubleshooting: [{ symptom: "Live reads are blocked by validation or mapping.", resolution: "Validate the exact facility's connection in Integrations and resolve its trusted license mapping. Another site's connected credential isn't sufficient." }, { symptom: "An action offers only preview.", resolution: "Read its dispatch and verification message. Unproven actions remain preview-only; don't change action type or environment to bypass the gate." }, { symptom: "Submission is unverified or uncertain.", resolution: "Retain the visible status and transaction reference and inspect the affected record or reconciliation workflow with an authorized operator. Don't create the same room again just because success wasn't shown." }],
    sourceFiles: ["frontend/src/pages/LocationSettingsPage.tsx", "backend/app/routers/location_settings.py", "backend/app/routers/integrations.py", "frontend/src/components/AppShell.tsx"]
  },
  "/help/settings/integrations": {
    title: "Choose operating mode and validate connections", category: "settings", summary: "Save the intended facility connection, test it separately, and keep sandbox, production, and AI settings distinct.", navPath: "Settings & Administration → Traceability & Accounting Integrations", appPath: "/settings/integrations",
    beforeYouStart: ["Confirm the facility and provider account. Don't copy another site's connection to remove a blocker.", "Native credential changes require administrator access. AI and Spacemail configuration are DEV settings.", "DEV navigation uses AI, Traceability & Accounting Integrations. Stored secrets aren't returned as editable plaintext."],
    steps: [
      { id: "select-facility-mode", title: "Choose how the facility runs", instructions: ["At Choose how this facility runs, read the current mode and message. Use DoobieLogic Sandbox selects local alpha operation; Use Metrc Sandbox opts this facility into connected sandbox operation.", "Change mode only when it matches the intended setup. This choice is separate from Buyer data mode and from a native provider's Production environment."], expected: "The selected mode shows Active and the page reports LOCAL ALPHA or METRC SANDBOX." },
      { id: "save-metrc-connection", title: "Save the exact Metrc connection when needed", instructions: ["First check the intended connection environment. This METRC form has no Environment selector and currently saves production as the connection environment. If you need a sandbox connection, keep the existing validated facility connection and have the responsible administrator resolve setup through the approved sandbox workflow before resaving here.", "For an intended production connection, enter METRC State and METRC License / Facility, and enter METRC User API Key for first setup or deliberate replacement. A blank key retains a saved key. Select Save, then verify the environment in Facility Setup before testing or operating."], fields: [{ label: "METRC User API Key", requirement: "Required for new setup; blank retains a saved key.", guidance: "Enter the authorized user key only here, never in shared notes or screenshots." }, { label: "METRC State", requirement: "Required for the connection.", guidance: "Use the supported jurisdiction or endpoint for this facility.", example: "MA" }, { label: "METRC License / Facility", requirement: "Required for the intended connection.", guidance: "Enter the exact provider license, not an internal display name." }], expected: "The card updates saved configuration and status; this alone doesn't prove connectivity." },
      { id: "test-saved-connection", title: "Test the saved provider and read its evidence", instructions: ["Select Test Connection on the saved card. Read the result, Status, Last validated, and any last error.", "Check facility mapping and environment through Integration Wizard or Facility Setup before operating. Validation doesn't itself synchronize stock, send transfers, or finish regulated actions."], expected: "The card shows a recorded validation outcome and time, or a concrete failure." },
      { id: "save-biotrack-connection", title: "Configure BioTrack only when it belongs to this setup", instructions: ["Under State & Accounting Connections, enter the approved BioTrack endpoint and facility and choose Environment deliberately.", "Username and Password are required on the first save; blank values later retain credentials. Use the approved Login Path. Choose Save, then Test Connection, and read whether validation represents training or live access."], fields: [{ label: "BioTrack API Base URL", requirement: "Required for BioTrack setup.", guidance: "Use the state-approved HTTPS endpoint." }, { label: "License / Facility", requirement: "Required.", guidance: "Use the exact licensed facility identifier." }, { label: "Environment", requirement: "Required; defaults to Sandbox / training.", guidance: "Choose only the authorized environment." }, { label: "Username", requirement: "Required on first save.", guidance: "Use the provider username; blank retains a saved value." }, { label: "Password", requirement: "Required on first save.", guidance: "Enter the provider password only in this password control." }, { label: "Login Path", requirement: "Required, with a default.", guidance: "Use the approved provider contract's path rather than guessing." }, { label: "I confirm this facility has approved BioTrack production API access.", requirement: "Required only for Production.", guidance: "Confirm only when that approval is in place." }], expected: "The card shows saved scope and a separately recorded validation outcome." },
      { id: "save-accounting-connection", title: "Connect the intended QuickBooks company", instructions: ["Enter Company Realm ID and choose Environment. Client ID, Client Secret, and Refresh Token are required on first save; blank values later keep stored credentials.", "Leave API Base URL Override blank for normal endpoints. For Production, check the company and its explicit confirmation, then Save and Test Connection.", "Review Item mappings and customer synchronization through Integration Wizard before invoice posting. A company test doesn't post accounting records."], fields: [{ label: "Company Realm ID", requirement: "Required for QuickBooks setup.", guidance: "Use the intended company identifier." }, { label: "Environment", requirement: "Required; defaults to Sandbox.", guidance: "Match the authorized company environment." }, { label: "Client ID", requirement: "Required on first save.", guidance: "Use the authorized integration client identity." }, { label: "Client Secret", requirement: "Required on first save.", guidance: "Enter only in its password field." }, { label: "Refresh Token", requirement: "Required on first save.", guidance: "Use the authorized company's token without copying it into notes." }, { label: "API Base URL Override", requirement: "Optional.", guidance: "Leave blank unless an approved override is supplied for the installation." }, { label: "I confirm this is the production QuickBooks company connection.", requirement: "Required only for Production.", guidance: "Check the company before confirming." }], expected: "The card reports validation for the saved company, with mapping work reviewed separately." },
      { id: "validate-ai-runtime", title: "Have the DEV operator validate AI routing when needed", instructions: ["For DEV setup, open DoobieLogic Local AI Runtime and enter the configured endpoint and model. Review embedding settings and provider routing before saving.", "Choose Local first or Local only in Provider Mode, check Provider Order and the cloud-fallback policy, then Save and Test Connection. Read the embedding availability and knowledge document count.", "Regular operators should report missing AI runtime access to the responsible DEV operator."], fields: [{ label: "Local AI Endpoint", requirement: "Required for runtime setup.", guidance: "Use the approved inference service endpoint." }, { label: "Local AI Model", requirement: "Required.", guidance: "Use the model name actually served at that endpoint." }, { label: "Local Endpoint API Key", requirement: "Conditional on endpoint authentication.", guidance: "Use an authorized key when required; blank retains a saved value." }, { label: "Embedding Endpoint", requirement: "Optional.", guidance: "Blank reuses the local AI endpoint." }, { label: "Embedding Model", requirement: "Conditional on embedding setup.", guidance: "Use the configured embedding model, not the chat model by assumption." }, { label: "Provider Mode", requirement: "Required routing choice.", guidance: "Choose Local first or Local only for the approved policy." }, { label: "Provider Order", requirement: "Routing configuration.", guidance: "Keep the intended provider priority order for this installation." }, { label: "Allow cloud fallback when objective routing/validation requires it", requirement: "Optional saved policy choice.", guidance: "Enable only when approved for this AI setup." }], expected: "The test reports runtime, embedding, and knowledge status without changing business records." },
      { id: "check-integration-readiness", title: "Return to the wizard and review remaining work", instructions: ["Select Resume Integration Wizard and Refresh evidence after saving or testing providers.", "Read remaining mapping and workflow blockers. Clear / Reset removes that card's saved connection; it isn't the normal retry for a failed test."], expected: "The wizard reflects current provider evidence and distinguishes optional services from required work." }
    ], completion: ["The intended facility mode and provider environment are visible.", "Configured connections have separately reviewed test results and any remaining mapping work is identified."],
    troubleshooting: [{ symptom: "A saved connection isn't ready.", resolution: "Run Test Connection and inspect its result and Last validated. Then review mapping and workflow evidence in Integration Wizard." }, { symptom: "AI or Spacemail controls aren't present.", resolution: "These are DEV settings. Ask the responsible DEV operator to review them; ordinary integration access doesn't include those settings." }, { symptom: "A native provider rejects first save.", resolution: "Check required initial credentials and the intended environment. Production requires its explicit confirmation. Don't switch environment merely to obtain a successful save." }],
    sourceFiles: ["frontend/src/pages/IntegrationsPage.tsx", "frontend/src/components/KnowledgeLibraryCard.tsx", "frontend/src/components/CultivationConnections.tsx", "frontend/src/components/AppShell.tsx", "backend/app/routers/integrations.py", "backend/app/routers/native_integrations.py"]
  },
  "/help/doobie-agent": {
    title: "Ask Doobie Agent and inspect its evidence", category: "intelligence", summary: "Ask from the current workspace, review sources and freshness, and distinguish previews from applied actions.", navPath: "App shell → Doobie Agent", appPath: "/doobie",
    beforeYouStart: ["Open the intended facility and workspace before launching the Agent.", "A configured provider is required. Server checks still control eligible operational actions and permissions.", "The /doobie route opens Action Center; conversation lives in the persistent Doobie Agent window in the shell."],
    steps: [
      { id: "open-doobie-window", title: "Open the Agent in the right context", instructions: ["Use Open Doobie Agent in the shell. You can keep working behind the window.", "Read the specialist name, description, focus, and provider line. The initial specialist follows the current operation and workspace."], expected: "The window shows the specialist and local or cloud provider status." },
      { id: "choose-specialist-question", title: "Choose a specialist and write a specific request", instructions: ["Use Specialist if a different offered specialist fits. Selecting a suggested question fills the question box without running it.", "In the Ask field labeled with the specialist's name, identify the relevant record, period, and outcome. Requests can be up to 8,000 characters. Keep passwords and API keys out of chat."], fields: [{ label: "Specialist", requirement: "Required selection with a contextual default.", guidance: "Choose the specialist whose described focus matches the job." }], expected: "The question box contains the intended request and Run agent is available when the provider is configured." },
      { id: "run-agent-request", title: "Run the question and read warnings", instructions: ["Select Run agent once and wait for the response.", "Read Missing data and Warnings before relying on the answer. If fallback was used, inspect the named provider and reason. An explanation can't supply missing operational records."], expected: "The question and answer appear with any missing-data or fallback notices." },
      { id: "inspect-agent-sources", title: "Check Sources and Data freshness", instructions: ["Read source titles, sections, types, and authority information in Sources. Check Data freshness for the age of supporting information.", "For compliance questions, verify jurisdiction, medical or adult-use scope, and current source material in Compliance Q&A. The Agent window doesn't always display a complete source URL or legal review status."], expected: "You can identify the evidence actually shown and any gaps requiring source review." },
      { id: "inspect-agent-actions", title: "Distinguish Previewed from Applied", warning: "An explicit request can apply a supported operational action when permission and preflight checks allow it. Ask for a preview first when you need to review the effect.", instructions: ["When intentionally requesting an action, read Operational actions. Previewed means it wasn't applied; Applied means the returned result reports a change. For scheduling, check the date range and scheduled and blocked counts.", "Verify the saved result in its destination workspace. An answer or Action applied badge doesn't prove external provider acceptance of a regulated transaction."], expected: "The action result distinguishes preview from application and the destination supplies the operational check." },
      { id: "review-queued-agent-action", title: "Review queued actions in Action Center", instructions: ["Open /doobie when you need Action Center. Select the intended row under EMPLOYEE APPROVAL QUEUE and inspect its full Preview and Execution payload before selecting Approve preview.", "Approval and execution are separate. Execute approved action or Submit approved regulatory action is only for the reviewed supported action. Reject declines a proposal. Resolve provider acceptance and reconciliation in the relevant workflow before considering regulated work complete."], expected: "Action Center shows the actual proposal state, distinct from provider verification." },
      { id: "clear-agent-conversation", title: "Manage the session conversation", instructions: ["Use Clear conversation to remove this specialist's current conversation from browser session storage.", "The window retains the latest 20 messages per organization, facility, and specialist in the session. Clearing chat doesn't undo an operation or erase its business record."], expected: "The conversation clears while operational records remain available." }
    ], completion: ["You have reviewed the answer's evidence, freshness, missing data, and warnings.", "Requested actions have been checked as Previewed or Applied and verified in the destination."],
    troubleshooting: [{ symptom: "Run agent is disabled or the provider is deterministic_only.", resolution: "Check the question isn't blank and no run is pending. Use Open AI integrations or ask the DEV operator to validate the runtime if no provider is configured." }, { symptom: "The answer has the wrong context or lacks records.", resolution: "Check Facility, Operation, workspace, and Specialist. Verify the underlying data is available before asking again." }, { symptom: "An action is denied or blocked.", resolution: "Read the warning and check the destination's permissions and prerequisites. Don't rephrase to evade a guard or repeat a write whose outcome is uncertain." }],
    sourceFiles: ["frontend/src/components/WorkspaceAgent.tsx", "frontend/src/components/WorkspaceWindow.tsx", "frontend/src/pages/DoobiePage.tsx", "backend/app/routers/ai_agents.py", "backend/app/routers/doobie.py", "frontend/src/lib/workspaceRoutes.ts"]
  },
  "/help/home/control-towers": {
    title: "Review Operations and Enterprise Control Towers", category: "home", summary: "Find facility exceptions, inspect their supporting records, and use the organization view to prioritize sites.", navPath: "Home → Operations Control Tower", appPath: "/home/control-tower",
    beforeYouStart: ["Confirm the facility. Operations Control Tower reviews that site; Enterprise Control Tower is the administrator's organization-wide view.", "Provider readiness and local action state are separate signals. An empty exception table isn't provider reconciliation evidence."],
    steps: [
      { id: "read-tower-overview", title: "Start with Overview", instructions: ["Open Operations Control Tower and select Overview. Read exception summaries and provider readiness with the operating metrics.", "Read an exception's explanation before using its action. The control opens a tab or workspace; it doesn't resolve the exception itself."], expected: "You can identify an issue and the destination holding its details." },
      { id: "inspect-action-queue", title: "Inspect Action Center before deciding", instructions: ["Select Action Center and compare Status, Risk, Action, Impact, and Preview.", "Long previews are shortened in this table. If any detail is hidden, open /doobie for the full Preview and Execution payload before approval."], expected: "The queue displays recorded action states or says no actions await review." },
      { id: "decide-reviewed-action", title: "Approve and execute only a complete reviewed change", warning: "Execute applies the approved action through its service. Check the complete intended change and facility first. Don't blindly retry uncertain writes.", instructions: ["Use Approve for a fully reviewed proposal. Execute appears for approved actions. Use Reject if the action shouldn't proceed.", "Inspect the refreshed Status after each decision and verify the affected workspace. Provider changes still require their own acceptance and reconciliation checks."], expected: "The queue refreshes to the resulting state, keeping approval separate from execution." },
      { id: "inspect-label-sop", title: "Inspect label and procedure signals", instructions: ["Open LabelGuard to review label content against an active facility rule set or the limited Generic completeness check.", "Open SOP Control for Active procedures and Open deviations. Creating a procedure version immediately activates it, so use the dedicated walkthrough before changing the library."], expected: "The selected tab shows review controls or recorded procedures and deviations." },
      { id: "inspect-cost-telemetry", title: "Check cost assumptions and machine freshness", instructions: ["In Profitability, compare Retail, Wholesale, Total revenue, COGS, Margin, and Production cost/unit. Missing production cost isn't a verified zero cost.", "In Machines, inspect State, Last seen, Faults, Downtime, Cycles, and Measurements. The view requests a 24-hour window; an old Last seen needs investigation before assuming present equipment health."], expected: "You can identify product costs or machine evidence requiring follow-up." },
      { id: "compare-enterprise-facilities", title: "Compare sites in Enterprise Control Tower", instructions: ["From Home, open Enterprise Control Tower when available. Review Facilities, Inventory value, Open A/R, Reconciliation, and Ranked by operational risk.", "Check each row's license and capabilities. Inventory value uses positive on-hand at standard unit cost. Risk ranking prioritizes review rather than authorizing changes."], expected: "The organization view shows facility totals and risk-ranked rows." },
      { id: "switch-before-followup", title: "Select the target facility before following up", instructions: ["Choose the intended Facility in Access Context before opening its work. Enterprise table rows aren't facility-switch buttons.", "Use Facility Control Tower to return and confirm the shell context before acting."], expected: "The facility view matches the site whose issue you intend to handle." }
    ], completion: ["A specific exception and its underlying record or workspace are identified.", "Decisions have reviewed states and cross-facility follow-up is in the correct context."],
    troubleshooting: [{ symptom: "An action preview is cut off.", resolution: "Open the Action Center at /doobie and inspect the full Preview and Execution payload. Don't infer hidden values." }, { symptom: "Enterprise Control Tower isn't offered.", resolution: "Navigation is limited to admin and dev roles. Use your facility view or ask an administrator for the organization review." }, { symptom: "Machine information is stale or absent.", resolution: "Check Last seen and configured facility machines. Received telemetry doesn't prove a live equipment poll has occurred." }],
    sourceFiles: ["frontend/src/pages/OperationsControlTowerPage.tsx", "frontend/src/pages/EnterpriseControlPage.tsx", "frontend/src/pages/DoobiePage.tsx", "frontend/src/components/AppShell.tsx", "backend/app/routers/control_tower.py", "backend/app/routers/enterprise_control.py"]
  },
  "/help/home/labelguard": {
    title: "Review label completeness with LabelGuard", category: "home", summary: "Check supplied label text against a reviewed rule set without mistaking generic completeness for legal approval.", navPath: "Home → Operations Control Tower → LabelGuard", appPath: "/home/control-tower",
    beforeYouStart: ["Have the actual proposed label text and intended facility context.", "Use an active reviewed facility rule set when available. Generic completeness check only checks populated fields and isn't jurisdiction law."],
    steps: [
      { id: "choose-label-rules", title: "Choose the review's rule set", instructions: ["Open Operations Control Tower, then LabelGuard. Choose the intended active template in Rule set.", "Check its displayed version and jurisdiction. If you choose Generic completeness check, keep the result within that limited scope."], fields: [{ label: "Rule set", requirement: "Required selection; defaults to Generic completeness check.", guidance: "Choose the appropriate active reviewed template when available." }], expected: "The selection identifies the basis for the upcoming review." },
      { id: "enter-label-identity", title: "Enter identity and contents as printed", instructions: ["Enter Product name and Net contents from the proposed label, including the quantity unit.", "Enter License number from that label. These inputs don't edit the facility connection or its license mapping."], fields: [{ label: "Product name", requirement: "Required by the generic completeness check.", guidance: "Use the printed identity.", example: "Training Flower" }, { label: "Net contents", requirement: "Required by the generic completeness check.", guidance: "Include printed quantity and unit.", example: "3.5 g" }, { label: "License number", requirement: "Missing value gives a warning in generic rules; template rules can differ.", guidance: "Use the license printed on the label under review." }], expected: "The form holds the proposed identity and contents without submitting a review." },
      { id: "enter-label-warning", title: "Supply the actual warning and full text", instructions: ["Copy Warning text and, if available, Extracted / printed label text from the label.", "Compare extracted text with the original. Don't invent wording just to satisfy a completeness test; use reviewed source material and approved content."], fields: [{ label: "Warning text", requirement: "Missing value gives a warning in generic rules; template rules can differ.", guidance: "Copy the exact warning being reviewed." }, { label: "Extracted / printed label text", requirement: "Optional review input.", guidance: "Paste the actual text and correct extraction mistakes." }], expected: "The input matches the label you intend to assess." },
      { id: "run-labelguard-review", title: "Run the review and inspect every finding", instructions: ["Select Run LabelGuard and wait for Findings.", "Read every pass, warning, or fail message, any source supplied, and the disclaimer. A generic pass doesn't establish legal compliance or release a package."], expected: "Findings shows the recorded review status and individual findings, or an error." },
      { id: "resolve-label-findings", title: "Correct the real label before reviewing again", instructions: ["Resolve content issues in the label authoring workflow, then update these fields to match the revised label.", "Run LabelGuard again and inspect the new findings. Use Label Studio and the required compliance review for final generation or release decisions."], expected: "The latest Findings corresponds to the revised submitted text." }
    ], completion: ["The findings and disclaimer have been reviewed against the selected rules.", "Unresolved warnings or failures are identified for correction in the actual label workflow."],
    troubleshooting: [{ symptom: "No facility rule set is available.", resolution: "Only active templates appear. Ask the responsible compliance operator to review approved templates; generic checking remains limited to completeness." }, { symptom: "A generic pass doesn't resolve concern about warning wording.", resolution: "Populated text can pass completeness without validating wording. Compare it with reviewed jurisdiction-specific sources and approved facility rules." }],
    sourceFiles: ["frontend/src/pages/OperationsControlTowerPage.tsx", "backend/app/routers/control_tower.py"]
  },
  "/help/home/sop-control": {
    title: "Review procedures and activate an SOP version", category: "home", summary: "Inspect the procedure library and deviations, then activate an approved version with its source reference.", navPath: "Home → Operations Control Tower → SOP Control", appPath: "/home/control-tower",
    beforeYouStart: ["Creating SOP versions requires dev, admin, or qa access.", "Have approved procedure text and its reference. This form creates an active version, not an unapproved draft.", "This form doesn't offer a facility-only scope selector. Its saved procedure defaults to organization-wide scope, so confirm that scope is intended."],
    steps: [
      { id: "inspect-active-procedures", title: "Check the procedure library first", instructions: ["Open Operations Control Tower, then SOP Control. Read Active procedures, including SOP, Version, Status, and Effective.", "Find the code you intend to use before adding a version so you understand the existing procedure."], expected: "Recorded versions appear, or No SOPs are loaded yet is shown." },
      { id: "inspect-sop-deviations", title: "Read deviations that need follow-up", instructions: ["Read Open deviations and note severity, rule key, and explanation or affected record reference.", "Investigate that record in its operating workspace. No open deviations are recorded doesn't prove every written instruction has an automated check."], expected: "You can identify the rule or record needing follow-up." },
      { id: "identify-approved-sop", title: "Identify the approved procedure", instructions: ["Under Add controlled SOP, enter Code and Title from the approved procedure.", "Supply Source / approved document reference so the team can locate the intended revision."], fields: [{ label: "Code", requirement: "Required for creation.", guidance: "Use the approved procedure identifier.", example: "SOP-TRAIN-001" }, { label: "Title", requirement: "Required for creation.", guidance: "Use a recognizable procedure title.", example: "Training receiving review" }, { label: "Source / approved document reference", requirement: "Optional input; provide for traceable review.", guidance: "Identify the approved document and revision without credentials." }], expected: "The unsaved form identifies the procedure and reference." },
      { id: "enter-approved-sop", title: "Enter and compare the approved text", instructions: ["Enter Procedure and compare it against the referenced approved document.", "This form doesn't expose required-role or automatic-control-rule inputs. The text alone doesn't create automated enforcement of every instruction."], fields: [{ label: "Procedure", requirement: "Procedure content input.", guidance: "Supply the approved operating instructions for the version." }], expected: "The form contains the content you intend to activate." },
      { id: "activate-approved-sop", title: "Create and activate the version", warning: "Create & activate version immediately saves an active organization-wide procedure version from this form. Confirm approval and scope before submitting.", instructions: ["Recheck code, title, reference, text, and intended organization scope, then select Create & activate version once.", "Wait for the list to refresh and inspect Version and Status. After a failure or uncertain response, inspect the library before submitting another version."], expected: "The procedure list reflects the saved version and state, or a form error explains the failure." }
    ], completion: ["The list shows the intended saved version and state.", "Open deviations have been identified separately rather than assumed resolved by adding procedure text."],
    troubleshooting: [{ symptom: "Create & activate version is disabled or denied.", resolution: "Complete Code and Title and wait for pending work. A server denial requires the appropriate dev, admin, or qa role; don't substitute a broader identity." }, { symptom: "A new procedure doesn't resolve existing deviations.", resolution: "Inspect each deviation and its affected operation. Activating text doesn't correct records or automatically create all required controls." }],
    sourceFiles: ["frontend/src/pages/OperationsControlTowerPage.tsx", "backend/app/routers/control_tower.py"]
  },
};
