import type { HelpWalkthroughRegistry } from "./types";

export const wholesaleWalkthroughs: HelpWalkthroughRegistry = {
  "/help/wholesale": {
    title: "Wholesale Ops overview",
    category: "wholesale",
    summary: "Find the next wholesale handoff, from a customer request through inventory, shipping, invoicing, and collection.",
    navPath: "Wholesale Ops → Overview",
    appPath: "/wholesale",
    beforeYouStart: [
      "Check that you're working in the intended facility. The wholesale workspace reads that facility's commercial and inventory records.",
      "Have the order number or customer name ready when investigating a handoff. Overview opens the relevant tab, but doesn't automatically select the row there.",
      "A submitted storefront request hasn't reserved stock. Approval creates a draft sales order; confirmation, allocation, and shipment are separate steps."
    ],
    steps: [
      { id: "open-wholesale-overview", title: "Open the wholesale summary", instructions: ["Open Wholesale Ops and select Overview.", "Read Sellable lots, Open sales orders, Storefront approvals, and Fill rate together. Available to sell is a summary across lots; use Inventory to check each lot's unit before promising a quantity."], expected: "The summary cards and Pending Storefront Orders section appear, or a specific loading or error message identifies data that hasn't loaded." },
      { id: "review-waiting-storefront-requests", title: "Find requests waiting for a decision", instructions: ["In Pending Storefront Orders, check Customer, Contact, License, Items, Estimated total, and Submitted.", "Choose Review order or Review approvals to open Storefront. The overview shows up to eight requests, so use the inbox for the full loaded list.", "Review the buyer and requested items in that inbox before approving anything. A supplied license isn't proof of external verification."], expected: "Storefront opens with the Approval & fulfillment inbox, where submitted requests can be reviewed." },
      { id: "follow-order-to-cash-stage", title: "Follow the next order handoff", instructions: ["In ORDER-TO-CASH PIPELINE, find the order and read Stage, Inventory handoff, Finance, and Next action.", "Compare allocated and remaining quantities. An allocation isn't a posted shipment, and an invoice balance isn't the same as the order's fulfillment status.", "Choose Open for that row. Confirm order and Allocate inventory lead to Orders; invoice and A/R stages lead to Accounting; other shipping stages lead to Fulfillment. Select the matching order after arriving."], expected: "The relevant tab opens. You can match the order number to the handoff shown on Overview." },
      { id: "inspect-wholesale-exceptions", title: "Work the named exception", instructions: ["Read Order-to-cash exceptions, including the message and Next action, before choosing Open.", "For QA hold or Manifest, follow the inventory or manifest review process rather than forcing a shipment. For Customer A/R or Invoice / A/R, check Accounting. For Low margin, review the order price and cost assumptions in Orders.", "Treat the displayed margin as an estimate based on current product cost, not a finalized accounting result."], expected: "You have a specific order, exception, and next workspace to investigate." },
      { id: "choose-wholesale-workspace", title: "Open the workspace for the job", instructions: ["Use Review inventory to inspect sellable lots, Work orders to create or confirm demand, and Open fulfillment to scan and ship.", "Use Customers for account history and follow-ups, Pipeline for sales opportunities, and Logistics for physical delivery runs.", "Return to Overview after completing a handoff and allow the refreshed data to load. The storefront queue and order-to-cash checks refresh periodically while Overview is open."], expected: "The refreshed order or exception reflects the saved source records when the next snapshot loads." }
    ],
    completion: ["You can identify the next action for the order from its Stage or exception message.", "The destination workspace shows the intended order or customer before you make a change."],
    troubleshooting: [
      { symptom: "A summary card looks empty or shows a dash.", resolution: "Wait for loading to finish and read any section-specific error. Don't interpret missing inventory or intelligence data as zero. Reopen the workspace after the connection recovers and verify the underlying Inventory or Orders view." },
      { symptom: "Open takes me to a tab but not the order.", resolution: "This control selects the destination tab only. Keep the order number from Overview and choose it in Open order or the warehouse queue. The pipeline displays up to 20 rows and exceptions up to 12, so absence from these summaries isn't proof that an order is closed." }
    ],
    sourceFiles: ["frontend/src/App.tsx", "frontend/src/lib/workspaceRoutes.ts", "frontend/src/pages/WholesaleOpsPage.tsx", "frontend/src/components/WholesaleRegulatoryHealth.tsx", "frontend/src/components/ManifestDraftControl.tsx", "backend/app/routers/storefronts.py", "modules/commerce_storefronts/wholesale_service.py", "modules/commerce_storefronts/intelligence.py"]
  },
  "/help/wholesale/inventory": {
    title: "Check wholesale inventory before committing stock",
    category: "wholesale",
    summary: "Find a product, compare on-hand stock with commitments, and understand why a lot is blocked from wholesale.",
    navPath: "Wholesale Ops → Inventory",
    appPath: "/wholesale",
    beforeYouStart: ["Open the intended facility before checking availability.", "Know the product, package, lot, or COA reference you're investigating. This page is a read-only view; it doesn't release QA holds or reserve stock.", "Wholesale eligibility requires released or available inventory, a passed COA reference, and positive quantity after commitments."],
    steps: [
      { id: "open-wholesale-inventory", title: "Open Inventory", instructions: ["Open Wholesale Ops, then choose Inventory.", "Read the SELLABILITY POLICY above the table. The list is drawn from existing production inventory; it isn't a separate stock count."], expected: "The inventory table shows Type, Product, Package / Lot, COA, Available, Reserved, Sellable, Location, and Status." },
      { id: "filter-wholesale-lots", title: "Narrow the list to the stock you need", instructions: ["Choose All, Bulk, or Retail Ready for the kind of stock you're checking.", "Enter a product, package, lot, COA, or location in Search. Clear Search and return to All if you need to widen the results."], fields: [{ label: "Search", requirement: "Optional filter.", guidance: "Use a known product name or identifying code, rather than a customer or sales-order number.", example: "DEMO-LOT-042" }], expected: "Only rows matching the selected type and search remain, or No inventory matches this wholesale view appears." },
      { id: "read-lot-quantities", title: "Compare available, reserved, and sellable quantities", instructions: ["Match Package / Lot and Product before reading quantities. A product can have more than one lot.", "Read Available as the lot's on-hand quantity, Reserved as commitments, and Sellable as the quantity left to offer. Keep the unit printed beside each number with your notes.", "Check Location before handing the lot to a picker. A blank location needs follow-up; it isn't an instruction to pick from any bin."], expected: "You have identified the exact lot, its unit, its commitments, and its remaining sellable quantity." },
      { id: "inspect-blocked-wholesale-stock", title: "Show the lots that aren't sellable", instructions: ["Select Show blocked inventory to include excluded lots.", "Check COA for Missing or a lab state that hasn't passed. On desktop, point at Blocked to read the recorded reasons.", "Take the lot code and reason to the person responsible for QA release or inventory commitments. Selecting this checkbox doesn't make a blocked lot orderable."], fields: [{ label: "Show blocked inventory", requirement: "Optional inspection control.", guidance: "Turn it on when a known lot is missing from the sellable list." }], expected: "Blocked rows appear alongside eligible rows when they match the current filters." },
      { id: "handoff-verified-stock", title: "Carry the verified lot into the order workflow", instructions: ["After any QA or inventory correction, reload this view and recheck the lot. Don't rely on the earlier quantity if another order may have reserved stock.", "Open Orders to confirm and reserve against the order, or Fulfillment to capture the physical lot identifier. The server checks availability again when the reservation is saved."], expected: "The lot is visible as Sellable before you attempt its reservation in the order workflow." }
    ],
    completion: ["The intended Package / Lot is shown with its COA, unit, Location, and Sellable quantity.", "Any excluded lot has been identified for correction without changing its eligibility from this screen."],
    troubleshooting: [
      { symptom: "A lot exists in production but doesn't appear here.", resolution: "Select All, clear Search, and enable Show blocked inventory. Check the active facility and the lot's COA, release status, and commitments. Correct the source record through its normal workflow, then reload Inventory." },
      { symptom: "Available is positive but Sellable is zero.", resolution: "Check Reserved and the Blocked reason. Existing production or wholesale commitments can consume the quantity, and a QA or COA restriction can prevent sale. Don't use Available alone to promise or reserve stock." },
      { symptom: "I can't read the Blocked explanation on my phone.", resolution: "The current table exposes the detailed reason as a hover tooltip. Use a desktop pointer to inspect it, or use the lot's COA and inventory record to investigate. Don't assume the reason from the quantity alone." }
    ],
    sourceFiles: ["frontend/src/pages/WholesaleOpsPage.tsx", "backend/app/routers/storefronts.py", "modules/commerce_storefronts/wholesale_service.py", "modules/inventory_availability/service.py", "modules/commercial/repository.py"]
  },
  "/help/wholesale/orders": {
    title: "Create, confirm, and reserve a wholesale order",
    category: "wholesale",
    summary: "Build a sales-order draft, confirm its terms, reserve the right lot, and verify fulfillment separately from payment.",
    navPath: "Wholesale Ops → Orders",
    appPath: "/wholesale/orders",
    beforeYouStart: ["Check the facility name in Orders. Products and the appropriate customer trade partner must already exist.", "Have agreed quantities, units, prices, due date, and customer reference ready. New Order initially uses product cost as its suggested Unit Price; review it as a selling price before saving.", "An approved storefront request or converted CRM quote already creates a draft sales order. Find that order first so you don't duplicate it."],
    steps: [
      { id: "find-existing-sales-order", title: "Check whether the order already exists", instructions: ["Open Orders and select Command Center. Use Search orders with the order number, partner, reference, or status.", "Review Outgoing sales orders before creating another order. Open statuses include Draft, Confirmed, Allocated, and Partially Fulfilled.", "If the order already exists, go to Allocate & Fulfill and choose it in Open order. Otherwise, select New Order."], fields: [{ label: "Search orders", requirement: "Optional filter.", guidance: "Search using the customer's reference or a known order number.", example: "DEMO-PO-104" }], expected: "You have either located the existing order or opened Create an order for a new draft." },
      { id: "enter-sales-order-header", title: "Enter the customer and order dates", instructions: ["Set Order type to Sales and select the intended Customer. Only Customer and Both trade partners are eligible for sales orders.", "Replace or complete the suggested Order number with a distinct reference. Set Order date and Due date, then enter the customer's reference if there is one.", "If no eligible customer appears, create the partner in Trade Partners with Relationship set to Customer or Both before returning."], fields: [
        { label: "Order type", requirement: "Required selection.", guidance: "Choose Sales for outbound customer demand; Purchase is the vendor receiving workflow." },
        { label: "Customer", requirement: "Required for a sales order.", guidance: "Choose the agreed buying business, not a similar name." },
        { label: "Order number", requirement: "Required.", guidance: "Use your order-number convention and check for an existing order first.", example: "SO-DEMO-104" },
        { label: "Order date", requirement: "Required date.", guidance: "Use the date the order is recorded." },
        { label: "Due date", requirement: "Optional date; the form supplies a suggested date.", guidance: "Review the suggestion against the agreed delivery schedule." },
        { label: "External reference", requirement: "Optional.", guidance: "Use the customer's PO or other agreed reference. Entering a reference doesn't submit anything to Metrc.", example: "DEMO-PO-104" }
      ], expected: "The header identifies the intended customer and order, with the dates you reviewed." },
      { id: "enter-sales-order-lines", title: "Build the product lines and review selling prices", instructions: ["Choose Product on each row, enter Quantity, and review Unit Price. Changing Product resets its suggested price to that product's cost.", "Quantities are stored in the selected product's base unit. Verify that unit from the product or inventory record before entering a case count or weight.", "Use Add row for another product and Remove for an unwanted row. Add Line notes and Order notes where the next operator needs context."], fields: [
        { label: "Product", requirement: "Required on every line.", guidance: "Choose an active product using both its SKU and name." },
        { label: "Quantity", requirement: "Required and greater than zero.", guidance: "Enter the ordered quantity in the product's base unit.", example: "24" },
        { label: "Unit Price", requirement: "Required numeric value; cannot be negative.", guidance: "Enter the agreed price per base unit. The initial cost value isn't an agreed customer price.", example: "12.50" },
        { label: "Line notes", requirement: "Optional.", guidance: "Record instructions specific to this item." },
        { label: "Order notes", requirement: "Optional.", guidance: "Record shipping requirements, terms, or internal handoff details." }
      ], expected: "At least one product row has the intended quantity and selling price." },
      { id: "save-sales-order-draft", title: "Save the draft and reopen it", instructions: ["Choose Create draft order once and wait for the created-as-a-draft message.", "Open Allocate & Fulfill and select the saved order in Open order. Check Ordered, Fulfilled, Remaining, Unit, and Price against the agreement.", "A draft records demand but doesn't confirm it, reserve a lot, ship stock, or create an invoice."], expected: "Open order shows the saved order as Draft and its line table matches the intended quantities and units." },
      { id: "confirm-sales-order", title: "Confirm the reviewed order", instructions: ["After checking the customer and line details, choose Confirm order.", "Wait for the status to change. Confirmation unlocks the allocation controls, but stock hasn't been reserved yet."], expected: "The order is Confirmed and Line to process, Inventory lot, and Quantity are available." },
      { id: "reserve-order-lot", title: "Reserve the lot for the selected line", instructions: ["Choose Line to process, then the matching Inventory lot. Check its identity and on-hand unit, along with the line's remaining quantity.", "Enter only the amount to reserve from this lot and choose Reserve lot. Repeat for other lots or lines only after checking the updated quantities.", "Read the currently reserved amount beneath the buttons. The service checks remaining demand and stock already claimed by other work."], fields: [
        { label: "Open order", requirement: "Required selection.", guidance: "Match the order number and current status before executing anything." },
        { label: "Line to process", requirement: "Required selection.", guidance: "Choose the product line still awaiting fulfillment." },
        { label: "Inventory lot", requirement: "Required selection.", guidance: "Choose the released lot belonging to that product and facility." },
        { label: "Quantity", requirement: "Required and positive.", guidance: "Use the line's unit and stay within both remaining demand and uncommitted stock." },
        { label: "Fulfillment reference", requirement: "Optional reference supplied by the form.", guidance: "Keep a useful order or shipment reference for the inventory movement.", example: "SO-DEMO-104" }
      ], expected: "Inventory reserved appears and the selected lot's currently reserved quantity reflects the saved allocation." },
      { id: "post-and-verify-sales-fulfillment", title: "Post only the quantity physically ready to leave", warning: "Post shipment writes an outbound inventory movement and increases fulfilled quantity. Check the lot, reservation, quantity, and manifest before selecting it. Don't click again after an uncertain response until you've checked the ledger.", instructions: ["Use the Fulfillment tab for the scan-and-verify workflow, or Post shipment here after the required reservation and shipment checks are complete.", "Package-backed stock requires a manifested shipment with a manifest reference attached to the order. A reference entered in this screen isn't external provider acceptance.", "After posting, check Fulfilled and Remaining. Partial delivery produces Partially Fulfilled; completing every line produces Fulfilled. Open Inventory Ledger to inspect the movement and reference."], expected: "The order's fulfilled quantities increase by the posted amount and Inventory Ledger contains the shipment movement." },
      { id: "keep-order-payment-and-cancellation-separate", title: "Handle payment state or cancellation deliberately", warning: "Cancel order releases active allocations and cancels the order. It doesn't reverse inventory that has already shipped. A fulfilled order can't be cancelled.", instructions: ["Use Payment and Update payment only to change the order's operational payment label. This action doesn't create an invoice payment or reduce an invoice balance.", "To record actual money received, use Wholesale + Finance and Invoice / payment instead.", "If an open order must be cancelled, check its fulfilled quantities first, then choose Cancel order only for the intended cancellation. Verify its removal from the open-order list and inspect Inventory Ledger for any earlier shipments."], fields: [{ label: "Payment", requirement: "Optional operational status change.", guidance: "Choose Not Invoiced, Draft, Sent, Partial, Paid, or Overdue only when that label accurately describes the order. Use invoice payment posting for accounting balances." }], expected: "The saved payment label appears on the order, or a cancelled order no longer appears among open orders. Existing shipment history remains visible in the ledger." }
    ],
    completion: ["The intended order shows the expected Draft, Confirmed, Allocated, Partially Fulfilled, or Fulfilled status.", "Ordered, Fulfilled, Remaining, and Unit agree with what was actually reserved or shipped.", "Any outbound posting can be found in Inventory Ledger; a payment label alone isn't treated as evidence of cash received."],
    troubleshooting: [
      { symptom: "Reserve lot rejects the quantity even though on-hand stock looks sufficient.", resolution: "Check the line's remaining amount and other reservations. The server includes production and wholesale claims. Reload the order and inventory before choosing a smaller valid quantity or another released lot." },
      { symptom: "Post shipment is disabled or fails.", resolution: "Verify enough stock is reserved from the selected lot, the order is confirmed, and the lot is still released. For a regulated package, complete the shipment and manifest handoff in Fulfillment. Don't use a different lot or invented manifest reference to bypass the guard." },
      { symptom: "A save or shipment request timed out.", resolution: "Reopen the order and inspect its quantities and Inventory Ledger before retrying. For a draft save, search the order number first. An uncertain response doesn't mean the write failed." }
    ],
    sourceFiles: ["frontend/src/App.tsx", "frontend/src/lib/workspaceRoutes.ts", "frontend/src/pages/OrdersPage.tsx", "frontend/src/pages/WarehousePickPackPage.tsx", "backend/app/routers/commercial.py", "modules/commercial/repository.py", "modules/commercial_finance/service.py"]
  },
  "/help/wholesale/warehouse-pick-pack": {
    title: "Pick, verify, pack, and post a wholesale shipment",
    category: "wholesale",
    summary: "Use the warehouse queue to match the physical lot, reserve its quantity, record packing and manifest readiness, and post the shipment.",
    navPath: "Wholesale Ops → Fulfillment",
    appPath: "/wholesale/fulfillment",
    beforeYouStart: ["Confirm the sales order in Orders before warehouse execution. Have the physical stock and its package, lot, or barcode identifier available.", "Use the intended facility and confirm that the lot is released. A scan confirms identity; it doesn't bypass order, inventory, or permission checks.", "For package-backed stock, complete the actual manifest process through the approved traceability workflow. This page records the shipment's reference and readiness; it doesn't submit a provider manifest."],
    steps: [
      { id: "select-warehouse-queue-line", title: "Find the order line you're picking", instructions: ["Open Fulfillment in Wholesale Ops, or Warehouse Pick Pack from navigation.", "Read the order number, LINE number, product, SKU, remaining quantity, and due date on the card. Use Previous and Next to move through the queue.", "If you see No released/available lot has positive inventory for this line, resolve inventory in the source workflow before continuing."], expected: "The card identifies the intended order line and shows available lots for that product." },
      { id: "choose-physical-inventory-lot", title: "Choose the lot you can physically verify", instructions: ["In Inventory lot, review the recommended lot and its Location, Expiration, and Available quantity.", "The recommendation uses earliest expiration first, then oldest receipt. Choose another available lot only when it's the stock you'll actually pick.", "Read the unit beside the available and remaining quantities. A missing expiration displays No date; don't infer an expiry from list position."], fields: [{ label: "Inventory lot", requirement: "Required selection.", guidance: "Match the package or lot identifier, location, and available amount to the physical stock." }], expected: "Location, Expiration, and Available describe the selected lot. Changing lots clears the prior captured identity." },
      { id: "capture-and-verify-lot", title: "Capture the identifier and check the match", instructions: ["Open Bluetooth / USB scanner or typed code. Scan into Package / lot identifier and press Enter, or type the identifier and choose Use code.", "A package ID, lot code, barcode, or internal lot ID must match the selected lot. A product SKU alone isn't enough for this warehouse check.", "Continue only after the identity-verified message appears. If it doesn't match, inspect the label and selected lot before capturing again."], fields: [{ label: "Package / lot identifier", requirement: "Required matching capture before reserve or shipment.", guidance: "Capture the actual selected lot's identifier; don't substitute another package's label." }], expected: "The page reports that identity is verified against the selected facility lot and displays the captured value." },
      { id: "reserve-captured-quantity", title: "Enter and reserve the pick quantity", instructions: ["Set Quantity to the amount you're taking from this lot, in the order line's displayed unit. Keep it within the remaining order amount and available stock.", "Review Shipment reference, then choose Reserve captured lot once. If the stock was already reserved in Orders, check that reservation there before reserving again.", "Wait for Lot reserved. Reservation commits stock to the line; it doesn't decrease physical on-hand inventory yet."], fields: [
        { label: "Quantity", requirement: "Required and positive.", guidance: "Enter the amount for this action, not the original total when part of the line has already shipped.", example: "6" },
        { label: "Shipment reference", requirement: "Optional; defaults to the order number.", guidance: "Keep a reference the next operator can recognize in the inventory history.", example: "SO-DEMO-104" }
      ], expected: "The Lot reserved message confirms the allocation was saved." },
      { id: "record-pick-pack-progress", title: "Create the shipment and record packing", instructions: ["In PACK & MANIFEST, choose Create shipment if the order doesn't yet have a shipment record.", "Check the displayed Shipment number and status. Choose Start picking while it is Planned, then Mark packed when the physical load is packed.", "These status updates describe the shipment handoff. They don't post the outbound inventory quantity."], expected: "Shipment progresses from Planned to Picking to Packed, with its shipment number still visible." },
      { id: "attach-verified-manifest-reference", title: "Record the manifest handoff for package-backed stock", instructions: ["If the selected lot is package-backed, enter the actual State transfer / manifest reference in Manifest reference after completing the approved manifest process.", "Choose Mark manifested when the shipment is Packed and the reference is present.", "Check for Manifest handoff ready. This is the local shipment readiness check, not a new provider submission or proof of external readback. For a lot without a package, the screen explains that this guard doesn't require a manifest reference."], fields: [{ label: "Manifest reference", requirement: "Required for the package-backed shipment handoff.", guidance: "Use the reference from the completed manifest process. Don't use the sales-order number as a stand-in." }], expected: "The shipment shows Manifested and the Manifest handoff ready message includes the recorded reference." },
      { id: "post-captured-shipment", title: "Post the verified quantity leaving inventory", warning: "Post shipment commits an outbound inventory movement. There is no undo control here. Verify the order, lot, quantity, reservation, and manifest before posting; inspect the order and ledger before retrying any uncertain response.", instructions: ["Recheck the captured identity and Quantity against the packed goods. Changing queue lines or refreshing shipment details can clear the capture, so capture the identifier again if needed.", "Choose Post shipment once and wait for the queue to update.", "Use Orders to check the line's Fulfilled and Remaining amounts and Inventory Ledger to inspect the shipment reference. Posting part of a line leaves more work in the queue."], expected: "The posted amount is reflected in the order and ledger, and the warehouse queue refreshes to show remaining work." }
    ],
    completion: ["The selected lot's identity was verified before execution.", "The order's Fulfilled quantity and inventory movement match the quantity physically shipped.", "Pick queue is clear appears only when no loaded open sales-order lines still need fulfillment."],
    troubleshooting: [
      { symptom: "Captured identity does not match this lot.", resolution: "Compare the physical label with Inventory lot. Select the correct lot, then capture again. Use a package ID, lot code, barcode, or internal lot ID rather than a product SKU." },
      { symptom: "The action button says Manifest required.", resolution: "Create the order shipment if necessary, record Start picking and Mark packed, then attach the real Manifest reference and choose Mark manifested after the approved manifest process. Don't invent a reference." },
      { symptom: "Post shipment says there isn't enough reserved quantity.", resolution: "Check the chosen lot's current reservation in Orders → Allocate & Fulfill. Reserve only the additional valid quantity needed, then return and capture the lot again. A matching scan doesn't create a reservation automatically." }
    ],
    sourceFiles: ["frontend/src/pages/WholesaleOpsPage.tsx", "frontend/src/pages/WarehousePickPackPage.tsx", "frontend/src/components/IdentifierCaptureInput.tsx", "backend/app/routers/warehouse.py", "backend/app/routers/commercial.py", "modules/commercial/repository.py", "modules/commercial_finance/service.py"]
  },
  "/help/wholesale/customers": {
    title: "Keep a wholesale customer account ready for the next handoff",
    category: "wholesale",
    summary: "Create the trade partner, review Customer 360, assign the next action, and record activities or a Work follow-up.",
    navPath: "Wholesale Ops → Customers",
    appPath: "/wholesale?tab=customers",
    beforeYouStart: ["Check the active organization and facility. Customer details and relationship records are scoped to your commercial access.", "Partner creation and CRM changes are permission-checked on the server. Ask your administrator for the appropriate access if a save is denied.", "Customer contact and license details are maintained in the trade-partner record. Customer 360 doesn't provide a general contact-edit form."],
    steps: [
      { id: "find-wholesale-customer", title: "Search before adding a customer", instructions: ["Open Wholesale Ops → Customers. Enter the business name in Find customer, then use Previous or Next if more accounts are available.", "Choose the customer's name to open Customer 360. If no account exists, go to Orders → Trade Partners to create it."], fields: [{ label: "Find customer", requirement: "Optional filter.", guidance: "Use the business name you expect on orders and invoices.", example: "Example Retail" }], expected: "Customer 360 opens for an existing account, or you've confirmed that a new trade partner is needed." },
      { id: "create-customer-trade-partner", title: "Create a trade partner when needed", instructions: ["In Orders → Trade Partners, fill in Add trade partner and select Customer or Both for Relationship.", "Check the business name, supplied license, contact details, and Default terms, then choose Create partner once.", "Wait for the added message and the entry in Partner directory. Return to Customers and open the new business. Recording a license here doesn't externally verify it."], fields: [
        { label: "Business name", requirement: "Required.", guidance: "Use the customer's business name as it should appear in commercial records.", example: "Example Retail" },
        { label: "Relationship", requirement: "Required selection.", guidance: "Choose Customer for buyers, or Both if the same business also supplies you." },
        { label: "License / registration", requirement: "Optional in this form.", guidance: "Record the supplied business credential exactly and verify it through your approved process." },
        { label: "Primary contact", requirement: "Optional.", guidance: "Use the person responsible for wholesale orders.", example: "Alex Example" },
        { label: "Email", requirement: "Optional.", guidance: "Use the agreed business contact address.", example: "orders@example.invalid" },
        { label: "Phone", requirement: "Optional.", guidance: "Record the agreed business contact number if available." },
        { label: "Default terms", requirement: "Required selection with a default.", guidance: "Choose the agreed Due on receipt, Net 7, Net 15, Net 30, Net 45, or Net 60 terms." }
      ], expected: "The new business appears in Partner directory and can be selected as a customer." },
      { id: "review-customer-context", title: "Review contact, sales, and balance context", instructions: ["In Customer 360, confirm the business heading, license, contact, and payment terms before recording work.", "Read Sales order value and Open invoice balance as separate measures. An open balance needs invoice review, even if the account's relationship Status is active.", "Look at Opportunities, Quotes, and Customer timeline for recent context. The timeline contains the latest 50 entries, not a complete lifetime history."], expected: "You can match the account to its commercial context and identify the next customer conversation." },
      { id: "save-account-next-action", title: "Assign the account's next action", instructions: ["In Account next action, choose Assigned rep. Use Find assigned user and More users to locate an eligible user if needed.", "Select Status, write a specific Next action, set Next action date if known, and choose Save account.", "This saves the account plan. It doesn't create a Work item; use Doobie Work follow-up when a tracked task is needed."], fields: [
        { label: "Assigned rep", requirement: "Optional; Unassigned is allowed.", guidance: "Choose an active eligible user in this organization and facility." },
        { label: "Status", requirement: "Required selection.", guidance: "Choose prospect, active, on_hold, or inactive to describe the relationship, not the order or invoice state." },
        { label: "Next action", requirement: "Optional, up to 1,000 characters.", guidance: "Name the concrete next conversation or handoff.", example: "Confirm the requested delivery window with the buyer." },
        { label: "Next action date", requirement: "Optional date.", guidance: "Set the intended follow-up date; this field doesn't include a time." }
      ], expected: "Saved. appears and the account plan remains visible with the chosen rep, status, action, and date." },
      { id: "record-customer-activity", title: "Record the conversation that happened", instructions: ["Under Record activity, choose Activity type and write Notes explaining the outcome and any commitment.", "Use Task or activity reference when there is a useful existing reference. If Activity type is task_reference, the reference must identify existing Work in this facility.", "Choose Record activity and check Customer timeline. Choosing email records an activity; it doesn't send an email."], fields: [
        { label: "Activity type", requirement: "Required selection.", guidance: "Choose call, email, meeting, note, or task_reference for the activity you're recording." },
        { label: "Notes", requirement: "Required, up to 10,000 characters.", guidance: "Record what was agreed and what still needs a decision.", example: "Buyer asked for delivery-window confirmation before the quote is converted." },
        { label: "Task or activity reference", requirement: "Optional except that task_reference needs an existing Work reference.", guidance: "Use the actual linked work identifier when recording a task reference." }
      ], expected: "The new activity appears in Customer timeline with its recorded time and actor." },
      { id: "create-customer-work-follow-up", title: "Create a tracked follow-up", instructions: ["Under Doobie Work follow-up, enter Follow-up title and choose the account or a specific Follow-up opportunity.", "Choose Follow-up assignee and Follow-up due if known. The due input uses your browser's local time and is saved as a timestamp.", "Choose Create Work follow-up. Use Open Doobie Work or the timeline's Open Work item link to manage the resulting task."], fields: [
        { label: "Follow-up title", requirement: "Required, up to 240 characters.", guidance: "Describe the action someone needs to complete.", example: "Confirm Example Retail delivery window" },
        { label: "Follow-up opportunity", requirement: "Optional link.", guidance: "Use Customer account for account-wide work, or select the related opportunity." },
        { label: "Follow-up assignee", requirement: "Optional.", guidance: "Choose the eligible person responsible for the task." },
        { label: "Follow-up due", requirement: "Optional local date and time.", guidance: "Check your device time zone before setting a timed commitment." }
      ], expected: "A Doobie Work follow-up created message includes the saved item ID, and the account timeline provides its Work link." }
    ],
    completion: ["Customer 360 shows the intended customer and saved Account next action.", "Recorded activity is visible in Customer timeline, and any requested Work follow-up has an item ID and link."],
    troubleshooting: [
      { symptom: "An assigned rep is missing or rejected.", resolution: "Use Find assigned user and More users. The server accepts only active CRM-authorized users in the account's organization and facility. Ask an administrator to review access rather than entering an unrelated user's ID." },
      { symptom: "Saving the account didn't create a task.", resolution: "Save account updates the relationship's next-action fields only. Use Create Work follow-up for a separate task and confirm its returned ID before creating another." },
      { symptom: "I can't change contact details in Customer 360.", resolution: "This screen shows trade-partner contact details but only edits relationship, opportunity, quote, activity, and follow-up information. Have the existing trade-partner record corrected through the available authorized maintenance workflow; don't create a duplicate customer to work around it." }
    ],
    sourceFiles: ["frontend/src/pages/WholesaleOpsPage.tsx", "frontend/src/pages/WholesaleCRMPanel.tsx", "frontend/src/pages/OrdersPage.tsx", "backend/app/routers/commercial.py", "backend/app/routers/commercial_crm.py", "modules/commercial/crm_contracts.py", "modules/commercial/crm.py", "modules/commercial/repository.py"]
  },
  "/help/wholesale/pipeline": {
    title: "Move a wholesale opportunity into a quoted sales order",
    category: "wholesale",
    summary: "Track the sales opportunity, save a priced quote, and convert it into a draft order without reserving stock prematurely.",
    navPath: "Wholesale Ops → Pipeline",
    appPath: "/wholesale",
    beforeYouStart: ["Create the customer in Orders → Trade Partners before adding its first opportunity.", "CRM writes require wholesale.manage_crm as well as an allowed commercial role. Product and owner selections are checked against the active scope.", "Opportunity stages describe sales progress. A won opportunity or saved quote doesn't confirm an order, reserve inventory, or record revenue."],
    steps: [
      { id: "open-sales-opportunity-account", title: "Open the customer from Pipeline", instructions: ["Open Wholesale Ops and choose Pipeline. Review Customer, Opportunity, Stage / Value, Assigned rep, Next action, and Due.", "Use Previous and Next for additional results. Choose the customer name to open Customer 360.", "If there are no opportunities yet, use Customers to open the account and begin with New opportunity. The Pipeline tab itself has no standalone add button."], expected: "Customer 360 shows the account's Opportunities and the New opportunity form." },
      { id: "save-wholesale-opportunity", title: "Describe and save the opportunity", instructions: ["Enter a specific Title, select Stage, and set Estimated value (USD) to your current estimate.", "Add Expected close date, Owner, and Source when known. Use Next action and Next action date to make the handoff clear.", "Choose Save opportunity and check the Opportunities table. To revise an existing opportunity, choose its title; use New opportunity to leave edit mode."], fields: [
        { label: "Title", requirement: "Required, up to 255 characters.", guidance: "Name the customer's purchase opportunity.", example: "Example Retail autumn assortment" },
        { label: "Stage", requirement: "Required selection.", guidance: "Choose lead, qualified, quoted, negotiating, won, or lost to match the conversation." },
        { label: "Estimated value (USD)", requirement: "Required nonnegative amount.", guidance: "Enter the opportunity estimate, not an invoice payment.", example: "1200" },
        { label: "Expected close date", requirement: "Optional date.", guidance: "Use the expected customer decision date." },
        { label: "Owner", requirement: "Optional.", guidance: "Choose an eligible user responsible for this opportunity." },
        { label: "Source", requirement: "Optional, up to 255 characters.", guidance: "Record where the opportunity came from.", example: "Buyer inquiry" },
        { label: "Next action", requirement: "Optional, up to 1,000 characters.", guidance: "Describe the next step needed to progress the sale.", example: "Review the proposed assortment with the buyer." },
        { label: "Next action date", requirement: "Optional date.", guidance: "Set the intended date for that action." }
      ], expected: "Saved. appears and Opportunities shows the saved stage, value, owner, and next action." },
      { id: "build-customer-quote", title: "Add products to a quote", instructions: ["Under Quotes, enter Quote title and choose the related Opportunity, or leave No linked opportunity.", "Use Find product, then Add product. Read the unit shown beside each added product before entering Quantity.", "Add one or more lines, up to 100, and use Remove for any unwanted line. These edits remain on the form until Save quote succeeds."], fields: [
        { label: "Quote title", requirement: "Required, up to 255 characters.", guidance: "Use a title that distinguishes this proposal from previous quotes.", example: "Example Retail assortment proposal" },
        { label: "Opportunity", requirement: "Optional link.", guidance: "Select the opportunity this quote supports." },
        { label: "Find product", requirement: "Optional filter.", guidance: "Search the active product names to narrow Add product." },
        { label: "Add product", requirement: "At least one line is required.", guidance: "Choose the intended product by name and SKU." },
        { label: "Quantity", requirement: "Required positive amount on each line.", guidance: "Use the base unit shown next to the product name.", example: "12" }
      ], expected: "Each proposed product has a visible quote line with its unit, quantity, and price input." },
      { id: "resolve-and-review-quote-price", title: "Save and check the resolved prices", instructions: ["Enter Unit price (USD), or leave it blank to use customer pricing and then facility wholesale pricing.", "If no unambiguous price is available, enter an explicit agreed price instead of assuming zero.", "Choose Save quote and read the saved quote card under Quotes. Review every saved quantity, unit, and price before conversion. Saving the quote doesn't reserve inventory."], fields: [{ label: "Unit price (USD)", requirement: "Optional only when a valid customer or facility wholesale price can be resolved; otherwise required.", guidance: "Enter a nonnegative price per displayed base unit. A blank price requests lookup; zero is an explicit price.", example: "12.50" }], expected: "A saved quote card lists the resolved line prices and its status." },
      { id: "convert-quote-to-draft-order", title: "Convert the agreed quote into an order draft", instructions: ["After reviewing the saved quote, choose Convert to draft sales order on that quote card.", "Wait for Draft sales order created or recovered and note the returned ID. The quote card then shows Sales order and the linked identifier.", "Continue in Orders. Confirm the draft and allocate stock through the usual workflow; conversion alone doesn't reserve or ship anything."], expected: "The quote has a linked sales-order ID and no longer offers its conversion button." },
      { id: "update-pipeline-handoff", title: "Record the next sales handoff", instructions: ["Update the opportunity Stage and Next action to reflect the actual conversation, then choose Save opportunity. Conversion doesn't replace this review.", "If someone needs a tracked task, use Doobie Work follow-up in the same customer account and link the opportunity.", "Choose Back to accounts to return to Pipeline and review the saved Stage / Value and Next action."], expected: "Pipeline shows the saved opportunity state and next action; Orders contains the linked draft for commercial execution." }
    ],
    completion: ["Pipeline shows the intended opportunity, stage, owner, value, and next action.", "The saved quote shows reviewed quantities and prices, and a converted quote displays its linked Sales order ID.", "The order remains a draft until separately confirmed in Orders."],
    troubleshooting: [
      { symptom: "Save quote asks for an explicit price.", resolution: "The customer or facility price couldn't be resolved safely. Enter the agreed Unit price (USD), save again, and review the price on the saved quote card before conversion." },
      { symptom: "I opened Pipeline but can't add an opportunity.", resolution: "Choose the customer name to open Customer 360. For a customer's first opportunity, open the account from Customers. Create a missing customer in Orders → Trade Partners first." },
      { symptom: "Conversion returned an error or the response was lost.", resolution: "Reload the customer and inspect the quote for its linked Sales order ID before creating anything else. The conversion service can recover an existing linked draft; don't manually duplicate the order while its outcome is uncertain." }
    ],
    sourceFiles: ["frontend/src/pages/WholesaleOpsPage.tsx", "frontend/src/pages/WholesaleCRMPanel.tsx", "frontend/src/pages/OrdersPage.tsx", "backend/app/routers/commercial_crm.py", "modules/commercial/crm_contracts.py", "modules/commercial/crm.py", "modules/commercial_finance/pricing.py", "modules/commercial/repository.py"]
  },
  "/help/wholesale/accounting": {
    title: "Review wholesale balances and record invoice payments",
    category: "wholesale",
    summary: "Use Accounting to reconcile orders, invoices, recorded payments, and stored QuickBooks links, then use order finance for approved changes.",
    navPath: "Wholesale Ops → Accounting",
    appPath: "/wholesale",
    beforeYouStart: ["Check the active facility and have the sales-order number, invoice number, and payment evidence ready.", "Accounting is a read-only summary. Invoice and payment actions live in Orders → Wholesale + Finance.", "The invoice endpoint requires the sales order to be fully fulfilled. Recording a payment also requires commercial.record_payment permission."],
    steps: [
      { id: "review-wholesale-ar", title: "Read the current receivables picture", instructions: ["Open Wholesale Ops → Accounting and choose Refresh before reconciling recent changes.", "Compare Accounts receivable, Overdue A/R, Current A/R, and the aging buckets under Outstanding customer balances.", "Open sales value is unfulfilled sales demand; it isn't the same as an outstanding invoice balance. The summary amounts are rounded for display, so use invoice detail when checking an exact payment amount."], expected: "The accounting summary and aging buckets load, or a specific load error appears." },
      { id: "match-invoice-order-payment", title: "Match the invoice to the order and recorded cash", instructions: ["In Wholesale invoices, match Invoice, Customer, and Order, then read Status, Due, Total, and Balance.", "Compare Wholesale sales orders for Order status and Payment status. A manually changed order payment label doesn't itself reduce the invoice balance.", "Review Recorded payments for Date, Invoice, Amount, Method, and Reference. This view shows up to 75 invoice and order rows and 50 recent payment rows, so use order finance if the required record isn't visible."], expected: "You have identified the invoice balance and any visible payment entries for the intended order." },
      { id: "open-order-finance", title: "Open the order's invoice controls", instructions: ["Choose Orders, then Wholesale + Finance. In Open order finance, select the correct sales order.", "Expand Invoice / payment and inspect existing invoices before creating a new one. The action controls operate on the first invoice returned for this order, so confirm its Invoice number and Balance.", "If fulfillment isn't complete, finish the real shipping workflow first rather than trying to bypass the invoice guard."], fields: [{ label: "Open order finance", requirement: "Required selection.", guidance: "Choose the exact order whose invoice or payment you're handling." }], expected: "Invoice / payment displays the selected order's invoice rows and available actions." },
      { id: "create-wholesale-invoice", title: "Create and review the invoice draft", instructions: ["If no intended invoice exists, enter Invoice number and review Due in days, then choose Create invoice from order.", "Use a distinct invoice number for this order. The service can return an existing invoice with the same organization invoice number, so never reuse a number from another order.", "Check the new invoice's Total, Balance, Due, and Status. The invoice copies the order lines; creating it sets the order's payment state to draft."], fields: [
        { label: "Invoice number", requirement: "Required.", guidance: "Use the correct invoice identifier for this order and check existing invoices first.", example: "INV-SO-DEMO-104" },
        { label: "Due in days", requirement: "Required nonnegative number; the UI offers 0 through 180.", guidance: "Review the default 30 days against agreed terms. This control sets the invoice due date; it doesn't automatically read the customer's displayed terms.", example: "30" }
      ], expected: "The invoice table shows the draft invoice with its total, open balance, and due date." },
      { id: "mark-invoice-sent", title: "Record that the invoice has been sent", instructions: ["After sending the invoice through your actual customer-delivery process, choose Mark invoice sent while the invoice is Draft.", "This button updates the saved invoice and order payment status. It doesn't send email or prove the buyer received it."], expected: "The invoice status changes to sent when a balance remains, and the order's payment state follows it." },
      { id: "post-invoice-payment", title: "Record a verified payment against the invoice", warning: "Post payment records money against the invoice and reduces its balance. Verify the invoice, amount, method, and reference first. There is no payment reversal control here, and you must check for a saved payment before retrying an uncertain response.", instructions: ["Enter the amount actually received in Payment, choose Method, and enter Reference from your payment evidence.", "Choose Post payment once. This records the payment in DoobieLogic; it doesn't charge a card or initiate an ACH transfer.", "Check the updated Balance and status. A remaining balance produces partial; clearing the balance produces paid. The form records today's local date and doesn't offer a payment-date input."], fields: [
        { label: "Payment", requirement: "Required, greater than zero and no more than the remaining balance.", guidance: "Enter the USD amount actually received. The prefilled balance isn't evidence that the full amount was paid.", example: "150" },
        { label: "Method", requirement: "Required selection.", guidance: "Choose ach, check, cash, card, or other to describe the payment already received." },
        { label: "Reference", requirement: "Optional, but useful for reconciliation.", guidance: "Record the payment reference without bank credentials or full card details.", example: "DEMO-PAY-104" }
      ], expected: "The invoice balance decreases by the saved amount and its status becomes partial or paid." },
      { id: "verify-accounting-and-sync-state", title: "Refresh Accounting and review link health", instructions: ["Return to Accounting and choose Refresh. Match the new Recorded payments entry and the invoice's updated Balance.", "Review Accounting synchronization health and Purchasing reconciliation for stored vendor, purchase-order, and item-mapping issues.", "Use QuickBooks settings to open Integrations when an authorized administrator needs to investigate. Linked and Last sync are stored metadata, not a fresh provider readback, and Refresh doesn't push records to QuickBooks."], expected: "Accounting reflects the saved invoice payment and exposes any existing QuickBooks link or purchasing reconciliation issues." },
      { id: "save-customer-price-rule", title: "Save an agreed customer price rule when needed", instructions: ["In Orders → Wholesale + Finance, expand Customer-specific pricing. Select Customer explicitly; don't assume it defaults to the customer on the selected order.", "Choose Product from the selected order's products. Enter a positive Fixed wholesale price, or leave that at zero and use Or discount % for a percentage rule. A positive fixed price takes precedence over the discount.", "Choose Save price rule and wait for Customer pricing saved. This updates the rule for that customer and product; it doesn't rewrite saved quote, order, or invoice line prices. Review resolved prices on the next saved quote."], fields: [
        { label: "Customer", requirement: "Required selection.", guidance: "Choose the customer whose future price lookup should use this rule." },
        { label: "Product", requirement: "Required selection.", guidance: "Choose the product covered by the agreement; options come from the selected order's lines." },
        { label: "Fixed wholesale price", requirement: "Nonnegative amount; use a positive value for a fixed-price rule.", guidance: "Enter the agreed USD price per product base unit. Zero means the percentage rule is used against the available channel base price.", example: "12.50" },
        { label: "Or discount %", requirement: "From 0 to 100; used when no positive fixed price is set.", guidance: "Enter the agreed discount percentage and review the resolved price on the next quote.", example: "5" }
      ], expected: "Customer pricing saved. appears; existing invoice balances and payment entries remain as recorded." }
    ],
    completion: ["The invoice's Balance and Status match the verified payment posting.", "Recorded payments shows the matching Invoice, Amount, Method, and Reference after Refresh.", "QuickBooks link status has been interpreted as stored synchronization metadata rather than proof of a new sync."],
    troubleshooting: [
      { symptom: "Create invoice from order says fulfillment must be completed.", resolution: "Check the order's line quantities in Allocate & Fulfill and complete only the actual remaining shipment. The invoice route requires Fulfilled status; don't mark a payment or shipment status just to force invoicing." },
      { symptom: "Payment status says Paid but the invoice still has a balance.", resolution: "Inspect Recorded payments and order finance. Update payment on an order changes only its operational label. Record a payment only after verifying money was received, or have the incorrect label corrected." },
      { symptom: "A payment timed out or the amount looks duplicated.", resolution: "Refresh Accounting and inspect Recorded payments and the invoice balance before doing anything else. Escalate a confirmed duplicate to your accounting owner; this screen has no reversal action." },
      { symptom: "QuickBooks says Not linked even though DoobieLogic has an invoice.", resolution: "A local invoice doesn't automatically establish a provider link. Review Accounting synchronization health and QuickBooks settings with an authorized administrator. Don't recreate the invoice merely to obtain a link." }
    ],
    sourceFiles: ["frontend/src/pages/WholesaleOpsPage.tsx", "frontend/src/pages/WholesaleAccountingPanel.tsx", "frontend/src/pages/OrdersPage.tsx", "backend/app/routers/wholesale_accounting.py", "services/wholesale_accounting.py", "backend/app/routers/commercial.py", "modules/commercial_finance/service.py", "modules/commercial_finance/pricing.py", "modules/commercial/repository.py"]
  },
  "/help/wholesale/storefront": {
    title: "Publish the wholesale storefront and review buyer requests",
    category: "wholesale",
    summary: "Save the site foundation and catalog, publish a reviewed design draft, and turn approved buyer requests into sales-order drafts.",
    navPath: "Wholesale Ops → Storefront",
    appPath: "/wholesale",
    beforeYouStart: ["Confirm the active facility, the intended storefront, and your access to publishing, design, catalog, pricing, and order approval. These are separate permissions.", "Have approved brand copy, images, product prices, minimums, and case increments ready. Storefront quantities can be shown in a different weight unit from operational inventory.", "Studio's Save design draft and Publish design control design only. Save storefront, Save storefront catalog, and Use on storefront are separate saves and aren't covered by the design draft.", "Plan to inspect Open storefront after saving. Live preview uses a small sample of products and placeholder lab values; it isn't evidence that the public site is correct."],
    steps: [
      { id: "save-storefront-foundation", title: "Save the storefront identity and contact details", instructions: ["Open Wholesale Ops → Storefront and find Storefront foundation.", "Enter the brand name, subdomain, headline, brand copy, and sales contact. Review Publish storefront before saving; leave it unchecked while preparing a new unpublished site.", "Choose Save storefront and verify the saved values after the data reloads. On an already published storefront, foundation changes are separate from the private Studio design draft."], fields: [
        { label: "Brand / storefront name", requirement: "Required.", guidance: "Use the customer-facing brand name.", example: "Example Wholesale" },
        { label: "DoobieLogic subdomain", requirement: "Required; 2 to 63 letters, numbers, or hyphens, subject to availability and reserved-name checks.", guidance: "Enter only the subdomain part, without a protocol or domain suffix.", example: "example-wholesale-demo" },
        { label: "Headline", requirement: "Optional copy with a default.", guidance: "Describe the wholesale offer plainly." },
        { label: "Brand story / landing-page copy", requirement: "Optional.", guidance: "Use approved customer-facing brand information." },
        { label: "Fallback logo URL", requirement: "Optional; must use HTTPS when supplied.", guidance: "Use an approved publicly accessible image URL if you aren't using an uploaded Studio logo." },
        { label: "Fallback hero image URL", requirement: "Optional; must use HTTPS when supplied.", guidance: "Use an approved hero image URL if you aren't using an uploaded Studio image." },
        { label: "Legacy accent color", requirement: "Required saved color with a default.", guidance: "Choose the fallback accent color; Studio has its own design colors." },
        { label: "Sales email", requirement: "Optional contact.", guidance: "Use the public wholesale contact address.", example: "sales@example.invalid" },
        { label: "Order instructions", requirement: "Optional.", guidance: "Explain the buyer's next step and review process without promising automatic approval." },
        { label: "Publish storefront", requirement: "Explicit publication choice.", guidance: "Saving with this checked makes the storefront available publicly; saving it unchecked unpublishes the site." }
      ], expected: "The saved foundation reloads and Open storefront points to the configured public address. An unpublished site isn't publicly available yet." },
      { id: "configure-storefront-catalog", title: "Choose products and review wholesale rules", warning: "Save storefront catalog saves the current selected set. Unselected products are removed from the active catalog. On a published site, don't treat this as a private design draft.", instructions: ["In Products, volume pricing & wholesale rules, select the intended products. Use Show all only if every listed product belongs on this storefront.", "Check Inventory for Ready to list, Coming soon, or Sold out. Listing a product doesn't override missing COA, hold, or availability restrictions.", "Review Base price and the two Minimum / case inputs, with minimum first and case increment second. Use + Add volume tier for quantity-based prices, and set Featured only for products you intend to feature.", "Choose Save storefront catalog after reviewing the selected rows. If a product uses a non-base display unit, check the saved and public quantities and prices carefully before accepting the result."], fields: [
        { label: "Show all", requirement: "Optional bulk selection.", guidance: "Selects every loaded product for the catalog; review the rows before saving." },
        { label: "Base price", requirement: "Nonnegative price on each selected row.", guidance: "The catalog save stores price per operational base unit. Check Source unit before editing when the storefront uses another display unit. This input is identified by its table heading." },
        { label: "Minimum / case", requirement: "Both quantities must be positive.", guidance: "The first input is the order minimum and the second is the case increment, stored in the operational base unit. These inputs share a table heading rather than individual labels." },
        { label: "Tier minimum quantity", requirement: "Required for each added tier.", guidance: "Use a unique threshold that meets the listing minimum and aligns with its case increment." },
        { label: "Tier price", requirement: "Required nonnegative price for each added tier.", guidance: "Enter the agreed price for quantities reaching that tier." },
        { label: "Featured", requirement: "Optional checkbox.", guidance: "Mark products to include in the Featured Drops presentation." }
      ], expected: "The saved catalog reloads with the selected products and wholesale rules." },
      { id: "set-storefront-display-units", title: "Choose the customer's display unit", instructions: ["In STOREFRONT DISPLAY UNITS, compare Source unit with Show on storefront as for each active listing.", "Choose a compatible unit from that product's selector, then choose Use on storefront. Review Displayed minimum and Displayed increment, and compare them with the actual public storefront before relying on the conversion.", "This changes customer-facing weight presentation and conversion, not inventory or Metrc source quantities. An approved order is converted back to the product's operational base unit."], fields: [{ label: "Show on storefront as", requirement: "Optional presentation change using the row's compatible choices.", guidance: "The selector's accessible name is Storefront display unit for followed by the product name. Choose the unit buyers should use, then verify the actual public minimum and increment." }], expected: "Storefront display unit updated appears and the selector retains the chosen unit after saving." },
      { id: "edit-storefront-design", title: "Build the design in Studio", instructions: ["Under Customize the customer experience, choose Theme preset, Font preset, Card style, and Image treatment. Review Primary accent, Secondary, and Surface colors in the preview.", "Use Logo upload, Hero upload, or Favicon upload for approved assets. Uploading an asset doesn't by itself publish the design.", "Review Page sections, the section-order arrows, and any Partnership heading, Partnership copy, Brand-story heading, or Brand-story copy you enable. Choose Product card fields and Card badges without attempting to type lab results."], fields: [
        { label: "Theme preset", requirement: "Saved design selection.", guidance: "Choose from the options supplied by Studio and inspect the preview." },
        { label: "Font preset", requirement: "Saved design selection.", guidance: "Choose readable type and check long product names." },
        { label: "Card style", requirement: "Saved design selection.", guidance: "Choose the desired product-card presentation." },
        { label: "Image treatment", requirement: "Saved design selection.", guidance: "Review how the selected treatment crops or fits your images." },
        { label: "Primary accent", requirement: "Saved color.", guidance: "Choose the main Studio accent color." },
        { label: "Secondary", requirement: "Saved color.", guidance: "Choose the secondary design color." },
        { label: "Surface", requirement: "Saved color.", guidance: "Choose the background surface color and check text readability." },
        { label: "Logo upload", requirement: "Optional PNG, JPEG, or WebP, maximum 1 MB.", guidance: "Use an approved logo asset." },
        { label: "Hero upload", requirement: "Optional PNG, JPEG, or WebP, maximum 4 MB.", guidance: "Use an approved hero image and inspect its crop." },
        { label: "Favicon upload", requirement: "Optional PNG, JPEG, or WebP, maximum 256 KB.", guidance: "Use a simple brand image readable at small size." },
        { label: "Show announcement bar", requirement: "Optional.", guidance: "Enable it only with current approved text in the adjacent announcement input." },
        { label: "Partnership heading", requirement: "Conditional when Retail partnership is enabled; up to 160 characters.", guidance: "Name the customer partnership section." },
        { label: "Partnership copy", requirement: "Conditional when Retail partnership is enabled; up to 3,000 characters.", guidance: "Explain the actual wholesale relationship and ordering process." },
        { label: "Brand-story heading", requirement: "Conditional when Brand story is enabled.", guidance: "Give the brand section a clear heading." },
        { label: "Brand-story copy", requirement: "Conditional when Brand story is enabled.", guidance: "Use approved brand copy suitable for the public site." }
      ], expected: "Live preview reflects the local design edits. THCA, TAC, and Terps remain locked presentation fields backed by actual lab data on the site." },
      { id: "save-and-publish-design", title: "Save the draft before publishing it", warning: "Publish design makes the saved design draft public. It publishes the last saved draft, not unsaved edits still in the form.", instructions: ["Use Desktop, Tablet, and Mobile in Live preview to inspect the layout, then choose Save design draft and wait for the saved snapshot to return.", "Check Draft changes are not live. When the saved design is ready, choose Publish design.", "Check Published design is current and Last published. The timestamp uses your browser's local display. The draft-status text reflects the saved snapshot, so don't rely on it to detect unsaved typing."], expected: "Studio shows the saved publication state and the last-published time after a successful design publish." },
      { id: "verify-public-storefront", title: "Open and inspect the actual site", instructions: ["When ready for public access, check Publish storefront in Storefront foundation and choose Save storefront if it isn't already published.", "Choose Open storefront. Inspect the actual branding, catalog, price units, minimums, increments, and ordering availability on the public site.", "Don't interpret placeholder dashes in Live preview as measured lab results. If public lab information is missing, investigate the source COA data rather than entering substitute values in Studio."], expected: "The public storefront loads with the saved foundation, published design, and current eligible catalog." },
      { id: "review-storefront-buyer-request", title: "Inspect the incoming request and buyer evidence", instructions: ["In Approval & fulfillment inbox, find the submitted request and match Buyer, Requested, Subtotal, and Status / decision.", "Review the license indicator. Local customer match is a local record match; a supplied license can still be unverified. Review requested delivery date, window, and PO reference.", "If a PO attachment is present, choose its Download PO button and compare it with the request. A submitted request hasn't reserved stock."], expected: "You have matched the buyer and request details before changing its quantities or making a decision." },
      { id: "approve-or-reject-storefront-request", title: "Save the approval decision with reviewed lines", warning: "Approve / apply changes creates a commercial draft order; Reject ends review of the submitted request. Verify the request and notes first. After an uncertain response, inspect both the inbox status and Orders before attempting another decision.", instructions: ["For approval, review each Qty and Price. You can reduce quantity or Remove a line, but keep at least one positive line and respect live availability and case increments.", "Write the reason in Approval / rejection note, then choose Approve / apply changes. To decline the request, choose Reject with a clear note instead.", "Check approved and Sales order created, or rejected and the saved review note. Open Orders to review and confirm an approved draft; approval doesn't reserve stock or submit a Metrc transfer."], fields: [
        { label: "Qty", requirement: "Required positive quantity for each retained approval line.", guidance: "Don't exceed the customer's requested amount or current availability. Keep the case increment and request unit in mind." },
        { label: "Price", requirement: "Required nonnegative amount for each retained line.", guidance: "Review the agreed price in the request's sales unit." },
        { label: "Approval / rejection note", requirement: "Optional text, strongly useful for explaining the decision.", guidance: "This is the textarea placeholder. Record why quantities or prices changed, or why the request was declined.", example: "Approved the available quantity after confirming it with the buyer." }
      ], expected: "The request shows the saved decision. An approved request shows Sales order created and is ready for review in Orders." },
      { id: "issue-private-customer-portal", title: "Issue account-specific access when needed", warning: "The generated private URL contains an access token. Keep it out of screenshots, shared notes, and public messages; provide it only to the intended account through your approved process.", instructions: ["Under Customer-specific pricing & terms, enter the verified Customer / partner ID and choose Access days. Use the actual customer record ID, not its name or license number.", "Choose Issue customer portal link only when this account needs access. The server restricts issuance to authorized roles and a customer or both trade partner in the organization.", "Store the displayed link securely when it appears. This creates access to the customer's portal; it doesn't change prices, save an order, or send the link to the buyer."], fields: [
        { label: "Customer / partner ID", requirement: "Required.", guidance: "Use the existing customer's internal trade-partner ID. Obtain it from the verified account context rather than guessing." },
        { label: "Access days", requirement: "Required, from 1 to 365.", guidance: "Choose the access period appropriate for the account; the form defaults to 90 days.", example: "30" }
      ], expected: "A private portal URL appears beneath Issue customer portal link for secure handling." }
    ],
    completion: ["The actual public storefront, not only Live preview, shows the intended saved catalog and published design.", "Approved requests show Sales order created, and the corresponding draft is reviewed separately in Orders.", "Display-unit changes have been checked against the saved minimums, increments, and public prices."],
    troubleshooting: [
      { symptom: "Publish design is disabled or ignores my latest edits.", resolution: "Choose Save design draft first and wait for the returned snapshot. Publish design uses the saved draft, while its enabled state uses the saved draft-dirty flag. Save any new local edits before publishing." },
      { symptom: "A selected product is Coming soon or Sold out.", resolution: "Check Inventory for release status, passed COA, and uncommitted quantity. Catalog selection doesn't override eligibility. Correct the source issue, then reload the catalog and public site." },
      { symptom: "Approval fails because inventory changed.", resolution: "Reload the inbox and Inventory, then review the request against current availability. Reduce approved Qty within the original request and case increment if appropriate, or reject it with a clear reason. Don't increase quantities beyond the request or assume the earlier subtotal reserved stock." },
      { symptom: "A save appears to do nothing and no error is visible.", resolution: "This manager doesn't display error messages for several foundation, design, catalog, and approval mutations. Preserve your intended values, reload to check what actually saved, and ask an administrator to review permission or validation failures. Don't keep clicking an approval while its result is uncertain." },
      { symptom: "Catalog values look different after changing display units.", resolution: "Compare Source unit, the saved Displayed minimum and Displayed increment, and the actual public price. Display conversion mustn't be treated as an inventory change. If a later catalog save changes terms unexpectedly, stop editing and have the conversion/save path reviewed before publishing further price changes." }
    ],
    sourceFiles: ["frontend/src/pages/WholesaleOpsPage.tsx", "frontend/src/components/CommerceStorefrontManager.tsx", "frontend/src/components/StorefrontSalesUnitManager.tsx", "backend/app/routers/storefronts.py", "backend/app/routers/storefront_units.py", "backend/app/routers/control_tower.py", "modules/operational_moats/service.py", "modules/commerce_storefronts/service.py", "modules/commerce_storefronts/wholesale_service.py", "modules/commerce_storefronts/studio.py", "modules/commerce_storefronts/sales_units.py"]
  },
  "/help/wholesale/logistics": {
    title: "Plan a dispatch run and record delivery outcomes",
    category: "wholesale",
    summary: "Assign existing shipments to stops, record delivery progress and proof of delivery, and create reconciliation work for exceptions.",
    navPath: "Wholesale Ops → Logistics",
    appPath: "/wholesale",
    beforeYouStart: ["Use the intended facility. Viewing logistics requires wholesale.view; saving dispatch changes requires wholesale.manage_dispatch.", "Create the commercial shipments before planning delivery. Logistics tracks physical delivery; it doesn't post inventory, change fulfilled quantities, or submit provider manifests.", "Have the delivery address, contact, driver and vehicle details, and any agreed windows ready. Times entered here use your browser's local time and are saved as timestamps."],
    steps: [
      { id: "select-dispatch-service-date", title: "Choose the day and inspect existing runs", instructions: ["Open Wholesale Ops → Logistics and set Service date.", "Check the run buttons for driver, vehicle plate, status, and stop count. Use Previous runs or More runs if needed.", "Open an existing run before creating another one for the same work. No runs for this service date refers only to the selected day."], fields: [{ label: "Service date", requirement: "Required date.", guidance: "Choose the planned delivery day. Changing it clears the selected run." }], expected: "The dispatch board shows the selected day's runs or its no-runs message." },
      { id: "create-dispatch-run", title: "Create the run and record its driver context", instructions: ["Expand Create dispatch run. Enter the known driver, vehicle, and Run notes, then choose Create run.", "Review the selected run's heading and details after the save. Empty optional details display as not recorded where applicable.", "While every stop is still planned, use Edit run and Save run to correct the service date or driver details."], fields: [
        { label: "Driver name", requirement: "Optional in the form.", guidance: "Record the actual assigned driver when known.", example: "Alex Example" },
        { label: "Driver license number (optional)", requirement: "Optional.", guidance: "Record only the appropriate driver credential for your approved dispatch process." },
        { label: "Vehicle make (optional)", requirement: "Optional.", guidance: "Record the assigned vehicle's make." },
        { label: "Vehicle model (optional)", requirement: "Optional.", guidance: "Record the assigned vehicle's model." },
        { label: "Vehicle plate", requirement: "Optional in the form.", guidance: "Use the actual assigned vehicle plate when known." },
        { label: "Run notes", requirement: "Optional, up to 4,000 characters.", guidance: "Record instructions applying to the whole run, without credentials or unrelated personal data." }
      ], expected: "The run is selected with its driver, vehicle, notes, and current stop count." },
      { id: "add-existing-shipment-stop", title: "Add a shipment and its delivery snapshot", instructions: ["Expand Add shipment stop and select Shipment by shipment number, order number, and customer. Use More shipments if necessary.", "Enter Delivery address snapshot and review the prefilled Contact snapshot. These are the details recorded for this stop, so correct them before adding it.", "Enter both window fields or neither. Enter both coordinates or neither if you want geographic planning, then choose Add stop."], fields: [
        { label: "Shipment", requirement: "Required selection.", guidance: "Choose an available shipment in the active organization and facility." },
        { label: "Delivery address snapshot", requirement: "Required, up to 2,000 characters.", guidance: "Record the agreed destination for this delivery, including details the driver needs." },
        { label: "Contact snapshot", requirement: "Optional, up to 2,000 characters.", guidance: "Review the copied customer contact and add the agreed delivery contact if needed.", example: "Receiving team, receiving@example.invalid" },
        { label: "Window start (local time)", requirement: "Optional, but requires Window end when supplied.", guidance: "Use the agreed start in your browser's local time zone." },
        { label: "Window end (local time)", requirement: "Required when Window start is supplied.", guidance: "Use an end time no earlier than the start." },
        { label: "Latitude (optional)", requirement: "Optional paired coordinate, from -90 to 90.", guidance: "Supply a verified latitude only with its longitude." },
        { label: "Longitude (optional)", requirement: "Optional paired coordinate, from -180 to 180.", guidance: "Supply the longitude matching the delivery latitude." },
        { label: "Stop notes", requirement: "Optional, up to 4,000 characters.", guidance: "Record stop-specific access or receiving instructions." }
      ], expected: "A numbered stop appears with its order, shipment, manifest reference, address, contact, and window." },
      { id: "review-dispatch-stop-order", title: "Set the stop order before loading", instructions: ["Check every stop's destination and use Move up or Move down to arrange the sequence.", "When there are at least two stops and every stop has coordinates, Plan from first stop can suggest a straight-line nearest-neighbor order. It keeps the first stop fixed and doesn't account for roads, traffic, or delivery windows, so review the result.", "Use Remove planned stop only for a shipment that shouldn't belong to this run. Finish all run edits, additions, removals, and reordering before recording any stop as loaded."], expected: "The numbered stops show the reviewed delivery sequence while all stops are still planned." },
      { id: "record-dispatch-departure", title: "Record loading and departure as they happen", warning: "Recording the first loaded stop locks run planning. Finish the route, addresses, and driver details before that transition.", instructions: ["At the intended stop, choose loaded in Next status and select Record loaded after loading the shipment.", "Choose en route and Record en route when departing, then arrived and Record arrived at the destination. The dropdown offers only the server-allowed next statuses.", "Departure requires the attached shipment to be manifested or shipped with a nonblank manifest reference, even for a lot that didn't require a manifest during warehouse posting. Resolve that shipment's manifest handoff instead of substituting a reference or changing unrelated stock."], fields: [
        { label: "Next status", requirement: "Required transition selection.", guidance: "Follow planned → loaded → en route → arrived, recording only events that have actually happened." },
        { label: "Delivery notes", requirement: "Optional for ordinary progress updates.", guidance: "Record useful context about the event you're saving." }
      ], expected: "Each stop's status advances after its saved event, and planning controls disappear once loading begins." },
      { id: "record-delivery-proof", title: "Record receipt or an exception", instructions: ["From arrived, choose delivered, partial, or rejected in Next status to match the actual outcome.", "For delivered or partial, enter Recipient name and review Delivered at (local time, defaults to now). Add Optional typed name acknowledgment only when appropriate.", "For partial or rejected, explain the discrepancy in Exception notes (required). Choose the matching Record button, then inspect the saved status and receipt details. The form records evidence and notes; it doesn't allocate accepted or returned quantities."], fields: [
        { label: "Recipient name", requirement: "Required for delivered or partial.", guidance: "Record who actually received the delivery." },
        { label: "Delivered at (local time, defaults to now)", requirement: "Optional for delivered or partial; defaults to now.", guidance: "Use the actual receipt time in your browser's local zone. Future delivery timestamps are rejected." },
        { label: "Optional typed name acknowledgment", requirement: "Optional for delivered or partial.", guidance: "Record the typed acknowledgment name only when it was actually provided." },
        { label: "Exception notes (required)", requirement: "Required for partial, rejected, or returned.", guidance: "Explain what was accepted, refused, or returned, using item references and quantities in the notes so the reconciliation owner can investigate." }
      ], expected: "The stop shows the recorded outcome. Delivered or partial displays Received by and the receipt time, with the acknowledgment name when supplied." },
      { id: "reconcile-delivery-exception", title: "Create work for unresolved delivery quantities", instructions: ["For partial, rejected, or returned stops, choose Create reconciliation work if no Work link is present.", "Choose Open Work to review the linked task and coordinate the approved return or quantity-reconciliation process. Creating the task doesn't return stock to inventory or change the invoice.", "A partial or rejected stop can later move to returned with required exception notes when the return actually happens. Delivered and returned have no further status actions in this screen."], expected: "The exception stop has an Open Work link, while its delivery evidence remains visible and inventory quantities remain unchanged by logistics." }
    ],
    completion: ["The run shows the intended shipment stops in the reviewed order.", "Each completed stop shows its actual outcome and any required recipient, time, and exception notes.", "An unresolved exception has an Open Work link for reconciliation; no inventory or financial adjustment is assumed from the logistics status alone."],
    troubleshooting: [
      { symptom: "The shipment isn't available in Add shipment stop.", resolution: "Confirm the active facility and that the commercial shipment exists. Use the shipment pagination controls. A shipment already assigned to a dispatch stop or otherwise unavailable can't be added again; inspect existing runs rather than duplicating the shipment." },
      { symptom: "Planning controls disappeared.", resolution: "Planning locks after any stop leaves planned. Don't attempt to change it back just to reorder the run. Work with the dispatch owner using the saved sequence and recorded delivery exceptions." },
      { symptom: "The page says dispatch changed before saving.", resolution: "Let the detail reload, review the latest stop status and run contents, and reapply only a change that's still needed. Another operator may already have saved the intended event." },
      { symptom: "A partial delivery didn't change fulfilled quantity or restore stock.", resolution: "That's expected: logistics records the delivery outcome only. Use Create reconciliation work and Open Work to coordinate the approved return process and any accounting correction. Don't post another outbound shipment to fix a delivery exception." }
    ],
    sourceFiles: ["frontend/src/pages/WholesaleOpsPage.tsx", "frontend/src/pages/WholesaleLogisticsPanel.tsx", "backend/app/routers/wholesale_logistics.py", "modules/wholesale_logistics/schemas.py", "modules/wholesale_logistics/service.py", "modules/wholesale_logistics/models.py"]
  }
};
