import { test, expect } from "@playwright/test";
const origin = "http://127.0.0.1:4194";
const fixture = origin + "/e2e/fixtures/connected-onboarding.html";
test.use({ channel: process.platform === "win32" ? "chrome" : undefined, video: "off" });
test.describe.configure({ mode: "serial" });
test.afterEach(async ({ page }, info) => { await page.screenshot({ path: info.outputPath("acceptance.png"), fullPage: true }); });
for (const width of [390, 1280]) {
  test(`existing Metrc records populate the real local workspace ${width}`, async ({ page }) => {
    await page.setViewportSize({ width, height: 900 });
    await page.goto(fixture);
    const panel = page.getByRole("region", { name: "Guided Metrc connection", exact: true });
    await panel.getByLabel("Your Metrc user API key", { exact: true }).fill("synthetic-browser-user-key");
    await panel.getByRole("button", { name: "Save user key securely", exact: true }).click();
    await expect(panel.getByLabel("Your Metrc user API key", { exact: true })).toHaveValue("");
    await expect(panel).toContainText("Your key is saved securely");
    await panel.getByRole("button", { name: "Find my Metrc facilities", exact: true }).click();
    await panel.getByRole("combobox", { name: "Metrc facility", exact: true }).selectOption("MC123456");
    await panel.getByLabel("I authorize this license selection and its DoobieLogic facility link.", { exact: true }).check();
    await panel.getByRole("button", { name: "Confirm facility link", exact: true }).click();
    await expect(panel).toContainText("Facility linked.");
    await panel.getByLabel("Create missing DoobieLogic records from this facility's Metrc evidence. Do not send changes to Metrc.", { exact: true }).check();
    await panel.getByRole("button", { name: /Import existing facility records|Sync or resume existing records/ }).click();
    await expect(panel.getByRole("status").filter({ hasText: /^Import:/ })).toContainText("completed", { timeout: 25000 });
    const counts = await (await page.request.get(origin + "/fixture/counts")).json();
    expect(counts.products).toBe(1); expect(counts.lots).toBe(1); expect(counts.inventory_transactions).toBe(1);
    await page.reload(); await expect(panel).toContainText("MC123456");
    await expect(panel.getByRole("status").filter({ hasText: /^Import:/ })).toContainText("completed");
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth + 1)).toBe(true);
  });
  test(`Aranet account to mapped saved Room 360 reading ${width}`, async ({ page }) => {
    await page.setViewportSize({ width, height: 900 });
    await page.goto(fixture + "?view=networks");
    const panel = page.getByRole("region", { name: "Sensor network setup", exact: true });
    await panel.getByLabel("Connection name", { exact: true }).fill(`Aranet browser ${width}`);
    await panel.getByLabel("Customer-owned API key", { exact: true }).fill("0".repeat(32));
    await panel.getByLabel("I authorize DoobieLogic to read this account's sensor data. Do not control equipment.", { exact: true }).check();
    await panel.getByRole("button", { name: "Connect account and find sensors", exact: true }).click();
    const review = panel.getByRole("form", { name: "Confirm network sensor rooms", exact: true });
    await review.getByLabel("Connect this sensor", { exact: true }).check();
    await review.getByRole("combobox", { name: "DoobieLogic room", exact: true }).selectOption("fixture-room");
    await review.getByLabel("I authorize read-only collection from these sensors into the rooms shown.", { exact: true }).check();
    await review.getByRole("button", { name: "Connect selected sensors", exact: true }).click();
    await expect(panel).toContainText("Sensors linked.");
    expect((await page.request.post(origin + "/fixture/sample")).status()).toBe(200);
    await expect(panel).toContainText("receiving", { timeout: 10000 });
    await page.goto(fixture + "?view=room");
    await page.getByRole("button", { name: "Environment", exact: true }).click();
    const latest = page.getByRole("region", { name: "Latest sensor readings", exact: true });
    await expect(latest).toContainText("25 C");
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth + 1)).toBe(true);
    await page.goto(fixture + "?view=networks");
    await expect(panel.getByRole("heading", { name: `Aranet browser ${width}`, exact: true })).toBeVisible();
  });
  test(`Things Stack device discovery requires a supported sample ${width}`, async ({ page }) => {
    await page.setViewportSize({ width, height: 900 });
    await page.goto(fixture + "?view=networks");
    const panel = page.getByRole("region", { name: "Sensor network setup", exact: true });
    await panel.getByRole("combobox", { name: "System", exact: true }).selectOption("things_stack");
    await panel.getByLabel("Connection name", { exact: true }).fill(`Things Stack browser ${width}`);
    await panel.getByLabel("Existing application ID", { exact: true }).fill("grow-app");
    await panel.getByLabel("Customer-owned API key", { exact: true }).fill("synthetic-things-stack-test-credential");
    await panel.getByLabel("I authorize DoobieLogic to read this account's sensor data. Do not control equipment.", { exact: true }).check();
    await panel.getByRole("button", { name: "Connect account and find sensors", exact: true }).click();
    const review = panel.getByRole("form", { name: "Confirm network sensor rooms", exact: true });
    await expect(review.getByLabel("Connect this sensor", { exact: true })).toBeDisabled();
    expect((await page.request.post(origin + "/fixture/sample")).status()).toBe(200);
    await review.getByLabel("Connect this sensor", { exact: true }).check();
    await review.getByRole("combobox", { name: "DoobieLogic room", exact: true }).selectOption("fixture-room");
    await review.getByLabel("I authorize read-only collection from these sensors into the rooms shown.", { exact: true }).check();
    await review.getByRole("button", { name: "Connect selected sensors", exact: true }).click();
    await expect(panel).toContainText("Sensors linked.");
    expect((await page.request.post(origin + "/fixture/sample")).status()).toBe(200);
    const saved = panel.locator("article.network-device").filter({ has: page.getByRole("heading", { name: `Things Stack browser ${width}`, exact: true }) });
    await expect(saved).toContainText("receiving", { timeout: 10000 });
    await saved.getByRole("button", { name: "Pause collection", exact: true }).click();
    await expect(saved).toContainText("disabled");
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth + 1)).toBe(true);
  });
}
test("viewer can inspect saved connections but cannot connect or import", async ({ page }) => {
  await page.goto(fixture + "?view=viewer");
  const panel = page.getByRole("region", { name: "Sensor network setup", exact: true });
  await expect(panel).toContainText("Read only.");
  await expect(panel.getByRole("form", { name: "Connect sensor account", exact: true })).toHaveCount(0);
  const denied = await page.request.post(origin + "/api/v1/cultivation-networks/connections", { data: { api_key: "synthetic-invalid" } });
  expect(denied.status()).toBe(403);
  const deniedImport = await page.request.post(origin + "/api/v1/integration-wizard/metrc-setup/import", { data: { confirmed: true } });
  expect(deniedImport.status()).toBe(403);
});
