// Lightweight metadata only: the entry bundle must not import long-form articles.
export const advisoryRoutes: Record<string, { title: string; description: string; kind: "website" | "service" | "article" }> = {
  "/tools/operations-score": { title: "Operations Health Check | DoobieLogic Advisory", description: "Use a self-assessment to organize questions about your operating habits and handoffs. Discussion context, not an audit or compliance score.", kind: "website" },
  "/tools/inventory-health-check": { title: "Inventory Health Check | DoobieLogic Advisory", description: "Analyze an inventory CSV privately in your browser. Map columns to review stock value, age and stock cover, with missing data explained.", kind: "website" },
  "/": { title: "DoobieLogic | Cannabis Operations Software & Consulting", description: "DoobieLogic is cannabis operations software in beta and advisory for cultivation, extraction, production, inventory, purchasing and retail teams.", kind: "website" },
  "/consulting": { title: "Cannabis Consulting & Operations Advisory | DoobieLogic", description: "Cannabis consulting for inventory, purchasing, SOPs, compliance operations, Metrc technology, production and extraction. Explore DoobieLogic Advisory services.", kind: "website" },
  "/resources": { title: "Cannabis Operations Resources | DoobieLogic Advisory", description: "Practical guides to days on hand, inventory reconciliation and Metrc API readiness, with primary-source references.", kind: "website" },
  "/consulting/inventory-profit-audit": { title: "Inventory & Profit Audit | DoobieLogic Advisory", description: "Review inventory age, stock cover, sell-through, margins and purchasing priorities. Inventory audits starting at $500; scope confirmed before work begins.", kind: "service" },
  "/consulting/fractional-purchasing": { title: "Fractional Purchasing | DoobieLogic Advisory", description: "Monthly purchasing support for forecasting, replenishment, assortment, vendor discussions and weekly inventory reviews.", kind: "service" },
  "/consulting/compliance-operational-audit": { title: "Compliance & Operational Audit | DoobieLogic Advisory", description: "Review receiving, reconciliation, records, access and SOP execution. Get an operational gap analysis and roadmap; not legal advice.", kind: "service" },
  "/consulting/sop-workflow-development": { title: "SOP & Workflow Development | DoobieLogic Advisory", description: "Build practical SOPs, checklists, logs, training notes and clear operating responsibilities for your cannabis team.", kind: "service" },
  "/consulting/metrc-technology": { title: "Metrc & Technology Advisory | DoobieLogic Advisory", description: "Independent advisory for API readiness, system mapping, testing and operational exceptions. No provider endorsement or certification implied.", kind: "service" },
  "/consulting/production-extraction": { title: "Production & Extraction Operations | DoobieLogic Advisory", description: "Review material flow, traceability, yield definitions, costing and production handoffs with a practical improvement plan.", kind: "service" },
  "/consulting/operational-diagnostic": { title: "Operational Diagnostic, Starting at $500 | DoobieLogic Advisory", description: "Review inventory, purchasing, people, process and technology. Leave with prioritized findings and an implementation plan. Scope confirmed before work begins.", kind: "service" },
  "/resources/days-on-hand-for-cannabis-inventory": { title: "Days on Hand: A Practical Inventory Review | DoobieLogic", description: "Calculate inventory cover with a worked example, recognize misleading averages and build a useful purchasing review worksheet.", kind: "article" },
  "/resources/inventory-reconciliation-checklist": { title: "Inventory Reconciliation Checklist | DoobieLogic", description: "A practical checklist for count boundaries, variance investigation, approved corrections and verified resolution. Operational guidance, not legal advice.", kind: "article" },
  "/resources/metrc-api-readiness-checklist": { title: "Metrc API Readiness Checklist | DoobieLogic", description: "Plan workflow scope, access, mappings, exception tests and readback verification using official Metrc documentation.", kind: "article" },
  "/beta": { title: "Apply for the DoobieLogic Beta | Cannabis Operations Software", description: "Cannabis operations software in beta for cultivation, extraction, production, inventory and purchasing teams. Bring connected operational context into view with DoobieLogic.", kind: "website" },
};
