export interface ConsultingService {
  slug: string; title: string; summary: string; intro: string; areas: string[];
  deliverables: string[]; price: string; cta: { label: string; href: string };
  relatedResources: string[]; scopeNote?: string;
}
const service = (value: Omit<ConsultingService, "cta">): ConsultingService => ({ ...value, cta: { label: "Book a free 20-minute consultation", href: `/consulting?service=${value.slug}#consultation` } });
export const services: ConsultingService[] = [
  service({ slug: "inventory-profit-audit", title: "Inventory & Profit Audit", summary: "Find where inventory decisions are tying up cash or leaving demand unmet.", intro: "A focused review of the inventory you carry, how it sells, and the purchasing decisions behind it. We turn the available data into a practical list of decisions to review with your team.", areas: ["Inventory age, days on hand and sell-through", "SKU, category and vendor performance", "Reorder decisions, stockouts and overstock", "Discounts, margins and inventory concentration"], deliverables: ["A findings summary with data limitations made explicit", "Prioritized recommendations by operational impact", "An action plan with owners and next steps", "A review session to walk through the decisions"], price: "Starting at $500", relatedResources: ["days-on-hand-for-cannabis-inventory"], scopeNote: "Final scope and fee depend on data availability, locations and the depth of review. Recommendations do not guarantee savings or profit." }),
  service({ slug: "fractional-purchasing", title: "Fractional Purchasing", summary: "Bring a consistent operating rhythm to buying, replenishment and vendor decisions.", intro: "Ongoing purchasing support for teams that need a second set of experienced eyes and a repeatable review process. The engagement is shaped around your assortment, constraints and decision authority.", areas: ["Demand review, forecasting and reorder planning", "Assortment and menu health", "Vendor performance and negotiation preparation", "Weekly purchasing and inventory reviews"], deliverables: ["A purchasing review cadence", "Reorder and assortment recommendations", "Vendor discussion priorities", "A running decision and follow-up log"], price: "Monthly engagements · scoped to your operation", relatedResources: ["days-on-hand-for-cannabis-inventory"], scopeNote: "Your authorized team retains purchasing and vendor-commitment decisions unless a separate written scope establishes otherwise." }),
  service({ slug: "compliance-operational-audit", title: "Compliance & Operational Audit", summary: "See where daily execution, documentation and review processes need attention.", intro: "A practical review of how work moves through the operation and how the supporting records are maintained. Any jurisdiction-specific requirement must be checked against the applicable current source and your license scope.", areas: ["Receiving and inventory reconciliation", "Waste workflows, access and visitor records", "Recordkeeping and SOP execution", "Corrective actions and ownership"], deliverables: ["An operational gap analysis", "An evidence and open-question register", "A prioritized corrective-action roadmap", "A review of responsibilities and follow-up checkpoints"], price: "Scoped after consultation", relatedResources: ["inventory-reconciliation-checklist"], scopeNote: "Operational consulting, not legal advice, a regulatory inspection or a guarantee of compliance. State, license and medical/adult-use scope are established before reviewing specific requirements." }),
  service({ slug: "sop-workflow-development", title: "SOP & Workflow Development", summary: "Give teams clear instructions, handoffs and records for the work they actually do.", intro: "Document the operating process with the people who use it. We focus on clear steps, named responsibilities, exception handling and training materials that can be reviewed as the operation changes.", areas: ["Standard operating procedures and checklists", "Logs, workflow maps and handoffs", "Role responsibilities and escalation paths", "Training and adoption planning"], deliverables: ["Draft SOPs aligned with the agreed scope", "Supporting checklists and logs", "A responsibility and handoff map", "Training notes and a revision plan"], price: "Scoped after consultation", relatedResources: ["inventory-reconciliation-checklist"] }),
  service({ slug: "metrc-technology", title: "Metrc & Technology Advisory", summary: "Work through integration readiness, data mapping and operational exceptions before they become daily friction.", intro: "Connect technical planning to the workflow an operator needs to complete. We review the target state and license context, available documentation, system boundaries and the evidence needed to evaluate an integration.", areas: ["API readiness and evaluation preparation", "State-specific endpoint and workflow analysis", "ERP/POS mapping and data ownership", "Testing, errors, synchronization and operator experience"], deliverables: ["A system and workflow map", "A readiness and documentation checklist", "A test and exception-handling plan", "Prioritized integration recommendations"], price: "Scoped after consultation", relatedResources: ["metrc-api-readiness-checklist"], scopeNote: "Independent advisory work. No Metrc endorsement, certification, partner status or universal state coverage is implied. Access and provider approval requirements remain with the applicable provider." }),
  service({ slug: "production-extraction", title: "Production & Extraction Operations", summary: "Understand material movement, yield, cost and loss across the production workflow.", intro: "Review the operational handoffs from raw material through processing, extraction, intermediate and finished goods, testing and packaging. The focus is planning, records and process visibility.", areas: ["Material flow and traceability", "Yield definitions and loss visibility", "Cost inputs and production planning", "Testing, packaging and release handoffs"], deliverables: ["A current-state material and workflow map", "A review of yield and costing assumptions", "A prioritized process improvement plan", "Recommended operating records and review checkpoints"], price: "Scoped after consultation", relatedResources: ["inventory-reconciliation-checklist"], scopeNote: "This service does not replace process engineering, equipment safety review, laboratory testing or applicable regulatory approval." }),
];
export const operationalDiagnostic = service({ slug: "operational-diagnostic", title: "Operational Diagnostic", summary: "Start with a clear picture of what needs attention and what to do next.", intro: "A focused first engagement across inventory, purchasing, people, process, compliance workflows and technology. We agree on the questions, review the available evidence and identify practical next steps.", areas: ["Inventory and purchasing decisions", "People, responsibilities and handoffs", "Processes and compliance workflows", "Technology and information gaps"], deliverables: ["Findings with supporting observations", "Impact and priority assessment", "Practical recommendations", "An implementation plan and review session"], price: "Starting at $500", relatedResources: ["days-on-hand-for-cannabis-inventory", "inventory-reconciliation-checklist", "metrc-api-readiness-checklist"], scopeNote: "Scope and fee are confirmed before work begins. A diagnostic identifies priorities; implementation and specialized reviews are scoped separately." });
export const allServices = [...services, operationalDiagnostic];
export const getConsultingService = (slug: string) => allServices.find(item => item.slug === slug);
