export { services, operationalDiagnostic, allServices, getConsultingService } from "./consultingServices";
export type { ConsultingService } from "./consultingServices";
export interface ConsultingResource {
  slug: string; title: string; summary: string; reviewedOn: string; scopeNote?: string;
  sections: { id: string; title: string; paragraphs: string[]; bullets?: string[] }[];
  sources: { title: string; url: string; publisher: string }[]; relatedServices: string[];
}
export const resources: ConsultingResource[] = [
  {
    slug: "days-on-hand-for-cannabis-inventory", title: "Days on hand: a practical inventory review", summary: "Calculate stock cover, recognize misleading averages and turn the number into a better purchasing conversation.", reviewedOn: "2026-09-19", scopeNote: "An operational planning guide. Examples are illustrative and do not establish a recommended inventory target.", relatedServices: ["inventory-profit-audit", "fractional-purchasing"],
    sections: [
      { id: "define", title: "Start with the question you want to answer", paragraphs: ["For a buyer, days on hand often means: how long would the stock available today last if the recent sales pace continued? That is a stock-cover estimate, not a forecast or a promise that an item will remain available.", "Keep that operating measure distinct from accounting days in inventory, which uses average inventory value and cost of goods sold. Do not mix quantities and dollars, or compare two reports until you know which definition each uses."] },
      { id: "calculate", title: "Calculate the estimate in consistent units", paragraphs: ["Average daily units sold = units sold during the lookback ÷ days in the lookback. Estimated days on hand = current sellable units ÷ average daily units sold.", "Example: 42 units sold in 14 days gives a pace of 3 units per day. With 84 sellable units on hand, estimated cover is 28 days. If 12 of those units are held and cannot be sold, the sellable quantity is 72 and cover is 24 days.", "Shopify’s inventory-report documentation uses this quantity-based approach with its own 28-day report window. That window is a product convention, not a universal target. Choose and label a lookback that makes sense for the decision, then use it consistently."] },
      { id: "prepare", title: "Build a small, reviewable worksheet", paragraphs: ["Use one row per SKU and location, with a consistent selling unit. Separate stock that exists physically from stock available to sell. The following is a suggested working template rather than a reporting requirement."], bullets: ["SKU, location, category, vendor and selling unit", "Snapshot date and time; sellable, held and reserved quantities", "Lookback start/end, days observed and units sold", "Average daily sales, estimated cover and oldest stock age", "Confirmed inbound quantity, expected arrival and supplier lead time", "Margin, recent promotions, stockout days and a next-action owner"] },
      { id: "exceptions", title: "Mark the cases where the number misleads", paragraphs: ["Zero sales should produce a review flag, not a convincing-looking coverage number. Shopify reports N/A where the sales history cannot support a prediction. Check whether the item is new, unavailable, incorrectly mapped or simply not moving.", "Recent stockouts can make observed sales lower than demand. Promotions can make them temporarily higher. A changed pack size or mixed units can make the calculation meaningless. Label those conditions before using the result to approve another order.", "A category average can hide both a stocked-out fast seller and a slow seller with excess stock. Review the underlying items. Do not take a simple average of SKU-level days and treat it as an accurate category coverage calculation."] },
      { id: "decide", title: "Use cover to frame the next decision", paragraphs: ["Review estimated cover alongside lead time, ordering cadence, minimum order quantities, inbound stock, age and margin. The same number can mean different things for a reliable local supplier and an uncertain delivery schedule.", "For low cover, verify demand and incoming orders before proposing replenishment. For high cover, check age, assortment overlap and purchasing commitments before discussing a smaller reorder, vendor conversation or promotion. A discount is a commercial decision with a margin cost, not an automatic response to an inventory ratio.", "Finish the review with a named decision, an owner and a revisit date. Track whether the action addressed the original issue; avoid claiming savings from inventory movement alone."] },
    ], sources: [
      { title: "Inventory reports — inventory remaining and days of inventory", publisher: "Shopify Help Center", url: "https://help.shopify.com/en/manual/reports-and-analytics/shopify-reports/report-types/default-reports/inventory-reports" },
      { title: "Days in inventory: accounting calculation", publisher: "Shopify", url: "https://www.shopify.com/blog/days-in-inventory" },
    ],
  },
  {
    slug: "inventory-reconciliation-checklist", title: "An inventory reconciliation checklist your team can use", summary: "Set a count boundary, investigate differences and document the path from observation to verified resolution.", reviewedOn: "2026-09-19", scopeNote: "Operational guidance, not legal advice. State: not state-specific. Medical/adult-use scope: not assessed. Review status: operational checklist; jurisdiction and license requirements need separate current-source review.", relatedServices: ["compliance-operational-audit", "sop-workflow-development", "production-extraction"],
    sections: [
      { id: "scope", title: "Agree on what you are reconciling", paragraphs: ["Reconciliation is more useful when everyone is comparing the same items, locations, units and moment in time. A physical count, a POS balance, an internal inventory ledger and an external traceability record can represent different statuses or timing. Write those boundaries down before declaring a variance.", "This checklist proposes an operating process. It does not prescribe a legal count frequency, reporting deadline, tolerance or adjustment method."], bullets: ["Name the facility, location, item/package scope and responsible reviewer.", "Choose a cut-off time and preserve timestamped source exports.", "Define the counting unit and conversion rules.", "Identify held, reserved, damaged and in-transit stock separately.", "Pause movements where practical, or log every movement during the count."] },
      { id: "count", title: "Count before trying to explain the result", paragraphs: ["Use a consistent count method and record who counted, when and where. Consider a count sheet that does not reveal the expected balance, then have another person recount significant exceptions under your agreed review process.", "Microsoft’s cycle-counting documentation separates creating count work, recording a count and resolving differences. That separation is a useful software example of why observation and approval should not be treated as the same step."], bullets: ["Record identifiers and units, not just product names.", "Check adjacent bins and recently moved stock.", "Record an inaccessible or unclear item as an exception rather than guessing.", "Keep the original observation when a recount changes the result."] },
      { id: "investigate", title: "Trace the difference to evidence", paragraphs: ["For each discrepancy, compare the physical observation with the relevant records and movements around the cut-off. Check timing before assuming loss. Check identifier and unit mapping before assuming a quantity problem.", "GS1’s traceability standard emphasizes identification and the exchange of traceability information across parties. For this worksheet, the practical implication is to preserve the item or package identity and movement context needed to follow the record."], bullets: ["Receiving recorded before or after the cut-off", "Transfers, returns or production movements not yet reflected in another system", "A held or reserved status included in one balance but excluded in another", "Duplicate entries, missing records or mismatched units", "Unresolved mapping or synchronization errors requiring technical review"] },
      { id: "resolve", title: "Separate a proposed correction from an approved one", paragraphs: ["Do not overwrite a balance merely to make two reports agree. Record the evidence, the proposed action, the responsible owner and the required approval. Use the authorized workflow for the system that owns the affected record.", "Where an external provider is involved, distinguish a request being sent from the provider accepting it and from the resulting record being verified. An unresolved error remains an exception, even if a local screen looks correct.", "After an approved change, recheck the affected records and preserve the verification result. Escalate questions about required reporting or permissible corrections to a qualified person using current jurisdiction-specific sources."] },
      { id: "template", title: "Use an exception log that supports follow-up", paragraphs: ["Suggested columns: reference, count time, facility/location, item or package identifier, unit, physical quantity, system quantity, difference, evidence reference, suspected cause, owner, proposed action, approval status and verification result.", "Keep credentials, customer details and unnecessary personal information out of the working log. Store supporting records in the access-controlled system your operation has approved.", "At the next review, group resolved exceptions by cause. A repeated receiving handoff, unit conversion or mapping issue may need a workflow change rather than another one-off correction."] },
    ], sources: [
      { title: "Cycle counting", publisher: "Microsoft Learn", url: "https://learn.microsoft.com/en-us/dynamics365/supply-chain/warehousing/cycle-counting" },
      { title: "Global Traceability Standard", publisher: "GS1", url: "https://www.gs1.org/standards/gs1-global-traceability-standard/current-standard" },
    ],
  },
  {
    slug: "metrc-api-readiness-checklist", title: "Metrc API readiness: the questions to answer before integration", summary: "Define the workflow, map the data and collect evidence that an integration handles both normal work and exceptions.", reviewedOn: "2026-09-19", scopeNote: "Independent technical planning guidance, not official Metrc evaluation criteria, certification or legal advice. State: state-neutral planning; linked California/Montana documentation is illustrative. Medical/adult-use scope must be established for the target license. Review status: verify exact current deployment documentation before implementation.", relatedServices: ["metrc-technology", "operational-diagnostic"],
    sections: [
      { id: "workflow", title: "Start with a business action, not an API checkbox", paragraphs: ["Write down what an operator is trying to complete, which system owns the underlying record and which information must reach Metrc. Receiving, inventory review and a production handoff are different workflows with different evidence needs.", "Record the state, license, facility, environment and API documentation version for each proposed action. Metrc’s published API terms note that functionality can vary by deployment. A successful test in one environment is not evidence of universal state coverage."], bullets: ["Business action and authorized operator role", "System of record and external record to be read or changed", "Exact documentation reference and required access", "Expected result and the evidence that will confirm it"] },
      { id: "access", title: "Confirm access and protect credentials", paragraphs: ["Assign an owner for provider onboarding, licensee authorization and credential management. The official Montana getting-started documentation describes integrator and user API credentials; use the documentation for your actual deployment to confirm its requirements.", "Keep secrets out of shared worksheets, screenshots, contact forms and test reports. Record that access was checked without copying the credential itself. Confirm who can revoke access and how a personnel change is handled."] },
      { id: "mapping", title: "Make the mappings explicit", paragraphs: ["Create a mapping table before sending data. Include internal and external identifiers, units, statuses, facility/license context and date/time conventions. Record whether a field is supplied, derived or unavailable.", "Agree on how ambiguous or missing mappings become visible to an operator. A guessed mapping can create a plausible-looking record that is difficult to reconcile later."], bullets: ["Identifiers and record matching", "Quantities and unit conversions", "Facility, license and location context", "Status transitions and effective timestamps", "Ownership of mapping changes and their review"] },
      { id: "test", title: "Test failures as deliberately as the happy path", paragraphs: ["Use synthetic data in the test environment. Metrc’s API terms distinguish test environments from production and require test data there; do not assume a test environment has production performance characteristics.", "The California sandbox documentation exposes topics including pagination, timestamps, server responses, rate limits and object limits. Treat those as prompts to review the exact deployment’s current documentation, not as a universal endpoint contract."], bullets: ["A complete multi-page read and an incremental update window", "Invalid input, missing access and unavailable mappings", "Timeouts and rate-limit responses", "Duplicate submission risk and safe retry behavior", "A partially completed workflow and its recovery path", "Readback of the resulting identifier, status and quantity"] },
      { id: "operations", title: "Define what success looks like on the operator’s screen", paragraphs: ["Keep proposed, validated, submitted, provider-accepted and verified states distinct. The operator should be able to see an unresolved exception and the person responsible for it. A generic success toast is not sufficient evidence of completed synchronization.", "For each test, record the action, expected outcome, observed outcome, relevant non-secret identifiers, timestamp and reviewer. Include the verification result and any follow-up needed. This creates a practical evidence pack for evaluation discussions without claiming provider approval.", "Before rollout, agree on support ownership, exception monitoring, authorized correction procedures and a recovery plan. Check the applicable provider terms and current documentation again when the integration scope or target deployment changes."] },
    ], sources: [
      { title: "Metrc Open API", publisher: "Metrc", url: "https://www.metrc.com/track-and-trace-technology/open-api/" },
      { title: "API Terms of Use (updated September 11, 2025)", publisher: "Metrc", url: "https://www.metrc.com/metrc-application-programming-interface-terms-of-use/" },
      { title: "Getting started — Montana API documentation", publisher: "Metrc", url: "https://api-mt.metrc.com/Documentation/getting-started" },
      { title: "California sandbox API documentation", publisher: "Metrc", url: "https://sandbox-api-ca.metrc.com/Documentation" },
    ],
  },
];
export const getConsultingResource = (slug: string) => resources.find(item => item.slug === slug);
