// Generated by scripts/sync-help-metadata.mjs from the detailed guides.
export const helpSeoRoutes: Record<string, { title: string; description: string; kind: "article" }> = {
  "/help/buying": {
    "title": "Review stock and decide what to order | DoobieLogic Help",
    "description": "Use Today for current stock, Decide for uploaded buying evidence, and Act to open purchasing after you've checked the need.",
    "kind": "article"
  },
  "/help/buying/recommendations": {
    "title": "Read Buying Recommendations before building an order | DoobieLogic Help",
    "description": "Review sales coverage, SKU risk and assortment gaps in Buyer Intelligence, then use purchasing to create the order.",
    "kind": "article"
  },
  "/help/buying/purchase-orders": {
    "title": "Create, save and confirm a purchase order | DoobieLogic Help",
    "description": "Build a facility-scoped draft, verify its saved total, then confirm it as committed inbound inventory.",
    "kind": "article"
  },
  "/help/buying/budget": {
    "title": "Estimate the buying budget | DoobieLogic Help",
    "description": "Compare current inventory cost with a coverage target and enter on-order cost to see the recommended purchasing position.",
    "kind": "article"
  },
  "/help/buying/delivery-performance": {
    "title": "Compare sales before and after a delivery | DoobieLogic Help",
    "description": "Load delivery manifests, verify their item matches and received dates, then compare sales around the delivery.",
    "kind": "article"
  },
  "/help/buying/planning-settings": {
    "title": "Set replenishment rules and build a draft PO | DoobieLogic Help",
    "description": "Save product-specific buying rules, check the recalculated need and convert selected products into a saved draft order.",
    "kind": "article"
  },
  "/help/inventory": {
    "title": "Find retail stock and choose the right action | DoobieLogic Help",
    "description": "Switch between product totals and physical packages, check availability and open the action that matches the work.",
    "kind": "article"
  },
  "/help/inventory/receiving": {
    "title": "Receive an inbound shipment into retail inventory | DoobieLogic Help",
    "description": "Match the physical shipment to the inbound queue, map each product, review fresh provider evidence and post the local receipt once.",
    "kind": "article"
  },
  "/help/inventory/reconciliation": {
    "title": "Compare retail packages with Metrc | DoobieLogic Help",
    "description": "Run a read-only package comparison for the active license and inspect differences without posting inventory changes.",
    "kind": "article"
  },
  "/help/inventory/transfers": {
    "title": "Transfer packages between licensed facilities | DoobieLogic Help",
    "description": "Post the local transfer out, receive each package at its destination and retain the state-system manifest reference.",
    "kind": "article"
  },
  "/help/inventory/product-360": {
    "title": "Review a product's stock, sales and buying context | DoobieLogic Help",
    "description": "Open an active retail product, inspect its packages and sales evidence, and carry the product into purchasing or an audit.",
    "kind": "article"
  },
  "/help/inventory/package-360": {
    "title": "Trace one package and inspect its current state | DoobieLogic Help",
    "description": "Resolve a package identifier, compare local stock with compliance-sync evidence and read its linked inputs, outputs and event history.",
    "kind": "article"
  },
  "/help/inventory/audits": {
    "title": "Start, count, pause and complete a retail audit | DoobieLogic Help",
    "description": "Keep one saved audit for the intended scope, finish its first counts and recounts, then explicitly choose whether completion posts stock corrections.",
    "kind": "article"
  },
  "/help/inventory/audits/import-inventory": {
    "title": "Load a Dutchie inventory report for the next audit | DoobieLogic Help",
    "description": "Preview the report, map its columns and import the intended retail stock before starting a separate physical count.",
    "kind": "article"
  },
  "/help/inventory/slow-movers": {
    "title": "Find slow stock and export a review list | DoobieLogic Help",
    "description": "Filter uploaded stock by sales coverage, inspect the tied-up units and cost, and export the items that need an operating decision.",
    "kind": "article"
  },
  "/help/inventory/catalog-admin": {
    "title": "Maintain retail products and label defaults | DoobieLogic Help",
    "description": "Find or create the right product, save its classification and package facts, and keep aliases, external mappings and prices traceable.",
    "kind": "article"
  },
  "/help/production": {
    "title": "Plan production and create a job | DoobieLogic Help",
    "description": "Review the next runs, investigate blockers, and save a production order before scheduling or recording physical work.",
    "kind": "article"
  },
  "/help/production/calendar": {
    "title": "Schedule a production run | DoobieLogic Help",
    "description": "Place an existing run on the calendar, review conflicts, and commit the exact schedule window.",
    "kind": "article"
  },
  "/help/production/run-360": {
    "title": "Record materials, output, and QA in Production Run 360 | DoobieLogic Help",
    "description": "Work one saved production order from material reservations through actual consumption, measured output, QA, and costs.",
    "kind": "article"
  },
  "/help/extraction": {
    "title": "Plan and work an extraction run | DoobieLogic Help",
    "description": "Reserve compatible feedstock, confirm preflight, consume the source at start, and record measured progress through the extraction process.",
    "kind": "article"
  },
  "/help/extraction/outputs-qa": {
    "title": "Create extraction outputs and record QA release | DoobieLogic Help",
    "description": "Create measured output lots, attach QA evidence, and distinguish local release from a queued state-system action.",
    "kind": "article"
  },
  "/help/white-label-repack": {
    "title": "Save and approve a White Label / Repack plan | DoobieLogic Help",
    "description": "Build a package and margin plan around existing source inventory, save a draft, and approve its production handoff.",
    "kind": "article"
  },
  "/help/package-studio": {
    "title": "Transform a package in Package Studio | DoobieLogic Help",
    "description": "Define actual outputs and source use, review the mass balance, and commit a local package transformation with its source trail.",
    "kind": "article"
  },
  "/help/production/inventory": {
    "title": "Review and receive production inventory | DoobieLogic Help",
    "description": "Find production packages, read available quantity after commitments, and receive material into the active facility.",
    "kind": "article"
  },
  "/help/production/inventory/transfers": {
    "title": "Transfer production inventory between facilities | DoobieLogic Help",
    "description": "Post the physical transfer out, receive its package lines at the destination, and retain the manifest relationship.",
    "kind": "article"
  },
  "/help/production/package-360": {
    "title": "Inspect a production package in Package 360 | DoobieLogic Help",
    "description": "Check one package's local balance, source relationships, event history, and separate compliance sync state.",
    "kind": "article"
  },
  "/help/production/products": {
    "title": "Set up a production product | DoobieLogic Help",
    "description": "Create or maintain the material and output identities used by production, including units, catalog scope, packaging defaults, and cost history.",
    "kind": "article"
  },
  "/help/production/inventory-audits": {
    "title": "Count production inventory and close an audit | DoobieLogic Help",
    "description": "Start a scoped production count, record and recount physical quantities, then review whether completion should post inventory corrections.",
    "kind": "article"
  },
  "/help/cultivation": {
    "title": "Cultivation: review rooms, record plant work, and plan a harvest | DoobieLogic Help",
    "description": "Find the right plants, check room capacity, record an individual or bulk change, and prepare a local harvest handoff.",
    "kind": "article"
  },
  "/help/cultivation/post-harvest": {
    "title": "Post-Harvest: record weights and hand off the next stage | DoobieLogic Help",
    "description": "Append measured weights, check remaining material, and move a harvest through the physical work stages without overwriting earlier readings.",
    "kind": "article"
  },
  "/help/cultivation/room-360": {
    "title": "Room 360: read current conditions and historical coverage | DoobieLogic Help",
    "description": "Review a room's plants, imported sensor readings, historical coverage, approved targets, and operational evidence without confusing missing data with healthy conditions.",
    "kind": "article"
  },
  "/help/cultivation/environment": {
    "title": "Room environment: record an observation and review follow-up | DoobieLogic Help",
    "description": "Save a manual measurement in its displayed unit, configure a room review range, and explicitly create Work for an environmental exception.",
    "kind": "article"
  },
  "/help/cultivation/crop-cycle-360": {
    "title": "Crop Cycle 360: record membership, room intervals, and harvest links | DoobieLogic Help",
    "description": "Create a crop cycle and maintain its plant membership and dated room history while preserving the distinction between cycle records and individual plant movements.",
    "kind": "article"
  },
  "/help/cultivation/recipes": {
    "title": "Recipes: draft and approve facility target versions | DoobieLogic Help",
    "description": "Record facility-defined stages and measurement bounds, review a saved draft, and approve an immutable recipe version for cycle context.",
    "kind": "article"
  },
  "/help/cultivation/connections": {
    "title": "Cultivation connections: register devices and map sensor placement | DoobieLogic Help",
    "description": "Create a file configuration, register known device identities, and map their channels and dated room placement before reviewing imported evidence.",
    "kind": "article"
  },
  "/help/cultivation/imports": {
    "title": "Cultivation imports: preview and commit JSON or CSV evidence | DoobieLogic Help",
    "description": "Load an explicit measurement export, review its validation and mappings, then commit the reviewed content and inspect every result category.",
    "kind": "article"
  },
  "/help/cultivation/evidence-maintenance": {
    "title": "Cultivation evidence: build local summaries and review retention | DoobieLogic Help",
    "description": "Build dated local aggregates, inspect archive acknowledgements, and review protected raw-reading retention before any removal.",
    "kind": "article"
  },
  "/help/cultivation/plant-exposure": {
    "title": "Plant exposure: review the evidence behind a plant's history | DoobieLogic Help",
    "description": "Read environmental exposure status, mother and group references, and cycle occupancy without treating a plant's current room as proven historical exposure.",
    "kind": "article"
  },
  "/help/cultivation/push-setup": {
    "title": "Set up a producer that sends cultivation readings | DoobieLogic Help",
    "description": "Create a normalized JSON connection, authorize one producer, map its sources and check what actually arrived.",
    "kind": "article"
  },
  "/help/cultivation/deviation-work": {
    "title": "Turn a reviewed historical deviation into Work | DoobieLogic Help",
    "description": "Check a proven out-of-range interval, create or reuse its Work item, and keep the link back to the exact room evidence.",
    "kind": "article"
  },
  "/help/cultivation/nearby-sensors": {
    "title": "Find and link a supported nearby sensor | DoobieLogic Help",
    "description": "Use the facility receiver to find supported broadcasts, check the sensor identity, and approve read-only collection for its room.",
    "kind": "article"
  },
  "/help/wholesale": {
    "title": "Wholesale Ops overview | DoobieLogic Help",
    "description": "Find the next wholesale handoff, from a customer request through inventory, shipping, invoicing, and collection.",
    "kind": "article"
  },
  "/help/wholesale/inventory": {
    "title": "Check wholesale inventory before committing stock | DoobieLogic Help",
    "description": "Find a product, compare on-hand stock with commitments, and understand why a lot is blocked from wholesale.",
    "kind": "article"
  },
  "/help/wholesale/orders": {
    "title": "Create, confirm, and reserve a wholesale order | DoobieLogic Help",
    "description": "Build a sales-order draft, confirm its terms, reserve the right lot, and verify fulfillment separately from payment.",
    "kind": "article"
  },
  "/help/wholesale/warehouse-pick-pack": {
    "title": "Pick, verify, pack, and post a wholesale shipment | DoobieLogic Help",
    "description": "Use the warehouse queue to match the physical lot, reserve its quantity, record packing and manifest readiness, and post the shipment.",
    "kind": "article"
  },
  "/help/wholesale/customers": {
    "title": "Keep a wholesale customer account ready for the next handoff | DoobieLogic Help",
    "description": "Create the trade partner, review Customer 360, assign the next action, and record activities or a Work follow-up.",
    "kind": "article"
  },
  "/help/wholesale/pipeline": {
    "title": "Move a wholesale opportunity into a quoted sales order | DoobieLogic Help",
    "description": "Track the sales opportunity, save a priced quote, and convert it into a draft order without reserving stock prematurely.",
    "kind": "article"
  },
  "/help/wholesale/accounting": {
    "title": "Review wholesale balances and record invoice payments | DoobieLogic Help",
    "description": "Use Accounting to reconcile orders, invoices, recorded payments, and stored QuickBooks links, then use order finance for approved changes.",
    "kind": "article"
  },
  "/help/wholesale/storefront": {
    "title": "Publish the wholesale storefront and review buyer requests | DoobieLogic Help",
    "description": "Save the site foundation and catalog, publish a reviewed design draft, and turn approved buyer requests into sales-order drafts.",
    "kind": "article"
  },
  "/help/wholesale/logistics": {
    "title": "Plan a dispatch run and record delivery outcomes | DoobieLogic Help",
    "description": "Assign existing shipments to stops, record delivery progress and proof of delivery, and create reconciliation work for exceptions.",
    "kind": "article"
  },
  "/help/getting-started": {
    "title": "Get started in the right facility | DoobieLogic Help",
    "description": "Sign in, check your access and data source, and open the workspace for your job.",
    "kind": "article"
  },
  "/help/home": {
    "title": "Choose the next job from Operations Home | DoobieLogic Help",
    "description": "Read the current facility's exceptions and open the record or workspace that needs attention.",
    "kind": "article"
  },
  "/help/home/work-queue": {
    "title": "Assign, track, and complete work | DoobieLogic Help",
    "description": "Create facility tasks, keep progress and evidence current, and generate recurring work when it is due.",
    "kind": "article"
  },
  "/help/reports/sales-category-trends": {
    "title": "Read Sales & Category Trends | DoobieLogic Help",
    "description": "Compare category mix, package sizes, and product movement using the facility's published inventory and sales sources.",
    "kind": "article"
  },
  "/help/reports/executive": {
    "title": "Generate Executive Reports | DoobieLogic Help",
    "description": "Download a report or operating pack for the current facility and check the data and session assumptions behind it.",
    "kind": "article"
  },
  "/help/reports/scheduled": {
    "title": "Schedule and verify report delivery | DoobieLogic Help",
    "description": "Create a facility subscription, send a deliberate test, and inspect delivery outcomes before sending again.",
    "kind": "article"
  },
  "/help/reports/insights": {
    "title": "Inspect recorded sales and delivery impact | DoobieLogic Help",
    "description": "Review recorded retail transactions, slow movers, and receipt comparisons on the live Reports & Insights route.",
    "kind": "article"
  },
  "/help/settings/imports-data": {
    "title": "Publish retail sources in Data Hub | DoobieLogic Help",
    "description": "Inspect a source, map its columns, and publish a reusable revision for the selected facility.",
    "kind": "article"
  },
  "/help/settings/import-production-data": {
    "title": "Import extraction run records | DoobieLogic Help",
    "description": "Review extraction log mappings and defaults before appending runs through Data Hub.",
    "kind": "article"
  },
  "/help/settings/admin": {
    "title": "Create users and manage facility access | DoobieLogic Help",
    "description": "Create a normal account, set its role and site access, and verify changes through Admin Tools.",
    "kind": "article"
  },
  "/help/settings/integration-wizard": {
    "title": "Set up a facility with Integration Wizard | DoobieLogic Help",
    "description": "Work through connection, validation, and mapping evidence without confusing finished steps with operational readiness.",
    "kind": "article"
  },
  "/help/settings/implementation": {
    "title": "Review implementation readiness | DoobieLogic Help",
    "description": "Check facility evidence, save supported manual reviews, and create follow-up work for unresolved setup.",
    "kind": "article"
  },
  "/help/settings/location": {
    "title": "Review Facility Setup and receiving defaults | DoobieLogic Help",
    "description": "Check the facility's provider context, load live structure on request, and distinguish previews from verified changes.",
    "kind": "article"
  },
  "/help/settings/integrations": {
    "title": "Choose operating mode and validate connections | DoobieLogic Help",
    "description": "Save the intended facility connection, test it separately, and keep sandbox, production, and AI settings distinct.",
    "kind": "article"
  },
  "/help/doobie-agent": {
    "title": "Ask Doobie Agent and inspect its evidence | DoobieLogic Help",
    "description": "Ask from the current workspace, review sources and freshness, and distinguish previews from applied actions.",
    "kind": "article"
  },
  "/help/home/control-towers": {
    "title": "Review Operations and Enterprise Control Towers | DoobieLogic Help",
    "description": "Find facility exceptions, inspect their supporting records, and use the organization view to prioritize sites.",
    "kind": "article"
  },
  "/help/home/labelguard": {
    "title": "Review label completeness with LabelGuard | DoobieLogic Help",
    "description": "Check supplied label text against a reviewed rule set without mistaking generic completeness for legal approval.",
    "kind": "article"
  },
  "/help/home/sop-control": {
    "title": "Review procedures and activate an SOP version | DoobieLogic Help",
    "description": "Inspect the procedure library and deviations, then activate an approved version with its source reference.",
    "kind": "article"
  },
  "/help/compliance": {
    "title": "Compliance overview | DoobieLogic Help",
    "description": "Check the active facility's traceability attention, then open the right tool for sources, labels, names, or state actions.",
    "kind": "article"
  },
  "/help/compliance/qa": {
    "title": "Compliance Q&A | DoobieLogic Help",
    "description": "Load reviewed source rows, ask within the correct state and program, and check the evidence returned with the answer.",
    "kind": "article"
  },
  "/help/compliance/traceability": {
    "title": "Traceability queue and reconciliation | DoobieLogic Help",
    "description": "Inspect a recorded transaction, compare its attempts and provider response, and record a human-reviewed resolution when appropriate.",
    "kind": "article"
  },
  "/help/compliance/state-actions": {
    "title": "State Actions | DoobieLogic Help",
    "description": "Review synchronization exceptions or validate and queue a specific state-system intent without mistaking the local queue for provider acceptance.",
    "kind": "article"
  },
  "/help/compliance/label-studio": {
    "title": "Label Studio: create finished labels | DoobieLogic Help",
    "description": "Build a saved label from tested inventory and Product Master, check its layout, assign the finished tag, and record a print request.",
    "kind": "article"
  },
  "/help/compliance/label-history-reprints": {
    "title": "Label Studio: History & Reprints | DoobieLogic Help",
    "description": "Find the original saved label and request a numbered replacement range without rebuilding it from current inventory or COA data.",
    "kind": "article"
  },
  "/help/compliance/advanced-labelguard": {
    "title": "Advanced LabelGuard & templates | DoobieLogic Help",
    "description": "Build a testing label from current inventory, review its COA association, and run the selected testing-label rules before printing.",
    "kind": "article"
  },
  "/help/compliance/facility-coa-library": {
    "title": "Facility COA Library | DoobieLogic Help",
    "description": "Store a laboratory PDF, check the extracted package identity and results, and verify how Label Studio resolves the certificate.",
    "kind": "article"
  },
  "/help/compliance/product-name-mapper": {
    "title": "Product Name Mapper | DoobieLogic Help",
    "description": "Review approved Dutchie catalog names against a METRC manifest, save confirmed mappings, and download one corrected name per original manifest row.",
    "kind": "article"
  },
  "/help/compliance/ma-flower-equivalency": {
    "title": "MA Flower Equivalency | DoobieLogic Help",
    "description": "Calculate the app's package-entry value from the right product inputs, review the breakdown, and copy the resulting number.",
    "kind": "article"
  }
};
